Installation script and packaging update for Linux and macOS
golemfactory/clay pull request #1004
Opened 2017-04-18 18:40 UTC by mfranciszkiewicz

- builds a `tar.gz` distribution for Linux and macOS
- fetches the latest linux release (via github api; **max 60 requests per hour and IP address**)
- enforces installed directory ownership

2017-04-18 19:33 UTC, gborowik commented
For macOS works great!

2017-04-19 13:35 UTC, banasiakadam60 requested changes

2017-04-19 13:35 UTC, banasiakadam60 commented on Installer/Installer_Linux/install.sh
> +    declare -r SUDO_USER=$(whoami)
When run with `sudo` it will set `SUDO_USER` to `root`
```
adam@adam:~ [15:26:33] $ cat test.sh 
#!/bin/bash

echo $(whoami)
adam@adam:~ [15:26:36] $ ./test.sh 
adam
adam@adam:~ [15:26:38] $ sudo ./test.sh 
root
adam@adam:~ [15:26:44] $ 
```
And we use `SUDO_USER` to get a name of user who called script (which is always launch with root privileges: https://github.com/golemfactory/golem/blob/develop/Installer/Installer_Linux/install.sh#L186)
`SUDO_USER       Set to the login of the user who invoked sudo`
So, if you want to use the user name (which always will be `root`), why don't use just `$USER`? As for me, you should remove this `if`

2017-04-19 14:05 UTC, mfranciszkiewicz commented on Installer/Installer_Linux/install.sh
> +    declare -r SUDO_USER=$(whoami)
I agree, it needs to be fixed. But it doesn't work when user is logged in as root, see https://github.com/golemfactory/golem/issues/1006

2017-04-19 14:52 UTC, banasiakadam60 approved these changes

2017-04-19 15:08 UTC, merged