Measure test time and display it to user
golemfactory/clay pull request #1021
Opened 2017-04-24 18:14 UTC by badb

2017-04-24 20:56 UTC, jiivan requested changes

2017-04-24 20:56 UTC, jiivan commented on tests/apps/core/benchmark/test_benchmarkrunner.py
> +            # values['run'].assert_called_once_with()
Uncomment/remove?

2017-04-24 20:56 UTC, jiivan commented on tests/apps/core/benchmark/test_benchmarkrunner.py
> +        self.instance.end_time = time.time() + 4
Maybe use absolute values here?

2017-04-24 20:56 UTC, jiivan commented on tests/apps/core/benchmark/test_benchmarkrunner.py
> +        # Start time not measure
`measured`

2017-04-24 20:56 UTC, jiivan commented on tests/apps/core/benchmark/test_benchmarkrunner.py
> +        super(self.__class__, self).setUp()
Isn't it called before by unittest?

2017-04-24 20:56 UTC, jiivan commented on tests/apps/core/benchmark/test_benchmarkrunner.py
> +        super(self.__class__, self).setUp()
May I suggest a rewrite of this method? I really feel this is overuse of OO programming. :) IMO:
 * No need to use instance attributes here - never used outside of this method. Simple vars would be more readable (without `self.`)
 * No need to use classmethod. A simple lambda or inner function would do. Yet in this context I would use a `Mock()`
 * No need for `_error()` method. It's ideal case for a `Mock()`

2017-04-24 20:56 UTC, jiivan commented on golem/task/localcomputer.py
> +    def _get_exc_time(self):
At first I though `exc` here was abbreviation of `exception` not `execution`. Maybe `get_time_spent()` or `get_execution_time()` would be clearer?

2017-04-24 20:56 UTC, jiivan commented on golem/task/localcomputer.py
> +    def _get_exc_time(self):
The same goes for `exc_time` argument passed to success callbacks. Maybe `execution_time` or `time_spent`? Or `exec_time` if you prefer abbreviated name?

2017-04-24 22:56 UTC, mfranciszkiewicz commented on gui/applicationlogic.py
> +        self.br.run()
This operation is blocking the GUI thread (`start` and immediate `join` on a thread). Since we have the whole callback machinery in place, is this change necessary?

2017-04-26 09:04 UTC, jiivan commented on tests/apps/core/benchmark/test_benchmarkrunner.py
> +            benchmark=benchmark,
Thank you :)

2017-04-26 09:04 UTC, jiivan approved these changes
LGTM

2017-04-26 10:11 UTC, mfranciszkiewicz approved these changes

2017-04-26 18:26 UTC, merged