Refactoring part of Incomes Matching PR
golemfactory/clay pull request #1026
Opened 2017-04-26 13:12 UTC by jiivan

Some refactorings that prepare ground for Incomes Matching.

2017-04-26 14:04 UTC, badb requested changes
Very cool, but needs more unittests, especially new Message class and tasksession/taskserver refactor functions.

2017-04-26 14:04 UTC, badb commented on golem/network/transport/message.py
> +class MessageRedefined(Message):
This needs another name. Like MessageWithMapping. Or just Message and we can replace all other messages with this class.

2017-04-26 14:04 UTC, badb commented on golem/task/tasksession.py
>  class TaskSession(MiddlemanSafeSession):
We should increase protocol version here (if we're introducing new type of Messages)

2017-04-26 14:04 UTC, badb commented on golem/task/tasksession.py
> +        self.send(message.MessageReportComputedTask(task_result.subtask_id, task_result.result_type, task_result.computing_time, node_name, address, port, self.task_server.get_key_id(), node_info, et
What line length do you suggest using? Previously we've used 120, right now I'm trying to use 100, but it was never directly specified.

2017-04-27 09:01 UTC, jiivan commented on golem/task/tasksession.py
>  class TaskSession(MiddlemanSafeSession):
Actually new messages will be introduced in second PR. Here the refactoring doesn't change the external representation of Msg.

2017-04-27 09:02 UTC, Elfoniok requested changes
There are errors to fix

2017-04-27 09:02 UTC, Radagast-red commented on golem/task/taskserver.py
> +        self.remove_forwarded_session_request(waiting_task_result.owner_key_id)
Are you sure that key_id is always owner_key_id?

2017-04-27 09:02 UTC, Radagast-red commented on golem/task/taskserver.py
>          if key_id in self.response_list:
key_id not defined here?

2017-04-27 09:02 UTC, Radagast-red commented on golem/task/taskserver.py
> +        self.client.want_to_start_task_session(wating_task_result, key_id, self.node, conn_id)
key_id not defined here? ...."wating" there is no such thing! One more thing you changed passed arguments list, but i don't see modification of Client function definition

2017-04-27 09:17 UTC, jiivan commented on golem/task/tasksession.py
> +        self.send(message.MessageReportComputedTask(task_result.subtask_id, task_result.result_type, task_result.computing_time, node_name, address, port, self.task_server.get_key_id(), node_info, et
[PEP8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) recommends something between 72 and 100 characters. I personally disagree with those limits. I feel that all moderately modern workstations are able to properly display any line length (with or without wrapping). That's why I disabled line length checks in [style checker](https://github.com/golemfactory/golem/blob/develop/golem/testutils.py#L137).

And this diff shows why I feel single lines are easier to maintain. When I added `message` namespace I just didn't want to go ascii arting with [aligned indentation](https://www.python.org/dev/peps/pep-0008/#indentation). That's why I quickly joined all lines. This won't be a problem with simple hanging indents though.

But I'm flexible in this matter. If most of you agree with line length restrictions I will enable them.

2017-04-27 09:23 UTC, jiivan commented on golem/task/taskserver.py
> +        self.remove_forwarded_session_request(waiting_task_result.owner_key_id)
Yes. SEE: https://github.com/golemfactory/golem/pull/1026/files/47a21c8720eecc0be34a7f0e876e273715d67951#diff-58d817e424421f899f53335aa2effd0eL797

2017-04-27 09:31 UTC, Radagast-red commented on golem/task/taskserver.py
> +        self.remove_forwarded_session_request(waiting_task_result.owner_key_id)
What about call site present inside __connection_for_task_result_failure ?

2017-04-27 09:44 UTC, jiivan commented on golem/task/taskserver.py
> +        self.remove_forwarded_session_request(waiting_task_result.owner_key_id)
https://github.com/golemfactory/golem/pull/1026/files/47a21c8720eecc0be34a7f0e876e273715d67951#diff-58d817e424421f899f53335aa2effd0eL535

2017-04-27 10:04 UTC, Radagast-red commented on golem/task/taskserver.py
> +        self.remove_forwarded_session_request(waiting_task_result.owner_key_id)
OK

2017-04-27 10:32 UTC, Radagast-red commented on golem/task/taskserver.py
> +        self.remove_forwarded_session_request(waiting_task_result.owner_key_id)
OK

2017-04-27 18:06 UTC, jiivan commented on tests/golem/task/test_taskserver.py
> +    def test_task_result_connection_failure(self):
@Radagast-red ok?

2017-04-28 10:59 UTC, Radagast-red commented on tests/golem/task/test_taskserver.py
> +    def test_task_result_connection_failure(self):
Ok

2017-04-28 11:02 UTC, Elfoniok approved these changes
As a general note, i understand that you have right in general, But as at least some tools (github for example) poorly support lines longer than 120 columns. I would opt for keeping and formatting code according to this.

2017-04-28 12:14 UTC, badb approved these changes

2017-04-28 12:41 UTC, mfranciszkiewicz commented on golem/model.py
> +        return "<Payment stid: %r v: %.3f s: %r tx: %s>" % (self.subtask, self.value/denoms.ether, self.status, tx)
Maybe it's not a big deal, but `%` formatting is inconsistent with the rest of the project.

2017-04-28 20:05 UTC, merged