Gevent
golemfactory/clay pull request #1031
Opened 2017-04-28 10:07 UTC by Radagast-red

2017-04-28 10:40 UTC, jiivan requested changes
`flake8 --ignore=e501` errors

2017-04-28 10:40 UTC, jiivan commented on golem/node.py
> +            	geventreactor.install()
```
golem/node.py:64:13: E101 indentation contains mixed spaces and tabs
golem/node.py:64:13: W191 indentation contains tabs
golem/node.py:65:13: E101 indentation contains mixed spaces and tabs
golem/node.py:65:13: W191 indentation contains tabs
```

2017-04-28 10:40 UTC, jiivan commented on gui/startapp.py
> +from twisted.internet.error import ReactorAlreadyRunning
```
gui/startapp.py:5:1: F401 'os.path' imported but unused
gui/startapp.py:6:1: F401 'twisted.internet.defer.setDebugging' imported but unused
gui/startapp.py:16:1: F811 redefinition of unused 'ReactorAlreadyRunning' from line 7
```

2017-04-28 10:40 UTC, jiivan commented on gui/startapp.py
> +            geventreactor.install()
```
gui/startapp.py:66:1: E101 indentation contains mixed spaces and tabs
gui/startapp.py:66:1: W191 indentation contains tabs
gui/startapp.py:67:1: E101 indentation contains mixed spaces and tabs
```

2017-04-28 10:40 UTC, jiivan commented on gui/startapp.py
> +    from golem.rpc.router import CrossbarRouter
```
gui/startapp.py:75:5: F811 redefinition of unused 'CrossbarRouter' from line 69
```

2017-04-28 10:40 UTC, jiivan commented on tests/gui/test_startapp.py
> +             patch('golem.reactor.geventreactor.install'), \
Probably better use decorator syntax like this:
```python
@patch('gui.startapp.start_gui')
@patch('golem.reactor.geventreactor.install')
# [...] More all other decorators
def _start_client(self, router_fails=False, session_fails=False, expected_result=None, *mocks):
```


```
tests/gui/test_startapp.py:70:14: E127 continuation line over-indented for visual indent
tests/gui/test_startapp.py:71:14: E127 continuation line over-indented for visual indent
tests/gui/test_startapp.py:72:14: E127 continuation line over-indented for visual indent
tests/gui/test_startapp.py:73:14: E127 continuation line over-indented for visual indent
tests/gui/test_startapp.py:74:14: E127 continuation line over-indented for visual indent
tests/gui/test_startapp.py:75:14: E127 continuation line over-indented for visual indent
```

2017-04-28 13:33 UTC, Radagast-red commented on golem/node.py
> +            	geventreactor.install()
Ok

2017-04-28 13:47 UTC, Radagast-red commented on gui/startapp.py
> +from twisted.internet.error import ReactorAlreadyRunning
Ok

2017-04-28 13:47 UTC, Radagast-red commented on gui/startapp.py
> +    from golem.rpc.router import CrossbarRouter
Ok

2017-04-28 13:47 UTC, Radagast-red commented on tests/gui/test_startapp.py
> +             patch('golem.reactor.geventreactor.install'), \
Please explain it in more details.

2017-04-28 13:47 UTC, Radagast-red commented on gui/startapp.py
> +            geventreactor.install()
Ok

2017-04-28 19:37 UTC, jiivan commented on tests/gui/test_startapp.py
> +             patch('golem.reactor.geventreactor.install'), \
```diff
diff --git a/tests/gui/test_startapp.py b/tests/gui/test_startapp.py
index 740598a..2a287cd 100644
--- a/tests/gui/test_startapp.py
+++ b/tests/gui/test_startapp.py
@@ -62,18 +62,17 @@ class TestStartAppFunc(TestDirFixtureWithReactor):
         assert len(envs) >= 2
 
     def _start_client(self, router_fails=False, session_fails=False, expected_result=None):
-
-        client = None
         queue = Queue()
 
-        with patch('gui.startapp.start_gui'), \
-             patch('golem.reactor.geventreactor.install'), \
-             patch('golem.client.Client.start', side_effect=lambda *_: queue.put(u"Success")), \
-             patch('golem.client.Client.sync'), \
-             patch('gui.startapp.start_error', side_effect=lambda err: queue.put(err)), \
-             patch('golem.rpc.router.CrossbarRouter.start', router_start(router_fails)), \
-             patch('golem.rpc.session.Session.connect', session_connect(session_fails)):
-
+        @patch('gui.startapp.start_gui')
+        @patch('golem.reactor.geventreactor.install')
+        @patch('golem.client.Client.start', side_effect=lambda *_: queue.put(u"Success"))
+        @patch('golem.client.Client.sync')
+        @patch('gui.startapp.start_error', side_effect=lambda err: queue.put(err))
+        @patch('golem.rpc.router.CrossbarRouter.start', router_start(router_fails))
+        @patch('golem.rpc.session.Session.connect', session_connect(session_fails))
+        def inner(*mocks):
+            client = None
             try:
                 client = Client(datadir=self.path,
                                 transaction_system=False,
@@ -89,12 +88,12 @@ class TestStartAppFunc(TestDirFixtureWithReactor):
 
                 message = queue.get(True, 10)
                 assert unicode(message).find(expected_result) != -1
-
             except Exception as exc:
                 self.fail(u"Cannot start client process: {}".format(exc))
             finally:
                 if client:
                     client.quit()
+        return inner()
 
     def _start_gui(self, session_fails=False, expected_result=None):
 ```

2017-05-08 08:51 UTC, jiivan approved these changes
LGTM

2017-05-08 10:11 UTC, paulperegud commented
On fresh virtualenv environment crashes with following when I launch `golemapp`:
```
Traceback (most recent call last):
  File "/home/pawel/.virtualenvs/golem-gevent/local/lib/python2.7/site-packages/crossbar/controller/node.py", line 478, in start
    yield self._startup(self._config)
AssertionError
Unhandled Error
Traceback (most recent call last):
  File "/home/pawel/code/ggolem/golem/golemapp.py", line 51, in start
    start_app(rendering=True, **config)
  File "/home/pawel/code/ggolem/golem/gui/startapp.py", line 120, in start_app
    transaction_system, **config_overrides)
  File "/home/pawel/code/ggolem/golem/gui/startapp.py", line 108, in start_client
    reactor.run()
  File "/home/pawel/.virtualenvs/golem-gevent/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
--- <exception caught here> ---
  File "/home/pawel/code/ggolem/golem/golem/reactor/geventreactor.py", line 369, in mainLoop
    c()
  File "/home/pawel/code/ggolem/golem/golem/reactor/geventreactor.py", line 192, in __call__
    self.func(*self.a, **self.kw)
  File "/home/pawel/.virtualenvs/golem-gevent/local/lib/python2.7/site-packages/gevent/hub.py", line 210, in kill
    if not greenlet.dead:
exceptions.AttributeError: 'NoneType' object has no attribute 'dead'
```

2017-05-08 12:48 UTC, paulperegud commented
LGTM

2017-05-08 12:54 UTC, paulperegud approved these changes

2017-05-10 11:35 UTC, badb commented on tests/golem/test_opt_node.py
> +    @patch('golem.core.common.config_logging')
Can you add this patch also to test_many_peers?

2017-05-10 11:36 UTC, badb approved these changes

2017-05-10 11:50 UTC, Radagast-red commented on tests/golem/test_opt_node.py
> +    @patch('golem.core.common.config_logging')
Done

2017-05-11 12:16 UTC, closed without merging