Denylist
golemfactory/clay pull request #1046
Opened 2017-05-09 16:59 UTC by badb

Add support for deny list. Users should be able to create file with nodes that they don't want to work with. It's not a longterm solution but it will be very useful for further beta testing.

2017-05-10 08:50 UTC, jiivan requested changes

2017-05-10 08:50 UTC, jiivan commented on golem/task/deny.py
> +    return [line.strip() for line in lines]
I suggest returning `set()`/`frozenset()` here. As it works better with bigger sets.

2017-05-10 08:50 UTC, jiivan commented on golem/task/deny.py
> +DENY_LIST_NAME = "deny.ini"
`.ini` extension suggests `ini file format` -> https://docs.python.org/2/library/configparser.html

Though I think your solution with simple node id per line is better. Maybe `.lst` or `.txt` extension?

2017-05-10 08:50 UTC, jiivan commented on golem/task/deny.py
> +        lines = f.readlines()
For potentially bigger sets I suggest:
```python
for line in f:
    blackset.add(line.strip())
```
or `f.xreadlines()`.

2017-05-12 17:12 UTC, mfranciszkiewicz approved these changes

2017-05-12 18:38 UTC, apolikamixitos commented
@badb I've just seen this PR, i checked the code and i saw that there isn't a wildcard support.

Is it possible to add this feature ? Cause i think it could be interesting for groups or companies to use their sort of 'Trusted Nodes' (Whitelisted nodes) and block all others in the meanwhile as long as the issue with shared content will be resolved . What do you think ?

2017-05-15 11:43 UTC, badb commented
@apolikamixitos Golem Ids and not names are used here, so I don't think that wild card mechanism will be useful. 
Whitelist mechanism is a good idea. 
Remember, however, that this is temporary alpha/beta Brass solution. It's not a final mechanism that will allow user to certify apps / developers in Clay

2017-05-15 12:56 UTC, jiivan approved these changes

2017-05-16 15:38 UTC, merged