Load incomplete payments on startup
golemfactory/clay pull request #1080
Opened 2017-05-24 16:27 UTC by jiivan

fixes: #266

2017-05-25 13:44 UTC, chfast reviewed
Looks good apart one concern raised.

But in general we should load all non-confirmed payments, not only awaiting?

2017-05-25 13:44 UTC, chfast commented on golem/ethereum/paymentprocessor.py
> +        if payment in self._awaiting:
When this can happen?

2017-05-26 10:00 UTC, jiivan commented on golem/ethereum/paymentprocessor.py
> +        if payment in self._awaiting:
Hopefully it won't happen, but IMHO it's an easy check, worth adding.

2017-05-26 10:30 UTC, chfast requested changes

2017-05-26 10:30 UTC, chfast commented on golem/ethereum/paymentprocessor.py
> +        if payment in self._awaiting:
For me it is exactly the opposite. The defensive code like this usually hides problems and means we have not idea what our code is doing. I can accept exception here, but not silent break.

2017-05-26 10:54 UTC, chfast approved these changes

2017-05-26 10:55 UTC, chfast commented
:shipit:

2017-05-26 11:12 UTC, merged