Golem tempdir
golemfactory/clay pull request #1085
Opened 2017-05-27 06:55 UTC by chfast

2017-05-29 14:00 UTC, badb requested changes
Some blender benchmark & verification tests fail on this branch on windows. Give me some time to investigate this issue.

2017-05-29 15:04 UTC, badb commented on golem/testutils.py
> +        cls.__root_dir = tempfile.mkdtemp(prefix='golem-tests-')
```
if is_windows():
    import win32api
     cls.__root_dir = win32api.GetLongPathName(cls.__root_dir)
``` should solve the issue

2017-05-30 10:25 UTC, Radagast-red commented
Wouldn't it be better to provide this option from config file?

2017-05-30 15:39 UTC, paulperegud approved these changes

2017-05-30 15:40 UTC, paulperegud commented
works on Linux; haven't managed to test it on Windows

2017-05-30 17:16 UTC, mfranciszkiewicz approved these changes
`test_opt_node` hangs on Windows 10 x64, but merging with `develop` seems to do the trick.

2017-05-30 17:19 UTC, merged