Bmw benchmark
golemfactory/clay pull request #1093
Opened 2017-05-31 09:48 UTC by jiivan

Change blender benchmark to more intensive BMW benchmark from https://www.blender.org/download/demo-files/

2017-06-07 17:03 UTC, badb requested changes

2017-06-07 17:03 UTC, badb commented on README.md
> +* Blender: [scene-Helicopter/BMW](https://www.blender.org/download/demo-files/)
Just BMW

2017-06-07 17:03 UTC, badb commented on tests/golem/docker/test_blender_job.py
> +            "scene_file": str(dest_scene_file),
On windows it's represented as '\golem\resources\cube.blend`, therefore this test fails.

2017-06-08 10:25 UTC, badb reviewed
Two more questions. 
Can you remove gpu version (we're not going to use it now)? 
Can  you make benchmark lighter? Like 2-3 times lighter - you can either decrease the reslution or spp in blender scene.

2017-06-09 11:23 UTC, jiivan commented
I decreased resolution from `1920x1080` to `480x270`. I also decreased sampling->samples->render from 35 to 20. Overall it changed my performance from `~160` to `~400`.

2017-06-16 15:24 UTC, badb approved these changes

2017-06-16 15:52 UTC, merged