Img verificator
golemfactory/clay pull request #1133
Opened 2017-06-20 15:47 UTC by ggruszczynski

2017-07-13 15:28 UTC, badb requested changes
Some issues about style

2017-07-13 15:28 UTC, badb commented on apps/blender/task/blenderrendertask.py
> +        self.test_task_res_path = dm.get_task_test_dir(self.header.task_id) #get_test_task_path(self.root_path)
Remove the commented line, please

2017-07-13 15:28 UTC, badb commented on apps/blender/task/blenderrendertask.py
> +
Unnecessary double extra line

2017-07-13 15:28 UTC, badb commented on apps/blender/task/verificator.py
> -    def _check_size(self, file_, res_x, res_y):
Why do you remove this function?

2017-07-13 15:28 UTC, badb commented on apps/core/task/verificator.py
> +
Not needed.

2017-07-13 15:28 UTC, badb commented on apps/lux/task/luxrendertask.py
> +        self.referenceRuns = 2
https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables Please keep isntance variables lowercase with underscore. Also consider making magic numer 2 constant

2017-07-13 15:28 UTC, badb commented on apps/lux/task/luxrendertask.py
> +    def _get_random_crop_window_for_verification(self,
Consider moving this function to scenefilereader

2017-07-13 15:28 UTC, badb commented on apps/lux/task/luxrendertask.py
> +        # self._temp_save("provscenejob.txt", scene_src)
should be removed?

2017-07-13 15:28 UTC, badb commented on apps/lux/task/verificator.py
> +
Not needed

2017-07-13 15:28 UTC, badb commented on apps/lux/task/verificator.py
> +    # def _advanced_check_files(self, tr_png_files, tr_flm_files):
Remove?

2017-07-13 15:28 UTC, badb commented on apps/lux/task/verificator.py
> +            imgVerificator = ImgVerificator()
img_verificator, please.

2017-07-13 15:28 UTC, badb commented on apps/lux/task/verificator.py
> +from apps.rendering.resources.ImgVerificator import ImgStatistics, ImgVerificator
Try to keep lines no longer then 80 characters. This applies to all changes in this file.

2017-07-13 15:28 UTC, badb commented on apps/rendering/resources/ImgVerificator.py
> +class ImgStatistics:
Use new style classes, please.

2017-07-13 15:28 UTC, badb commented on apps/rendering/resources/ImgVerificator.py
> +    def find_outliers(self, imgStats):
Do you need it?

2017-07-13 15:28 UTC, badb commented on apps/rendering/resources/imgcompare.py
> -
.... and this is needed.

2017-07-13 15:28 UTC, badb commented on apps/rendering/resources/imgcompare.py
> +
Too many empty lines

2017-07-13 15:28 UTC, badb commented on apps/rendering/resources/imgcompare.py
> +
This is not needed:

2017-07-13 15:28 UTC, badb commented on apps/rendering/resources/imgcompare.py
> +        if isinstance(img, PILImgRepr) and isinstance(cmp_img, PILImgRepr): #
Remove "#"

2017-07-13 15:28 UTC, badb commented on apps/rendering/task/verificator.py
> +            if not self.make_advance_verification(file_for_adv_ver, subtask_info, subtask_id, task):
Under 80, please!

2017-07-13 15:28 UTC, badb commented on golem/task/localcomputer.py
> +        self.dirManager = DirManager(root_path)
dir_manager

2017-07-13 15:28 UTC, badb commented on golem/task/localcomputer.py
> +        self.test_task_res_path = self.dirManager.get_task_test_dir("")#self.task.header.task_id)
some cleaning up would be nice

2017-07-13 15:28 UTC, badb commented on golem/task/taskmanager.py
> +
Not needed (same for lines below)

2017-07-13 15:28 UTC, badb commented on tests/apps/rendering/resources/test_imgcompare.py
> +# from apps.rendering.resources.imgcompare import (advance_verify_img,
Just remove it.

2017-07-14 08:14 UTC, ggruszczynski commented on apps/blender/task/verificator.py
> -    def _check_size(self, file_, res_x, res_y):
The override does exactly the same as base function.

2017-07-14 08:31 UTC, ggruszczynski commented on apps/blender/task/verificator.py
> -    def _check_size(self, file_, res_x, res_y):
its is back now

2017-07-19 18:22 UTC, badb commented
It doesn't work for .exr output files. Reference image is always generated with png extension, but final_image_ready checks for default output format.

2017-07-20 17:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=1133) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=1133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=1133) it.</sub>

2017-07-24 14:28 UTC, badb commented
Can  you bring back protocol versions? Also please, don't touch reputation in this branch.

2017-07-24 14:53 UTC, badb commented on apps/lux/task/verificator.py
> +            if task.output_format == "exr":
You can use load_img function from imgrepr

2017-08-02 12:24 UTC, merged