Version for network show
golemfactory/clay pull request #1214
Opened 2017-07-06 21:05 UTC by maaktweluit

Resolves #991 

- Reused `client_ver` in the `HelloMessage`, was it meant for this purpose?
- Default was 0, so left it. Could be `None` or `0.6.0`

`network dht` now also shows the column printing `None`. Is this a new issue or should it be fixed here?

2017-07-12 17:40 UTC, mfranciszkiewicz approved these changes
LGTM

2017-07-18 06:35 UTC, Elfoniok approved these changes

2017-07-24 07:02 UTC, maaktweluit commented
Hey Golem team,

I'm off on holiday for 2 weeks, please continue this issue without me if needed. When back i can fix comments / conflicts.

Have a good one!

Maaktweluit

2017-08-24 15:17 UTC, badb requested changes
There is one change to be made because of version upgrade. Apart from that it looks good and can be merged as soon as verision number in test is fixed.

2017-08-24 15:17 UTC, badb commented on tests/golem/network/p2p/test_peersession.py
> +            'CLI_VER': '0.7.1',
Since we've waited so long and there was a new release, version now is 0.8.0. Can you please change this tests so expected version is get from `golem.core.variables.py`?

2017-08-24 16:47 UTC, maaktweluit commented on tests/golem/network/p2p/test_peersession.py
> +            'CLI_VER': '0.7.1',
Thank you for the reply!

Waiting long should not break the test, hard coding was wrong, thank you for the golden tip to fix it.

Pushed these changes and it is building again.

2017-08-24 18:24 UTC, badb approved these changes

2017-08-24 18:24 UTC, merged