Update for startup process reports
golemfactory/clay pull request #1227
Opened 2017-07-12 13:45 UTC by mfranciszkiewicz

2017-07-17 10:03 UTC, badb requested changes
It somehow messes up with DockerMachine starting process. 
I got 3 warnings:
` WARNING  [golem.docker.manager               ] Docker machine is not available: (-2147221008, 'Funkcja CoInitialize nie zosta\xb3a wywo\xb3ana.', None, None)`
Docker update config is also not properly triggered. Everything works fine on develop branch with same configuration.

2017-07-17 10:45 UTC, mfranciszkiewicz commented
@badb From what you've written, config update seems to be a follow-up issue. The code hasn't changed.

2017-07-17 11:54 UTC, badb approved these changes

2017-07-18 06:34 UTC, Elfoniok approved these changes

2017-08-22 11:33 UTC, banasiakadam60 commented
#1285

2017-08-22 12:41 UTC, banasiakadam60 approved these changes

2017-08-22 13:17 UTC, Elfoniok approved these changes

2017-08-22 14:47 UTC, merged