Reputation cleanup
golemfactory/clay pull request #1248
Opened 2017-08-03 15:03 UTC by ggruszczynski

2017-08-03 15:09 UTC, ggruszczynski commented
main changes:

1) negative trust would cause negative weights which can sum up to 0 later on 
--> (sum_weight += weight).

As for quick fix i changed the trust to be from 0 to 1
__neighbour_weight(local_trust):
    return NEIGHBOUR_WEIGHT_BASE ** (NEIGHBOUR_WEIGHT_POWER * local_trust)

2) it seems that there was a mismatch in def computed_neighbours_rank(node_id, neighbours) and
def requested_neighbours_rank(node_id, neighbours) in usage of requested/computed weights

2017-08-03 17:56 UTC, gborowik approved these changes

2017-08-09 18:02 UTC, gborowik commented
approved!!!

2017-08-21 15:56 UTC, banasiakadam60 commented
@ggruszczynski What's the status? Can it be merged? Or you need to change sth in this PR?

2017-08-24 17:16 UTC, ggruszczynski commented
to prevent mess, it was scheduled to be merged after release

2017-08-24 19:19 UTC, badb requested changes

2017-08-24 19:19 UTC, badb commented on golem/ranking/helper/min_max_utility.py
> +# def count_trust(pos, neg):
Can you remove commented out code?

2017-08-24 19:19 UTC, badb commented on golem/ranking/helper/trust_const.py
> +MIN_TRUST = 0.0
If I understand this properly and we changed trust range from [-1, 1] to [0, 1] then we should change default values in appconfig from -1 to 0 & change the way we scale this value in GUI (old & new). Correct me, if that's not needed.

2017-08-29 16:47 UTC, badb commented
Merge together with: https://github.com/golemfactory/golem-electron/tree/trust_range

2017-09-06 15:47 UTC, merged