Fix ethereum address
golemfactory/clay pull request #1260
Opened 2017-08-14 13:10 UTC by paulperegud

fixes #1243

2017-08-16 09:54 UTC, chfast requested changes

2017-08-16 09:54 UTC, chfast commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +            self.__node_address_raw = privtoaddr(node_priv_key)
Don't use `_raw` suffix. We should keep addresses as raw bytes everywhere and encode on the fly.

2017-08-16 09:54 UTC, chfast commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        return '0x' + encode_hex(self.__node_address_raw)
Is this method needed? If only in UI, let UI to encode it.

2017-08-16 10:58 UTC, paulperegud commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        return '0x' + encode_hex(self.__node_address_raw)
No, we also use it in our network code.
E.g. here https://github.com/golemfactory/golem/blob/develop/golem/task/taskserver.py#L618

2017-08-16 10:58 UTC, chfast approved these changes

2017-08-16 13:39 UTC, ggruszczynski commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        return '0x' + encode_hex(self.__node_address_raw)
why dont use the utility class - EthereumAddress

2017-08-17 09:51 UTC, paulperegud commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        return '0x' + encode_hex(self.__node_address_raw)
It does not know how to handle private keys

2017-08-24 19:53 UTC, badb commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +            client=Client(datadir),
Be careful, during merge you should add "port" here

2017-08-24 19:53 UTC, badb commented on tests/golem/docker/test_docker_luxrender_task.py
> +        task.res_y = 300
Why is this change in this PR? @ggruszczynski Can you please do the merge, because I'm not sure if the version from this PR or from develop should stay.

2017-08-29 16:46 UTC, badb commented
Moved to https://github.com/golemfactory/golem/pull/1316

2017-08-29 16:46 UTC, closed without merging