Dummy task
golemfactory/clay pull request #1278
Opened 2017-08-18 17:08 UTC by inexxt

This PR: 
 - creates dummy task, using old dummy task concept (PoW computations)
 - in particular, dummy task allows for easier code and data for tasks
 - turns off old dummy task tests
 - refactors Tasks structure a little, creating some interfaces and allowing for easier task creation
 - annotates types in a few places
 - adds `enforce` dependency, for strict types checking (it is not enabled by default, and currently only works in the DummyTask class, but because of type annotations can easily be used everywhere)
 - removes randomness from luxrender tests

Known bugs:
 - During task creation, temporary directory is created under /tmp (or equivalent), which is not removed aftrewards. Partial solution to this will be creation of the directory under temp inside task dir, but it has to be done in the Task itself, not in the TaskDefinition.

All tests are passing in principle, but it seems that some server is down and `test_swift_resourcemanager` is currently (temporary?) not working.

2017-08-18 17:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=1278) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=1278) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=1278) it.</sub>

2017-08-24 20:20 UTC, badb commented on apps/dummy/task/dummytaskstate.py
> +        os.symlink(self.code_dir, os.path.join(self.tmp_dir, "code"))
Throws error on Windows when called by unprivileged user. You'll probably need some symlink_or_copy method here.

2017-08-24 20:20 UTC, badb commented on .gitignore
> +luxrender-output.exr
Are those files left by some golem tests?

2017-08-28 11:11 UTC, inexxt commented on .gitignore
> +luxrender-output.exr
They were, I think it's fixed now

2017-08-28 17:40 UTC, inexxt commented
I think it will be necessary to turn off linters this time (or turn it on only for specific files) - because a lot of code is touched in this PR, linters found ~2k warnings and errors.

2017-08-29 17:18 UTC, badb commented on apps/dummy/task/dummytaskstate.py
> +        os.symlink(common_data_path, os.path.join(self.tmp_dir, "data"))
Same problem as above, should be symlink_or_copy

2017-08-29 17:21 UTC, inexxt commented on apps/dummy/task/dummytaskstate.py
> +        os.symlink(common_data_path, os.path.join(self.tmp_dir, "data"))
Fixed

2017-08-29 17:55 UTC, badb commented on tests/golem/logs/golemdocker_test.log.2017-08-09
> +2017-08-09 17:08:47 WARNING  golem.appconfig                     Can't open file /home/jacek/.local/share/golem/SimpleEnv/GOODSETTINGS: [Errno 2] No such file or directory: '/home/jacek/.local/share/
Are these logs needed?

2017-08-29 18:06 UTC, badb commented on tests/apps/dummy/task/test_dummytaskstate.py
> +            assert os.path.islink(os.path.join(td.tmp_dir, "code"))
It will fail on Windows without privilieged mode

2017-08-29 18:18 UTC, inexxt commented on tests/apps/dummy/task/test_dummytaskstate.py
> +            assert os.path.islink(os.path.join(td.tmp_dir, "code"))
Fixed, changed to isdir

2017-08-29 18:22 UTC, inexxt commented on tests/golem/logs/golemdocker_test.log.2017-08-09
> +2017-08-09 17:08:47 WARNING  golem.appconfig                     Can't open file /home/jacek/.local/share/golem/SimpleEnv/GOODSETTINGS: [Errno 2] No such file or directory: '/home/jacek/.local/share/
No, a mistake with commit. All logs deleted now.

2017-09-07 13:47 UTC, banasiakadam60 requested changes

2017-09-07 13:47 UTC, banasiakadam60 commented on apps/core/task/coretask.py
> +            # logger.warning("Subtask %r has wrong type", subtask_id)
Please remove this 3 commented logs

2017-09-07 13:47 UTC, banasiakadam60 commented on apps/dummy/benchmark/benchmark.py
> +        # td.out_file_basename)
Remove or uncomment

2017-09-07 13:47 UTC, banasiakadam60 commented on apps/dummy/benchmark/benchmark.py
> +        td.task_id = u"{}".format("dummy_benchmark")
this:
`td.task_id = u"{}".format("dummy_benchmark")`
is equivalent to to:
`td.task_id = "dummy_benchmark"`
Please change it

2017-09-07 13:47 UTC, banasiakadam60 commented on apps/dummy/gui/controller/dummytaskcustomizer.py
> +logger = logging.getLogger("apps.dummy")
Why do you need logger here? If I'm right, it isn't used

2017-09-07 13:47 UTC, banasiakadam60 commented on apps/dummy/resources/code_dir/computing.py
> +          ', difficulty = 0x%08x' % difficulty)  # TODO remove that print
@TODO?

2017-09-07 13:47 UTC, banasiakadam60 commented on apps/dummy/resources/code_dir/computing.py
> +    print('[DUMMY TASK] computation finished, time =', time.clock() - t0, 'sec')
Should it also be removed?

2017-09-07 13:47 UTC, banasiakadam60 commented on apps/dummy/resources/scripts/docker_dummytask.py
> +WORK_DIR = "/golem/work"  # we don't need that, all the work is done in memory
It isn't used. Should it be removed?

2017-09-07 13:47 UTC, banasiakadam60 commented on tests/apps/lux/task/test_luxrendertask.py
> +        p = Path(__file__).parent.parent.parent / \
IMO more readable will be:
```
        from golem.core.common import get_golem_path
        from os.path import join
        p = join(get_golem_path(), 'tests', "apps",
                  "rendering", "resources", "testfile.EXR")
```

But it's just a suggestion

2017-09-07 13:47 UTC, banasiakadam60 commented on tests/golem/docker/test_docker_dummy_task.py
> +        # DockerTestCase.setUpClass()
Remove comments

2017-09-07 13:47 UTC, banasiakadam60 commented on tests/golem/docker/test_docker_dummy_task.py
> +        # DockerTestCase.tearDownClass()
As above

2017-09-07 14:54 UTC, inexxt commented on apps/dummy/resources/scripts/docker_dummytask.py
> +WORK_DIR = "/golem/work"  # we don't need that, all the work is done in memory
No, I left it here for "educational" purposes (so if someone is swapping his own code in place of `computation.py` and is trying to modify the docker script, he will notice that there is this `WORK_DIR` waiting for him to be used)

2017-09-07 14:55 UTC, inexxt commented on tests/apps/lux/task/test_luxrendertask.py
> +        p = Path(__file__).parent.parent.parent / \
Not really my code, but I can change it.

2017-09-08 09:10 UTC, banasiakadam60 commented on apps/dummy/resources/scripts/docker_dummytask.py
> +WORK_DIR = "/golem/work"  # we don't need that, all the work is done in memory
OK

2017-09-11 13:22 UTC, inexxt commented on apps/dummy/resources/code_dir/computing.py
> +    print('[DUMMY TASK] computation finished, time =', time.clock() - t0, 'sec')
TODO was actually about removing old-style print and using new-style print()

2017-09-11 13:23 UTC, inexxt commented on apps/dummy/resources/code_dir/computing.py
> +          ', difficulty = 0x%08x' % difficulty)  # TODO remove that print
TODO was actually about removing old-style `print` and replacing with new style `print()`

2017-09-11 13:24 UTC, inexxt commented on apps/dummy/gui/controller/dummytaskcustomizer.py
> +logger = logging.getLogger("apps.dummy")
Same as below, *educational* purposes

2017-09-11 13:25 UTC, inexxt commented on apps/dummy/benchmark/benchmark.py
> +        td.task_id = u"{}".format("dummy_benchmark")
Done

2017-09-11 13:25 UTC, inexxt commented on apps/dummy/benchmark/benchmark.py
> +        # td.out_file_basename)
Done

2017-09-11 13:27 UTC, inexxt commented on apps/core/task/coretask.py
> +            # logger.warning("Subtask %r has wrong type", subtask_id)
I didn't know if the function should `raise Exception` or just log the event and go on.
What do you think?

2017-09-11 13:27 UTC, inexxt commented on apps/dummy/resources/code_dir/computing.py
> +    print('[DUMMY TASK] computation finished, time =', time.clock() - t0, 'sec')
Same as above

2017-09-11 13:28 UTC, inexxt commented on tests/golem/docker/test_docker_dummy_task.py
> +        # DockerTestCase.setUpClass()
Done

2017-09-11 13:28 UTC, inexxt commented on tests/golem/docker/test_docker_dummy_task.py
> +        # DockerTestCase.tearDownClass()
Done

2017-09-11 20:14 UTC, badb commented on apps/core/task/coretask.py
> +            # logger.warning("Subtask %r has wrong type", subtask_id)
This function should be called only if the subtasks was really accepted, ie. it was all right. This exception should never be triggered with normal execution, ie. keeping Exception should be better.

2017-09-11 20:14 UTC, badb commented on apps/core/task/coretask.py
> +    ENVIRONMENT_CLASS = None  # type: Type[Environment]
Or maybe default Enironment. Can we keep it with # TODO annotation for now?

2017-09-11 20:16 UTC, badb commented on apps/core/task/coretask.py
> +    def query_extra_data_for_test_task(self) -> ComputeTaskDef:
History... Should be moved to Task

2017-09-11 20:57 UTC, badb commented on apps/dummy/resources/scripts/docker_dummytask.py
> +    with open(result_path, "w") as f:  # TODO try catch and log errors
https://github.com/golemfactory/golem/issues/1353

2017-09-11 21:29 UTC, badb commented on golem/task/tasktester.py
> +    # TODO I think there should be Task, not CoreTask type
https://github.com/golemfactory/golem/issues/1355

2017-09-11 21:29 UTC, badb commented on tests/apps/dummy/gui/controller/test_dummytaskcustomizer.py
> +# TODO
Will be removed with removing GUI part

2017-09-11 21:35 UTC, badb commented on apps/dummy/benchmark/benchmark.py
> +        self._normalization_constant = 1000  # TODO tweak that
https://github.com/golemfactory/golem/issues/1356

2017-09-11 22:01 UTC, badb approved these changes

2017-09-11 22:55 UTC, mfranciszkiewicz commented
3 more tests are failing on macOS in comparison to develop (#1358):
https://gist.github.com/mfranciszkiewicz/57b8a328d98ee59f1149c1f9dddca0d6

2017-09-11 23:07 UTC, mfranciszkiewicz commented
Local test issue:
```
WARNING  [golem.docker.task_thread           ] Task stderr:
Traceback (most recent call last):
  File "/golem/work/job.py", line 33, in <module>
    params.result_file)
  File "/golem/work/job.py", line 23, in run
    result_size)
  File "/golem/resources/code/computing.py", line 58, in run_dummy_task
    solution = find_pow(all_input, difficulty, result_size)
  File "/golem/resources/code/computing.py", line 34, in find_pow
    if check_pow(solution, input_data, difficulty):
  File "/golem/resources/code/computing.py", line 16, in check_pow
    sha.update(input_data.encode(encoding='UTF-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```

2017-09-11 23:54 UTC, mfranciszkiewicz approved these changes
Please fix those (extra) failing tests on macOS.

2017-09-12 13:25 UTC, inexxt commented
Waiting for https://github.com/golemfactory/golem/pull/1362 to be merged first

2017-09-12 13:35 UTC, mfranciszkiewicz commented
Those 3 tests are still failing with #1362

2017-09-12 17:04 UTC, badb commented
We're merging, @inexxt please fix the failing tests with separate PR.

2017-09-12 17:05 UTC, merged

2017-09-13 08:40 UTC, marmistrz commented
@innext why are you using `jsonpickle` in your tests? We intend to remove the dependency altogether, `jsonpickle` was removed from the rest of the codebase in #1254