[WIP] Slow and fast tests
golemfactory/clay pull request #1300
Opened 2017-08-24 17:35 UTC by maaktweluit

Split the testing into 2 suites:
- Fast 
- Slow

The fast tests are run by default, they should contain: code style, compilation, type and unit tests.
The slow tests run only when a  `--runslow` argument is given. This triggers all tests to run, adding integration tests to the list above.

Any test can be added to the "slow" suite by attaching the `@pytest.mark.slow` decorator:
```
import pytest

@pytest.mark.slow
def test_hello_world:
# ...
```

All CI platforms are configured to run the fast test on pull requests with < 2 approvals. All branches and approved pull requests get to endure the slow test.

Known issues:
- Does not re-trigger builds after 2 approvals, leaving the light green

Possible solutions:
- [ ] Investigate if a web-hook on 2 approvals can be configured ( each approval also possible )
- [ ] If above solution does not work: the build can always fail when testing fast

2017-08-26 13:06 UTC, maaktweluit commented
[Found a way](https://gist.github.com/bjhess/2726012) to trigger a webhook on each pull request event.
We should make an endpoint to filter the requests and trigger the build accordingly.

I propose to implement the exit code for now, it can even skip coverage in fast mode.
For the hooks we can make an issue or wait for buildbot to make it better.

2017-08-26 18:39 UTC, maaktweluit commented
Made all agents fail when only fast test ran. Looks like only circle is able to query github today, added a known issue in the main comment.

Also picked #1310 fix to this branch to get proper linting results.

2017-08-28 18:09 UTC, maaktweluit commented
Ready for review!

Builds will only show proper coverage-diff and full green statuses after 2 approvals

2017-09-01 18:18 UTC, maaktweluit commented
Marked some more tests as slow.

On circle this removed 400s compared to the previous build.
On appveyor it only removed 60s, probably due to `@ci_skip`.

Please note 'checks' are red until 2 approvals, unless #1314 happens.

2017-09-06 07:28 UTC, marmistrz commented
The status checks being red has one intrinsic issue. The status checks failing or succeeding makes it easier to find out if my change is not broken. If the status check is always red, people will start to ignore it, finding out that the tests fail only when they're *ready* with a change.

Besides, Circle tests failing will clutter the inbox.

I understand that your intent is to block changes with not enough approvals?

2017-09-06 07:55 UTC, maaktweluit commented
Agree with all points above.
As described in the OP there where 2 solves, use github (statuses and webhooks) OR fail when ran slow.

Also i am not sure if coverage show properly when only parts of the test run.

I propose to leave this pull as is and make a follow up issue to migrate the exit 0 to a new status / webhook call.

2017-09-06 07:57 UTC, marmistrz commented
My idea would be to make the approval check a separate status check, just as the CLA check is.

We could just mark it somewhere that the coverage should be ignored until the full tests run.

2017-09-06 08:08 UTC, maaktweluit commented
the approval check is already native to github, the current problem is using the same status for slow and fast runs.

> Does not re-trigger builds after 2 approvals, leaving the light green

This problem was solved with `exit 1`, and could be solved with a separate status or webhook.

@badb should I change this in this issue or make a follow up?

2017-09-08 16:18 UTC, badb approved these changes

2017-09-12 08:00 UTC, marmistrz requested changes

2017-09-12 08:00 UTC, marmistrz commented on .travis.yml
> +  - if [[ -z "${ARG_RUNSLOW}" ]]; then echo "Not enough approvals."; exit 1; fi
I still believe that failing the tests just because there are not enough approvals is not the right way to do this. This should be properly done using the GitHub hooks.

If the fast CI suite will always fails, people will start ignoring the failing status checks on Circle/Travis. Moreover, people with a CircleCI account (as me, I had a CI there for another project) get an e-mail message whenever a test fails. With the current approach - there'll be a mail flood here.

Additionally, it's sometimes useful to see which is the last commit to pass the test, especially when developing something in a hurry (because it's a blocker)

2017-09-12 08:00 UTC, marmistrz commented on circle.yml
> +    - sudo apt-get install -y gcc-5 g++-5 libfreeimage3 libfreeimage-dev
Separating the dependency requirements is basically a good idea, but will require `apt` to parse the dependency tree twice. I'm not sure if this won't slow down the CI a little (but this may not be a great deal)

2017-09-12 08:00 UTC, marmistrz commented on circle.yml
> +    # Slow tests only on branches and PRs with >= 2 approvals
This is out of date.

2017-09-12 08:00 UTC, marmistrz commented on conftest.py
> +                                  items: list) -> None:
Do you know the type of the items contained in the items? If yes, then you may annotate it as `List[T]`, where `T` is the type.

2017-09-12 08:00 UTC, marmistrz commented on scripts/get-slow-argument.py
> +        req = urllib.request.Request(url, headers={'User-Agent': 'build-bot'})
You may want to use the famous `requests` module, especially that Golem is already using it, it's a little less verbose.

2017-09-12 20:10 UTC, maaktweluit commented on .travis.yml
> +  - if [[ -z "${ARG_RUNSLOW}" ]]; then echo "Not enough approvals."; exit 1; fi
Fully agree, we can fix this in #1365

2017-09-12 20:12 UTC, maaktweluit commented on circle.yml
> +    - sudo apt-get install -y gcc-5 g++-5 libfreeimage3 libfreeimage-dev
good thought!

was thinking here the taskcollector should be a single binary installation

I can fix it if you want, but would propose to leave it.

2017-09-12 20:14 UTC, maaktweluit commented on circle.yml
> +    # Slow tests only on branches and PRs with >= 2 approvals
fixed 3x

2017-09-12 21:03 UTC, maaktweluit commented on conftest.py
> +                                  items: list) -> None:
nope, but would love to find out.
Looked it up and seems like `List[_pytest.Item]` from [source](https://github.com/pytest-dev/pytest/blob/e57cc5571979009f0dd7ec447891d7ab761a93d5/_pytest/main.py#L534)
Do you know an easy reference for looking types up?
Also i see currently the `list` is without capital, does this matter for python typing?

2017-09-12 21:12 UTC, maaktweluit commented on scripts/get-slow-argument.py
> +        req = urllib.request.Request(url, headers={'User-Agent': 'build-bot'})
thanks for the tip, replaced it super easily.

2017-09-13 07:53 UTC, maaktweluit commented
ready for another round of reviews.

travis fails in a weird way, can not reproduce on my mac.
will look into this and the next comments tonight.

2017-09-13 08:46 UTC, marmistrz commented on conftest.py
> +                                  items: list) -> None:
If you are not sure, you can always try `enforce`. `List` (capital) is simply a generic version of `list`. By specifying the contained type you can get extra checks, but in a helper script it's not a big deal.

As for looking types up.... welcome to Python! :) There's basically no such way, since the essence of Python is dynamic duck-typing. What you can do is:
* inspect the code
* use `print(type(foo))` to find out what the type is in runtime
* use `enforce` to validate your hypotheses
* ask colleagues

2017-09-13 08:49 UTC, marmistrz commented on circle.yml
> +    - sudo apt-get install -y gcc-5 g++-5 libfreeimage3 libfreeimage-dev
leaving this up to you, it shouldn't be a big deal either. If we're going to move to our own Docker image, then we can leave it.

CircleCI 2.0 uses Docker anyway, the image circleci/classic:latest by default, I don't know about 1.0 (which we're using right now)

2017-09-13 08:53 UTC, marmistrz commented
From travis:
```
Traceback (most recent call last):
  File "scripts/get-slow-argument.py", line 27, in <module>
    result = [a for a in json_data if a["state"] == "APPROVED"]
  File "scripts/get-slow-argument.py", line 27, in <listcomp>
    result = [a for a in json_data if a["state"] == "APPROVED"]
TypeError: string indices must be integers
```
Looks like some type mismatch, it may be a good idea to print the response.

Note that some tests may fail due to #1278 having been merged.

2017-09-13 16:42 UTC, maaktweluit commented on conftest.py
> +                                  items: list) -> None:
Thanks for the great tips!

Updated it and it seems to work when running and linting it.

2017-09-17 12:43 UTC, maaktweluit commented
Lowered the required approvals to 1 and fixed travis!

2017-09-28 12:31 UTC, badb reviewed
Test

2017-09-28 12:31 UTC, badb requested changes
Test

2017-09-28 12:54 UTC, maaktweluit commented
removing the approval keeps it on the API:
https://api.github.com/repos/golemfactory/golem/pulls/1300/reviews

We should make the script smarter to only look at the last entry per user/reviewer.

2017-09-28 13:04 UTC, badb approved these changes

2017-09-28 13:43 UTC, Wolf480pl submitted a review, later dismissed
I want these slow tests split ASAP so accept.

2017-09-28 14:32 UTC, badb commented
@maaktweluit Hm, it seems now that slow tests are always skipped, doesn't matter how many approvals they have. Can you check this out?

2017-09-28 16:14 UTC, maaktweluit commented
@badb it looks like the old approval remains in the list, so the un-approval does not override it.
https://api.github.com/repos/golemfactory/golem/pulls/1300/reviews

Will have a look if i can remove duplicates ( per user ) before checking the approval count

2017-09-28 16:43 UTC, maaktweluit commented
@badp resolved in latest commit, it only takes the last "vote" of each user now

love python!

2017-09-29 13:34 UTC, badb commented
Ok, but still slow (dummy) tests are skipped, even though there are 2 approvals.

2017-09-29 13:57 UTC, maaktweluit commented
@badb they are skipped for a different reason:
```
SKIP [1] tests/golem/task/dummy/test_dummy_task.py:9: It doesn't work, using new dummy task instead
```

Want me to remove these skips? not sure what the impact will be, the message states it does not work.

2017-09-29 14:29 UTC, badb requested changes
Test

2017-10-01 13:51 UTC, badb approved these changes

2017-10-01 16:53 UTC, merged