Lintdiff improvements
golemfactory/clay pull request #1308
Opened 2017-08-25 14:40 UTC by marmistrz

Additionally, reformat with the script with shfmt

2017-08-28 14:07 UTC, banasiakadam60 requested changes

2017-08-28 14:07 UTC, banasiakadam60 commented on lintdiff.sh
> +usage() {
Is it used anywhere? Maybe you should add `-h/--help` option?

2017-08-28 14:07 UTC, banasiakadam60 commented on lintdiff.sh
> +while getopts "b:" opt; do
If you want to parse arguments, please make sure, that you handel all options. Right now, in case of typo, eg
`./lintdiff.sh b develop` instead of `./lintdiff.sh -b develop`
everything fails:
```adam@adam:~/Repo/temp/golem(lintdiff) [16:05:02] $ ./lintdiff.sh b develop
Fetching new changes from develop...
Note: checking out 'origin/develop'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 438de66e... Img verificator (#1133)
Checking branch origin/develop, commit: 438de66edbe00b7ae7e7284b51d91a4b90c7d213...
b develop
./lintdiff.sh: linia 53: b: nie znaleziono polecenia
HEAD is now at 438de66e Img verificator (#1133)
Previous HEAD position was 438de66e... Img verificator (#1133)
Switched to branch 'lintdiff'
Your branch is up-to-date with 'origin/lintdiff'.
Checking branch lintdiff, commit: e3a95583a5902b4fa3fa858a70dd2fa83450cc4a...
b develop
./lintdiff.sh: linia 63: b: nie znaleziono polecenia
HEAD is now at e3a95583 Fix changes being lost if they were to be overwritten by switching branches
Already on 'lintdiff'
Your branch is up-to-date with 'origin/lintdiff'.
Check OK, no new findings...
adam@adam:~/Repo/temp/golem(lintdiff) [16:06:14] $
```

This is a place where you can call `usage` (see this https://github.com/golemfactory/golem/blob/develop/Installer/Installer_Linux/install.sh#L313)

2017-08-28 14:37 UTC, banasiakadam60 submitted a review, later dismissed
Additionally please use `${VARIABLE}` instead of `$VARIABLE`, it's more readable

2017-08-28 15:22 UTC, marmistrz commented on lintdiff.sh
> +while getopts "b:" opt; do
That's expected. This means: execute `b develop`.
I can't know if the user has an alias `b` for some tool.

2017-08-29 10:04 UTC, banasiakadam60 approved these changes

2017-08-29 10:14 UTC, merged