Eth payment matching v2
golemfactory/clay pull request #1316
Opened 2017-08-29 08:27 UTC by ggruszczynski

2017-09-06 09:24 UTC, jiivan commented on golem/ethereum/paymentprocessor.py
> +    DEFAULT_DEADLINE = 10  # todo GG changed to speed up life-tests ;)  10 * 60
Should this go to production?

2017-09-06 09:24 UTC, jiivan commented on golem/ethereum/paymentprocessor.py
> +    def __check(self):
Why the migration to double underscore instance method? Is it used anywhere outside `synchronized` method?

2017-09-06 09:24 UTC, jiivan commented on golem/ethereum/paymentprocessor.py
> +    def raw_address(self, privkey):
I think this oneliner method unnecessarily complicates logic. I would prefer using `keys.privtoaddr` directly when it's needed.

2017-09-06 09:24 UTC, jiivan commented on golem/ethereum/paymentprocessor.py
> +        return self.enc_address(self.__privkey, zpad)
Is this oneliner method really needed?

2017-09-06 09:24 UTC, jiivan commented on golem/network/p2p/peersession.py
> +P2P_PROTOCOL_ID = 14666  # todo GG remove in release
?

2017-09-06 09:24 UTC, jiivan commented on golem/task/taskserver.py
> +            session_cbk=lambda session,
line ending

2017-09-06 09:24 UTC, jiivan commented on golem/task/taskserver.py
> +            session_cbk=lambda session,
line ending

2017-09-06 09:24 UTC, jiivan commented on golem/task/taskserver.py
> +                'task_request']: self.__connection_for_task_request_established,
Maybe breaking after colon (`: \`) would be more readable?

2017-09-06 09:24 UTC, jiivan commented on golem/task/tasksession.py
> +TASK_PROTOCOL_ID = 15666  # todo GG remove in release
?

2017-09-06 09:24 UTC, jiivan commented on golem/transactions/ethereum/ethereumincomeskeeper.py
> +    def __init__(self, processor: PaymentProcessor) -> None:
Result typing here is unnecessary as the `__init__()` result is ignored in python.

2017-09-06 09:24 UTC, jiivan commented on golem/transactions/ethereum/ethereumincomeskeeper.py
> +                             "{}".format(e))
I suggest using percent formatting in logger: https://gist.github.com/jiivan/eedb505574ccb2503af48fa2e3043036

2017-09-06 09:24 UTC, jiivan commented on golem/transactions/ethereum/ethereumincomeskeeper.py
> +                             "{}".format(e))
Also consider using `exc_info` argument of logger or `.exception()` method.

2017-09-06 09:24 UTC, jiivan commented on golem/transactions/ethereum/ethereumincomeskeeper.py
> +        while not is_synchronized:
Why not directly calling `while not self.processor.synchronized():`?
Is it possible that code will hang in this loop forever?

2017-09-06 09:24 UTC, jiivan commented on golem/transactions/ethereum/ethereumincomeskeeper.py
> -        # signed int
Will be good to actually test this overflow with hex encoded field in db. :)

2017-09-06 09:24 UTC, jiivan commented on golem/transactions/ethereum/ethereumpaymentskeeper.py
> +class EthAccountInfo(object):
:+1:

2017-09-06 09:24 UTC, jiivan commented on golem/transactions/transactionsystem.py
> +                 incomes_keeper_class=IncomesKeeper()):
First of all it's no longer a class but an instance of a class.

Secondly this will instantiate those classes during definition of `TransactionSystem`. Therefore every instance of `TransactionSystem` with default parameters will use the same instances of payments/incomes keepers. Is this intended? It can be misleading.

2017-09-06 09:24 UTC, jiivan commented on tests/golem/test_model.py
> -class TestReceivedPayment(DatabaseFixture):
Is this test no longer needed?

2017-09-06 09:24 UTC, jiivan commented on tests/golem/transactions/ethereum/test_ethereumincomeskeeper.py
> +    # def test_transaction_overflow(self):
Are you sure this overflow won't occur? If you think this test is no longer needed the please remove it. If not, please uncommment it.

2017-09-06 09:45 UTC, ggruszczynski commented on golem/ethereum/paymentprocessor.py
> +    DEFAULT_DEADLINE = 10  # todo GG changed to speed up life-tests ;)  10 * 60
# todo GG are my personalized notes, they won't go to production :)

2017-09-06 09:52 UTC, ggruszczynski commented on golem/ethereum/paymentprocessor.py
> +    def __check(self):
lets keep the original version

2017-09-06 09:59 UTC, ggruszczynski commented on golem/transactions/ethereum/ethereumincomeskeeper.py
> +    def __init__(self, processor: PaymentProcessor) -> None:
huehe, tell it to pylint/mypy :p

2017-09-06 10:14 UTC, ggruszczynski commented on golem/ethereum/paymentprocessor.py
> +        return self.enc_address(self.__privkey, zpad)
fixed

2017-09-06 10:14 UTC, ggruszczynski commented on golem/ethereum/paymentprocessor.py
> +    def raw_address(self, privkey):
fixed

2017-09-06 10:19 UTC, ggruszczynski commented on golem/task/taskserver.py
> +            session_cbk=lambda session,
result of auto-reformat...

2017-09-06 10:20 UTC, ggruszczynski commented on golem/task/taskserver.py
> +            session_cbk=lambda session,
result of auto-reformat...

2017-09-06 10:23 UTC, ggruszczynski commented on golem/task/taskserver.py
> +                'task_request']: self.__connection_for_task_request_established,
result of auto-reformat...

2017-09-12 16:50 UTC, badb commented on golem/ethereum/paymentprocessor.py
> +    DEFAULT_DEADLINE = 10  # todo GG changed to speed up life-tests ;)  10 * 60
So can you make it production ready?

2017-09-12 17:47 UTC, ggruszczynski commented on golem/ethereum/paymentprocessor.py
> +    DEFAULT_DEADLINE = 10  # todo GG changed to speed up life-tests ;)  10 * 60
I will notify you once its ready for review.

2017-09-21 14:40 UTC, badb commented on golem/model.py
> +    description = TextField(default="")
This on was removed, please don't add it back

2017-09-21 15:16 UTC, badb commented on golem/transactions/ethereum/ethereumincomeskeeper.py
> +            receiver = income_log['topics'][2]
Are you sure that this change is saved?

2017-09-21 15:19 UTC, badb commented on golem/transactions/transactionsystem.py
> +    def __init__(self, payments_keeper_class=PaymentsKeeper(),
Can you change the names from `payment_keeper_class` to `payment_keeper` if  you are changing the behaviour?

2017-09-21 15:23 UTC, badb requested changes
Few small changes requested (ie. variable name, unnecessary variable in model, one check) 

I was not able to produce situation where I saw income actually being noted. Any suggestions? 

Apart from that changes are all right, for sure they are not making situation worse & can be merged.

2017-09-21 17:28 UTC, ggruszczynski commented on golem/model.py
> +    description = TextField(default="")
fixed, it was artefact from previous branch (fix_ethereum_address)

2017-09-21 17:28 UTC, ggruszczynski commented on golem/transactions/transactionsystem.py
> +    def __init__(self, payments_keeper_class=PaymentsKeeper(),
done

2017-09-21 17:28 UTC, ggruszczynski commented on golem/transactions/ethereum/ethereumincomeskeeper.py
> +            receiver = income_log['topics'][2]
what do you mean?

2017-09-21 17:32 UTC, ggruszczynski commented
I was not able to produce situation where I saw income actually being noted. Any suggestions?
Re:
I will retest on Monday.
I always check whether the Provider was informed about the payment:tasksession._react_to_subtask_payment and that the Requestor informs him: tasksession.inform_worker_about_payment()

2017-09-25 11:28 UTC, badb approved these changes

2017-09-25 13:21 UTC, merged