Limit `cpu_count` for vm to 32 due to VBox limitations
golemfactory/clay pull request #1332
Opened 2017-08-31 09:54 UTC by banasiakadam60

Signed-off-by: Adam Banasiak <banasiakadam60@gmail.com>

2017-08-31 10:03 UTC, banasiakadam60 commented
From [VBox Manual](http://download.virtualbox.org/virtualbox/5.1.26/UserManual.pdf)
On page 14
```
– Guest multiprocessing (SMP). VirtualBox can present up to 32 virtual CPUs to each
virtual machine, irrespective of how many CPU cores are physically present on your
host.
```

Section `3.4.2` (page 51)
```
Starting with version 3.0, VirtualBox supports symmetrical multiprocessing (SMP)
and can present up to 32 virtual CPU cores to each virtual machine.
```

2017-09-01 15:58 UTC, banasiakadam60 commented
Can it be merged?

2017-09-01 17:16 UTC, mfranciszkiewicz requested changes

2017-09-01 17:16 UTC, mfranciszkiewicz commented on apps/blender/resources/scripts/docker_blendertask.py
> +def get_cpu_count():
The script in question is executed inside a Docker container. These constraints are ineffective, because `cpu_count` will be limited by the VM (Windows, macOS) or cgroup (Linux).

2017-09-01 17:16 UTC, mfranciszkiewicz commented on apps/lux/resources/scripts/docker_luxtask.py
> +def get_cpu_count():
Same as `docker_blendertask.py`

2017-09-01 17:16 UTC, mfranciszkiewicz commented on golem/core/hardware.py
>          return affinity[:-1] or affinity
This will list available / assigned CPU cores that may go well above VirtualBox limits. Not available on macOS.

2017-09-01 17:34 UTC, banasiakadam60 commented on apps/blender/resources/scripts/docker_blendertask.py
> +def get_cpu_count():
Done

2017-09-01 17:34 UTC, banasiakadam60 commented on apps/lux/resources/scripts/docker_luxtask.py
> +def get_cpu_count():
Done

2017-09-01 17:34 UTC, banasiakadam60 commented on golem/core/hardware.py
>          return affinity[:-1] or affinity
Fixed

2017-09-01 20:21 UTC, badb approved these changes

2017-09-06 09:28 UTC, mfranciszkiewicz approved these changes

2017-09-06 09:47 UTC, merged