A little of refactor in task manager and task keeper
golemfactory/clay pull request #1366
Opened 2017-09-13 09:36 UTC by marmistrz

2017-09-25 12:32 UTC, jiivan requested changes

2017-09-25 12:32 UTC, jiivan commented on golem/task/taskmanager.py
> +def log_subtask_key_error(*args):
Unless you change `golem.core.common.HandleError.__call__` decorator it won't work. What is the reason of this change?

2017-09-25 12:32 UTC, jiivan commented on golem/task/taskmanager.py
> +def log_task_key_error(*args):
Unless you change `golem.core.common.HandleError.__call__` decorator it won't work. What is the reason of this change?

2017-09-25 13:00 UTC, marmistrz commented on golem/task/taskmanager.py
> +def log_task_key_error(*args):
This was fixed while merging @Wolf480pl's change: https://github.com/golemfactory/golem/commit/56a7944f9305666dfdada0d3870ea394b1668d5e

2017-10-27 10:00 UTC, maaktweluit reviewed
LGTM!

When FIXME is fixed ( or made as issue ) will approve

2017-10-27 10:00 UTC, maaktweluit commented on golem/task/taskmanager.py
> +        except Exception:
Maybe catch a more specific exception if possible?

2017-10-27 10:20 UTC, jiivan commented
Closed in favor of #1581

2017-10-27 10:20 UTC, closed without merging