Remove from preview for tasks in frames #896
golemfactory/clay pull request #1379
Opened 2017-09-14 13:51 UTC by jiivan

fixes: #896

2017-09-19 12:02 UTC, marmistrz commented on apps/rendering/task/framerenderingtask.py
> +    def _remove_from_preview(self, subtask_id):
It may be a good idea to annotate the type of `subtask_id`. It's very far from being obvious.

2017-09-20 15:26 UTC, gborowik commented
@jiivan Why circleci and travis did fail?

2017-09-21 12:44 UTC, jiivan commented
@gborowik CircleCI passed after merging with develop. Travis failed because of premature dependency removal in `requirements-test.txt`. Fixed.

2017-09-22 16:02 UTC, gborowik approved these changes

2017-10-08 20:01 UTC, Elfoniok requested changes

2017-10-08 20:01 UTC, Radagast-red commented on apps/rendering/task/framerenderingtask.py
> +        if not isinstance(self.preview_file_path, list):
didn't we agree that isinstance is inherently wrong? what if someone change this to set? for example.

2017-10-08 20:01 UTC, Radagast-red commented on golem/interface/cli.py
> +            print(namespace)
What for print statments?

2017-10-08 20:01 UTC, Radagast-red commented on golem/interface/cli.py
> +        formatter = self.get_formatter(clean)
Why this is taken out of try block?

2017-10-08 20:01 UTC, Radagast-red commented on golem/interface/cli.py
> +        if not hasattr(clean, 'callback'):
I don't thin it is necessary, is it? Some previous bug caused that some function threw exception here but it will be fixed after transferring some fixes from devp2p branch.

2017-10-08 20:01 UTC, Radagast-red commented on golem/interface/cli.py
> +            traceback.print_exc()
why print it here?

2017-10-09 07:43 UTC, jiivan commented on apps/rendering/task/framerenderingtask.py
> +        if not isinstance(self.preview_file_path, list):
In this case it has to be ordered sequence (ordering matters). Added check for `tuple`.

2017-10-09 07:43 UTC, jiivan commented
@Radagast-red `golem/interface/cli.py` was added by accident. Thanks for pointing this out.

2017-10-09 10:18 UTC, Elfoniok approved these changes

2017-10-09 10:28 UTC, merged