Fixing duplication of task temp directory creation
golemfactory/clay pull request #1391
Opened 2017-09-15 19:45 UTC by inexxt

Task temp dir was created in two places: in `initialize()` in `Task` and in `add_new_task` in `TaskManager`.

This PR removes the `TaskManager` one.

2017-09-18 10:25 UTC, marmistrz requested changes

2017-09-18 10:25 UTC, marmistrz commented on apps/core/task/coretask.py
>          self.tmp_dir = dir_manager.get_task_temporary_dir(self.header.task_id, create=True)
Can you fix the line-too-long warning here, since you're touching this code anyway?
And check if `dir_manager` is of class `DirManager`, if yes - annotate the types. This should be trivial using `enforce`.

2017-09-18 10:25 UTC, marmistrz commented on golem/task/taskmanager.py
> -
Since you're touchting `add_new_task`, can you fix the `pycodestyle` warning at line 151?

2017-09-18 16:08 UTC, inexxt commented on golem/task/taskmanager.py
> -
Done

2017-09-18 16:14 UTC, marmistrz commented
I'd squash those two style commits into one, so that there is a total of 2 commits.

2017-11-06 11:28 UTC, maaktweluit approved these changes
LGTM

2018-01-10 16:42 UTC, badb approved these changes

2018-01-10 16:43 UTC, merged