Add a possibility to export keys
golemfactory/clay pull request #1410
Opened 2017-09-21 15:42 UTC by marmistrz

Closes #741.

2017-09-24 12:55 UTC, chfast commented
@marmistrz Are you still planning to finish this?

If yes, can you separated changes related to Python types from functional changes?

2017-09-25 11:04 UTC, marmistrz commented
@chfast This seems finished to me. As for the Python type changes, they are neatly separated into distinct commits.

2017-09-25 13:35 UTC, chfast requested changes

2017-09-25 13:35 UTC, chfast commented on golem/rpc/mapping/aliases.py
> +class Golem:
Why are you removing this?

2017-09-25 13:35 UTC, chfast commented on golem/interface/client/account.py
> +    # that's in fact golem.rpc.session.Client, which is created dynamically,
Please write comments as sentences: start with a capital letter, end with a full stop.

2017-09-25 13:35 UTC, chfast commented on golem/interface/client/tasks.py
> +    # that's in fact golem.rpc.session.Client, which is created dynamically,
Please write comments as sentences: start with a capital letter, end with a full stop.

2017-09-25 13:35 UTC, chfast commented on golem/interface/client/account.py
> +        client = Account.client
Is it worthy to copy the client reference?

2017-09-25 13:35 UTC, chfast commented on golem/interface/client/account.py
> +            print("An error occurred...")
Maybe "Saving keys failed!"?

2017-09-25 13:35 UTC, chfast commented on golem/interface/client/account.py
> +            print("Saving the results failed: {}".format(err.args[1]))
Maybe "Saving the keys failes..."?

2017-09-25 13:35 UTC, chfast commented on golem/interface/client/account.py
> +    @command(arguments=(privkey, pubkey), help="Export the keys")
We must specify exactly what kind of keys they are. @badb can you help with this?

2017-09-25 15:42 UTC, marmistrz commented on golem/rpc/mapping/aliases.py
> +class Golem:
Because it's redundant now. All the classes are new-style in Python 3.

2017-09-25 15:42 UTC, marmistrz commented on golem/interface/client/account.py
> +            print("Saving the results failed: {}".format(err.args[1]))
Of course that should be keys, not results.

2017-09-26 15:11 UTC, Wolf480pl commented on golem/rpc/mapping/aliases.py
> +class Golem:
Explicit is better than implicit

2017-09-27 08:08 UTC, marmistrz commented on golem/rpc/mapping/aliases.py
> +class Golem:
Tell it the Python authors: https://docs.python.org/3.1/tutorial/classes.html

2017-09-27 10:23 UTC, chfast commented on golem/rpc/mapping/aliases.py
> +class Golem:
I agree with @marmistrz on this. I forgot that `class C(object)` and `class C` is same in Py3.

2018-11-28 17:11 UTC, closed without merging