Disconnect peers which have invalid port or address information
golemfactory/clay pull request #1445
Opened 2017-10-06 09:27 UTC by Radagast-red

Signed-off-by: Lukasz Foniok <lukaszfoniok@gmail.com>

2017-10-06 09:44 UTC, jiivan approved these changes

2017-10-06 09:44 UTC, jiivan commented on golem/network/p2p/peersession.py
> +P2P_PROTOCOL_ID = 24
?

2017-10-06 09:44 UTC, jiivan commented on golem/network/p2p/peersession.py
> +                self.disconnect(PeerSession.DCRNotValid)
maybe `return` after `disconnect()`. In this way we can reduce indentation of the remaining of this method.

2017-10-10 21:38 UTC, maaktweluit requested changes
one small comment, besides LGTM

2017-10-10 21:38 UTC, maaktweluit commented on golem/network/p2p/peersession.py
>              else:
`else` after a single `if` ending in  `return` doest not add anything

2017-10-10 21:39 UTC, maaktweluit approved these changes

2018-01-10 12:49 UTC, closed without merging