Resource handshake [WIP]
golemfactory/clay pull request #1446
Opened 2017-10-06 09:57 UTC by mfranciszkiewicz

TBD

2017-10-11 17:17 UTC, gborowik commented
Travis failed:
"/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! (RuntimeError)
The command "brew install python3 qt5 openexr freeimage" failed and exited with 1 during .
Your build has been stopped.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found"

2017-10-11 20:14 UTC, mfranciszkiewicz commented
@gborowik Yes, this issue is affecting all PRs

2017-10-12 09:26 UTC, gborowik approved these changes

2017-10-12 10:26 UTC, jiivan requested changes
My main issue is the usage of obsolete external `mock` package.

2017-10-12 10:26 UTC, jiivan commented on golem/core/variables.py
> +APP_VERSION = "0.8.1"
If `TASK_PROTOCOL_ID` changes we should bump minor version not patch.

2017-10-12 10:26 UTC, jiivan commented on golem/resource/resourcehandshake.py
> +            traceback.print_exc()
Isn't it enough to just use logger in `_handshake_error()`?

2017-10-12 10:26 UTC, jiivan commented on golem/task/tasksession.py
> -    def request_task(
Isn't it still referenced in `golem/task/taskserver.py`?

2017-10-12 10:26 UTC, jiivan commented on tests/golem/resource/test_resourcehandshake.py
> +from mock import Mock, patch, ANY
Since python3 `mock` is part of standard library in `unittest.mock`. We shouldn't use external package.

2017-10-12 10:26 UTC, jiivan commented on tests/golem/resource/test_resourcehandshake.py
> +    def __create_task_server(self, session):
Why using the double underscore here?

2017-10-12 10:26 UTC, jiivan commented on tests/golem/resource/test_resourcehandshake.py
> +        )
maybe `session = MockTaskSession(self.tempdir)` and following initialization could be put here in `setUp()`? It is used in all tests in this TestCase.

2017-10-12 10:31 UTC, mfranciszkiewicz commented on golem/core/variables.py
> +APP_VERSION = "0.8.1"
This updates the version according to the latest tag, for some reason `develop` is still in `0.8.0`. I will abstain from bumping the version above the limit here.

2017-10-12 10:32 UTC, mfranciszkiewicz commented on golem/task/tasksession.py
> -    def request_task(
It's been moved to the parent (mixin) class.

2017-10-12 10:36 UTC, mfranciszkiewicz commented on golem/resource/resourcehandshake.py
> +            traceback.print_exc()
Probably, in most cases, yes.

2017-10-12 10:36 UTC, mfranciszkiewicz commented on tests/golem/resource/test_resourcehandshake.py
> +    def __create_task_server(self, session):
I don't see why this cannot be a private(ish) function.

2017-10-12 10:40 UTC, mfranciszkiewicz commented on tests/golem/resource/test_resourcehandshake.py
> +        )
But sometimes with different parameters (emulating successful resource downloads / uploads).

2017-10-13 15:44 UTC, badb approved these changes

2017-10-13 17:05 UTC, jiivan approved these changes

2017-10-20 17:43 UTC, merged