Check version updates (#1430)
golemfactory/clay pull request #1447
Opened 2017-10-06 12:11 UTC by mdtanrikulu

2017-10-08 20:43 UTC, Elfoniok requested changes

2017-10-08 20:43 UTC, Radagast-red commented on golem/version.py
> +        response.raise_for_status()
Where you catch exception threw here?

2017-10-08 20:43 UTC, Radagast-red commented on golem/version.py
> +    latest_release = max(response.json(), key=lambda ev: ev['tag_name'])
Don't you get strings from here?  If so max can not work well

2017-10-08 20:43 UTC, Radagast-red commented on golem/version.py
> +    if latest_version > current_version:
Same here if you compare strings 10 version will be lower than 9

2017-10-08 20:43 UTC, Radagast-red commented on golem/version.py
> +    return True
What does it mean to return True here?

2017-10-09 09:55 UTC, mdtanrikulu commented on golem/version.py
> +    if latest_version > current_version:
This is the feature of [semantic_version](https://pypi.python.org/pypi/semantic_version/) package. `Version` classes easily comparable with simple comparison operators.

2017-10-09 10:06 UTC, mdtanrikulu commented on golem/version.py
> +        response.raise_for_status()
Requests(v2.8.0 >=) library has it's own exception handling, if status code is not one of the success codes 2xx , it will raise exception.

2017-10-09 10:11 UTC, Radagast-red commented on golem/version.py
> +    if latest_version > current_version:
Ok great

2017-10-09 10:11 UTC, Radagast-red commented on golem/version.py
> +        response.raise_for_status()
Yes so? where you are going to catch those exceptions? I can see you are catching this in tests, buy what for client? or even RPC call?

2017-10-09 10:53 UTC, mdtanrikulu commented on golem/version.py
> +        response.raise_for_status()
On RPC call there's an exception handling but for CLI there's no, so I'll fix it soon.

2017-10-09 10:56 UTC, mdtanrikulu commented on golem/version.py
> +    return True
If the current version is latest one, just returned boolean instead of sending json message about it, and I'll check the type on client-side if message is boolean or not.

2017-10-09 10:59 UTC, Radagast-red commented on golem/version.py
> +    return True
Can you add a comment to this function?

2017-10-09 12:21 UTC, mdtanrikulu commented on golem/version.py
> +    return True
Sure.

2017-10-09 16:25 UTC, Elfoniok approved these changes

2017-10-11 12:28 UTC, jiivan commented on golemcli.py
> +        print(e)
`traceback.print_exc()`

2017-11-08 09:15 UTC, maaktweluit commented
@jiivan @mdtanrikulu this looks like a duplicate of PR #1479 can this be closed or is it different?

2018-01-05 12:45 UTC, mdtanrikulu commented
Yeap duplicate, we can close it.

2018-01-05 12:50 UTC, closed without merging