Move linux unit tests to buildbot
golemfactory/clay pull request #1455
Opened 2017-10-09 17:20 UTC by maaktweluit

First step in #1400 

Adds the linux unit tests to the buildbot:
- Installs the dependencies with ansible
- Adds `test_factory` with all test steps from circleci
- Needed test-daemon scripts, buildbot does not start background tasks

TODO:
- [ ] When cancelling the build the daemons remain running, maybe kill on start as well?
- [ ] Requires #1301 to be merged, else the tests will fail on the linux server based on error in the description.

2017-10-09 17:24 UTC, maaktweluit commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +            repourl='https://github.com/maaktweluit/golem.git',
When TODO is fixed will update this back.

2017-10-15 19:24 UTC, Elfoniok requested changes

2017-10-15 19:24 UTC, Radagast-red commented on scripts/test-daemon-start.sh
> +#!/bin/sh
What for are this scripts?

2017-10-15 19:24 UTC, Radagast-red commented on scripts/test-daemon-stop.sh
> +#!/bin/sh
How this script is used?

2017-10-15 19:24 UTC, Radagast-red commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +- name: Install ipfs
Where do you use IPFS?

2017-10-15 19:24 UTC, Radagast-red commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +    name: ethereum
What version of geth this will install?

2017-10-15 19:24 UTC, Radagast-red commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +                    command=['scripts/test-daemon-start.sh']),
Actually you don't need start hyperg, golem should start this on his own.

2017-10-15 19:24 UTC, Radagast-red commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +                'LANG': 'en_US.UTF-8',  # required for some tests
In what test this is required?

2017-10-15 19:24 UTC, Radagast-red commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +            repourl='https://github.com/maaktweluit/golem.git',
Which TODO? Why are you using your own fork?

2017-10-15 20:01 UTC, maaktweluit commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +            repourl='https://github.com/maaktweluit/golem.git',
TODO's are in the OP

there is a link to PR 1301 that describes the error on ubuntu server 16.04

2017-10-15 20:02 UTC, maaktweluit commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +                    command=['scripts/test-daemon-start.sh']),
got different errors when hyperg was not in path and when not running.

Will test next time without starting hyperg manually and let you know what tests fail if any.

2017-10-15 20:04 UTC, maaktweluit commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +                'LANG': 'en_US.UTF-8',  # required for some tests
not sure, will test without and get the errors.

this can also be moved to the setup of the buildbot-worker user if it is required.

2017-10-15 20:05 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +    name: ethereum
the latest stable, i think...

should we use a specific version?

2017-10-15 20:06 UTC, maaktweluit commented on scripts/test-daemon-start.sh
> +#!/bin/sh
the test failed when hyperg and ipfs are not running, took them from `circle.yml`.

Buildbot does not support `&` background commands, so had to solve it with a start and stop script.

2017-10-15 20:08 UTC, maaktweluit commented on scripts/test-daemon-stop.sh
> +#!/bin/sh
At the end of the test this will kill the daemons started before the tests.

This is a not water tight cleanup, but better then nothing.

Will investigate if `ipfs` and `hyperg` can be started by the tests alone and remove these 2 scripts if possible.

2017-10-15 20:10 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +- name: Install ipfs
the test need it to run, copied from `circle.yml`. 
its started from `scripts/test-daemon-start.sh` and called from `test_factory()`

2017-10-15 20:17 UTC, maaktweluit commented
@Radagast-red Thanks for the review! Replied on the "conversation" page to all questions, do not see them on the "files changed", sorry!

I am traveling tomorrow but will run some tests Tuesday and make fixes or show logs.

2017-10-16 08:32 UTC, Radagast-red commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +                'LANG': 'en_US.UTF-8',  # required for some tests
Hm i think tests should be independent, different platform can and will have set it differently, our tests should be agnostic as well if there is a dependency on that we should fix this.

2017-10-17 14:27 UTC, maaktweluit commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +                    command=['scripts/test-daemon-start.sh']),
Ran some tests and there are a lot of tests skipping when the daemons are not running:

```
SKIP [1] tests/golem/test_client.py:281: IPFS metadata is currently disabled
SKIP [1] tests/golem/task/dummy/test_runner_script.py:26: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/task/dummy/test_runner_script.py:89: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/resource/ipfs/test_ipfs_resourcemanager.py:51: IPFS daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_daemon_manager.py:146: IPFS daemon isn't running
SKIP [1] tests/golem/task/dummy/test_runner_script.py:13: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/task/dummy/test_dummy_task.py:16: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/network/ipfs/test_ipfs_daemon_manager.py:86: IPFS daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_daemon_manager.py:96: IPFS daemon isn't running
SKIP [1] tests/golem/resource/ipfs/test_ipfs_resourcemanager.py:73: IPFS daemon isn't running
SKIP [1] tests/golem/resource/ipfs/test_ipfs_resourcemanager.py:62: IPFS daemon isn't running
SKIP [1] tests/golem/task/dummy/test_runner_script.py:60: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/network/ipfs/test_ipfs_daemon_manager.py:34: IPFS daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_client.py:32: IPFS daemon isn't running
SKIP [1] tests/golem/resource/ipfs/test_ipfs_resourcemanager.py:44: IPFS daemon isn't running
SKIP [1] golem/resource/base/resourcetest.py:124: IPFS daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_daemon_manager.py:23: IPFS daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_client.py:88: IPFS daemon isn't running
SKIP [1] tests/golem/task/dummy/test_runner_script.py:73: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/network/ipfs/test_ipfs_client.py:52: IPFS daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_client.py:38: IPFS daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_daemon_manager.py:47: IPFS daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_daemon_manager.py:104: IPFS daemon isn't running
SKIP [1] tests/golem/core/test_hostaddress.py:95: Find network testing framework
SKIP [1] golem/resource/base/resourcetest.py:124: Hyperdrive daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_client.py:72: IPFS daemon isn't running
SKIP [1] tests/golem/network/ipfs/test_ipfs_client.py:79: IPFS daemon isn't running
SKIP [1] tests/golem/task/dummy/test_runner_script.py:43: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/task/dummy/test_dummy_task.py:10: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/task/dummy/test_runner_script.py:80: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/task/dummy/test_dummy_task.py:21: It doesn't work, using new dummy task instead
SKIP [1] tests/golem/network/ipfs/test_ipfs_daemon_manager.py:16: IPFS daemon isn't running
```

I propose to keep it as is for this PR and make a follow up issue to let the tests start the daemon's them selves.

2017-10-17 14:28 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +- name: Install ipfs
See logs and proposed solve in the other reply.

2017-10-17 14:28 UTC, maaktweluit commented on scripts/test-daemon-start.sh
> +#!/bin/sh
See logs and proposed solve in the other reply.

2017-10-17 14:28 UTC, maaktweluit commented on scripts/test-daemon-stop.sh
> +#!/bin/sh
See logs and proposed solve in the other reply.

2017-10-17 15:16 UTC, maaktweluit commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +                'LANG': 'en_US.UTF-8',  # required for some tests
fully agree!

Also I can not "break" it again by removing it from the code. Will remove it for now and clean it up, next fresh install might give problems, in that case it belongs to proper user setup, every user should have LANG defined on ubuntu ( but we should warn the user if they do-not )

2017-10-17 15:16 UTC, maaktweluit commented
Started my machines and ran some tests based on the comments, the results:
- With the current configuration the daemon-stop command still runs when cancelling the build. only when the worker crashes this can still be a problem.
- LANG is not needed to run the tests, removed it. ( take care when re-installing the machine )
- hyperg and ipfs need to run in daemon mode else a lot of tests are skipped. Propose to make a separate issue to remove this 'manual' dependency and start the daemons from the test. ( @badb ? )

2017-10-17 15:33 UTC, maaktweluit commented
pushed, but PR does not update.. bad github..

https://github.com/golemfactory/golem/compare/develop...maaktweluit:mwu/linux_unit_test?expand=1

@Radagast-red please check again, all q's are replied to

2017-10-24 11:19 UTC, Elfoniok commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/www.py
> +_auth = util.GitHubAuth(local_settings['github_client_id'],
I don't understand why this is moved?

2017-10-24 11:19 UTC, Elfoniok commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +    name: ethereum
Actually we are, but looks like Circle was also set up this way, so it's ok.

2017-10-24 11:19 UTC, Elfoniok commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +- name: Install ipfs
Actually no, we don't need IPFS is some test need this , it should be removed.

2017-10-24 11:19 UTC, Elfoniok commented on scripts/test-daemon-start.sh
> +#!/bin/sh
Ok i will accept solutions taken from Circle but please remove IPFS

2017-10-24 11:19 UTC, Elfoniok commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/builders.py
> +                    command=['scripts/test-daemon-start.sh']),
Yes i can confirm currently hyperg daemon should be run in background when running tests

2017-10-24 11:27 UTC, Elfoniok commented
I would advise to remove ipfs, really. Can you update 

> Requires

 #1301 to be merged, else the tests will fail on the linux server based on error in the description.

Although this one is closed, no gui was already merged, so i think we can proceed with finishing this and merging. You are right, we should create follow up issues, if there is nothing very important. Will be good to have tests on buildboot.

2017-10-24 12:46 UTC, maaktweluit commented on scripts/ci/roles/buildbot-master/files/src/golem_buildbot/www.py
> +_auth = util.GitHubAuth(local_settings['github_client_id'],
to allow test environments to work without github access / auth, see comment above.

2017-10-24 12:55 UTC, maaktweluit commented
Updated the repo back to the original now `nogui` is merged.

Also created #1548 to get rid of all IPFS references, tests and dependencies.

2017-10-24 13:04 UTC, Elfoniok approved these changes

2017-10-24 13:05 UTC, Elfoniok commented
Just fix all failing tests, maybe there are old test, testing old UI?

2017-10-24 13:24 UTC, maaktweluit commented
Circle failed due to approvals, now running again
Appveyor failed on ethereum, think it has to do with the full harddrive, will re-run when this is reported fixed.

2017-11-16 10:41 UTC, etam commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +    src: https://github.com/mfranciszkiewicz/golem-hyperdrive/releases/download/v0.2.1/hyperg_0.2.1_linux-x64.tar.gz
hyperg was updated

2017-11-16 10:41 UTC, etam approved these changes

2017-11-16 10:44 UTC, etam approved these changes

2017-11-16 10:50 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +    src: https://github.com/mfranciszkiewicz/golem-hyperdrive/releases/download/v0.2.1/hyperg_0.2.1_linux-x64.tar.gz
Good one! commented tasks in the main issue, will update this with the removal of python2 and IPFS. #1400

2017-11-16 10:52 UTC, merged