Balance and Task List PubSub's changed as RPC, mangled members issue …
golemfactory/clay pull request #1471
Opened 2017-10-11 01:53 UTC by mdtanrikulu

…fixed on test_client

2017-11-06 12:03 UTC, maaktweluit reviewed
LGTM!

No approval since i know too little of this.

Also 3 comments left to remove in rpc mapping

2017-11-06 12:03 UTC, maaktweluit commented on golem/client.py
> +            b, ab, d = self.transaction_system.get_balance()
maybe name these variables for clarity

2018-01-25 21:44 UTC, badb commented
I go this error when I try to add app with some previously finished tasks

```  
File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\defer.py", line 746, in send
    raise result.value
TypeError: add_task() got an unexpected keyword argument 'async'
Subprocess 7184 terminated```

2018-01-25 21:45 UTC, badb requested changes
Check the comment above

2018-01-29 11:47 UTC, badb approved these changes

2018-01-29 13:02 UTC, merged