Changes to message serialization, signing and verification
golemfactory/clay pull request #1476
Opened 2017-10-11 19:13 UTC by mfranciszkiewicz

- speeds up signature verification by operating on a binary blob, instead of re-serializing of the message
- removes the need of sorting the properties of serialized objects inside a message

Addresses #1457

2017-10-17 08:43 UTC, etam requested changes

2017-10-17 08:43 UTC, etam commented on golem/network/transport/message.py
> +        return struct.pack('!HQ?', self.TYPE,
E: golem/network/transport/message.py:102:35: Instance of 'Message' has no 'TYPE' member (no-member)

2017-10-17 08:43 UTC, etam commented on golem/core/databuffer.py
> +        self.buffered_data = b"".join([self.buffered_data, data])
Is this bytes or strings?

```python
>>> b''.join([b'123', "abc"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sequence item 1: expected a bytes-like object, str found
```

If it's all bytes, then this should be fine:
```python
self.buffered_data += data
```

2017-10-17 08:43 UTC, etam commented on golem/core/databuffer.py
>  class DataBuffer:
Comments in this class suggests, that it operates on strings, but instead it operates on bytes.

2017-10-17 08:43 UTC, etam commented on golem/core/variables.py
> -APP_VERSION = "0.8.0"
Is this supposed to go in here?

2017-10-17 08:43 UTC, etam commented on golem/network/transport/message.py
> +                self.sig = b'0' * 65
Magic constant

2017-10-17 08:43 UTC, etam commented on tests/golem/network/transport/test_network.py
> +        return b'1' * 65
Magic constant

2017-10-17 09:27 UTC, Krigpl commented on golem/network/transport/message.py
> +        self._raw = raw  # whole message
I might be missing something but is it used at all?

2017-10-17 09:31 UTC, mfranciszkiewicz commented on golem/core/databuffer.py
>  class DataBuffer:
Comments weren't changed while porting from Python 2 to Python 3.

2017-10-17 09:32 UTC, mfranciszkiewicz commented on golem/core/databuffer.py
> +        self.buffered_data = b"".join([self.buffered_data, data])
Yes, it should be fine. `''.join` is just faster.

2017-10-17 09:35 UTC, mfranciszkiewicz commented on golem/network/transport/message.py
> +                self.sig = b'0' * 65
Actually I've tried replacing all byte counts with constants and the code was IMO less readable. I'd like to hear another opinion.

2017-10-17 09:35 UTC, mfranciszkiewicz commented on golem/core/variables.py
> -APP_VERSION = "0.8.0"
The setup script automatically updates the version and it's pointless to fight it with every PR.

2017-10-17 09:36 UTC, mfranciszkiewicz commented on tests/golem/network/transport/test_network.py
> +        return b'1' * 65
I believe that this is ok in tests.

2017-10-17 09:39 UTC, mfranciszkiewicz commented on golem/network/transport/message.py
> +        return struct.pack('!HQ?', self.TYPE,
The base `Message` class is not instantiated in the application. Where is that message from?

2017-10-17 09:43 UTC, Krigpl requested changes
Overall looks good, just a couple of comments to make the Message class even a bit simpler.

2017-10-17 09:43 UTC, Krigpl commented on golem/network/transport/message.py
> +        self._payload = payload  # child's payload only (may be encrypted)
`self.encrypted`, `self.sig` and `self._payload` don't need to exist.
They are only set and used during serialization, we can just used them there locally.

2017-10-17 09:43 UTC, Krigpl commented on golem/network/transport/message.py
> +        self._raw = raw  # whole message
I might be missing something but is it used?

2017-10-17 09:43 UTC, Krigpl commented on golem/network/transport/message.py
>      def get_short_hash(self):
I believe this doesn't have to be exposed anymore.
And by making it an internal method we can get rid of the properties I mentioned in the other comment

2017-10-17 09:45 UTC, mfranciszkiewicz commented on golem/network/transport/message.py
> +        self._raw = raw  # whole message
This will be used in the near future

2017-10-17 09:48 UTC, mfranciszkiewicz commented on golem/network/transport/message.py
>      def get_short_hash(self):
Agreed

2017-10-17 09:55 UTC, etam commented on golem/core/databuffer.py
> +        self.buffered_data = b"".join([self.buffered_data, data])
```
$ python3 -m timeit 'b1 = b"0"*100; b2 = b"f"*100; b1 = b"".join([b1, b2])'
10000000 loops, best of 3: 0.19 usec per loop
$ python3 -m timeit 'b1 = b"0"*100; b2 = b"f"*100; b1 += b2'
10000000 loops, best of 3: 0.126 usec per loop
```
It looks like `+=` is faster.

2017-10-17 09:56 UTC, etam commented on golem/network/transport/message.py
> +        return struct.pack('!HQ?', self.TYPE,
From pylint, run by shippable.

2017-10-17 10:02 UTC, mfranciszkiewicz commented on golem/core/databuffer.py
> +        self.buffered_data = b"".join([self.buffered_data, data])
Though 100 bytes is by orders of magnitude too low for this test, it seems that it is no longer true in Python 3.

2017-10-17 10:04 UTC, mfranciszkiewicz commented on golem/core/databuffer.py
> +        self.buffered_data = b"".join([self.buffered_data, data])
I'll revert changes all changes made in databuffer and address them in a separate PR.

2017-10-17 10:05 UTC, etam commented on golem/core/databuffer.py
> +        self.buffered_data = b"".join([self.buffered_data, data])
At 10000 bytes they become equal

2017-10-17 10:16 UTC, mfranciszkiewicz commented on golem/network/transport/message.py
> +        self._payload = payload  # child's payload only (may be encrypted)
Without more refactoring, these are still needed for signature verification, done outside the class.

2017-10-17 11:49 UTC, Krigpl commented on golem/network/transport/message.py
> +                self.sig = b'0' * 65
It's used three times and in one place you put a comment explaining what it is so might be worth using an actual constant.
Something like `SIG_LEN = 65` shouldn't hurt legibility too much

2017-10-17 12:24 UTC, Krigpl approved these changes
I'm fine with the current version, just one clean up suggestion.
Approving, but double check with @etam whether he has any more comments.

2017-10-17 12:24 UTC, Krigpl commented on golem/network/transport/message.py
>  from golem.core.databuffer import DataBuffer
I think it'd be nice if we'd get rid of DataBuffer here. That would mean removing `deserialize` method and leaving only `deserialize_message` which doesn't depend on DataBuffer. `deserialize` is only used in `tcpnetwork.py` and that's where DataBuffer logic should live. You already did pretty much the same with `decrypt_and_deserialize` so removing DataBuffer dependency altogether would be nice.

2017-10-17 12:51 UTC, mfranciszkiewicz commented on golem/network/transport/message.py
> +        return struct.pack('!HQ?', self.TYPE,
I've added `TYPE = None` to make the linter happy, but this part will fail (0 and up are reserved, negative value is not really possible). Overall, it doesn't make much sense.

2017-10-17 12:58 UTC, etam commented on golem/network/transport/message.py
> +        return struct.pack('!HQ?', self.TYPE,
Without TYPE it will fail anyway, so it's absolutely fine.

2017-10-17 12:58 UTC, etam approved these changes

2017-10-17 13:13 UTC, mfranciszkiewicz commented on golem/network/transport/message.py
>  from golem.core.databuffer import DataBuffer
The difference is that `decrypt_and_deserialize` was only used in tests, so I did that freely. I suggest leaving this for the DataBuffer-related PR.

2017-10-18 16:10 UTC, mfranciszkiewicz commented
@Krigpl @etam I've removed the `DataBuffer` dependency from message.py, in preparation for the forthcoming `DataBuffer` changes.

2017-10-19 13:55 UTC, etam approved these changes
LGTM

2017-10-19 15:24 UTC, Krigpl approved these changes

2017-10-20 16:50 UTC, merged