checking whether a new version of Golem is currently available #1430
golemfactory/clay pull request #1479
Opened 2017-10-12 09:51 UTC by jiivan

fixes: #1430

2017-10-24 09:43 UTC, Krigpl reviewed
Looks good, just minor comments

2017-10-24 09:43 UTC, Krigpl commented on golem/client.py
> +            log.warning('New version of golem available: %r',
This message won't be seen by the end user so this PR doesn't fully addresses #1430, right? Any follow up for that?

2017-10-24 09:43 UTC, Krigpl commented on golem/network/p2p/peersession.py
> +            return []
Log an error message? This is not expected after all

2017-10-24 09:43 UTC, Krigpl commented on golem/network/p2p/peersession.py
> +        if (self.address, int(msg.port)) in self.p2p_service.seeds:
`msg.port` is already an `int` I believe, no need to cast it

2017-11-06 12:38 UTC, maaktweluit requested changes
LGTM

Only `semantic_version` comments are important i think.

2017-11-06 12:38 UTC, maaktweluit commented on golem/network/p2p/peersession.py
> +    if _machine_version(variables.APP_VERSION) < mv_client:
maybe use the `semantic_version` module instead of the bespoke `_machine_version` to compare the versions.

2017-11-06 12:38 UTC, maaktweluit commented on golem/client.py
> +                kwargs['version'])
too little indent

2017-11-06 12:38 UTC, maaktweluit commented on tests/golem/network/p2p/test_peersession.py
> +            'node_name': 'How could youths better learn to live than by at once trying the experiment of living? --HDT',
line looks too long

2017-11-06 12:38 UTC, maaktweluit commented on tests/golem/network/p2p/test_peersession.py
> +        list_version = [int(s) for s in APP_VERSION.split('.')]
`semantic_version.next_*()` can do this more easily

2017-11-06 13:26 UTC, jiivan commented on golem/client.py
> +            log.warning('New version of golem available: %r',
Yes, created this issue: https://github.com/golemfactory/golem-electron/issues/156

2017-11-08 09:04 UTC, maaktweluit approved these changes

2017-11-08 10:11 UTC, merged