Implement PoW for public keys
golemfactory/clay pull request #1480
Opened 2017-10-12 09:58 UTC by etam

This should make it harder to perform a Sybil attack on Golem network.

2017-10-12 09:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=1480) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=1480) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=1480) it.</sub>

2017-10-23 12:08 UTC, maaktweluit reviewed
Not enough knowledge to approve, just one small q.

2017-10-23 12:08 UTC, maaktweluit commented on golem/core/keysauth.py
> +            logging.warning("Current key is not difficult enough. Creating new one.")
`logger` vs `logging`? what is the difference?

2017-10-23 12:16 UTC, etam commented on golem/core/keysauth.py
> +            logging.warning("Current key is not difficult enough. Creating new one.")
https://docs.python.org/3/howto/logging.html
TL;DR: Typo

2017-10-26 16:58 UTC, ggruszczynski requested changes
God job, however some code cleanup would be beneficial.

2017-10-26 16:58 UTC, ggruszczynski commented on golem/core/keysauth.py
> +    def is_pubkey_difficult(cls, pub_key: Union[bytes, str],
signature mismatch with baseclass:
``` python
@staticmethod
def is_pubkey_difficult(pub_key: Union[bytes, str],
                            difficulty: IntFloatT) -> bool:
```

2017-10-26 16:58 UTC, ggruszczynski commented on golem/core/keysauth.py
> +            pub_key = decode_hex(pub_key)
this is not covered by unit tests:
``` python
if isinstance(pub_key, str):
     pub_key = decode_hex(pub_key)
```
Do we use it anywhere? What happens if someone send a key in a bad format?

2017-10-26 16:58 UTC, ggruszczynski commented on golem/core/keysauth.py
> +
It is quite confusing to get the logic, because there are 3 methods with similar names:
Merge/clean them please.

``` python
def generate_new(self, difficulty: IntFloatT) -> None:

@classmethod
def _generate_keys(cls, private_key_loc, public_key_loc, difficulty: IntFloatT):

@staticmethod
def _generate_new_keys(difficulty: IntFloatT) -> (bytes, bytes):
```

2017-10-26 16:58 UTC, ggruszczynski commented on golem/core/keysauth.py
> +        key, pub_key = cls._generate_new_keys(difficulty)
Please keep nomenclature `priv_key, pub_key = cls._generate_new_keys(difficulty)` ... just in case ;)

2017-10-26 16:58 UTC, ggruszczynski commented on golem/core/keysauth.py
> +
It seems, that `get_difficulty` has a lot of common with `is_***_difficult`, I think that they should be merged like:

```python
def is_difficult_enought(some_key, difficulty):
    return get_difficulty(some_key) > difficulty
```

2017-10-31 11:29 UTC, etam commented on golem/core/keysauth.py
> +
The thing is that `get_difficulty` takes much more time to compute, than current `is_difficult_enough`. And it's crucial when generating new keys.

2017-11-15 11:08 UTC, etam commented
ReReview please. I've made a lot of cleanups and refactoring around KeysAuth to untangle the spaghetti there was.

2017-11-15 13:22 UTC, maaktweluit approved these changes
RE checked the separate commits and the full change set, 2 small questions.

Besides those LGTM!

2017-11-15 13:22 UTC, maaktweluit commented on golem/core/keysauth.py
> +    def get_public_key(self) -> bytes:
why does this have a getter when `public_key` is a public attribute?

2017-11-15 13:22 UTC, maaktweluit commented on golem/core/keysauth.py
> +    def get_key_id(self) -> str:
same q as above

2017-11-15 15:38 UTC, etam commented on golem/core/keysauth.py
> +    def get_public_key(self) -> bytes:
fixed

2017-11-15 15:38 UTC, etam commented on golem/core/keysauth.py
> +    def get_key_id(self) -> str:
fixed

2017-11-15 15:51 UTC, etam commented on golem/core/keysauth.py
> +            pub_key = decode_hex(pub_key)
> this is not covered by unit tests

will fix that

> Do we use it anywhere?

We use it here: https://github.com/golemfactory/golem/blob/2c82f8e7a1af783ef59ee8cda472c1fe768b6259/golem/network/p2p/peersession.py#L390

> What happens if someone send a key in a bad format?

Shit happens ;) But seriously, if such event happens, it should be detected at lower layer of networking stack. And if it reaches here, then decode_hex will throw an exception.

2017-11-16 10:45 UTC, etam commented on golem/core/keysauth.py
> +            pub_key = decode_hex(pub_key)
fixed

2017-11-16 16:20 UTC, ggruszczynski requested changes

2017-11-16 16:20 UTC, ggruszczynski commented on golem/core/keysauth.py
> +        return (priv_key, pub_key)
The method shall also check whether pubkey matches the privkey...
or store only the priv_key.

2017-11-16 16:20 UTC, ggruszczynski commented on golem/core/keysauth.py
> +        self.key_id = self._cnt_key_id(pub_key)
I think that:
```python
 self.key_id = encode_hex(pub_key)
```
is enought, because `_def _cnt_key_id(public_key: bytes)` isn't used anywhere else (only in tests).
Moreover the `cnt` shorcut is strange.

2017-11-16 16:20 UTC, ggruszczynski commented on golem/core/keysauth.py
> +    def is_difficult(self, difficulty: IntFloatT) -> bool:
the `def is_difficult(self, difficulty: IntFloatT)` is a dead code. Appears only in tests.

2017-11-16 16:20 UTC, ggruszczynski commented on golem/core/keysauth.py
> +    def load_from_file(self, file_name: str) -> bool:
I think that we shall always use the safer method: _load_and_check_keys(...)
BTW, maybe it is enough to store just the priv_key?

2017-11-16 16:20 UTC, ggruszczynski commented on golem/core/keysauth.py
> +            logger.warning("Current key is not difficult enough. "
What will happen when GolemFactory will decide to increase the difficulty?
I am afraid that silent overwriting of the previous keys may result in unexpected lost of identity, founds etc.
For now, let the `self._save_keys()` just create a new file "keys_no1-DD-MM-YYYY)" then "keys_no1-DD-MM-YYYY".

2017-11-23 09:31 UTC, etam commented on golem/core/keysauth.py
> +        self.key_id = self._cnt_key_id(pub_key)
done

2017-11-23 09:37 UTC, etam commented on golem/core/keysauth.py
> +    def is_difficult(self, difficulty: IntFloatT) -> bool:
Well, but it might be useful. And it makes the interface complete.

2017-11-23 09:38 UTC, etam commented on golem/core/keysauth.py
> +    def load_from_file(self, file_name: str) -> bool:
I asked a question https://github.com/imapp-pl/golem_rd/issues/132#issuecomment-345200716 
no reply so far

2017-11-23 09:44 UTC, etam commented on golem/core/keysauth.py
> +    def load_from_file(self, file_name: str) -> bool:
But anyway, I've made it use _load_and_check_keys

2017-11-23 09:48 UTC, etam commented on golem/core/keysauth.py
> +        return (priv_key, pub_key)
done

2017-11-23 11:08 UTC, etam commented on golem/core/keysauth.py
> +            logger.warning("Current key is not difficult enough. "
done

2017-12-01 14:02 UTC, ggruszczynski commented on golem/core/keysauth.py
> +            return None
Please, avoid silent try-except block.
Please, add a logger in the except block.

2017-12-01 14:41 UTC, ggruszczynski approved these changes
Minor dead-code cleanup left.
Please do not git-rebase large amount of code. 
It overrides commit history making re-review from previous-review impossible.
Good job, thank you!

2017-12-01 14:41 UTC, ggruszczynski commented on golem/core/keysauth.py
> +            return None
Please, avoid silent try-except block.
Please, add a logger in the except block.

2017-12-01 14:41 UTC, ggruszczynski commented on golem/core/keysauth.py
> +        """ Load private key from given file. If it's proper key, then generate
`def load_from_file` is a deadcode together with 
`def load_keys_from_file(self, file_name):` from golem/client.py
Remove please.

2017-12-01 14:41 UTC, ggruszczynski commented on golem/core/keysauth.py
>          """ Save current pair of keys in given locations
`def save_to_files(self, private_key_loc: str, public_key_loc: str) -> bool: deadcode`
Please remove together with
`def save_keys_to_files(self, private_key_path, public_key_path)` from golem/client.py

2017-12-01 14:41 UTC, ggruszczynski commented on golem/core/keysauth.py
> +    def is_difficult(self, difficulty: IntFloatT) -> bool:
There is to much features (and dead code) which might be useful in golem. 
It is enough to keep the live code in develop branch.
Please remove this function.

2018-02-12 13:55 UTC, tworec commented
closes imapp-pl/golem_rd#132

2018-02-12 16:01 UTC, tworec commented on golem/core/keysauth.py
> +            logger.warning("Current key is not difficult enough. "
according to what I have ack from @badb, as for Golem Brass we will accept that node will re-generate key when difficulty is increased.

2018-02-12 16:01 UTC, tworec commented on requirements.txt
> +# TODO: revert this before merging
why?

2018-02-13 14:46 UTC, etam commented on requirements.txt
> +# TODO: revert this before merging
https://github.com/golemfactory/golem-messages/pull/25 was merged

2018-02-13 14:47 UTC, tworec commented on requirements.txt
> +# TODO: revert this before merging
I've realized that already but thanks

2018-02-16 13:53 UTC, etam commented on golem/core/keysauth.py
> +    private and public keys based on ECC (curve secp256k1). Keeps only private.
This "Keeps only private" is confusing and, I think, unneeded.

2018-02-16 14:02 UTC, tworec commented on golem/core/keysauth.py
> +    private and public keys based on ECC (curve secp256k1). Keeps only private.
thx @etam, please check it again now

2018-02-16 14:43 UTC, etam commented
@tworec Github doesn't allow me to approve this PR, because I created it. But I approve.

2018-02-16 14:48 UTC, merged

2018-02-16 14:54 UTC, etam commented
🎉