Limit TaskHeaders sent
golemfactory/clay pull request #1489
Opened 2017-10-16 08:25 UTC by Radagast-red

Signed-off-by: Lukasz Foniok <lukaszfoniok@gmail.com>

2017-10-18 12:25 UTC, ggruszczynski requested changes
Please:
1) use drawing without repetition.
2) to keep a good test coverage add a simple unit test 
Have a look at test_peerseession and test_taskserver.test_add_task_header --> get_example_task_header.

2017-10-18 12:25 UTC, ggruszczynski commented on golem/network/p2p/peersession.py
> +                tasks_to_send.append(tasks[random.randint(0, max_ind)])
random.randint(0, max_ind) can return the same number several times.
Please, use drawing without repetition.

2017-10-18 13:33 UTC, mfranciszkiewicz commented on golem/network/p2p/peersession.py
> +                tasks_to_send.append(tasks[random.randint(0, max_ind)])
In Python 3.6, there is a `random.choices(collection)` function. We can backport it to 3.5 from [here](https://github.com/python/cpython/blob/master/Lib/random.py#L342)

2017-10-19 09:14 UTC, Radagast-red commented on golem/network/p2p/peersession.py
> +                tasks_to_send.append(tasks[random.randint(0, max_ind)])
But choices is with repetition, no? I want to try random.sample is this all right?
https://docs.python.org/3/library/random.html#random.sample

2017-10-19 15:57 UTC, ggruszczynski commented on tests/golem/network/p2p/test_peersession.py
> +        assert len(sent_tasks) == len(set(sent_tasks))
what is the purpose of  `assert len(sent_tasks) == len(set(sent_tasks))` ?
I think that `assert len(sent_tasks) == TASK_HEADERS_LIMIT` should be enought

2017-10-20 09:12 UTC, Radagast-red commented on tests/golem/network/p2p/test_peersession.py
> +        assert len(sent_tasks) == len(set(sent_tasks))
I would but it's better to check if all entries are unique, as you pointed out without repetition.

2017-10-25 08:11 UTC, ggruszczynski approved these changes

2017-10-30 11:40 UTC, jiivan approved these changes
Small comment, not a stopper.

2017-10-30 11:40 UTC, jiivan commented on golem/network/p2p/peersession.py
> +        if max_ind < 0:
Maybe this would be more readable?
```python
if not tasks:
    return
```

2017-11-06 13:14 UTC, maaktweluit commented
@Elfoniok This PR looks ready for merge, anything left to fix? If so, can i help?

2017-11-06 13:38 UTC, merged