Protovol_id_v2
golemfactory/clay pull request #1526
Opened 2017-10-19 15:19 UTC by ggruszczynski

Solves:
Run golem nodes in sub-network #1380

Signed-off-by: ggruszczynski <ggruszczynski@golem.network>

2017-10-31 13:24 UTC, etam commented on golem/core/variables.py
> +    https://docs.python.org/2/faq/programming.html#how-do-i-share-global-variables-across-modules
`docs.python.org/3`

2017-10-31 13:24 UTC, etam commented on golem/core/variables.py
> +    https://bytes.com/topic/python/answers/19859-accessing-updating-global-variables-among-several-modules
Actually, this might be not needed.

If everywhere there was
```python
import golem.core.variables as vars

[...]

vars.P2P_PROTOCOL_ID
```
then it would work fine.

But
```python
from golem.core.variables import PROTOCOL_ID
```
creates a local copy of the variable, which is surprising.

Well, it wouldn't be surprising if anyone would care about what pylint and flake8 have to say about our code.

2017-10-31 15:54 UTC, ggruszczynski commented on golem/core/variables.py
> +    https://bytes.com/topic/python/answers/19859-accessing-updating-global-variables-among-several-modules
That's right, however I decided to introduce a class just in case that someone could use it the other way around  ;-)

2017-11-02 12:13 UTC, etam commented
One more thing: `PROTOCOL_ID.P2P_ID` there's too much `_ID`. It'd be better `PROTOCOL.P2P_ID` or `PROTOCOL_ID.P2P`.

2017-11-07 12:40 UTC, etam requested changes

2017-11-07 12:40 UTC, etam commented on tests/test_golemapp.py
> +        super(TestGolemApp, self).tearDown()
```
W: tests/test_golemapp.py:17:4: Useless super delegation in method 'setUp' (useless-super-delegation)
W: tests/test_golemapp.py:20:4: Useless super delegation in method 'tearDown' (useless-super-delegation)
```

Are those methods needed?

2017-11-07 13:43 UTC, etam approved these changes

2017-11-07 14:57 UTC, Elfoniok approved these changes

2017-11-07 15:25 UTC, merged