add config scripts for a windows buildbot worker
golemfactory/clay pull request #1535
Opened 2017-10-22 20:04 UTC by pstiasny

2017-10-23 10:35 UTC, etam requested changes

2017-10-23 10:35 UTC, etam commented on scripts/ci/requirements.txt
> +git+https://github.com/ansible/ansible.git@60e98a363548454e03bedd09636e236c07b1666c#egg=ansible
This git id is meaningless. I don't know if or when it should be updated and why. It would be better if it was a tag or branch.

2017-10-23 10:35 UTC, etam commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +  notify: pywin32 installed
Handlers are run at the end of play. And this looks like something that should be run before next commands (or am I wrong? IDK)

If that's the case, then add `register: pywin32_installed` and change the handler as a next task with `when: pywin32_installed|changed`.

2017-10-23 10:49 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +  notify: pywin32 installed
good suggestion!

Another option would be to call `flush_handlers` if it is better to keep it as handler

2017-10-23 10:55 UTC, maaktweluit requested changes
Only the password comment is important.

LGTM!

Will you still add the service or is this something i can pick up?

2017-10-23 10:55 UTC, maaktweluit commented on scripts/ci/site.yml
> +        ansible_password: "{{win_password['win_password']}}"
does this automatically apply `no_log` for hiding the password?

2017-10-23 10:55 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    url: 'https://s3.amazonaws.com/golem-buildbot-build-resources/pywin32-221-cp36-cp36m-win_amd64.whl'
why is this loaded from a private source? is there no public trusted source available?

2017-10-23 10:55 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    - name: docker-toolbox
in all my tests there was no need for docker tool-box, yet.
Did not get it to work on AWS due to VirtualBox limitations.

2017-10-26 19:52 UTC, pstiasny commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    - name: docker-toolbox
Yes, unfortunately VirtualBox won't run on AWS. It will be necessary to move to a different platform if we want to test with it.
I'll remove the package.

2017-10-26 19:54 UTC, pstiasny commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    url: 'https://s3.amazonaws.com/golem-buildbot-build-resources/pywin32-221-cp36-cp36m-win_amd64.whl'
This is mirrored from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32. That package was recommended by @mfranciszkiewicz IIRC.

2017-10-26 20:38 UTC, pstiasny commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +  notify: pywin32 installed
This is not required for any of the current commands, although it will be required before initializing a windows service.

2017-10-26 20:55 UTC, pstiasny commented
Thanks for your comments. I pushed changes to address them.

2017-10-26 21:10 UTC, pstiasny commented
@maaktweluit Feel free to take over for the windows service.

In addition to the post I linked in the issue, if you haven't already, you might want to look into [the ansible user right module](https://docs.ansible.com/ansible/devel/win_user_right_module.html) for setting "SeServiceLogonRight" ("log on as a service", required by buildbot).

2017-10-27 15:57 UTC, maaktweluit requested changes
LGTM!

While testing i got quite some timeouts, to solve them i've added:


```
  set_fact:
    ansible_winrm_read_timeout_sec: 60
```
and 
```
- win_chocolatey:
    timeout: 5400
```

did you have those too or is it my local connection?

Besides this and the small q its approved!

2017-10-27 15:57 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    url: 'https://s3.amazonaws.com/golem-buildbot-build-resources/pywin32-221-cp36-cp36m-win_amd64.whl'
Discussed with @mfranciszkiewicz and we can use the public source too:
https://sourceforge.net/projects/pywin32/files/pywin32/Build%20221/pywin32-221.win-amd64-py3.6.exe

wget works for me ( must follow redirects )

2017-10-29 14:08 UTC, pstiasny commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    url: 'https://s3.amazonaws.com/golem-buildbot-build-resources/pywin32-221-cp36-cp36m-win_amd64.whl'
Are you sure about this? I feel having own mirror would be more reliable than sourceforge.

2017-10-29 14:12 UTC, pstiasny commented
@maaktweluit I had no problems with timeouts, but feel free to tweak to whatever works for you. Although wouldn't it be more appropriate to put `ansible_winrm_read_timeout_sec` in group_vars instead of using set_fact?

2017-10-30 13:03 UTC, maaktweluit approved these changes

2017-10-30 13:05 UTC, maaktweluit commented
good one! will add those when testing from a clean machine, when running the second time it goes through fine.

Will discuss if we trust Sourceforge enough to use the "official" project URL, for now the internal one is fine, just for my own AWS it will not work.

2017-10-30 18:38 UTC, pstiasny commented
@maaktweluit the file is publicly available, it should work for you just fine (unless you need a different version).

2017-10-30 19:21 UTC, maaktweluit commented
My bad! i assumed it was internal only :$ then we can leave it for sure!

2017-11-07 15:48 UTC, maaktweluit commented
@etam are all your requested changes fixed? just finished the service and want to merge this PR before making a new PR.

2017-11-07 16:01 UTC, etam commented
@maaktweluit My comment about git id in requirements is without any answear

2017-11-07 16:08 UTC, maaktweluit commented
@etam Thanks!

@pstiasny Can you look at this last comment? or want me to include it in my service PR?

2017-11-09 11:35 UTC, pstiasny commented
@etam, I addressed that issue in adf28e4029863897dbc082b2ace2e345dc99eac4

2017-11-09 11:37 UTC, etam approved these changes

2017-11-10 13:59 UTC, merged