Improvements to test_peerkeeper.py
golemfactory/clay pull request #1537
Opened 2017-10-23 09:44 UTC by Krigpl

- It checks pep8 for peerkeeper.py
- Checks whether returned neighbours are the closest
- Checks whether old peers are being replaces

(Also pep8 changes to peerkeeper.py)

2017-10-27 16:26 UTC, mfranciszkiewicz approved these changes

2017-10-31 12:54 UTC, etam requested changes

2017-10-31 12:54 UTC, etam commented on golem/network/p2p/peerkeeper.py
> +        return neigh
What do you think about this?
```python
return itertools.islice(
    (peer for peer in bucket.peers_by_id_distance(key_num) if int(peer.key, 16) != key_num
          for bucket in self.buckets_by_id_distance(key_num))
    , alpha)
```

2017-10-31 12:54 UTC, etam commented on tests/golem/network/p2p/test_peerkeeper.py
> +            if self.peer_keeper.add_peer(peer) is None:
`if not self.peer_keeper.add_peer(peer):`

2017-10-31 12:54 UTC, etam commented on tests/golem/network/p2p/test_peerkeeper.py
> +            if peer_to_remove is not None:
`if peer_to_remove:`

2017-10-31 14:50 UTC, Krigpl commented on golem/network/p2p/peerkeeper.py
> +        return neigh
More compact, much less legible, less efficient (alpha is usually small). Imo not worth it.

2017-10-31 14:50 UTC, Krigpl commented on tests/golem/network/p2p/test_peerkeeper.py
> +            if self.peer_keeper.add_peer(peer) is None:
This is Python and I feel safer checking against `None` explicitly

2017-10-31 14:50 UTC, Krigpl commented on tests/golem/network/p2p/test_peerkeeper.py
> +            if peer_to_remove is not None:
ditto

2017-10-31 15:06 UTC, etam commented on golem/network/p2p/peerkeeper.py
> +        return neigh
> More compact

True

> much less legible

Disputable

For me checking twice `len(neigh) == alpha` makes it not much legible either.

> less efficient

Questionable

What about this?
```python
def neigh():
    for bucket in self.buckets_by_id_distance(key_num):
        for peer in bucket.peers_by_id_distance(key_num):
            if int(peer.key, 16) != key_num:
                yield peer
return itertools.islice(neigh(), alpha)

2017-11-06 14:43 UTC, maaktweluit commented
@etam are the changes/replies good to approve?

2017-11-06 14:56 UTC, etam approved these changes

2017-11-14 15:35 UTC, merged