DataBuffer cleanup
golemfactory/clay pull request #1538
Opened 2017-10-23 10:41 UTC by Krigpl

Addresses #1504
In particular
- doesn't show warning messages on short data
- removes DataBuffer from ResourceManager since it wasn't used there
- DataBuffer doesn't have buffer size limit now, the limit is checked by the client (currently only tcpnetwork)
- tcpnetwork closes connection on too long messages
- test for the above

2017-10-23 14:09 UTC, etam commented
Please rebase onto current 'develop' branch, so the tests could successfully run.

2017-10-23 14:20 UTC, etam requested changes

2017-10-23 14:20 UTC, etam commented on golem/core/databuffer.py
> +    def append_string(self, data):
`data` is not `str`. It's `bytes`

2017-10-23 14:20 UTC, etam commented on golem/core/databuffer.py
> +        self.buffered_data = b"".join([self.buffered_data, data])
`self.buffered_data += data`

2017-10-23 14:20 UTC, etam commented on golem/core/databuffer.py
> +    def append_string(self, data):
It should be updated in whole class, not just here.

2017-10-23 17:44 UTC, mfranciszkiewicz commented on golem/network/transport/tcpnetwork.py
> +        if self.db.data_size() > MAX_MESSAGE_SIZE:
You should probably check this before calling `self._data_to_messages(data)`

2017-10-24 08:39 UTC, Krigpl commented on golem/network/transport/tcpnetwork.py
> +        if self.db.data_size() > MAX_MESSAGE_SIZE:
I dunno, if `MAX_MESSAGE_SIZE` means we want to reject massages longer than this then it can happen that we will receive half of message of length `3/4*MAX` then the other half + another message of length `1/2*MAX`. Both messages are under `MAX` but total number of bytes in the buffer is larger than `MAX`.
We can of course change it so we won't allow buffer to be larger than some maximum size, but current approach is fine as well imo.

2017-10-24 10:30 UTC, etam requested changes

2017-10-24 10:30 UTC, etam commented on golem/core/databuffer.py
> +        :param str data: bytes to append
`:param bytes data: ...`

2017-10-24 10:30 UTC, etam commented on golem/core/databuffer.py
> +        :param str data: bytes to append
In whole class, not just here, ofc.

2017-10-24 10:44 UTC, etam approved these changes

2017-10-24 11:29 UTC, mfranciszkiewicz commented on golem/network/transport/tcpnetwork.py
> +        if self.db.data_size() > MAX_MESSAGE_SIZE:
If we receive a message of size `MAX + 1`, we append it to the buffer and read it in the next step. The buffer is now empty.

2017-10-24 11:34 UTC, Krigpl commented on golem/network/transport/tcpnetwork.py
> +        if self.db.data_size() > MAX_MESSAGE_SIZE:
Good point, in that case probably peeking `len` and checking against `MAX` is the way to go

2017-11-06 14:51 UTC, maaktweluit approved these changes
LGTM!

One small cleanup possible replacing `mock` with native `unittest.mock`

2017-11-06 14:51 UTC, maaktweluit commented on tests/golem/network/transport/test_tcpnetwork.py
>          protocol.session = MagicMock()
maybe update to `unittest.mock` now this file is touched.

2017-11-06 14:52 UTC, maaktweluit commented
Does this resolve #1504 ? in this case its better to change the initial comment to "resolves" over "addresses" since github will auto-close in that case.

2017-11-13 09:53 UTC, Krigpl commented on tests/golem/network/transport/test_tcpnetwork.py
>          protocol.session = MagicMock()
There are 14 instances of `MagickMock` in this file, I'd rather not add noise in this commit by changing them

2017-11-13 09:56 UTC, Krigpl commented
> Does this resolve #1504 ? in this case its better to change the initial comment to "resolves" over "addresses" since github will auto-close

TIL

2017-11-13 15:09 UTC, merged