Hardening logging startup
golemfactory/clay pull request #1566
Opened 2017-10-25 16:13 UTC by jiivan

2017-10-31 13:28 UTC, etam requested changes

2017-10-31 13:28 UTC, etam commented on golem/core/common.py
> +    if datadir is None:
`if not datadir:`

2017-10-31 13:28 UTC, etam commented on golem/core/common.py
> +        from golem.core.simpleenv import get_local_datadir
Put all imports at the top of the file.

2017-11-03 10:35 UTC, jiivan commented on golem/core/common.py
> +    if datadir is None:
It will also catch `''` witch is not desired.

2017-11-03 10:41 UTC, etam approved these changes

2017-11-03 11:07 UTC, merged