Task persistance a.k.a. Code for saving task manager state
golemfactory/clay pull request #1581
Opened 2017-10-27 10:20 UTC by jiivan

fixes: #1339

2017-10-31 09:03 UTC, jiivan commented on golem/task/taskmanager.py
> +                    )
I think that moving `dispatcher.send` inside `try` and `with` block is a mistake. File should be closed before dispatching, and try block handles unpickling related errors.

2017-10-31 15:17 UTC, ggruszczynski approved these changes

2017-11-06 11:04 UTC, Elfoniok requested changes
Please revert changes that delete task.state updates. There were done very poorly (only some random set instructions were removed) moreover, i think its bad idea to remove state from task. Actually this is task state. Its true tat it looks like those two (task_states dict and state in task) should be unified. But this should be done in separate PR. Probably it would be better to remove dict itself.

2017-11-06 11:04 UTC, Elfoniok commented on golem/task/taskmanager.py
> +        logger.debug('DUMP TASK CALLED')
Please add task id to logs

2017-11-06 11:04 UTC, Elfoniok commented on golem/task/taskmanager.py
> +        self.tasks_dir = tasks_dir / "tmanager"
Can you get this dir from config?

2017-11-06 11:55 UTC, Elfoniok approved these changes

2017-11-06 12:03 UTC, etam commented on golem/task/taskmanager.py
> +        self.tasks_dir = tasks_dir / "tmanager"
Shouldn't this be managed by DirManager? It already does something similar for other directories.

2017-11-06 12:33 UTC, merged