Cleaning up rpc method names
golemfactory/clay pull request #1595
Opened 2017-10-31 10:07 UTC by Elfoniok

Signed-off-by: Lukasz Foniok <lukaszfoniok@gmail.com>

2017-10-31 10:11 UTC, Krigpl approved these changes

2017-10-31 11:08 UTC, etam commented
It's a good practice to rename files in one commit and change them in second. This way git better tracks renames. (In this case I need to use "git diff -M10%" to see what changed in renamed files)

2017-10-31 11:20 UTC, etam requested changes

2017-10-31 11:20 UTC, etam commented on golem/rpc/mapping/rpcmethodnames.py
> +    get_golem_version=      'golem.version',
Why not aliases, like it was before?

This way it's easier to make mistake. You'll spend hours debugging if there's mismatch in strings. You'll get instant error if object does not exist.

2017-10-31 11:20 UTC, etam commented on golem/rpc/mapping/rpcmethodnames.py
> +    get_golem_version=      'golem.version',
Yep. You removed 'golem.version' from the other file.

2017-10-31 11:37 UTC, jiivan approved these changes
Great! Maybe in a next step change meaningless classes in `golem/rpc/mapping/rpceventnames.py` to plain dicts?

2017-10-31 12:42 UTC, etam commented
If we have constant set of methods, then using dict is not a good idea. Better use enums, or leave it as is.

2017-10-31 15:53 UTC, Elfoniok commented on golem/rpc/mapping/rpcmethodnames.py
> +    get_golem_version=      'golem.version',
You will not, there is not point for using those in code, that is why events, are left as aliases, but method names are passed to crossbar ruter only. You don't need them unless you are using debug class, but i guess then you know what are you doing and can use those correctly.

2017-11-03 12:15 UTC, etam approved these changes

2017-11-03 12:32 UTC, merged