updated payment msg and logger msg
golemfactory/clay pull request #1608
Opened 2017-11-02 12:18 UTC by ggruszczynski

1 We don't care what is the value of reward in the message since byzantine node can send whatever it likes.
2 Updated msg info-logs

Signed-off-by: ggruszczynski <ggruszczynski@golem.network>

2017-11-06 11:01 UTC, jiivan approved these changes

2017-11-06 11:02 UTC, jiivan requested changes

2017-11-06 11:02 UTC, jiivan commented on golem/task/taskkeeper.py
> +                               t.ownner_key_id, t.task_id)
`t.owner_key_id`

2017-11-07 16:12 UTC, jiivan approved these changes

2017-11-15 12:37 UTC, etam approved these changes

2017-11-16 11:49 UTC, merged