Buildbot Windows service
golemfactory/clay pull request #1636
Opened 2017-11-08 11:44 UTC by maaktweluit

Another step as part of #1455 

Requires #1535 to be merged first

Added buildbot as a windows service with automatic startup.

2017-11-09 21:36 UTC, pstiasny requested changes

2017-11-09 21:36 UTC, pstiasny commented on scripts/ci/README.md
> +
In https://github.com/golemfactory/golem/pull/1535#issuecomment-339801915 I mentioned it should be possible to set appropriate user right via the [user rights module](https://docs.ansible.com/ansible/devel/win_user_right_module.html#examples). Did you try it?

2017-11-09 21:36 UTC, pstiasny commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    password: "{{site_settings.worker_pass}}"
I'm not sure it's a good idea to reuse the worker pass (for the master-worker protocol) as a Windows password. Seems unnecessary and weakens security. It would be best to generate a random one, or at least use a separate variable.

2017-11-09 21:36 UTC, pstiasny commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    path: 'C:\Python27\lib\site-packages\win32\PythonService.exe'
Would it be possible to omit `path`? Won't `buildbot_worker_windows_service.exe` already take care of configuring that?

2017-11-09 21:36 UTC, pstiasny commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +  ignore_errors: yes
Looking at `win_service` examples, it looks like it should be possible to use it to query service state without going through the shell:
```
- name: check if a service is installed
  win_service:
    name: service name
  register: service_info
```

2017-11-10 08:26 UTC, maaktweluit commented on scripts/ci/README.md
> +
great one! forgot about it, will try it right away!

2017-11-10 08:27 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +  ignore_errors: yes
will try this, its only to start the service after configuring, maybe the name alone is enough

2017-11-10 08:27 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    password: "{{site_settings.worker_pass}}"
fully agree, will generate a password and store it in the local secret file.

2017-11-10 08:28 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
> +    path: 'C:\Python27\lib\site-packages\win32\PythonService.exe'
i do not know, this string comes from `buildbot_worker_service.exe` so hopefully it can start the service without, making it less error prone on changes. will test it

2017-11-13 14:43 UTC, maaktweluit commented
@pstiasny please re-review, all comments are fixed and tested.

2017-11-13 15:48 UTC, pstiasny approved these changes

2017-11-20 10:53 UTC, maaktweluit commented
@badb or @mfranciszkiewicz could you please review this PR?

2017-12-19 17:33 UTC, mfranciszkiewicz approved these changes

2017-12-20 13:41 UTC, merged