Mwu/concent client
golemfactory/clay pull request #1642
Opened 2017-11-08 16:36 UTC by maaktweluit

resolves #1627

2017-11-10 10:41 UTC, lukasz-glen requested changes

2017-11-10 10:41 UTC, lukasz-glen commented on golem/network/concent/client.py
> +            if e.response:
the exception should be logged anyway, to not loose information regardless of the code below

2017-11-10 11:38 UTC, maaktweluit commented on golem/network/concent/client.py
> +            if e.response:
also logged exception thrown here, please check again

2017-11-10 15:15 UTC, lukasz-glen approved these changes

2017-11-15 08:51 UTC, jiivan approved these changes
Looks great. Just added my personal suggestions (`cause you asked ;) )

2017-11-15 08:51 UTC, jiivan commented on golem/network/concent/client.py
> +import requests
A tiny remark here. I don't that keeping stdlib and custom libs import separated is necessary. It really doesn't matter, and just keeping them alphabetically sorted is enough.

2017-11-15 08:51 UTC, jiivan commented on golem/network/concent/client.py
> +    def message(self, message):
I have a gut feeling that naming this method `send()` would let us avoid problems. :)

2017-11-15 08:51 UTC, jiivan commented on golem/network/concent/client.py
> +                response = e.response
If I may suggest: I prefer handling failed cases in ifs and returning in them, and handling positive logical path afterwards.

2017-11-15 08:51 UTC, jiivan commented on golem/network/concent/client.py
> +    def is_available(self):
Accessors are really not necessary in python. Maybe just use `self.is_available` attr instead of `self._is_available`?

2017-11-15 09:40 UTC, maaktweluit commented on golem/network/concent/client.py
> +    def message(self, message):
good one! updated it :)

2017-11-15 09:42 UTC, maaktweluit commented on golem/network/concent/client.py
> +import requests
pylint errors when trying to sort them alphabetically, leaving as is for now to keep the alphabetical per list.

2017-11-15 09:43 UTC, maaktweluit commented on golem/network/concent/client.py
> +                response = e.response
swapped all if's top facilitate this, good one!

2017-11-15 09:44 UTC, maaktweluit commented on golem/network/concent/client.py
> +    def is_available(self):
pylint does not allow classes with only one public function, maybe we can add `reset_counter()` and make this a public attr?

2017-11-15 10:01 UTC, jiivan commented on golem/network/concent/client.py
> +    def is_available(self):
`__can_call_concent()` can easily be public. I think that pylint intention (however this sounds :) ) is to avoid small classes which could be implemented with simple functions. Is this the case here? Well it's worth a second thought.

2017-11-15 11:17 UTC, maaktweluit commented on golem/network/concent/client.py
> +    def is_available(self):
Solved :D

2017-11-15 11:52 UTC, jiivan commented on tests/golem/network/concent/test_concent_client.py
> +class TestConcentClient(TestCase):
One last thought (sorry that it's late, just popped in): consider adding `golem.testutils.PEP8MixIn`.

2017-11-15 12:09 UTC, maaktweluit commented on tests/golem/network/concent/test_concent_client.py
> +class TestConcentClient(TestCase):
Good thought! Made #1664 to align it with the linters running on shippable.

2017-11-15 12:55 UTC, merged