add boto to buildbot ansible requirements
golemfactory/clay pull request #1653
Opened 2017-11-10 16:47 UTC by pstiasny

2017-11-10 16:48 UTC, maaktweluit requested changes

2017-11-10 16:48 UTC, maaktweluit commented on scripts/ci/requirements.txt
>  boto3
this still needed too?

2017-11-10 19:52 UTC, pstiasny commented on scripts/ci/requirements.txt
>  boto3
yep

2017-11-13 10:21 UTC, maaktweluit approved these changes

2017-11-13 11:14 UTC, merged