Added loglevel argument
golemfactory/clay pull request #1660
Opened 2017-11-14 16:19 UTC by maaktweluit

Enabled `--loglevel` as argument and replace the following objects with the new level:
- ROOT logger
- handlers
- loggers

Possible values are `WARNING`, `INFO` and `DEBUG`

Also fixed some linting errors along the way

2017-11-17 12:20 UTC, Krigpl approved these changes

2017-11-28 18:49 UTC, mfranciszkiewicz requested changes

2017-11-28 18:49 UTC, mfranciszkiewicz commented on golem/core/common.py
> +        for _logger in list(LOGGING.get('loggers', {}).values()):
Conversion to `list` is superfluous

2017-11-28 18:49 UTC, mfranciszkiewicz commented on golem/core/common.py
> +logger = logging.getLogger(__name__)
Could we avoid using loggers prior to configuring them?

2017-11-29 09:23 UTC, maaktweluit commented on golem/core/common.py
> +logger = logging.getLogger(__name__)
Moved log message to after the config is applied, good catch!

2017-11-29 09:24 UTC, maaktweluit commented on golem/core/common.py
> +        for _logger in list(LOGGING.get('loggers', {}).values()):
Indeed, removed it and everything seems to still work :)

2017-12-05 12:37 UTC, mfranciszkiewicz approved these changes

2017-12-05 13:06 UTC, merged