Fixes issue #856
golemfactory/clay pull request #1677
Opened 2017-11-19 02:31 UTC by SLongofono

The ipaddress module doesn't appear to support the local scope addressing.  As elsewhere in the code, this considers only the address itself, ignoring anything at or beyond the '%'.  Also checks the convention for local-only addresses of using the 'fe80' prefix.

2017-11-19 02:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=1677) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=1677) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=1677) it.</sub>

2017-11-20 16:36 UTC, badb commented
Issue #856

2017-11-20 16:54 UTC, badb requested changes
@SLongofono Thank you for contributing! There are however still some issues with this PR:

1) Fixing just is_ip_address method in tests won't fix problem with golem (when ip_address method fails). 
2) There should be some tests added. 
3) Current implemention is not working properly.

2017-11-20 16:54 UTC, badb commented on tests/golem/core/test_hostaddress.py
> +            return (s[0][:4].lower().startswith('fe80'))
s is still a string, so `s[0]` is the first char in the string.

2017-11-20 17:28 UTC, SLongofono commented on tests/golem/core/test_hostaddress.py
> +            return (s[0][:4].lower().startswith('fe80'))
str.split() returns a list, so that should work as expected, passing this string less the scoping or the unmodified string into ip_address.

As for the tests, forgive my ignorance, where should I submit the ones I verified my code with?

2017-11-26 20:06 UTC, SLongofono commented on tests/golem/core/test_hostaddress.py
> +            return (s[0][:4].lower().startswith('fe80'))
Fixed.  Added tests, please let me know if they belong elsewhere.

2019-05-07 08:16 UTC, mplebanski commented
Can we close this?

2019-05-07 17:48 UTC, closed without merging