Concent: MessageForceReportComputedTask
golemfactory/clay pull request #1699
Opened 2017-11-24 15:51 UTC by mfranciszkiewicz

Addresses https://github.com/golemfactory/golem-messages/issues/16

Please submit your feedback on `ConcentClientService` and `ConcentClient`.

`ConcentClientService`:
- separate service thread
- processes a queue of `ConcentRequest`s
- handles Concent HTTP request errors
- requests can be deferred (and cancelled)
- requests have a predefined lifetime (maximum queue time)

`ConcentClient` changes:
- no longer handles the grace period; now it's a responsibility of `ConcentClientService`
- differentiation of client HTTP request and server errors

Possible further changes:
- `ConcentRequest` callbacks on success / errbacks on error, timeout

2017-11-24 16:30 UTC, maaktweluit requested changes
LGTM!

Sorry for the list of questions.
Some things that need attention, but all could be my mistake, will approve on reply!

2017-11-24 16:30 UTC, maaktweluit commented on requirements.txt
> +-e git://github.com/golemfactory/golem-messages.git@message-service-refused#egg=golem_messages
TODO: release before merge?

2017-11-24 16:30 UTC, maaktweluit commented on golem/network/concent/client.py
> +        return response.content or None
initial requirement was to return `None` instead of empty string.

Does this work like javascript and do that?

2017-11-24 16:30 UTC, maaktweluit commented on golem/network/concent/client.py
> +    MIN_GRACE_TIME = 5.  # s
nice addition!

2017-11-24 16:30 UTC, maaktweluit commented on golem/network/concent/client.py
> +    def __init__(self, enabled=False):
what is the future default value of `enabled`?

In case of true it might be easier to clean up if you switch the default.

2017-11-24 16:30 UTC, maaktweluit commented on golem/network/concent/client.py
> +               delay: Optional[float] = None) -> None:
I think adding a delay is more likely then adding a custom URL, maybe you can switch the order to make it callable without `None` url

2017-11-24 16:30 UTC, maaktweluit commented on golem/network/concent/client.py
> +        from twisted.internet import reactor
any reason to not import on top of the file?

2017-11-24 16:30 UTC, maaktweluit commented on golem/network/concent/client.py
> +        if req.deadline_ts < time.time():
call `time.time()` 2x quickly in a row, when it was one more a variable would be preferred

2017-11-24 16:30 UTC, maaktweluit commented on golem/network/concent/client.py
> +        self._queued[req.key] = req
this looks like the `req` is added to `self._queued` twice, or am i reading something wrong?

2017-11-24 16:30 UTC, maaktweluit commented on tests/golem/network/concent/test_concent_client.py
> +    def test_submit(self, *_):
maybe this can assert the `MockClient` got called

2017-11-24 16:41 UTC, mfranciszkiewicz commented on golem/network/concent/client.py
> +        return response.content or None
Yes, it's returning `None` in case the response evaluates to `False` (empty string, collections, None).

2017-11-24 16:43 UTC, mfranciszkiewicz commented on golem/network/concent/client.py
> +    def __init__(self, enabled=False):
`enabled` is currently for enabling / disabling concent requests. It will probably be removed soon.

2017-11-24 16:44 UTC, mfranciszkiewicz commented on golem/network/concent/client.py
> +        from twisted.internet import reactor
Yes, reactor defines global values and installs signal handlers. We do not want that on import.

2017-11-24 16:48 UTC, maaktweluit commented on golem/network/concent/client.py
> +    def __init__(self, enabled=False):
should the default be `true` in that case so its better prepared for the future?

2017-11-24 16:58 UTC, mfranciszkiewicz commented on golem/network/concent/client.py
> +        self._queued[req.key] = req
It's queued instantly if there is no delay (and put in `_queued`), otherwise a deferred call to `_enqueue` is saved in `_waiting`. It doesn't seem that it's queued twice.

2017-11-24 17:26 UTC, mfranciszkiewicz commented on tests/golem/network/concent/test_concent_client.py
> +    def test_submit(self, *_):
There are no calls to `ConcentClient` here, but I've added explicit checks to `test_loop*` methods.

2017-11-27 17:23 UTC, mfranciszkiewicz commented on golem/network/concent/client.py
> +        if req.deadline_ts < time.time():
Done

2017-11-27 17:23 UTC, mfranciszkiewicz commented on golem/network/concent/client.py
> +               delay: Optional[float] = None) -> None:
Done

2017-11-27 17:24 UTC, mfranciszkiewicz commented on requirements.txt
> +-e git://github.com/golemfactory/golem-messages.git@message-service-refused#egg=golem_messages
FIXME added

2017-11-30 11:55 UTC, jiivan commented on golem/network/concent/client.py
> +        super(ConcentClientService, self).__init__(daemon=True)
Simplified form of just calling `super().__init__(daemon=True)` could be more readable.

2017-11-30 11:55 UTC, jiivan commented on golem/network/concent/client.py
> +    Initial = 0
If values of this "enum" are not important than maybe use `object()` (or `auto()` in python3.6) instead of manual series of ints?

2017-11-30 11:55 UTC, jiivan commented on golem/task/tasksession.py
> +        concent_msg._raw = concent_msg.serialize(self.sign)
Why use a cache in `_raw` attribute instead of just calling `serialize()` where it's needed? Is this cache invalidated every time the message contents change?

2017-11-30 11:55 UTC, jiivan commented on golem/network/concent/client.py
> +class ConcentRequestStatus(Enum):
If this class is only used for `ConcentRequest` class maybe it would be cleaner to put it's definition inside `ConcentRequest` and just call it `STATUS(Enum)`?

2017-11-30 12:17 UTC, mfranciszkiewicz commented on golem/network/concent/client.py
> +class ConcentRequestStatus(Enum):
It’s also meant for external usage. In that case ConcentRequest.STATUS.Initial doesn’t seem appealing.

2017-11-30 12:19 UTC, mfranciszkiewicz commented on golem/task/tasksession.py
> +        concent_msg._raw = concent_msg.serialize(self.sign)
Serialize requires a signing function (+keys), which isn’t available further in the call stack.

2017-11-30 12:57 UTC, jiivan commented on golem/task/tasksession.py
> +        concent_msg._raw = concent_msg.serialize(self.sign)
Maybe then either pass keys, or serialized message to the call stack?

2017-11-30 13:19 UTC, mfranciszkiewicz commented on golem/task/tasksession.py
> +        concent_msg._raw = concent_msg.serialize(self.sign)
I don't think passing private keys around is a good practice. Currently, message type information is needed and further deserialization is an overkill. Maybe passing both is a good idea.

2017-11-30 13:22 UTC, jiivan commented on golem/task/tasksession.py
> +        concent_msg._raw = concent_msg.serialize(self.sign)
If it's really needed then passing both is a better idea than introducing cache attribute IMO.

2017-11-30 13:24 UTC, mfranciszkiewicz commented on golem/task/tasksession.py
> +        concent_msg._raw = concent_msg.serialize(self.sign)
`_raw` is already present in `Message` but is only populated for ingress messages

2017-11-30 19:46 UTC, mfranciszkiewicz commented on golem/task/tasksession.py
> +        concent_msg._raw = concent_msg.serialize(self.sign)
Done

2017-11-30 19:46 UTC, mfranciszkiewicz commented on golem/network/concent/client.py
> +        super(ConcentClientService, self).__init__(daemon=True)
Done

2017-11-30 19:46 UTC, mfranciszkiewicz commented on golem/network/concent/client.py
> +    Initial = 0
Done (using `object`)

2017-12-01 11:06 UTC, jiivan approved these changes

2017-12-01 11:38 UTC, maaktweluit approved these changes

2017-12-01 11:39 UTC, maaktweluit commented
Thanks for checking, fixing and replying to all review comments: All have been resolved.

Please let me know when parts have changed requiring re-review

2017-12-04 19:16 UTC, merged