Remove old tasks
golemfactory/clay pull request #1701
Opened 2017-11-27 10:18 UTC by etam

Fixes #1667

2017-11-27 10:40 UTC, jiivan requested changes
Looks great and proves that your `Service` architecture is neat! Only one question below:

2017-11-27 10:40 UTC, jiivan commented on golem/client.py
> +            if task['time_started'] + self.older_than_seconds <= now:
What if task timeout is greater than `CLEAN_TASKS_OLDER_THAN_SECONDS`? Maybe it will be better to check against `time_finished`? It will probably be `time_started + time_elapsed if remaining_time == 0`?

2017-11-27 11:31 UTC, etam commented on golem/client.py
> +            if task['time_started'] + self.older_than_seconds <= now:
If tasks never starts at all, there will be no `time_finished` nor `time_elapsed`.
Maybe just `time_started + timeout + older_than_seconds`?

2017-11-27 11:33 UTC, jiivan commented on golem/client.py
> +            if task['time_started'] + self.older_than_seconds <= now:
Seems reasonable

2017-11-30 15:45 UTC, jiivan approved these changes

2017-12-04 17:16 UTC, ggruszczynski approved these changes
LGTM

2017-12-05 11:27 UTC, merged