Requestor-oriented stats #1492
golemfactory/clay pull request #1702
Opened 2017-11-27 14:01 UTC by RDProjekt

Statistics about requested tasks are gathered using pydispatch signals sent from `TaskManager` objects. They are transmitted to the monitor in `MonitoringPublisherService`'s `_run` method. The statistics are collected per-session and are not stored on application's exit.

2017-11-29 13:48 UTC, maaktweluit requested changes
LGTM!

One thing i think needs changing, the log message formatter.
The other comments are all optional, will approve if replied to :)

2017-11-29 13:48 UTC, maaktweluit commented on golem/task/taskmanager.py
> +    HyperdriveResourceManager  # noqa
Can the `# noqa` be removed now the line is properly split?

2017-11-29 13:48 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +        old: Optional[TaskStats],
Should optional arguments be always last?

2017-11-29 13:48 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +                logger.info("Skipping completed task {}".format(task_id))
should this be info or debug? does it have use to read for end user too or only for development?

2017-11-29 13:48 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +            logger.info("Unknown TaskOp {}".format(task_op.name))
how bad is this? maybe upgrade to warning?

2017-11-29 13:48 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +            logger.info("Unknown TaskOp {}".format(task_op.name))
Also please use native logger formatters `logger.info('message: %r', variable)`
`.format()` is a bad practice since it will always parse the string, while the native logger ignores parsing when the level is turned off

2017-11-29 13:48 UTC, maaktweluit commented on tests/golem/task/test_taskmanager.py
> +        del h
should this tests assert some things, like for instance mock called?

2017-11-29 13:48 UTC, maaktweluit commented on tests/golem/task/test_taskmanager.py
> +        del h
More tests in this file have the same question

2017-11-29 13:48 UTC, maaktweluit commented on tests/golem/task/test_taskrequestorstats.py
> +    PEP8_FILES = [
FYI, the PEP8 mix in is in progress of being replaced with mandatory linter tests on CI #1664

2017-12-01 17:37 UTC, ggruszczynski commented on golem/task/taskmanager.py
>          dispatcher.send(
self.task_persistence is a bool being true by default.
We dont need another `persist=True` flag.

2017-12-01 17:37 UTC, ggruszczynski commented on golem/task/taskrequestorstats.py
> +    ("tasks_cnt", int),
What is the difference between TaskStats and CurrentStats?
Please, add some documentation.

2017-12-01 17:37 UTC, ggruszczynski commented on golem/task/taskstate.py
> +class TaskOp(Enum):
Do we really need another `TaskOp` class/enum containing similar fields that classes above?

2017-12-04 18:01 UTC, RDProjekt commented on golem/task/taskmanager.py
> +    HyperdriveResourceManager  # noqa
Absolutely, done.

2017-12-04 18:02 UTC, RDProjekt commented on golem/task/taskrequestorstats.py
> +        old: Optional[TaskStats],
This one is `Optional` as in "can be `None`", but the parameter needs to be always provided. I think it would be weird to pass `new` first and `old` after it.

2017-12-04 18:02 UTC, RDProjekt commented on golem/task/taskrequestorstats.py
> +                logger.info("Skipping completed task {}".format(task_id))
End user can't do much about it and it does not really affect her. Demoted to debug.

2017-12-04 18:04 UTC, RDProjekt commented on golem/task/taskrequestorstats.py
> +            logger.info("Unknown TaskOp {}".format(task_op.name))
Changed all new logger calls to use logger formatters. If this ever happens it means that someone changed `TaskOp` enum but did not update the stats collecting code. End user can't do anything about it, so instead of upgrading demoted it to debug.

2017-12-04 18:04 UTC, RDProjekt commented on tests/golem/task/test_taskmanager.py
> +        del h
`c()` does that, first thing it checks is if the handler has been called.

2017-12-04 18:10 UTC, RDProjekt commented on golem/task/taskmanager.py
>          dispatcher.send(
This is kind of opposite of `self.task_persistence`, which describes if the system has persistence enabled. `persist` parameter says if the particular change that called `notice_task_updated` was important enough to save the task. I have added a comment describing this in more details.

2017-12-04 18:11 UTC, RDProjekt commented on golem/task/taskrequestorstats.py
> +    ("tasks_cnt", int),
They have different fields. `TaskStats` are about a single task, `CurrentStats` is a summary for all tasks in the session. Added documentation to `CurrentStats`, `TaskStats` already had it.

2017-12-04 18:11 UTC, RDProjekt commented on golem/task/taskstate.py
> +class TaskOp(Enum):
Yes, other structures describe current state of the task and `TaskOp` describes the _change_ of the state.

2017-12-05 13:10 UTC, maaktweluit approved these changes

2018-02-01 02:10 UTC, tworec requested changes
Few comments from me.

2018-02-01 02:10 UTC, tworec commented on golem/task/taskmanager.py
> +                                     task_op=TaskOp.WORK_OFFER_RECEIVED)
according to doc in `notice_task_updated` (line 850) this op should be notified with `persist=False`

2018-02-01 02:10 UTC, tworec commented on golem/task/taskrequestorstats.py
> +    NamedTuple, List, Optional, DefaultDict)
ugly: `DefaultDict` import is only for type annotation comments

2018-02-01 02:10 UTC, tworec commented on golem/task/taskstate.py
> +class TaskOp(Enum):
This enum is a mess. It mixes TASK, SUBTASK and others.

2018-02-01 02:10 UTC, tworec commented on tests/golem/task/test_taskmanager.py
> +        del h
`h()` and `c()` are meaningless. They should be  fully named.

2018-02-01 02:10 UTC, tworec commented on golem/task/taskrequestorstats.py
> +def update_finished_stats_with_task(
code in this method looks awful/boilerplate because of using immutable tuples instead of mutable class. But I'll leave it as is, to not be burried into marginal style fixes any more

2018-02-07 19:45 UTC, closed without merging