fix pytest version
golemfactory/clay pull request #1704
Opened 2017-11-28 10:29 UTC by etam

2017-11-28 10:30 UTC, maaktweluit requested changes

2017-11-28 10:30 UTC, maaktweluit commented on requirements.txt
> +pytest>=3.0.5,<3.3.0
is this required to run the app normally? think the only one that should stay is in `-test.txt`

2017-11-28 10:33 UTC, etam commented on requirements.txt
> +pytest>=3.0.5,<3.3.0
It's used in setup.py.

2017-11-28 10:40 UTC, etam commented on requirements.txt
> +pytest>=3.0.5,<3.3.0
It's used indirectly. It allows to run `python setup.py test`, but it seems broken.

2017-11-28 11:15 UTC, maaktweluit approved these changes

2017-11-28 14:28 UTC, mfranciszkiewicz approved these changes

2017-11-28 15:07 UTC, merged

2017-11-29 10:03 UTC, etam commented
@mfranciszkiewicz Please don't squash my commits.

2017-11-29 11:40 UTC, mfranciszkiewicz commented
@etam Your commits specifically? Please elaborate why.

2017-11-29 12:04 UTC, etam commented
@mfranciszkiewicz Because they are supposed to be separate, with their own commit messages. Now it makes no sense, that commit titled 'fix pytest version' does also something different. It's not a big issue in this case, because the squashed commit is small, but I really hate those huge commits that changes bazillion things at once.
I also use various git features (like rebase interactive) to keep the history nice and clean.

2017-11-29 12:36 UTC, mfranciszkiewicz commented
@etam If "fix pytest version" does more than it says, then this PR's title is simply wrong. The rest is a matter of personal preference, but I will keep that in mind.

2017-11-29 12:48 UTC, etam commented
@mfranciszkiewicz Yes, I agree, that the second commit goes beyond what this PR was about. I should have created a second one for it.