test dirmanager symlink_or_copy
golemfactory/clay pull request #1705
Opened 2017-11-29 11:15 UTC by etam

I was supposed to fix #1644, but it seems the import works fine.

It's nice to have more tests anyway.

2017-11-29 11:49 UTC, jiivan requested changes
Have you also seen pathlib? It may simplify your code (but of course it's just a matter of taste).

2017-11-29 11:49 UTC, jiivan commented on tests/golem/resource/test_dirmanager.py
> +        os.symlink = raise_OSError
This overwrites `os.symlink` for all other tests. Better use `unittest.mock` with `side_effect`.

2017-11-29 11:49 UTC, jiivan commented on tests/golem/resource/test_dirmanager.py
> +        os.symlink = raise_OSError
`unittest.mock` with side effect

2017-11-29 12:19 UTC, etam commented on tests/golem/resource/test_dirmanager.py
> +        os.symlink = raise_OSError
I tried
```python
    @patch('os.symlink')
    def test_conflict_file(self, os_symlink):
        os_symlink = Mock(side_effect=OSError)
```
But flake8 says `F841 local variable 'os_symlink' is assigned to but never used` and it seems it doesn't change anything. And I don't want to patch whole `os` module.

2017-12-04 08:24 UTC, etam commented on tests/golem/resource/test_dirmanager.py
> +        os.symlink = raise_OSError
I've found a way to patch os.symlink just for tested function.

2017-12-04 08:45 UTC, jiivan approved these changes

2017-12-05 12:23 UTC, Krigpl approved these changes

2017-12-05 12:58 UTC, merged