Task persistence, continued [WIP]
golemfactory/clay pull request #1709
Opened 2017-11-30 11:59 UTC by mfranciszkiewicz

- registers a task event listener in unplicked tasks
- restores / adds resources for unplicked tasks
- stores information on shared resource hash in `TaskState`
- removes the unused `Task.task_status` property

2017-12-06 09:51 UTC, jiivan requested changes
LGTM, only minor remarks

2017-12-06 09:51 UTC, jiivan commented on golem/resource/hyperdrive/resourcesmanager.py
> +        if not all(os.path.exists(f) for f in files.keys()):
`.keys()` is not needed. Iterating over dicts always iterates over its keys.

2017-12-06 09:51 UTC, jiivan commented on golem/task/taskmanager.py
>              logger.warning("Couldn't remove dump file: %s - %s", e)
I just noticed missing parameter `filepath` in this log.

2017-12-06 09:51 UTC, jiivan commented on tests/golem/resource/hyperdrive/test_hyperdrive_resourcemanager.py
> +    def test_add_files(self):
This method should be split into separate case i.e.:
 * `test_add_files_invalid_paths()`
 * `test_add_files_empty_resource_hash()`
etc.

2017-12-06 09:51 UTC, jiivan commented on tests/golem/task/test_taskserver.py
> +        return Mock(side_effect=_raise)
` side_effect` can be an exception (class or instance). What's the benefit of `_build_raise()` method?

https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.side_effect

2017-12-06 10:34 UTC, jiivan approved these changes
Thanks!

2017-12-06 10:55 UTC, maaktweluit approved these changes
LGTM!

Small comments, replies are enough :)

2017-12-06 10:55 UTC, maaktweluit commented on golem/resource/hyperdrive/resourcesmanager.py
> +            logger.error("Resource manager: missing files (task: %r)", task_id)
is task_id enough to investigate?
if not maybe a list of files in a debug log next to it would be helpful

2017-12-06 10:55 UTC, maaktweluit commented on golem/task/taskmanager.py
> +        logger.info("Task %s added", task_id)
nice cleanup!

2017-12-06 10:55 UTC, maaktweluit commented on golem/task/taskmanager.py
> -        task.task_status = TaskStatus.notStarted
is still still the default status now its gone here?

2017-12-06 10:55 UTC, maaktweluit commented on golem/task/taskmanager.py
> +        logger.info("Restarting task %s", task_id)
Log not consistent with other info's in the class, `Task %s restarting`.
Super small, can be ignored...

2017-12-06 10:55 UTC, maaktweluit commented on golem/task/taskserver.py
> +            logger.error("Cannot restore resources for task: %r", task_id)
is it worth noting the difference between `ConnectionError` and `HTTPError` in the logged message?

2017-12-06 10:55 UTC, maaktweluit commented on tests/golem/resource/hyperdrive/test_hyperdrive_resourcemanager.py
> +        open(file_path, 'w').close()
looks like a raw method to ensure file, is there a native function for that?

2017-12-06 11:16 UTC, jiivan commented on tests/golem/resource/hyperdrive/test_hyperdrive_resourcemanager.py
> +        open(file_path, 'w').close()
https://docs.python.org/3/library/pathlib.html#pathlib.Path.touch

2017-12-06 16:08 UTC, mfranciszkiewicz commented on golem/task/taskserver.py
> +            logger.error("Cannot restore resources for task: %r", task_id)
Yes, `ConnectionError` means that there were problems connecting to HyperG, whereas `HTTPError` means that there was a problem with the request. In this case, `resource_hash` is not known by HyperG, so we should add those files again.

2017-12-06 16:12 UTC, mfranciszkiewicz commented on golem/task/taskmanager.py
> -        task.task_status = TaskStatus.notStarted
`task.task_status` is not used outside this file, so I've removed it in favor of `TaskState.status`

2017-12-07 12:03 UTC, maaktweluit commented on golem/task/taskserver.py
> +            logger.error("Cannot restore resources for task: %r", task_id)
maybe this can be added to the log.error messages? 
For example: `No conection` for the top one, `no resource_hash` for the bottom one
It would help finding a problem in this region when it occurs

2017-12-07 12:05 UTC, maaktweluit commented
Thanks for the fixes and replies!

Replied to the last open thread

2017-12-08 11:56 UTC, merged