Message history log [WIP]
golemfactory/clay pull request #1718
Opened 2017-12-01 19:52 UTC by mfranciszkiewicz

2017-12-06 12:02 UTC, jiivan commented on golem/client.py
> +            MessageHistoryService()
Maybe a hanging comma so further additions won't modify previous lines? Just an aesthetic :)

2017-12-06 12:02 UTC, jiivan commented on golem/model.py
> +class Actor(Enum):
Would it be possible to use string values, to make debugging with external tools easier?

2017-12-06 12:02 UTC, jiivan commented on golem/model.py
> +    node = CharField()
Is this a recipient node or a sender node? I'm confused.

2017-12-06 12:02 UTC, jiivan commented on golem/network/history.py
> +class MessageHistoryService(threading.Thread):
Would it be possible to inherit from `golem.core.service.Service`?

2017-12-06 12:02 UTC, jiivan commented on tests/golem/network/test_history.py
> +    return len(NetworkMessage.select().execute())
Why not `.select().count()`?

2017-12-06 12:07 UTC, mfranciszkiewicz commented on tests/golem/network/test_history.py
> +    return len(NetworkMessage.select().execute())
Thanks, I forgot to change this - at one point there was a `where` clause

2017-12-06 12:10 UTC, mfranciszkiewicz commented on golem/network/history.py
> +class MessageHistoryService(threading.Thread):
Unfortunately `Service` uses a fixed-interval looping call. This service locks on a queue and saves messages asap (apart from sweeping old messages, etc.).

2017-12-06 12:14 UTC, mfranciszkiewicz commented on golem/model.py
> +    node = CharField()
Well, it's the "other" node. Depending on context (local / remote role, message class) it may be a receiver or a sender.

2017-12-06 12:15 UTC, mfranciszkiewicz commented on golem/client.py
> +            MessageHistoryService()
Ok :)

2017-12-06 12:15 UTC, mfranciszkiewicz commented on golem/model.py
> +class Actor(Enum):
Will do

2017-12-06 12:17 UTC, jiivan commented on golem/model.py
> +    node = CharField()
Could you put this comment in code?

2017-12-06 12:18 UTC, jiivan commented on golem/network/history.py
> +class MessageHistoryService(threading.Thread):
Yes, I thought that sweep method fits in a `core.service` structure. Thanks for claryfing. Could you also put this comment in code (maybe class docstring)?

2017-12-06 13:28 UTC, mfranciszkiewicz commented on golem/network/history.py
> +class MessageHistoryService(threading.Thread):
Done

2017-12-06 13:31 UTC, jiivan reviewed
There are some shippable errors worth fixing. Mostly in tests, but still.

2017-12-06 13:31 UTC, jiivan commented on tests/golem/network/test_history.py
> +    def _build_raise(cls):
`side_effect` (also fixes a warning from Shippable)

2017-12-07 09:40 UTC, jiivan approved these changes

2017-12-07 10:03 UTC, etam requested changes
Added one comment.

Thanks for nice type annotations.

2017-12-07 10:03 UTC, etam commented on golem/client.py
> +            MessageHistoryService(),
The type annotation of `_services` is `List[Service]` (with `from golem.core.service import Service`).
With this new type of service, I think it should be changed that they all implement a common metaclass.

2017-12-07 10:37 UTC, jiivan commented on golem/client.py
> +            MessageHistoryService(),
Are you sure you meant a metaclass https://docs.python.org/3/reference/datamodel.html?highlight=metaclass#metaclasses ? :)

A common mixin class may or may not be a good addition though.

2017-12-07 10:40 UTC, etam commented on golem/client.py
> +            MessageHistoryService(),
Maybe not directly a metaclass, but an Abstract Base Class.

2017-12-07 11:33 UTC, mfranciszkiewicz commented on golem/client.py
> +            MessageHistoryService(),
I've created a common interface for `Service`s (called `IService`, derived from `ABC`). Also, `Service` became ambiguous, and it's now named `LoopingCallService`.

2017-12-07 11:33 UTC, etam approved these changes

2017-12-07 11:34 UTC, etam commented on golem/client.py
> +            MessageHistoryService(),
Nice

2017-12-08 12:24 UTC, merged