handle image save errors
golemfactory/clay pull request #1720
Opened 2017-12-04 10:44 UTC by etam

Fixes #1662

2017-12-04 11:38 UTC, jiivan requested changes
LGTM just minor comments

2017-12-04 11:38 UTC, jiivan commented on apps/rendering/resources/utils.py
> +                     "format '{}'".format(image_format))
Please use percent formatting with logger. https://gist.github.com/jiivan/eedb505574ccb2503af48fa2e3043036

2017-12-04 11:38 UTC, jiivan commented on apps/rendering/resources/utils.py
> +                     "format '{}'".format(image_format))
Are you sure `KeyError` always means `unsupported image`? Maybe some additional checks would prevent covering other errors? Or at least a `.debug("Detailed information about image saving failure", exc_info=True)`?

2017-12-04 11:38 UTC, jiivan commented on tests/apps/rendering/resources/test_utils.py
> +    assert b.getvalue()
Something more elaborate than just a boolean test? :) Since it's 1x1 image.

2017-12-04 11:40 UTC, etam commented on apps/rendering/resources/utils.py
> +                     "format '{}'".format(image_format))
I'm sure https://pillow.readthedocs.io/en/4.3.x/reference/Image.html#PIL.Image.Image.save

2017-12-04 11:46 UTC, etam commented on tests/apps/rendering/resources/test_utils.py
> +    assert b.getvalue()
It checks if any bytes were written without throwing exceptions.

2017-12-04 13:21 UTC, jiivan approved these changes

2017-12-04 16:12 UTC, mfranciszkiewicz commented on apps/blender/task/blenderrendertask.py
> +            save_image_or_log_error(image, output_file_name, self.output_format)
I think it would be a good idea to call `image.close()` wherever possible, instead of waiting for the GC.

2017-12-04 16:12 UTC, mfranciszkiewicz commented on apps/blender/task/blenderrendertask.py
> +            save_image_or_log_error(image, output_file_name, self.output_format)
`image.close()`

2017-12-04 16:12 UTC, mfranciszkiewicz commented on apps/rendering/task/framerenderingtask.py
> +            save_image_or_log_error(img, preview_file_path, PREVIEW_EXT)
`img.close()`

2017-12-04 16:12 UTC, mfranciszkiewicz commented on apps/rendering/task/framerenderingtask.py
> +            save_image_or_log_error(image, output_file_name, self.output_format)
`image.close()`

2017-12-04 16:12 UTC, mfranciszkiewicz commented on apps/rendering/task/framerenderingtask.py
> +            save_image_or_log_error(image, output_file_name, self.output_format)
`image.close()`

2017-12-04 16:12 UTC, mfranciszkiewicz commented on apps/rendering/task/framerenderingtask.py
> +        save_image_or_log_error(img_task, preview_task_file_path, PREVIEW_EXT)
`img_task.close()`

2017-12-04 16:12 UTC, mfranciszkiewicz commented on apps/rendering/task/renderingtask.py
> +        save_image_or_log_error(img, self.preview_file_path, PREVIEW_EXT)
`img.close()`

2017-12-04 16:12 UTC, mfranciszkiewicz commented on apps/rendering/task/renderingtask.py
> +        save_image_or_log_error(img_task, preview_task_file_path, PREVIEW_EXT)
`img_task.close()`

2017-12-05 11:30 UTC, etam commented on apps/blender/task/blenderrendertask.py
> +            save_image_or_log_error(image, output_file_name, self.output_format)
done

2017-12-05 12:37 UTC, mfranciszkiewicz approved these changes

2017-12-05 12:53 UTC, merged