Fill ForceReportComputedTask with contents
golemfactory/clay pull request #1742
Opened 2017-12-11 11:11 UTC by jiivan

Utilises addition of MessageHistoryService.

2017-12-15 14:37 UTC, Krigpl requested changes

2017-12-15 14:37 UTC, Krigpl commented on tests/golem/task/test_tasksession.py
> +        with patch('golem.network.history.MessageHistoryService.get_sync')\
As I understand this a way to check and we returned early from the function and didn't send anything to Concent.
This check depends on this particular implementation, more natural check would be a check against `self.concent_service.submit` not being called, since this is the side effect that should not happen.

2017-12-15 14:37 UTC, Krigpl commented on tests/golem/task/test_tasksession.py
> +            history.MessageHistoryService.instance = None
Why is this needed ?

2017-12-15 14:37 UTC, Krigpl commented on tests/golem/task/test_tasksession.py
> +    def test_send_report_computed_task_concent_succes(self):
`s/succes/success/`

2017-12-18 11:25 UTC, jiivan commented on tests/golem/task/test_tasksession.py
> +            history.MessageHistoryService.instance = None
Moved to `tearDown()`. It resets `MessageHistoryService` state to it's default state.

2017-12-18 11:27 UTC, jiivan commented on tests/golem/task/test_tasksession.py
> +        with patch('golem.network.history.MessageHistoryService.get_sync')\
Thanks for  pointing this out! It was a mistake. `get_sync` doesn't depend on `instance`.

2017-12-19 09:51 UTC, Krigpl approved these changes

2017-12-19 09:53 UTC, Krigpl commented on tests/golem/task/test_tasksession.py
> +            history.MessageHistoryService.instance = None
I don't know the internals of how python tests work, but I understand that each test is not run in a separate process and we need to perform cleanup of the global state after each test?

2017-12-21 10:47 UTC, merged