Unit tests on buildbots
golemfactory/clay pull request #1754
Opened 2017-12-12 11:27 UTC by maaktweluit

Resolves #1400 

Depends on #1743

- Moved all unit tests to buildbot
- Added inno installer to the `buildpackage_windows` job
- Moved linter tests to buildbot
- Lowered github status count to 2, `test` and `build`
- Increased workers to 2 per OS ( + 2 for linting )

Open Tasks:
- [ ] Deploy production servers
  - [ ] Setup AWS
  - [ ] Tweak config
  - [ ] Install AWS
  - [ ] Testing
  - [ ] Switch public DNS record
- [ ] Finish nightly build script

Possible follow up improvements:
- [ ] Kill hyperg instead of using old process for tests, fail if not successful

2018-01-04 14:32 UTC, maaktweluit commented
Made issues for:
- Nightly uploads
- Redundant master

Will try to fix the rebuild-slow and rebase to get this finished PR merged.

2018-01-15 15:24 UTC, maaktweluit commented
Updated the code to the latest of develop and made all follow up issues.

Now this PR is ready to be reviewed and merged :)

2018-01-17 11:34 UTC, ktomala requested changes
Please review and fix the changes

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
According to ANSIBLE0017 you should probably add "become: yes" also

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
According to ANSIBLE0017 you should probably add "become: yes" also

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
According to ANSIBLE0017 you should probably add "become: yes" also

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
According to ANSIBLE0017 you should probably add "become: yes" also

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/roles/buildbot-worker-mac/tasks/main.yml
> +  become_user: buildbot-worker
According to ANSIBLE0017 you should probably add "become: yes" also

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/roles/buildbot-worker-mac/tasks/main.yml
> +  become_user: buildbot-worker
According to ANSIBLE0017 you should probably add "become: yes" also

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/roles/buildbot-worker-mac/tasks/main.yml
> +  become_user: buildbot-worker
According to ANSIBLE0017 you should probably add "become: yes" also

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/roles/buildbot-worker-mac/tasks/main.yml
> +  become_user: buildbot-worker
According to ANSIBLE0017 you should probably add "become: yes" also

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/site-worker-control.yml
> +    - master_host: {{hostvars[groups['master'][0]]['ec2_private_ip_address']}}
Please wrap template variable in double quotes, i.e.:
``` - master_host: "{{hostvars[groups['master'][0]]['ec2_private_ip_address']}}"```

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/site-worker-mac.yml
> +      worker_master_hostname: {{hostvars[groups['master'][0]]['ec2_public_ip_address']}}
Please wrap template variable in double quotes, i.e.:
``` worker_master_hostname: {{hostvars[groups['master'][0]]['ec2_public_ip_address']}}```

2018-01-17 11:34 UTC, ktomala commented on scripts/ci/site-worker-windows.yml
> +      worker_master_hostname: {{hostvars[groups['master'][0]]['ec2_private_ip_address']}}
Please wrap template variable in double quotes, i.e.:
```  worker_master_hostname: "{{hostvars[groups['master'][0]]['ec2_private_ip_address']}}" ```

2018-01-17 11:56 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
Never knew there was an Ansible set of `PEP001` rules as well, awesome!

Since it is already running and in production i do not feel safe adding this and running it again. Durning installation there where some problems with `become: yes`, though mostly on mac and windows.

2018-01-17 11:57 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-mac/tasks/main.yml
> +  become_user: buildbot-worker
on mac this does not work as intended, maybe we have to re-configure become-method.

Propose to investigate this when splitting up the roles.

2018-01-17 11:59 UTC, maaktweluit commented on scripts/ci/site-worker-control.yml
> +    - master_host: {{hostvars[groups['master'][0]]['ec2_private_ip_address']}}
Tried to keep everything without "" if it would still run, is that not a good practice?

2018-01-18 20:38 UTC, Elfoniok approved these changes
LGTM! hell of a job. We should celebrate this ;)

2018-01-19 08:13 UTC, etam commented on scripts/ci/site-worker-control.yml
> +    - master_host: {{hostvars[groups['master'][0]]['ec2_private_ip_address']}}
http://docs.ansible.com/ansible/latest/playbooks_variables.html#using-variables-about-jinja2

2018-01-19 08:26 UTC, etam commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
http://docs.ansible.com/ansible/latest/become.html
> become_user - [...] Does NOT imply become: yes

2018-01-19 12:59 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
When trying to fix this i found there is a bug in `ANSIBLE0017`: https://github.com/willthames/ansible-lint/issues/215

in `site-linux-worker.yml` become is set for the full role.

2018-01-19 13:00 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
replied above

2018-01-19 13:00 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
replied above

2018-01-19 13:07 UTC, ktomala commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
Should we ignore ANSIBLE0017 for now?

2018-01-19 13:15 UTC, maaktweluit commented
Thank you all for the great comments!

Replied to all and updated the PR.

Also added 1 small fix after the "pull request webhooks" got enabled and broke ( SHA c66ee6a )

2018-01-19 13:23 UTC, maaktweluit commented on scripts/ci/roles/buildbot-worker-linux/tasks/main.yml
> +  become_user: "{{worker_user}}"
Yes, think it is best.

We should find a solve for both mac and linux separately before enabling this check.

2018-01-23 11:09 UTC, ktomala approved these changes

2018-01-23 17:04 UTC, merged