Verification refactor
golemfactory/clay pull request #1773
Opened 2017-12-15 16:18 UTC by badb

2017-12-22 11:20 UTC, Elfoniok approved these changes

2017-12-28 13:35 UTC, Elfoniok requested changes
I have found one problem. There is error with get_resource definition. This occur when using task persistence. Simply add some task to golem, quit, run it again, wait for loading remembered task, then it will crash.

2017-12-29 12:20 UTC, badb commented
@Elfoniok Fixed.

2018-01-02 16:08 UTC, Elfoniok approved these changes

2018-01-08 15:40 UTC, merged