Add timestamp property to Payment
golemfactory/clay pull request #1803
Opened 2017-12-22 13:59 UTC by Krigpl

It's needed to correctly calculate `closure_time` for `batchTransfer`

2017-12-22 14:12 UTC, jiivan requested changes

2017-12-22 14:12 UTC, jiivan commented on golem/model.py
> +    timestamp = IntegerField(null=True)
DateTimeField is more customary in DB context: http://docs.peewee-orm.com/en/latest/peewee/models.html#datetimefield-datefield-and-timefield

Maybe call it `processed_at`? So it will be more obvious that it's a time of processing not creation/modification time.

2017-12-22 14:12 UTC, jiivan commented on tests/golem/transactions/ethereum/test_paymentprocessor.py
> +    def test_payment_timestamp(self):
You can use `freezegun` to test time related cases.

2017-12-22 14:12 UTC, jiivan commented on tests/golem/transactions/ethereum/test_paymentprocessor.py
> +        self.assertEqual(ts, p.timestamp)
Does this test wether mock works properly? :)

2017-12-22 15:11 UTC, Krigpl commented on golem/model.py
> +    timestamp = IntegerField(null=True)
> SQLite does not have a native date type, so dates are stored in formatted text columns.

I'd rather stay with integers

2017-12-22 15:12 UTC, Krigpl commented on tests/golem/transactions/ethereum/test_paymentprocessor.py
> +        self.assertEqual(ts, p.timestamp)
What do you mean? It tests whether `timestamp` field has been set on payment during the `PaymentProcessor::add` call.

2017-12-22 15:27 UTC, jiivan commented on tests/golem/transactions/ethereum/test_paymentprocessor.py
> +        self.assertEqual(ts, p.timestamp)
It seems to me that this test is too low-level. Almost like testing:
```
a = 1
assert a == 1
```

2017-12-22 15:32 UTC, Krigpl commented on tests/golem/transactions/ethereum/test_paymentprocessor.py
> +        self.assertEqual(ts, p.timestamp)
It isn't, it tests exactly the lines of code I've added here:
```
            ts = int(time.time())
            with Payment._meta.database.transaction():
                payment.timestamp = ts
                payment.save()
```
This test will fail if those fail to execute. Why do you think it's too low level?

2017-12-27 09:22 UTC, Krigpl commented on tests/golem/transactions/ethereum/test_paymentprocessor.py
> +    def test_payment_timestamp(self):
I looked at the `freezegun` package and correct me if I'm wrong but you need to specify the time in human readable format, can't just provide a unix timestamp? Which would make this test less clear about what it's doing.

2017-12-27 09:50 UTC, jiivan commented on tests/golem/transactions/ethereum/test_paymentprocessor.py
> +    def test_payment_timestamp(self):
Are you suggesting that human readable time is less readable than an integer/float? ;) By default you can use datetime instance or anything that is parsable by [dateutil](https://dateutil.readthedocs.io/en/stable/parser.html).

2018-01-03 08:47 UTC, jiivan approved these changes

2018-01-03 10:44 UTC, merged