Upgrade golem-messages to 1.3.3
golemfactory/clay pull request #1858
Opened 2018-01-05 13:05 UTC by jiivan

* It assures that all fields in messages exist and are initialized with `None`
 * Additionally hardened `PeerSession._react_to_hello` to first check protocol
   before accessing other attributes

It also fixes recent `msg.node_name AttributeError` from messages from `drohlum-go-bootstrap`

2018-01-05 16:16 UTC, mfranciszkiewicz approved these changes

2018-01-05 16:44 UTC, mfranciszkiewicz requested changes
There seems to be an issue related to timestamps (from the dummy task test):
```DEBUG    [golem.network.transport.tcpnetwork ] SafeProtocol._data_to_messages(): received GetTasks(timestamp=1515170456, encrypted=True, sig=b'$X\x034(\xb2c\xd0\xf7\xe18\xa6{\x07\x91\xc9\xda\x92\xfagJ\x9d\t\x90\x02\xa8\xaa(\x98\x10LQa$\x11\xdeJ\x10\xf4\x01[\xffe%\xb1\xe9\xa8\xc1\xca\x8b\x1f\x03xW\xa77\xdb\xc5)\xb0\xf9\xdaz\x1d\x01', slots=[])
DEBUG    [golem.network.transport.tcpnetwork ] SafeProtocol._data_to_messages(): received Tasks(timestamp=1515170456, encrypted=True, sig=b"\x9d\xc5~J[\xfe\xdd\xf2X%\xb3\xcc\xfaw\xc8>\x83C@\xa9\xc6\xf9\xa0\xf6\xd0\xbd\xe4\xdc\xf1\xb2\xdb\xd7;\x0e'\xebY\xfc\x8cl\x89\xda\xabR\x0eb\x15\xe2\xb1P\xd8\x9b2\xa4\xa8\x90\x95\xf8\xf6_+\r\x8b\xb4\x00", slots=[['tasks', []]])
DEBUG    [golem.network.transport.tcpnetwork ] SafeProtocol._prepare_msg_to_send(Tasks(timestamp=1515170456, encrypted=False, sig=None, slots=[['tasks', [{'signature': b'\xbcV\xe5\xc1,y\xb05\x06\xa9q\xb0\xc3\xb8\xbb\xc0\x02\xe7k\xc2\xb6\xeeC-k\x82V\x9b\xc2\xe8Q\x14_\xc2\xc3\xb3hHq\xd5\xf7w&\x82\x97/\x82)3\xaa\xcfe\xa1 \xe2\xda\x0f\xf00\x86Xs\x8f\x9f\x01', 'task_owner': {'prv_addresses': ['10.30.10.95', '172.17.0.1', '192.168.117.1', '172.16.240.1'], 'pub_addr': '1.2.3.4', 'p2p_pub_port': None, 'key': '7f9d41c148ae6a478634dfbe0fd0c550799c785f6432487e17ac616a6664128b3fd48bc8249d2adc933638b557e5a723a8ea2b8e09b1de0a3b71c98493fec35d', 'node_name': '', 'port_status': None, 'prv_port': 40107, 'prv_addr': '10.30.10.95', 'nat_type': 'Open Internet', 'p2p_prv_port': 40106, 'pub_port': None}, 'estimated_memory': 0, 'node_name': '', 'task_owner_key_id': '7f9d41c148ae6a478634dfbe0fd0c550799c785f6432487e17ac616a6664128b3fd48bc8249d2adc933638b557e5a723a8ea2b8e09b1de0a3b71c98493fec35d', 'task_owner_port': 40107, 'task_owner_address': '10.30.10.95', 'docker_images': None, 'deadline': 1515184834.171028, 'last_checking': 1515170434.171068, 'min_version': '0.10.1', 'max_price': 500000000000000000, 'task_id': '002d30fb-7d92-466d-b3ff-279d79bc278f', 'resource_size': 3072, 'subtask_timeout': 1200, 'environment': 'DUMMY'}]]]))
DEBUG    [golem.network.transport.message    ] msg_type: 1006
DEBUG    [golem.network.transport.message    ] msgdt 2018-01-05 16:40:56 Δ 0:00:00.459235 Δfuture -1 day, 23:59:59.540765
DEBUG    [golem.network.transport.tcpnetwork ] SafeProtocol._data_to_messages(): received Tasks(timestamp=1515170456, encrypted=True, sig=b"\x9d\xc5~J[\xfe\xdd\xf2X%\xb3\xcc\xfaw\xc8>\x83C@\xa9\xc6\xf9\xa0\xf6\xd0\xbd\xe4\xdc\xf1\xb2\xdb\xd7;\x0e'\xebY\xfc\x8cl\x89\xda\xabR\x0eb\x15\xe2\xb1P\xd8\x9b2\xa4\xa8\x90\x95\xf8\xf6_+\r\x8b\xb4\x00", slots=[['tasks', []]])
```

2018-01-08 09:11 UTC, etam requested changes

2018-01-08 09:11 UTC, etam commented on tests/golem/network/p2p/test_peersession.py
> +    def test_react_to_hello_malformed(self, disconnect_mock, super_mock):
What's `super_mock`? It's unused.

2018-01-08 09:11 UTC, etam commented on golem/network/p2p/peersession.py
> +            compare_version(getattr(msg, 'client_ver', None))
I think it would be much cleaner, to have a first step that checks if required fields are not None and after that use `msg.whatever` like before.

2018-01-08 09:54 UTC, jiivan commented on tests/golem/network/p2p/test_peersession.py
> +    def test_react_to_hello_malformed(self, disconnect_mock, super_mock):
@mfranciszkiewicz Unfortunatelly it's something else: :( Problem with timestamp would result in `"Message error: invalid timestamp: %r %s"` https://github.com/golemfactory/golem-messages/blob/master/golem_messages/message.py#L261Delta < 1s is not a problem.

2018-01-08 09:54 UTC, jiivan commented
@mfranciszkiewicz Unfortunatelly it's something else: :( Problem with timestamp would result in `"Message error: invalid timestamp: %r %s"` https://github.com/golemfactory/golem-messages/blob/master/golem_messages/message.py#L261 Delta < 1s is not a problem.

2018-01-08 11:17 UTC, jiivan commented on tests/golem/network/p2p/test_peersession.py
> +    def test_react_to_hello_malformed(self, disconnect_mock, super_mock):
It comes from: `@mock.patch('golem.network.transport.session.BasicSession._react_to_hello')`. Without this, disconnect would be called by it (different golem_messages_version)

2018-01-08 11:59 UTC, etam commented on golem/network/p2p/peersession.py
> +        # and we don't want this before compare_version()
This comment implies some connection between compare_version and connection. It made me confused for a bit.
I think it's enough that the code is in correct order and this comment should be removed.

2018-01-08 11:59 UTC, etam approved these changes

2018-01-08 15:39 UTC, mfranciszkiewicz approved these changes

2018-01-08 16:06 UTC, merged