Restart task by creating a new one
golemfactory/clay pull request #1866
Opened 2018-01-08 15:11 UTC by etam

Fixes #1748

2018-01-08 15:15 UTC, etam commented
golem-electron part: golemfactory/golem-electron#192

2018-01-10 10:15 UTC, jiivan requested changes

2018-01-10 10:15 UTC, jiivan commented on apps/dummy/task/dummytask.py
> +            difficulty = int(difficulty, 16)
~~Why?Is your intention to prevent casting to `int` anything other than `str`?~~

2018-01-10 10:15 UTC, jiivan commented on golem/task/taskmanager.py
> +    def put_task_in_restarted_state(self, task_id):
Could you add a docstring that states explicitly that restarted state means that a task is stopped and duplicate is created?

2018-01-10 10:15 UTC, jiivan commented on tests/golem/test_client.py
> +        assert task_manager.tasks_states[task_id].status == TaskStatus.restarted
Maybe also test subtasks? Or test only `golem.client` here mocking `TaskManager.put_task_in_restarted_state()` and test `put_task_in_restarted_state` in place of removed `test_restart_task`.

2018-01-10 10:19 UTC, etam commented on apps/dummy/task/dummytask.py
> +            difficulty = int(difficulty, 16)
My intention is to handle both hex string and int input.
`TaskManager.get_task_definition_dict` returns `difficulty` as int.

2018-01-10 14:31 UTC, jiivan commented on apps/dummy/task/dummytask.py
> +            difficulty = int(difficulty, 16)
Oh, now I see that casting is made with base 16. My bad.

2018-01-11 10:23 UTC, jiivan approved these changes

2018-01-15 15:04 UTC, Elfoniok approved these changes

2018-01-16 16:35 UTC, badb commented
https://github.com/golemfactory/golem-electron/pull/192 should be merged as well

2018-01-16 16:35 UTC, merged