Empty hostname fix
golemfactory/clay pull request #1871
Opened 2018-01-08 18:56 UTC by mdtanrikulu

Resolves #1827.

2018-01-10 16:02 UTC, badb requested changes
Situation where peer_info["address"] is malformed is somehow special. We

2018-01-10 16:02 UTC, badb commented on golem/network/p2p/p2pservice.py
> +                (peer_info["address"] is str and peer_info["address"] != '')):
Can you user `SocketAddress.is_proper_address` method here instead?

2018-01-10 16:02 UTC, badb commented on golem/network/transport/tcpnetwork.py
> +                "Can't stop listening on port {}, wasn't listening.".format(port))
Some changed lines in this file are still too long. The changes in this file are irrelevant for the issue in this PR, but you have already changed them, so finish this in a way that makes linter happy.

2018-01-24 18:57 UTC, badb commented on golem/network/p2p/p2pservice.py
> +        socket_address = tcpnetwork.SocketAddress(
Is this needed?

2018-01-30 12:46 UTC, maaktweluit requested changes
LGTM!

One small cleanup, will approve on reply :)

2018-01-30 12:46 UTC, maaktweluit commented on golem/network/p2p/p2pservice.py
> +            .where(KnownHosts.is_seed == False):  # noqa
`# noqa` can be removed now the line is no longer too long.

2018-02-04 13:27 UTC, mdtanrikulu commented on golem/network/p2p/p2pservice.py
> +            .where(KnownHosts.is_seed == False):  # noqa
yeap, that's right 👍

2018-02-04 13:28 UTC, mdtanrikulu commented on golem/network/p2p/p2pservice.py
> +        socket_address = tcpnetwork.SocketAddress(
It's not, I removed it.

2018-02-13 12:00 UTC, maaktweluit approved these changes

2018-02-13 12:44 UTC, badb approved these changes

2018-02-13 12:44 UTC, merged