Rececive single set_tasks_session msg once for 60sec from each peer
golemfactory/clay pull request #1872
Opened 2018-01-09 13:44 UTC by Elfoniok

Signed-off-by: Lukasz Foniok <lukaszfoniok@gmail.com>

2018-01-10 09:26 UTC, jiivan requested changes
Good job, but I think implementation could be simplified. Adding tests would be a good idea :) They should be quite straightforward with `freezegun`.

Also have you seen choker (pol. dławik) from original bittorrent implementation? Maybe this approach will work better for us? Not a request, just an inspiration.
https://github.com/mgp/bittorrent-dissected/blob/master/Choker.py
https://github.com/mgp/bittorrent-dissected#chokerpy

2018-01-10 09:26 UTC, jiivan commented on golem/network/transport/spamprotector.py
> +            if self.last_msg_map[msg_type] - int(time.time()) < __class__.FeqDict[msg_type]:
`./golem/network/transport/spamprotector.py:36:81: E501 line too long (92 > 80 characters)`

2018-01-10 09:26 UTC, jiivan commented on golem/network/transport/spamprotector.py
> +        if msg_type == __class__.SetTaskSessionType:
Why not explicitly use `golem_messages.message.SetTaskSession.TYPE`?

2018-01-10 09:26 UTC, jiivan commented on golem/network/transport/spamprotector.py
> +    SetTaskSessionFrq = 20
Unused, just move 20 to `FreqDict`?

2018-01-10 09:26 UTC, jiivan commented on golem/network/transport/spamprotector.py
> +        self.last_msg_map = dict()
If `FreqDict` then `self.last_msg_*dict*` also?

2018-01-10 09:26 UTC, jiivan commented on golem/network/transport/spamprotector.py
> +    FeqDict = { SetTaskSessionType: SetTaskSessionFrq}
If this is meant to be constant then maybe `FREQ_DICT`?

2018-01-10 09:26 UTC, jiivan commented on golem/network/transport/spamprotector.py
> +        return self._check_msg_type(msg_type)
Instead of implementing helper `_check_msg_type()` just ask `FreqDict`?

```python
if msg_type not in self.FreqDict:
    return True
now = time.time()
last_received = self.last_msg_map.get(msg_type, 0)
delta = now - last_received
if delta > self.FreqDict[msg_type]:
    self.last_msg_map[msg_type] = now
    return True
return False
```

2018-01-10 11:51 UTC, Elfoniok commented on golem/network/transport/spamprotector.py
> +    SetTaskSessionFrq = 20
No the point is to have names on such constants.

2018-01-10 11:52 UTC, Elfoniok commented on golem/network/transport/spamprotector.py
> +    FeqDict = { SetTaskSessionType: SetTaskSessionFrq}
Done

2018-01-10 11:53 UTC, Elfoniok commented on golem/network/transport/spamprotector.py
> +        self.last_msg_map = dict()
Lets just leave this. I have changed previous name

2018-01-10 12:02 UTC, Elfoniok commented on golem/network/transport/spamprotector.py
> +        return self._check_msg_type(msg_type)
Done

2018-01-10 12:02 UTC, Elfoniok commented on golem/network/transport/spamprotector.py
> +        if msg_type == __class__.SetTaskSessionType:
Done

2018-01-10 12:02 UTC, Elfoniok commented on golem/network/transport/spamprotector.py
> +            if self.last_msg_map[msg_type] - int(time.time()) < __class__.FeqDict[msg_type]:
Done

2018-01-10 12:06 UTC, Elfoniok commented
Its a good idea (choker) and we might keep that in mind for future development. But bit torrent use case is for data not messages so its not easy to incorporate this, but we might get inspired and try to design something more sophisticated later in time.

2018-01-10 14:10 UTC, mfranciszkiewicz approved these changes

2018-01-10 14:10 UTC, mfranciszkiewicz commented on golem/network/transport/spamprotector.py
> +        logger.debug("DROPING SPAM message")
IMO this message could include the message class and remote peer's address. The latter is not available here, so this might have to be logged in `Basic/SafeProtocol`.

2018-01-10 14:12 UTC, jiivan commented on tests/golem/network/transport/test_tcpnetwork.py
> +            frozen_datetime.move_to("2014-02-12 11:30:45")
```python
protocol.session.interpret.reset_mock()
protocol.session.interpret.assert_called_once_with(msg)
```

2018-01-10 14:15 UTC, jiivan commented on golem/network/transport/spamprotector.py
> +        logger.debug("DROPING SPAM message")
`s/DROPING/DROPPING/`

2018-01-10 14:17 UTC, jiivan commented on golem/network/transport/spamprotector.py
> +    SetTaskSessionInterval = 20
It's already named and easily referenced by INTERVALS[SetTaskSession.TYPE], why add another label?

2018-01-10 14:33 UTC, Elfoniok commented on golem/network/transport/spamprotector.py
> +    SetTaskSessionInterval = 20
To understand what it means

2018-01-11 08:53 UTC, jiivan commented
I suggest closing this pull request. Merging #1879 to b0.10.1 and then merging b0.10.1 to develop. Otherwise we will have duplicated commits and possible merging nightmare.

2018-01-11 11:48 UTC, closed without merging