Ensure 50% of sending task header to be self
golemfactory/clay pull request #1897
Opened 2018-01-15 08:00 UTC by Elfoniok

Signed-off-by: Lukasz Foniok <lukaszfoniok@gmail.com>

2018-01-15 09:24 UTC, jiivan commented
```
Changed lines findings:

./tests/golem/network/p2p/test_peersession.py:371:81: E501 line too long (85 > 80 characters)
./tests/golem/task/test_taskserver.py:331:81: E501 line too long (93 > 80 characters)
```

Otherwise LGTM

2018-01-17 09:05 UTC, jiivan approved these changes

2018-01-17 11:27 UTC, etam requested changes

2018-01-17 11:27 UTC, etam commented on tests/golem/network/p2p/test_peersession.py
> +        peer_session.p2p_service.get_tasks_headers.return_value = None,\
This should be split into small test cases.

2018-01-17 11:27 UTC, etam commented on golem/task/taskserver.py
> +        return [th.to_dict() for th in ths_tm], [th.to_dict() for th in ths_tk]
[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself): call the methods below.

2018-01-17 11:27 UTC, etam commented on golem/task/taskserver.py
> +        return ret
This could be collapsed into one line. Or at least two (`ths_tk` variable is OK, `ret` not so much).

2018-01-17 11:27 UTC, etam commented on golem/task/taskserver.py
> +    def get_other_tasks(self):
`get_other_tasks_headers`

2018-01-17 11:27 UTC, etam commented on golem/task/taskserver.py
> +    def get_my_tasks(self):
`get_my_tasks_headers`

2018-01-17 11:27 UTC, etam commented on tests/golem/task/test_taskserver.py
> +            self.assertEqual(len(ts.get_tasks_headers()[1]), 0)
`ts.get_other_tasks_headers()` is better than `ts.get_tasks_headers()[1]`

2018-01-17 19:14 UTC, Elfoniok commented on tests/golem/task/test_taskserver.py
> +            self.assertEqual(len(ts.get_tasks_headers()[1]), 0)
This function is not available anymore.

2018-01-18 07:52 UTC, etam commented on tests/golem/task/test_taskserver.py
> +            self.assertEqual(len(ts.get_tasks_headers()[1]), 0)
Shame. The current form is very hard to read and confusing. `get_my_tasks_headers` and `get_other_tasks_headers` was nice and clear.

2018-01-18 08:42 UTC, Elfoniok commented on tests/golem/task/test_taskserver.py
> +            self.assertEqual(len(ts.get_tasks_headers()[1]), 0)
This is only for tests

2018-01-18 09:00 UTC, etam commented on tests/golem/task/test_taskserver.py
> +            self.assertEqual(len(ts.get_tasks_headers()[1]), 0)
We shouldn't have illegible code in tests either.
I think `get_tasks_headers` should be deleted and replaced by two methods.

2018-01-18 09:31 UTC, Elfoniok commented on tests/golem/task/test_taskserver.py
> +            self.assertEqual(len(ts.get_tasks_headers()[1]), 0)
Doesn't make sens, code in test often use function in crude way, because it's trying to create specific environment. In golem we only need one function. This is small change not api refactor.

2018-01-18 09:35 UTC, etam commented on golem/network/p2p/peersession.py
> +            logger.debug("Unexected format of my task list %r", my_tasks)
typo: "Unexected" -> "Unexpected"

2018-01-18 09:37 UTC, etam commented on golem/network/p2p/peersession.py
> +                my_tasks, int(variables.TASK_HEADERS_LIMIT / 2))
`int(a/b)` -> `a//b`

2018-01-18 09:50 UTC, etam commented on tests/golem/task/test_taskserver.py
> +            self.assertEqual(len(ts.get_tasks_headers()[1]), 0)
Splitting this function is a small change. Public api or not, more readable code is always better.

2018-01-18 11:37 UTC, etam approved these changes
Nice!

2018-01-18 11:59 UTC, merged