Benchmark error callback
golemfactory/clay pull request #1915
Opened 2018-01-18 11:21 UTC by etam

Fixes #1873

2018-01-18 20:21 UTC, Elfoniok requested changes

2018-01-18 20:21 UTC, Elfoniok commented on golem/client.py
> +                err = Exception(err)
Can't you do this once in run_benchmark function?

2018-01-19 08:11 UTC, etam commented on golem/client.py
> +                err = Exception(err)
I don't understand. Could you elaborate?

2018-01-19 10:26 UTC, Elfoniok approved these changes

2018-01-22 14:10 UTC, etam commented
rebased onto develop

2018-01-22 17:22 UTC, badb approved these changes

2018-01-23 08:15 UTC, merged