Kt/issue 1900
golemfactory/clay pull request #1923
Opened 2018-01-18 16:04 UTC by ktomala

Fix for issue #1900. Please review and merge.

2018-01-18 16:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=1923) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=1923) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: maaktweluit<br/>:x: Karol Tomala<br/><hr/>**Karol Tomala** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=1923) it.</sub>

2018-01-19 14:13 UTC, maaktweluit commented
Could you `rebase -i` the branch `mwu/bb-unit-tests` out of this PR?

This can go directly from and to develop since the files you touched are not changed in `mwu/bb-unit-tests`

As discussed I will run some tests on windows and mac, then review the rest of the PR.

2018-01-19 14:49 UTC, maaktweluit requested changes

2018-01-19 14:49 UTC, maaktweluit commented on scripts/test-daemon-start.ps1
> +  Stop-Process -Id $HyperdriveProcess
missing `.Id` after `$HyperdriveProcess`

2018-01-19 14:51 UTC, ktomala commented
Branch was rebased.

2018-01-19 14:58 UTC, maaktweluit commented
Thank you for the rebase!

Ran tests on mac as well, these went flawless.
Also see `buildbot/control_test` is green so looks good :)

Only the 1 windows comment left on the PR.

2018-01-19 15:47 UTC, maaktweluit approved these changes

2018-01-23 09:09 UTC, ktomala commented
@badb Could we merge this PR?

2018-01-24 13:42 UTC, merged