add support for allow list
golemfactory/clay pull request #1930
Opened 2018-01-19 15:21 UTC by etam

fixes #1836

2018-01-20 15:34 UTC, jiivan requested changes
LGTM! Small remarks

2018-01-20 15:34 UTC, jiivan commented on tests/golem/resource/test_resourcehandshake.py
> +from pathlib import Path
`C: tests/golem/resource/test_resourcehandshake.py:3:0: standard import "from pathlib import Path" should be placed before "from golem_messages import message" (wrong-import-order)`

2018-01-20 15:34 UTC, jiivan commented on golem/task/acl.py
> +        return set(line.strip() for line in f)
```python
try:
    with path.open() as f:
        #...
except OSError:
    return set()
```
Would protect against race conditions and is generally considered more pythonic.
https://docs.python.org/3/glossary.html?highlight=eafp#term-lbyl

2018-01-22 10:03 UTC, Krigpl commented
Having two lists for denied and allowed users and both of them being non empty feels weird.
Something like one list with the list of specified users and a mode (deny/allow) would be cleaner imo.
Not insisting though, so if it's too much to change then I'm good.

2018-01-22 11:07 UTC, etam commented on golem/task/acl.py
> +        return set(line.strip() for line in f)
I don't think we should care about race conditions in this case (unless you like to race with editing config files against a starting application). Also I wrote it this way, because in C++ an expected condition shouldn't be handled with exceptions. But that's python, so I think it's OK to change it as you propose.

2018-01-22 11:44 UTC, etam commented
@Krigpl good point

2018-01-22 12:57 UTC, jiivan approved these changes

2018-01-22 14:29 UTC, Krigpl commented on tests/golem/task/test_acl.py
> +        assert acl._deny_set == set()
`self.AssertEqual` and family are preferable since they give much better errors messages compared to these simple asserts

2018-01-22 14:29 UTC, Krigpl commented on golem/task/acl.py
> +    nodes_ids = _read_set_from_file(datadir / DENY_LIST_NAME)
I understand that `Path` is os aware and `datadir / DENY_LIST_NAME` will use `\` for Windows?

2018-01-22 14:33 UTC, etam commented on golem/task/acl.py
> +    nodes_ids = _read_set_from_file(datadir / DENY_LIST_NAME)
Yes

2018-01-22 14:37 UTC, etam commented on tests/golem/task/test_acl.py
> +        assert acl._deny_set == set()
https://docs.pytest.org/en/latest/unittest.html

> Benefits out of the box
> By running your test suite with pytest you can make use of several features, in most cases without having to modify existing code:
> - [...]
> - Use plain assert-statements instead of self.assert* functions

2018-01-22 14:47 UTC, Krigpl commented on tests/golem/task/test_acl.py
> +        assert acl._deny_set == set()
Huh, I must have been blind because I thought the messages are not descriptive. TIL

2018-01-22 14:48 UTC, Krigpl approved these changes

2018-01-22 15:28 UTC, merged