[WIP] Ack or Reject ReportComputedTask
golemfactory/clay pull request #1946
Opened 2018-01-22 19:42 UTC by jiivan

fixes: #1626

2018-01-29 11:01 UTC, etam commented on tests/golem/task/test_concent_logic.py
> +"""Tests related to ConCent integration.
Con **C** ent ?

2018-01-29 11:21 UTC, etam requested changes

2018-01-29 11:21 UTC, etam commented on tests/factories/messages.py
> +class TaskOwner(factory.DictFactory):
Isn't it possible to reuse those from golem-messages?

2018-01-29 11:21 UTC, etam commented on tests/golem/task/test_concent_logic.py
> +        self.datadir = tempfile.TemporaryDirectory('golem-test-concent')
use `golem.testutils.TempDirFixture`?

2018-01-29 11:21 UTC, etam commented on tests/golem/task/test_concent_logic.py
> +        with freeze_time(after_deadline):
This time freezing would be better if you'd use a single timestamp as a starting point both here and in setUp.

2018-01-29 13:09 UTC, jiivan commented on tests/golem/task/test_concent_logic.py
> +"""Tests related to ConCent integration.
I'm not sure about that. Concent suggests there is a typo (consent), but it's more widely used as concent now. Changed.

2018-01-29 13:11 UTC, jiivan commented on tests/factories/messages.py
> +class TaskOwner(factory.DictFactory):
It's hard because tests are not included in golem-messages library. I don't know how to resolve this reasonably now. Also they're really simple straightforward declarative definitions. I think the abuse of DRY here is not big.

2018-01-29 13:11 UTC, jiivan commented on tests/golem/task/test_concent_logic.py
> +        self.datadir = tempfile.TemporaryDirectory('golem-test-concent')
done

2018-01-29 13:11 UTC, jiivan commented on tests/golem/task/test_concent_logic.py
> +        with freeze_time(after_deadline):
done

2018-01-29 15:38 UTC, etam commented on tests/factories/messages.py
> +class TaskOwner(factory.DictFactory):
You could make it as a part of library (something like golem.testutils) and import it in both places.

2018-01-29 15:40 UTC, etam requested changes

2018-01-29 15:40 UTC, etam commented on tests/golem/task/test_concent_logic.py
> +import tempfile
'tempfile' imported but unused

2018-02-01 10:09 UTC, jiivan commented on tests/factories/messages.py
> +class TaskOwner(factory.DictFactory):
Could work. Created an issue for that https://github.com/golemfactory/golem-messages/issues/117

2018-02-01 10:30 UTC, shadeofblue commented on tests/factories/messages.py
> +class TaskOwner(factory.DictFactory):
@jiivan I think I'd second @etam here and - of course, acknowledging that it's _that_ much of a problem - I'd be for including the tests into the library so they can be reused, especially that we'll most likely have more and more code even there and it seems a waste indeed to have to maintain two copies...

2018-02-01 10:34 UTC, shadeofblue commented
hmm, given the above comment from @jiivan : `https://github.com/golemfactory/golem/pull/1946#discussion_r165308289` I personally don't see any other issues ... though, probably it would be better if a review from someone more versed with golem's code expressed their approval...

2018-02-01 10:35 UTC, shadeofblue approved these changes

2018-02-01 12:53 UTC, etam approved these changes

2018-02-01 13:15 UTC, merged