Generate crops in Blender verifier
golemfactory/clay pull request #1952
Opened 2018-01-23 16:47 UTC by badb

2018-01-23 21:38 UTC, Elfoniok approved these changes

2018-01-24 09:37 UTC, jiivan requested changes
LGTM minus easily fixable issues. Generally I would appreciate more docstrings and comments in whole verifier class.

2018-01-24 09:37 UTC, jiivan commented on apps/blender/task/verifier.py
> +                    "results: {}".format(time_spend, results))
`[logging-format-interpolation] Use % formatting in logging functions and pass the % parameters as arguments`
https://gist.github.com/jiivan/eedb505574ccb2503af48fa2e3043036

2018-01-24 09:37 UTC, jiivan commented on apps/blender/task/verifier.py
> +        logger.info("Crop for verification render failure {}".format(error))
`[logging-format-interpolation] Use % formatting in logging functions and pass the % parameters as arguments`

2018-01-24 09:37 UTC, jiivan commented on apps/blender/task/verifier.py
> +        # FIXME (root path)
What does it mean? Is there an issue for that?

2018-01-24 09:37 UTC, jiivan commented on apps/blender/task/verifier.py
> -    # pylint: disable=unused-argument
pylint still reports unused argument
`apps/blender/task/verifier.py|69 col 43 warning| [unused-argument] Unused argument 'resources'`

2018-01-24 09:37 UTC, jiivan commented on apps/blender/task/blenderrendertask.py
> +        self.subtasks_given[hash]['tmp_dir'] = self.tmp_dir  # FIXME
What's here to fix? Is there an issue for that?

2018-01-24 10:47 UTC, badb commented on apps/blender/task/blenderrendertask.py
> +        self.subtasks_given[hash]['tmp_dir'] = self.tmp_dir  # FIXME
https://github.com/golemfactory/golem/issues/1955

2018-01-24 10:47 UTC, badb commented on apps/blender/task/verifier.py
> +        # FIXME (root path)
# pylint: disable=unused-argument

2018-01-24 11:09 UTC, jiivan commented on apps/blender/task/blenderrendertask.py
> +        self.subtasks_given[hash]['tmp_dir'] = self.tmp_dir  # FIXME
Could put a reference to this issue in `# FIXME` comment?

2018-01-24 11:09 UTC, jiivan commented on apps/blender/task/verifier.py
> +        # FIXME (root path)
Could put a reference to this issue in `# FIXME` comment?

2018-01-24 12:39 UTC, jiivan approved these changes

2018-01-24 12:39 UTC, merged