Blender verify function is now async
golemfactory/clay pull request #1957
Opened 2018-01-24 12:51 UTC by Elfoniok

Signed-off-by: Lukasz Foniok <lukaszfoniok@gmail.com>

2018-01-24 13:13 UTC, jiivan commented on apps/blender/task/verifier.py
> +        logger.info("Crop for verification render failure %r" % (error))
missing `,` before `%`

2018-01-24 14:34 UTC, Elfoniok commented on apps/blender/task/verifier.py
> +        logger.info("Crop for verification render failure %r" % (error))
Done

2018-01-24 15:52 UTC, Krigpl commented on apps/blender/task/verifier.py
> +        super(BlenderVerifier, self).__init__(callback)
I think the `BlenderVerifier, self` part is no longer needed

2018-01-24 15:52 UTC, Krigpl commented on apps/blender/task/verifier.py
> +        super(BlenderVerifier, self)._verify_imgs(
ditto

2018-01-24 15:52 UTC, Krigpl commented on apps/core/task/coretask.py
> +        self.verifier.computer = ComputerAdapter()
Why is that?

2018-01-24 16:23 UTC, Elfoniok commented on apps/core/task/coretask.py
> +        self.verifier.computer = ComputerAdapter()
verifier is local variable, it can die before threads finish with verification

2018-01-25 09:05 UTC, Krigpl commented on apps/core/task/verifier.py
> +                     callback):
When `callback` is not equal to `self.verification_completed`?

2018-01-25 09:05 UTC, Krigpl commented on apps/core/task/coretask.py
> +        self.verifier.computer = ComputerAdapter()
I'm not familiar with this code, but where is the asynchronous part? I just followed the flow of the `start_verification` and can't find where it does anything asynchronously.

2018-01-25 13:36 UTC, Elfoniok commented on apps/core/task/verifier.py
> +                     callback):
Done, actually self is bind to callback function passed to LocalComputer, so verifier should live long enough.

2018-01-25 13:37 UTC, Elfoniok commented on apps/core/task/verifier.py
> +                     callback):
Done

2018-01-25 13:39 UTC, Elfoniok commented on apps/blender/task/verifier.py
> +        super(BlenderVerifier, self).__init__(callback)
Done

2018-01-25 13:39 UTC, Elfoniok commented on apps/blender/task/verifier.py
> +        super(BlenderVerifier, self)._verify_imgs(
Done

2018-01-25 14:24 UTC, jiivan requested changes
Some comments in code plus easy to clean lints from shippable:
```
./apps/rendering/task/framerenderingtask.py:90:81: E501 line too long (88 > 80 characters)
./apps/rendering/task/framerenderingtask.py:91:52: E251 unexpected spaces around keyword / parameter equals
./apps/rendering/task/framerenderingtask.py:91:54: E251 unexpected spaces around keyword / parameter equals
./golem/task/taskbase.py:251:81: E501 line too long (88 > 80 characters)
./tests/apps/blender/task/test_blenderrendertask.py:100:14: E128 continuation line under-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:101:14: E128 continuation line under-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:102:14: E128 continuation line under-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:114:81: E501 line too long (87 > 80 characters)
./tests/apps/blender/task/test_blenderrendertask.py:115:20: E127 continuation line over-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:119:14: E128 continuation line under-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:120:14: E128 continuation line under-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:121:14: E128 continuation line under-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:122:14: E128 continuation line under-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:136:81: E501 line too long (82 > 80 characters)
./tests/apps/blender/task/test_blenderrendertask.py:137:21: E128 continuation line under-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:140:81: E501 line too long (87 > 80 characters)
./tests/apps/blender/task/test_blenderrendertask.py:141:20: E127 continuation line over-indented for visual indent
./tests/apps/blender/task/test_blenderrendertask.py:96:13: E265 block comment should start with '# '
./tests/apps/blender/task/test_blenderrendertask.py:99:14: E128 continuation line under-indented for visual indent
./tests/golem/task/test_taskmanager.py:436:41: E127 continuation line over-indented for visual indent
./tests/golem/task/test_taskmanager.py:440:41: E127 continuation line over-indented for visual indent
./tests/golem/task/test_taskmanager.py:446:41: E127 continuation line over-indented for visual indent
```

2018-01-25 14:24 UTC, jiivan commented on golem/task/taskmanager.py
> +            return
This return is not needed

2018-01-25 14:24 UTC, jiivan commented on tests/apps/blender/task/test_blenderrendertask.py
> +import mock
`import unittest.mock as mock`

2018-01-25 14:24 UTC, jiivan commented on apps/blender/task/verifier.py
> +                self.failure()
Looks like it will `failure()` only when last crop failed.

2018-01-25 14:24 UTC, jiivan commented on apps/blender/task/verifier.py
> +                self.success()
Looks like it will `success()` only when last crop is successfully rendered

2018-01-25 14:32 UTC, Elfoniok commented on apps/blender/task/verifier.py
> +                self.success()
This is intention

2018-01-25 14:35 UTC, Elfoniok commented on apps/blender/task/verifier.py
> +                self.failure()
Done

2018-01-25 14:36 UTC, Elfoniok commented on tests/apps/blender/task/test_blenderrendertask.py
> +import mock
Done

2018-01-25 14:37 UTC, Elfoniok commented on golem/task/taskmanager.py
> +            return
Done

2018-01-25 14:38 UTC, Krigpl commented on tests/apps/blender/task/test_blenderrendertask.py
> +import mock
What's wrong with `mock` ?

2018-01-25 16:33 UTC, jiivan commented on tests/apps/blender/task/test_blenderrendertask.py
> +import mock
@Krigpl Since python3.3 it's part of stdlib `unittest.mock`. We should remove dependency on custom mock library completely. I've done it once on `devp2p` branch...

2018-01-25 21:21 UTC, badb approved these changes
Nice update, just check those linter warnings, they should be easy to fix.

2018-01-26 10:03 UTC, jiivan approved these changes

2018-01-26 10:35 UTC, merged