fix requirements.txt
golemfactory/clay pull request #1983
Opened 2018-01-28 12:29 UTC by peteut

`pip install -r requirements.txt` fails w/ pip@9.0.1, with this patch applied it works again.

2018-01-28 12:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=1983) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=1983) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=1983) it.</sub>

2018-01-29 10:03 UTC, jiivan requested changes
Thank you for your contribution! Still it needs polishing to meet our qa level.

2018-01-29 10:03 UTC, jiivan commented on requirements.txt
> +# --extra-index-url https://builds.golem.network
This change alone is unacceptable as there are packages missing for python3.5 which are custom build in this place.

2018-01-29 10:03 UTC, jiivan commented on requirements.txt
> +git+https://github.com/mfranciszkiewicz/pyelliptic.git@openssl_1_1#egg=pyelliptic
Could be accepted only temporariliy. Finally this release should be placed on builds.golem.network.

2018-01-29 10:03 UTC, jiivan commented on requirements.txt
> +git+https://github.com/golemfactory/golem-messages@v1.6.1#egg=golem-messages
It's a step back. All golem-messages releases are on builds.golem.network.

2018-11-28 13:57 UTC, Krigpl commented
Not relevant anymore

2018-11-28 13:57 UTC, closed without merging