rebased and fixed: Requestor-oriented stats #1492 #1702
golemfactory/clay pull request #2006
Opened 2018-02-01 02:46 UTC by tworec

rebased and fixes #1702 
resolves #1492

2018-02-02 13:15 UTC, tworec commented
closed by mistake

2018-02-05 09:27 UTC, tworec commented
hi @maaktweluit, this is rebase + some style fixes for #1702 which you have previously reviewed

2018-02-05 16:45 UTC, maaktweluit requested changes
LGTM!

Some small comments, will approve when replied to or fixed :)

2018-02-05 16:45 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +                    download_in_progress = True
should it break the second loop when it found what it was looking for?
Or do you only want the last message result?

2018-02-05 16:45 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +            finish_time = time.time()
@jiivan had some down-sides on using time, please double check if this is correct.

2018-02-05 16:45 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +            for msg in st.messages:
break loop when found?

2018-02-05 16:45 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +            logger.debug("Unknown operation %r", op.name)
would log this as an info warning, debug logs are not visible by default.
you can ignore this comment if an unknown OP has no affect for the end user

2018-02-05 16:45 UTC, maaktweluit commented on tests/apps/blender/task/test_blenderverifier.py
> +import mock
Please use `unittest.mock` from the stdlib, `mock` is deprecated since we upgraded to python3

2018-02-05 16:45 UTC, maaktweluit commented on tests/golem/monitor/test_monitor.py
> +import mock
`unittest.mock`

2018-02-06 12:48 UTC, tworec commented on golem/task/taskrequestorstats.py
> +                    download_in_progress = True
no, we want to see the last status, and if it is `RESULT_DOWNLOADING` then increase counter

2018-02-06 12:49 UTC, tworec commented on golem/task/taskrequestorstats.py
> +            finish_time = time.time()
@jiivan can you please comment on this?

2018-02-06 12:50 UTC, tworec commented on golem/task/taskrequestorstats.py
> +            for msg in st.messages:
same as above

2018-02-06 12:52 UTC, tworec commented on golem/task/taskrequestorstats.py
> +            logger.debug("Unknown operation %r", op.name)
should be rather hidden form user

2018-02-06 12:54 UTC, tworec commented on tests/apps/blender/task/test_blenderverifier.py
> +import mock
I'm touching this file only to please linters - this is pure/dumb/automatic import optimization.

2018-02-06 12:56 UTC, tworec commented on tests/golem/monitor/test_monitor.py
> +import mock
ok, I'll fix it here

2018-02-06 12:57 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +                    download_in_progress = True
thank you for the explanation

in that case why do we loop?
`msg = st.messages[-1]` should also get the last message

2018-02-06 12:57 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +            for msg in st.messages:
same as above

2018-02-06 12:59 UTC, maaktweluit commented on tests/apps/blender/task/test_blenderverifier.py
> +import mock
the linter only complains on changed lines: https://github.com/golemfactory/golem/blob/develop/lintdiff.sh#L115

though i like every single linter please :)

2018-02-06 13:01 UTC, tworec commented on golem/task/taskrequestorstats.py
> +                    download_in_progress = True
good point! :) I was not precise.
Task is considered not_downloaded, when there was `RES_DOWNL` msg, not followed by `FINISHED` nor `NOT_ACCEPTED`. Other msg are ignored

2018-02-06 13:04 UTC, tworec commented on tests/apps/blender/task/test_blenderverifier.py
> +import mock
;) It was complaining here. I don't know precisely why. Maybe because of my manual rebase steps (those RDP commits were very old and had conflicts)

2018-02-06 13:21 UTC, maaktweluit commented on golem/task/taskrequestorstats.py
> +                    download_in_progress = True
This makes the singe item fetch a lot less feasible.
Still think the loop is not optimal, but its nice and readable.

Since we had some questions about it maybe a comment would help our future self

2018-02-06 17:09 UTC, tworec commented on golem/task/taskrequestorstats.py
> +            finish_time = time.time()
@maaktweluit please approve (via rocket chat)

2018-02-06 17:14 UTC, tworec commented on golem/task/taskrequestorstats.py
> +                    download_in_progress = True
ok. no problem. i'll put a few words

2018-02-06 17:15 UTC, maaktweluit approved these changes

2018-02-07 19:45 UTC, merged