Task name check from json file on CLI
golemfactory/clay pull request #2030
Opened 2018-02-03 00:40 UTC by mdtanrikulu

2018-02-07 17:22 UTC, jiivan requested changes
Would be great to see this in develop! I'd suggest some small refactorings.

There are also some easy lints in shippable.

2018-02-07 17:22 UTC, jiivan commented on golem/interface/client/tasks.py
> +            raise SyntaxError(
I'd suggest using different exception. SyntaxError is reserved to parser errors and may be misleading in the context of user input.

https://docs.python.org/3/library/exceptions.html#SyntaxError

2018-02-07 17:22 UTC, jiivan commented on golem/interface/client/tasks.py
> +                 than 4 or more than 24 characters.")
String could be concatenated:
```python
"Length of task name cannot be less"
" than 4 or more than 24 characters."
```
To avoid ugly msg:
```
(36golem81) dybi@rybi-labelle:~/repo/golem81$ ./golemcli.py tasks create ../task_invalidname.json 
[17:56:55.645480] ERROR: Exception: Length of task name cannot be less                 than 4 or more than 24 characters.
```

2018-02-07 17:22 UTC, jiivan commented on golem/interface/client/tasks.py
> +                 spaces between characters, underline, dash or dot.")
ditto

2018-02-07 17:22 UTC, jiivan commented on golem/interface/client/tasks.py
> +        if not pattern.match(task_name):
How about:
```python
dictionary['task_name'] = dictionary['task_name'].strip()  # Remove surrounding whitespace
re.match(r"(\w|[\-\. ]){4,24}$", dictionary['task_name'], re.ASCII)
```
This regex will handle both length and allowed characters in name.

2018-02-11 21:39 UTC, mdtanrikulu commented on golem/interface/client/tasks.py
> +            raise SyntaxError(
Thanks for review! I updated it as ValueError.

2018-02-11 21:39 UTC, mdtanrikulu commented on golem/interface/client/tasks.py
> +                 than 4 or more than 24 characters.")
👍 done.

2018-02-11 21:39 UTC, mdtanrikulu commented on golem/interface/client/tasks.py
> +                 spaces between characters, underline, dash or dot.")
👍

2018-02-11 21:46 UTC, mdtanrikulu commented on golem/interface/client/tasks.py
> +        if not pattern.match(task_name):
Thanks! I applied it, looks more compact, but still I wanted to keep length condition separately to address the error precisely, if it's just a length or character error.

2018-02-12 09:03 UTC, jiivan approved these changes
Thanks for your changes! There are some small shippable warnings, otherwise LGTM!

2018-02-13 15:13 UTC, mfranciszkiewicz commented on golem/interface/client/tasks.py
> +        if (len(task_name) < 4 or len(task_name) > 24):
Doesn't the regex below already check the length?

2018-02-13 15:13 UTC, mfranciszkiewicz commented on golem/interface/client/tasks.py
> +        if not re.match(r"(\w|[\-\. ]){4,24}$", task_name, re.ASCII):
Do we really need to limit the character subset to ASCII?

2018-02-13 17:05 UTC, mfranciszkiewicz commented on golem/interface/client/tasks.py
> +        if (len(task_name) < 4 or len(task_name) > 24):
Resolved.

2018-02-13 17:07 UTC, mfranciszkiewicz approved these changes

2018-02-13 17:15 UTC, merged