increase default key difficulty + key generation in separate thread
golemfactory/clay pull request #2155
Opened 2018-02-19 21:27 UTC by tworec

this is WIP

2018-02-19 21:36 UTC, tworec commented
Below are the benchmarks results executed on
```
  Processor Name:		Intel Core i7
  Processor Speed:		3,1 GHz
  Number of Processors: 	1
  Total Number of Cores:	4
  L2 Cache (per Core):		256 KB
  L3 Cache:			8 MB
  Memory:			16 GB
```

```
$ pytest keygen_benchmark.py --benchmark-max-time=10
============================================================================================================================ test session starts =============================================================================================================================
platform darwin -- Python 3.6.4, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
benchmark: 3.1.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=10 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/tworec/git/golem, inifile: setup.cfg
plugins: xdist-1.22.0, forked-0.2, cov-2.5.1, benchmark-3.1.1
collected 5 items                                                                                                                                                                                                                                                            

keygen_benchmark.py .....                                                                                                                                                                                                                                              [100%]


------------------------------------------------------------------------------------------------ benchmark: 5 tests ------------------------------------------------------------------------------------------------
Name (time in ms)                  Min                     Max                   Mean                 StdDev                 Median                    IQR            Outliers     OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_key_gen_speed[10]         35.2159 (1.0)        3,176.7138 (1.0)         854.1354 (1.0)         842.4962 (1.0)         705.5675 (1.0)         508.2130 (1.0)           1;1  1.1708 (1.0)          11           1
test_key_gen_speed[13]        700.2690 (19.89)    108,522.5988 (34.16)    33,597.9387 (39.34)    44,837.0831 (53.22)     8,932.7569 (12.66)    52,640.3683 (103.58)        1;0  0.0298 (0.03)          5           1
test_key_gen_speed[12]      1,595.4099 (45.30)     73,004.3185 (22.98)    20,340.3297 (23.81)    29,949.6925 (35.55)     8,359.4709 (11.85)    27,272.7219 (53.66)         1;1  0.0492 (0.04)          5           1
test_key_gen_speed[11]      2,327.4743 (66.09)     16,982.1488 (5.35)      8,324.2786 (9.75)      6,058.2309 (7.19)      8,450.9157 (11.98)     9,662.4112 (19.01)         1;0  0.1201 (0.10)          5           1
test_key_gen_speed[14]     14,110.7288 (400.69)   115,298.3730 (36.29)    57,102.7105 (66.85)    39,910.2886 (47.37)    42,575.4573 (60.34)    57,555.7886 (113.25)        2;0  0.0175 (0.01)          5           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean

```

2018-02-20 10:45 UTC, tworec commented
Two another tests 
@ iMac Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

```
----------------------------------------------------------------------------------------------- benchmark: 5 tests ----------------------------------------------------------------------------------------------
Name (time in ms)               Min                     Max                   Mean                 StdDev                 Median                    IQR            Outliers     OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_key_gen_speed[10]      40.7094 (1.0)       19,371.4156 (1.02)      2,689.5515 (1.0)       3,186.1004 (1.0)       1,724.6201 (1.0)       2,871.7728 (1.0)           6;1  0.3718 (1.0)          50           1
test_key_gen_speed[12]      52.1858 (1.28)      48,996.1285 (2.59)     11,342.8272 (4.22)     11,765.5044 (3.69)      6,976.4463 (4.05)     15,081.3476 (5.25)          9;1  0.0882 (0.24)         50           1
test_key_gen_speed[11]      96.0609 (2.36)      18,949.8724 (1.0)       6,061.5277 (2.25)      5,371.2832 (1.69)      4,868.5300 (2.82)      7,700.4046 (2.68)         13;0  0.1650 (0.44)         50           1
test_key_gen_speed[13]     615.1619 (15.11)    127,062.2297 (6.71)     24,462.0909 (9.10)     26,980.7204 (8.47)     13,478.9322 (7.82)     24,098.6109 (8.39)         10;5  0.0409 (0.11)         50           1
test_key_gen_speed[14]     988.7483 (24.29)    223,784.4456 (11.81)    37,550.8076 (13.96)    39,103.9630 (12.27)    29,679.9115 (17.21)    32,223.6887 (11.22)         6;3  0.0266 (0.07)         50           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
============================================================================ 5 passed in 4230.19 seconds ============================================================================
```

@ ubuntu 17.10 Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz

```
----------------------------------------------------------------------------------------------- benchmark: 5 tests ----------------------------------------------------------------------------------------------
Name (time in ms)               Min                     Max                   Mean                 StdDev                 Median                    IQR            Outliers     OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_key_gen_speed[10]      18.2399 (1.0)       10,340.6203 (1.0)       2,450.6223 (1.0)       2,388.1239 (1.0)       1,631.9897 (1.0)       2,863.5448 (1.0)          10;1  0.4081 (1.0)          50           1
test_key_gen_speed[11]      18.3371 (1.01)      27,177.3431 (2.63)      4,854.3056 (1.98)      6,317.4357 (2.65)      2,823.1518 (1.73)      4,856.7541 (1.70)          6;6  0.2060 (0.50)         50           1
test_key_gen_speed[14]     137.2563 (7.53)     159,282.3099 (15.40)    33,065.0918 (13.49)    33,145.2159 (13.88)    21,819.2223 (13.37)    34,500.2574 (12.05)         8;2  0.0302 (0.07)         50           1
test_key_gen_speed[13]     195.1459 (10.70)    123,794.4634 (11.97)    24,851.0860 (10.14)    28,830.9805 (12.07)    14,434.9302 (8.84)     28,757.5679 (10.04)         9;3  0.0402 (0.10)         50           1
test_key_gen_speed[12]     595.4765 (32.65)     54,871.8523 (5.31)     11,176.2379 (4.56)     10,852.6973 (4.54)      6,714.9746 (4.11)     13,120.7848 (4.58)          9;1  0.0895 (0.22)         50           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
============================================================================ 5 passed in 4013.63 seconds ============================================================================
```

2018-02-21 09:41 UTC, Krigpl requested changes

2018-02-21 09:41 UTC, Krigpl commented on golem/client.py
> +                address=geth_address, )
nope

2018-02-21 09:41 UTC, Krigpl commented on golem/client.py
> +        log.info('Client "%s", datadir: %s', self.config_desc.node_name,
This PR is 400+ lines, I went through first 100 and most of them are style changes like this one.
This introduces a lot of noise to the PR and makes it really unclear which changes are important which results in more difficult review process.
Also these changes are counter productive - personally I prefer the style on the left, it's more flexible when new stuff needs to be added and the indent size is consistent. But if others have different preferences then we should come up with a single convention for the whole team to avoid going back and forth all the time.
Please revert all unnecessary style changes from this PR to make it more legible.

2018-02-21 11:20 UTC, tworec commented on golem/client.py
> +        log.info('Client "%s", datadir: %s', self.config_desc.node_name,
ok, thx for feedback
I've used automatic PyCharm format feature. I'll revert style changes

2018-02-21 14:24 UTC, Krigpl requested changes
Much more easier to review :)

2018-02-21 14:24 UTC, Krigpl commented on golem/client.py
> +        self.keys_auth: KeysAuth = keys_auth
Since `keys_auth` is already typed I think `self.keys_auth` doesn't need to be typed separately unless the two types are different.

2018-02-21 14:24 UTC, Krigpl commented on golemapp.py
> +        Node(
I find it odd that constructor of an object is blocking the calling thread, `run` is more explicit in this regard (but this is just my opinion).

2018-02-21 14:24 UTC, Krigpl commented on golem/node.py
> +        self._setup_docker()
afaik this step could be done asynchronously as well

2018-02-21 14:24 UTC, Krigpl commented on golem/node.py
> +    def _key_auth_ready(self, keys_auth: KeysAuth, *_):
`_key_auth_ready` is not thread safe with `_rpc_router_ready`. Those two methods can be called in parallel and it is possible that both will end up calling `self._setup_client()`.
See my other comment on an alternative approach.

2018-02-21 14:24 UTC, Krigpl commented on golem/node.py
> +            self._setup_keys_auth()
Alternatively and in a thread safe way we could make these `_setup_*` methods return `deferred` objects, collect them (check out `DeferredList`) and only then call `_setup_client`.

2018-02-21 19:56 UTC, tworec commented on golem/client.py
> +        self.keys_auth: KeysAuth = keys_auth
indeed. thx

2018-02-21 19:58 UTC, tworec commented on golemapp.py
> +        Node(
I was looking somebody tell that! :)

2018-02-21 20:00 UTC, tworec commented on golem/node.py
> +    def _key_auth_ready(self, keys_auth: KeysAuth, *_):
right! thx

2018-02-21 20:03 UTC, tworec commented on golem/node.py
> +            self._setup_keys_auth()
@mfranciszkiewicz reccomended the same approach. I'll give it a shot

2018-02-22 16:01 UTC, tworec commented
Yet another benchmark on @ iMac Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
```
------------------------------------------------------------------------------------------------- benchmark: 7 tests -------------------------------------------------------------------------------------------------
Name (time in ms)                 Min                     Max                    Mean                  StdDev                 Median                     IQR            Outliers     OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_key_gen_speed[12]         2.7274 (1.0)       66,101.7542 (7.44)      14,878.3008 (5.68)      15,444.0144 (7.05)     10,769.2757 (4.90)      15,709.3433 (8.83)          3;1  0.0672 (0.18)         20           1
test_key_gen_speed[11]        10.7606 (3.95)      12,381.9417 (1.39)       4,459.9398 (1.70)       3,674.7270 (1.68)      3,633.8061 (1.65)       6,450.3969 (3.63)          7;0  0.2242 (0.59)         20           1
test_key_gen_speed[10]        42.8730 (15.72)      8,887.8740 (1.0)        2,620.6149 (1.0)        2,191.9316 (1.0)       2,196.8609 (1.0)        1,778.4849 (1.0)           5;2  0.3816 (1.0)          20           1
test_key_gen_speed[14]     1,719.7146 (630.54)   146,329.9454 (16.46)     54,657.0149 (20.86)     46,100.0178 (21.03)    45,632.2525 (20.77)     70,029.3814 (39.38)         6;0  0.0183 (0.05)         20           1
test_key_gen_speed[15]     1,863.9600 (683.43)   710,181.0133 (79.90)    108,385.2654 (41.36)    157,419.1749 (71.82)    66,728.5877 (30.37)    121,269.4743 (68.19)         1;1  0.0092 (0.02)         20           1
test_key_gen_speed[13]     1,910.1986 (700.38)    91,270.1693 (10.27)     31,860.8138 (12.16)     27,950.9698 (12.75)    25,768.8348 (11.73)     39,835.9067 (22.40)         6;0  0.0314 (0.08)         20           1
test_key_gen_speed[16]     4,396.1369 (>1000.0)  484,158.3144 (54.47)    118,075.3310 (45.06)    119,805.3338 (54.66)    73,730.6087 (33.56)    153,670.4776 (86.41)         3;1  0.0085 (0.02)         20           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

I'll choose difficulty 14, which will result in mean/median key generation time be slightly below 1 min (with max of 3 minutes) on my 4Ghz i7. While my CPU is high end, according to http://store.steampowered.com/hwsurvey/processormfg/ it no more than 2x as fast as average user machine. Thus `difficulty 14` should result in average key generation time below 2 mins, and below 6 mins in 99% of cases.

2018-02-22 16:39 UTC, mfranciszkiewicz commented on golemapp.py
> +        Node(
+1

2018-02-23 09:28 UTC, Krigpl commented on golem/node.py
> +        deferred = rpc._start_node(rpc.options, self._reactor)
Why private `_start_node` instead of previously used `start`?

2018-02-23 09:28 UTC, Krigpl commented on golem/node.py
> +        if self._use_docker_manager:
I usually like to reduce indentation if do
```
if not self._use_docker_manager:
  return None
<rest of the code>
```

2018-02-23 09:28 UTC, Krigpl commented on golem/node.py
> +                self._setup_client, _error('rpc, keys or docker'))
I don't know if it's the case right now (doesn't look like it) but we should stop reactor and exit application if any of the setup steps is unsuccessful.

2018-02-23 09:39 UTC, mfranciszkiewicz commented on golem/node.py
> +        deferred = rpc._start_node(rpc.options, self._reactor)
IMO `start` should be refactored to do exactly what `_start_node` does. Probably in another PR.

2018-02-23 09:46 UTC, mfranciszkiewicz commented on golem/node.py
> +                self._setup_client, _error('rpc, keys or docker'))
The (lambda) function returned by `_error` could do a `reactor.callFromThread(reactor.stop)` / `reactor.stop()` after logging the error.

2018-02-23 09:49 UTC, mfranciszkiewicz reviewed
The DummyTask test would benefit from a lower key difficulty, currently it times out on CircleCI.

2018-02-23 12:20 UTC, tworec commented on golem/node.py
> +        deferred = rpc._start_node(rpc.options, self._reactor)
yup! I do not want this refactoring in this PR

2018-02-23 12:21 UTC, tworec commented on golem/node.py
> +        if self._use_docker_manager:
cool! new python insight for me, thx!

2018-02-23 12:22 UTC, tworec commented on golem/node.py
> +                self._setup_client, _error('rpc, keys or docker'))
thx! I overlooked this

2018-02-23 13:50 UTC, mfranciszkiewicz approved these changes

2018-02-23 13:53 UTC, Krigpl approved these changes
![coolkid](https://user-images.githubusercontent.com/3904252/36597404-5045ecea-18a9-11e8-9478-79c63c996844.gif)

2018-02-23 14:21 UTC, merged