Limit the rate of new connections
golemfactory/clay pull request #2163
Opened 2018-02-20 18:45 UTC by mfranciszkiewicz

2018-02-26 12:42 UTC, maaktweluit approved these changes
LGTM!

Two small q's, no blockers so approved!

2018-02-26 12:42 UTC, maaktweluit commented on golem/network/transport/limiter.py
> +                 rate: float = 5.,
Would it be possible to use int's here? i remember an issue before this should be preferred.

2018-02-26 12:42 UTC, maaktweluit commented on tests/golem/network/transport/test_tcpnetwork.py
> +# pylint: disable=no-member
Can this be enabled again after the errors have passed? this will protect the rest of the file of errors

2018-02-26 12:56 UTC, mfranciszkiewicz commented on golem/network/transport/limiter.py
> +                 rate: float = 5.,
Done

2018-02-26 15:17 UTC, maaktweluit commented
Thank you for the fix!

Appveyor has a time / assertion error, is this related or should we just rebuild?

2018-02-27 15:17 UTC, etam requested changes

2018-02-27 15:17 UTC, etam commented on golem/network/transport/limiter.py
> +    def call(self,
Names with double underscore at the beginning and end are reserved for Python.

This would be cleaner if `call` function was called once from outside and some other private method was passed to reactor. The problem of `*args, **kwargs` can be then solved by passing it as a tuple `(args, kwargs)` to this private method and unpacking it when required `*args[0], **args[1]`.

2018-02-27 15:17 UTC, etam commented on tests/golem/network/transport/test_limiter.py
> +        for _ in range(5):
minor: use variables from `CallRateLimiter` instead of hard-coding magic numbers.

2018-02-27 15:17 UTC, etam commented on tests/golem/network/transport/test_limiter.py
> +        n = int(limiter._limiter._capacity * 1.5)
minor: like above

2018-02-27 15:30 UTC, mfranciszkiewicz commented on tests/golem/network/transport/test_limiter.py
> +        n = int(limiter._limiter._capacity * 1.5)
It's supposed to be more than current capacity.

2018-02-27 15:40 UTC, mfranciszkiewicz commented on golem/network/transport/limiter.py
> +    def call(self,
I agree with double underscores, but strongly disagree on calling nested / private functions and unmangling arg tuples being a cleaner solution.

2018-02-28 08:30 UTC, etam approved these changes

2018-03-05 12:09 UTC, merged