Fix race in updating preview
golemfactory/clay pull request #2218
Opened 2018-02-23 19:17 UTC by Elfoniok

Signed-off-by: Lukasz Foniok <lukaszfoniok@gmail.com>

2018-02-23 19:48 UTC, mfranciszkiewicz requested changes

2018-02-23 19:48 UTC, mfranciszkiewicz commented on apps/blender/task/verifier.py
> +from twisted.internet import reactor
Please avoid global reactor imports

2018-02-23 21:09 UTC, mfranciszkiewicz approved these changes

2018-02-23 21:39 UTC, merged

2018-02-26 08:31 UTC, etam commented
Does that resolve #2059?