Don't silently regenerate wallet
golemfactory/clay pull request #2220
Opened 2018-02-26 10:09 UTC by Krigpl

Those cases shouldn't happen but if they do the solution isn't to quietly generate new identity imo.

2018-02-26 10:23 UTC, etam commented
@badb decided this should be this way for now, but is should be changed before mainnet release. See #2213 

I don't know if just throwing an exception is a good enough solution.

2018-02-26 10:40 UTC, Krigpl commented
My reasoning is that this scenario either:
- will not happen in mainnet at all
- will happen in mainnet and handling it should be muuuuuch more carefully done, including informing the user about backup, why the address has changed, why they lost all theirs reputation etc

Second case is obviously much more complicated but we don't plan supporting that at the moment, so we're fine with 1. In which case exceptions are fine. For testnet we can just ask users to uninstall previous golem version before installing new one which we has done in the past iirc.

Anyway, I don't really need this change, I just thought it'd be clearer this way.

2018-03-01 11:52 UTC, tworec requested changes
@Krigpl your reasoning is ok. I have just one comment

2018-03-01 11:52 UTC, tworec commented on golem/core/keysauth.py
> +            raise Exception("Loaded key is not difficult enough")
I think we should point out some solution, for example to reinstall golem, or delete old key file... or even some url to some FAQ page with question: how to transfer GNT(W) from old golem account...

2018-03-01 11:54 UTC, etam commented on golem/core/keysauth.py
> +            raise Exception("Loaded key is not difficult enough")
#2213

2018-03-01 12:23 UTC, tworec commented on golem/core/keysauth.py
> +            raise Exception("Loaded key is not difficult enough")
yes, but until #2213 will happened we should, at least, inform user how to deal with this issue... for example "Loaded key is not difficult enough. To regenerate please reinstall golem or remove key file `path`.

2018-03-01 12:28 UTC, etam commented on golem/core/keysauth.py
> +            raise Exception("Loaded key is not difficult enough")
I think this PR should be closed without merging. This issue should be properly and completely handled in #2213 and any partial solutions are bad in their own ways and not worth spending time.

2018-03-01 12:36 UTC, tworec commented on golem/core/keysauth.py
> +            raise Exception("Loaded key is not difficult enough")
I agree the latter part of your statement, but this PR is good foundation to final #2213 solution :)

2018-03-08 06:25 UTC, tworec commented
included in #2281

2018-03-08 06:25 UTC, closed without merging