Handle Challenge or RandVal messages after disconnecting in Hello
golemfactory/clay pull request #2241
Opened 2018-02-27 10:17 UTC by etam

Fixes #2150

2018-02-27 10:20 UTC, etam commented
This is because `PeerSession._react_to_hello` sends `Hello` and `RandVal` or `ChallengeSolution` one after another. If a node decides to disconnect in `_react_to_hello` it'll still receive the second message.

2018-02-27 10:34 UTC, Krigpl commented on golem/network/transport/session.py
> +    key_id: Optional[str] = None
Pardon my ignorance but why is it better compared to `self.key_id =` in the constructor? Doesn't it make it possible to access it via `BasicSafeSession.key_id` which is useless (i.e. class vs object member)?

2018-02-27 10:39 UTC, etam commented on golem/network/transport/session.py
> +    key_id: Optional[str] = None
https://www.python.org/dev/peps/pep-0526/#class-and-instance-variable-annotations

2018-02-27 10:54 UTC, Krigpl approved these changes

2018-02-27 10:54 UTC, Krigpl commented on golem/network/transport/session.py
> +    key_id: Optional[str] = None
![wat](https://user-images.githubusercontent.com/3904252/36724884-d959705c-1bb4-11e8-8fd0-12f6aaaf3d96.jpg)

2018-02-27 13:30 UTC, mfranciszkiewicz requested changes
Resource handshakes time out and so does the DummyTask test

2018-02-27 15:55 UTC, etam commented
@mfranciszkiewicz fixed

2018-02-27 16:00 UTC, mfranciszkiewicz approved these changes

2018-02-28 08:47 UTC, jiivan approved these changes

2018-03-06 15:55 UTC, merged