Limit number of crop rendering containers
golemfactory/clay pull request #2265
Opened 2018-02-28 15:47 UTC by Elfoniok

2018-03-02 18:53 UTC, badb requested changes

2018-03-02 18:53 UTC, badb commented on apps/blender/task/verifier.py
> +        self.docker_manager = DockerManager.install()
I don't think that's the right approach. Can we at least use DockerTaskThread here?

2018-03-02 18:53 UTC, badb commented on apps/blender/task/blendercropper.py
> +        if results and time_spend and verification_context:
It's not clear what is happening here and in which situation these 3 arguments should be None. Can you refactor or at least add some comments?

2018-03-07 10:07 UTC, Elfoniok commented on apps/blender/task/verifier.py
> +        self.docker_manager = DockerManager.install()
Docker Task Thread is well for Task, its not well prepared to handle something else, but i try to make it nicer.

2018-03-07 14:13 UTC, Elfoniok commented
Closing in favor of https://github.com/golemfactory/golem/pull/2306

2018-03-07 14:13 UTC, closed without merging