support for ^C (SIGINT) @ key generation
golemfactory/clay pull request #2281
Opened 2018-03-02 15:06 UTC by tworec

closes #2230

2018-03-05 11:18 UTC, tworec commented
For reviw brevity pls look only @ first commit a41c04dfd.
Second one is just tests speed-up

2018-03-05 11:55 UTC, mfranciszkiewicz commented on golem/node.py
> +            if not self._reactor._stopped:  # pylint: disable=protected-access
`if self._reactor.running:` should be safer to use

2018-03-05 11:55 UTC, mfranciszkiewicz commented on golem/core/keysauth.py
> +            if reactor._startedBefore:  # pylint: disable=protected-access
Alternatively, you could do something like `while reactor.running` and conditionally raise the exception outside the loop.

2018-03-05 12:59 UTC, tworec commented on golem/node.py
> +            if not self._reactor._stopped:  # pylint: disable=protected-access
right

2018-03-05 13:01 UTC, tworec commented on golem/core/keysauth.py
> +            if reactor._startedBefore:  # pylint: disable=protected-access
ok, I was thinking about something similar, but thought that it will be too much hassle with tests, where `KeysAuth` is not invoked from within reactor. But I've found solution for this

2018-03-05 13:51 UTC, Krigpl commented on tests/golem/core/test_keysauth.py
> +        with patch.dict('ethereum.keys.PBKDF2_CONSTANTS', {'c': 1}):
Would it be possible to somehow override this constant in `testutils.TempDirFixture::setUp`? Then everything would so much easier.

2018-03-05 13:54 UTC, tworec commented on tests/golem/core/test_keysauth.py
> +        with patch.dict('ethereum.keys.PBKDF2_CONSTANTS', {'c': 1}):
good point, I'll try

2018-03-05 14:18 UTC, tworec commented on tests/golem/core/test_keysauth.py
> +        with patch.dict('ethereum.keys.PBKDF2_CONSTANTS', {'c': 1}):
@Krigpl done

2018-03-05 14:32 UTC, Krigpl requested changes

2018-03-05 14:32 UTC, Krigpl commented on golem/testutils.py
> +        # instead of patch.dict('ethereum.keys.PBKDF2_CONSTANTS', {'c': 1})
A small comment explaining why, like `KeysAuth uses it but by default it takes too long which is unnecessary for tests blah balh`

2018-03-05 14:32 UTC, Krigpl commented on golem/core/keysauth.py
> +                logger.warning("reactor stopped, aborting key generation ..")
No need for log message if you're throwing an exception - it's gonna be caught somewhere and logged anyway

2018-03-05 14:32 UTC, Krigpl commented on tests/golem/core/test_keysauth.py
>  import json
Can you check whethe rlines 24-36 are still needed after the patching in `TempDirFixture` ?

2018-03-05 14:32 UTC, Krigpl commented on tests/golem/task/dummy/runner.py
> -    with mock.patch.dict('ethereum.keys.PBKDF2_CONSTANTS', {'c': 1}):
I'd leave this one as it may or may not be called from unit test env.

2018-03-06 08:24 UTC, tworec commented on golem/testutils.py
> +        # instead of patch.dict('ethereum.keys.PBKDF2_CONSTANTS', {'c': 1})
ok

2018-03-06 08:25 UTC, tworec commented on golem/core/keysauth.py
> +                logger.warning("reactor stopped, aborting key generation ..")
nope. it is not caught because reactor is stopped...

2018-03-06 08:29 UTC, tworec commented on tests/golem/task/dummy/runner.py
> -    with mock.patch.dict('ethereum.keys.PBKDF2_CONSTANTS', {'c': 1}):
this is inside `tests` dir. Is there any other purpose of this code than testing?

2018-03-06 09:22 UTC, Krigpl commented on golem/core/keysauth.py
> +                logger.warning("reactor stopped, aborting key generation ..")
Then it will crash the process and be logged on the stderr anyway, right?

2018-03-06 09:22 UTC, Krigpl commented on tests/golem/task/dummy/runner.py
> -    with mock.patch.dict('ethereum.keys.PBKDF2_CONSTANTS', {'c': 1}):
The way it works is that `test_dummy` is in the unittest env, patches this method then calls `run_simulation` which spawns new processes for the clients, meaning that this particular call is executed not in the unittest env anymore, thus this method is not patched.
I think that's the case, not 100% sure so you can always just run it and see.

2018-03-06 09:30 UTC, tworec commented on golem/core/keysauth.py
> +                logger.warning("reactor stopped, aborting key generation ..")
nope

2018-03-06 09:37 UTC, Krigpl commented on golem/core/keysauth.py
> +                logger.warning("reactor stopped, aborting key generation ..")
So it's silently swallowed? That doesn't sound right

2018-03-06 15:38 UTC, Krigpl requested changes
lgtm in general, but give me back my exception :(

2018-03-06 15:38 UTC, Krigpl commented on golem/core/keysauth.py
> +    random = get_random(min_value=1, max_value=sys.maxsize - 1)
Awesome, I was always disgusted by the previous implementation but never got to change it :P

2018-03-06 15:38 UTC, Krigpl commented on golem/core/keysauth.py
> -class WrongPasswordException(Exception):
Can I have it back? I actually use it in my PR.

2018-03-06 15:38 UTC, Krigpl commented on golem/core/keysauth.py
> -    def encrypt(self, data: bytes, public_key: Optional[bytes] = None) -> bytes:
Hard to tell for me whether they are actually no used (yay Python), so I assume you tested it e2e?

2018-03-06 15:38 UTC, Krigpl commented on requirements-test.txt
> -freezegun
huh ?

2018-03-06 17:05 UTC, tworec commented on requirements-test.txt
> -freezegun
sorry, I wasn't careful

2018-03-06 17:06 UTC, tworec commented on golem/core/keysauth.py
> +    random = get_random(min_value=1, max_value=sys.maxsize - 1)
it was clumsy and... broken. It would never return anything below 0.1

2018-03-06 17:10 UTC, tworec commented on golem/core/keysauth.py
> +                logger.warning("reactor stopped, aborting key generation ..")
please notice that this exception is thrown **_after_** reactor is stopped, so no callback nor errback would be executed. I'm throwing it to break processing. It could be `return`, but i think `raise` is more natural in this situation. Logger is additional, to be informative to our users.

2018-03-06 17:11 UTC, tworec commented on golem/core/keysauth.py
> -class WrongPasswordException(Exception):
ok

2018-03-07 08:04 UTC, tworec commented on golem/core/keysauth.py
> -    def encrypt(self, data: bytes, public_key: Optional[bytes] = None) -> bytes:
yup. i've succesfully act as a requestor and provider with this code

2018-03-07 08:04 UTC, tworec commented on tests/golem/task/dummy/runner.py
> -    with mock.patch.dict('ethereum.keys.PBKDF2_CONSTANTS', {'c': 1}):
yes, thats was the case. Thanks pointing out

2018-03-07 08:16 UTC, tworec commented on tests/golem/network/transport/test_tcpnetwork.py
> +        session.decrypt.side_effect = lambda x: x
I've tested it e2e ie. started node and requested task which successfully finished, and from other side my node has successfully served as a provider. Can I remove this test?

2018-03-07 08:16 UTC, tworec commented on tests/golem/network/transport/test_tcpnetwork.py
> +        session.decrypt.side_effect = lambda x: x
same here...

2018-03-07 09:08 UTC, jiivan approved these changes
LGTM

2018-03-07 09:08 UTC, jiivan commented on tests/golem/network/transport/test_tcpnetwork.py
> +        session.decrypt.side_effect = lambda x: x
Yes, this functionality is not used anymore (moved to golem-messages)

2018-03-07 09:36 UTC, Krigpl commented on golem/core/keysauth.py
> +class NotDifficultEnough(Exception):
I introduced `WrongPasswordException` because I'm actually catching it, I dunno if there's need for specialized exception types for those two other errors.

2018-03-07 09:36 UTC, Krigpl commented on golem/core/keysauth.py
> +        reactor_started = reactor.running
I don't fully understand meaning of this variable. When can it be `false`? When we received SIGINT just after reactor has started and we haven't reached this point yet, right? In which case we won't abort the while loop. What am I missing?

2018-03-07 10:13 UTC, tworec commented on tests/golem/network/transport/test_tcpnetwork.py
> +        session.decrypt.side_effect = lambda x: x
thx @jiivan !

2018-03-07 10:15 UTC, tworec commented on golem/core/keysauth.py
> +class NotDifficultEnough(Exception):
ok, I taught that it is a good practice to introduce named exception in python... will remove two other

2018-03-07 10:21 UTC, tworec commented on golem/core/keysauth.py
> +        reactor_started = reactor.running
maybe it is wrong by design, but it is here just for tests purposes; `keysauth` is invoked w/o `reactor` in most test cases, and  `reactor.running = False` all the time then. But in production `keysauth` is invoked as `deferred` from within `reactor`,  so it must be up and running already.

2018-03-07 10:40 UTC, Krigpl commented on golem/core/keysauth.py
> +        reactor_started = reactor.running
That looks sketchy and should be resolved on the unit tests level.
How about introducing a method like `should_stop_generating_key` which returns whether reactor is running and can be mocked in tests to simply return true?

2018-03-07 18:52 UTC, tworec commented on golem/core/keysauth.py
> +        reactor_started = reactor.running
to much hassle... ;) after re-consideration I think it is good in current shape, as it enables `keysauth` usage from outside of reactor.

2018-03-08 08:35 UTC, merged

2018-03-08 09:29 UTC, Krigpl commented on golem/core/keysauth.py
> +        reactor_started = reactor.running
I'm not gonna insist on changing that but want to stress my points again:
1. This is prone to race condition I mentioned, where we receive SIGINT and stop reactor before setting this value, this the loop won't break.
2. I find it bad practice to put some code in production code just to make the tests pass, as you mentioned it indicated bad design. But if we decide to go this route then an explanatory comment would be beneficial as there might be other people like me wondering what this variable is for and trying to remove it, because it looks unnecessary - just to find out later that it breaks all the tests for some reason.

2018-03-08 12:58 UTC, tworec commented on golem/core/keysauth.py
> +        reactor_started = reactor.running
ad1. right, but it is race condition between reactor and user mainly, so in worst case user will wait... not a big deal I think, while it is near impossible to hit CTRL+C between `reactor.run` and invocation of this assignment. 

ad2. fell free to add such a comment. I see that you're changing this file in #2289

2018-03-08 13:01 UTC, tworec commented on golem/core/keysauth.py
> +        reactor_started = reactor.running
and @Krigpl thanks for really insightful comments