Check gnt
golemfactory/clay pull request #2293
Opened 2018-03-05 15:45 UTC by badb

Part of https://github.com/golemfactory/golem/issues/2292

2018-03-05 17:55 UTC, mfranciszkiewicz commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        if price > gnt_available:
`eth_available` for gas?

2018-03-05 17:55 UTC, mfranciszkiewicz commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        price = subtask_price * task.total_tasks
I believe that price calculation belongs to the `Task` class, since all the implementation details are there (headers, prices, timeouts).

2018-03-05 17:55 UTC, mfranciszkiewicz commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        price = subtask_price * task.total_tasks
IMO this function could be a simple balance check. What do you think, @badb?

2018-03-06 10:30 UTC, Krigpl commented on golem/testutils.py
> +def get_key_auth_for_tests(datadir, difficulty=0):
This won't be needed after #2281

2018-03-06 10:30 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        price = subtask_price * task.total_tasks
I second that

2018-03-09 13:13 UTC, Krigpl requested changes

2018-03-09 13:13 UTC, Krigpl commented on apps/core/task/coretask.py
> +        subtask_price = self.header.max_price * self.header.subtask_timeout / 6
What's 6 ?

2018-03-09 13:13 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +    def check_funds_for_task(self, task):
This really introduces unnecessary dependency (transaction system depends on tasks, in compilable languages that would be even more explicit and unnecessary).
Imo it's better to just use `get_balance` to get available GNT and perform this `if` check in `golem/client.py`.

2018-03-12 09:53 UTC, Krigpl requested changes

2018-03-12 09:53 UTC, Krigpl commented on golem/transactions/transactionsystem.py
> +    def check_funds_for_task(self, task):
rm

2018-03-12 09:53 UTC, Krigpl commented on golem/transactions/ethereum/exceptions.py
> +class NotEnoughFunds(Exception):
It's not thrown anywhere in the `transactions.ethereum` module, I doubt it belongs here in that case

2018-03-12 09:53 UTC, Krigpl commented on tests/golem/test_client.py
> +                keys_auth=keys_auth,
why is this needed now?

2018-03-12 09:53 UTC, Krigpl commented on tests/golem/test_client.py
> +        c.keys_auth = KeysAuth(c.datadir, 'priv_key', '')
If using real keysauth is to stay in `setUp` then it's not required anymore I believe

2018-03-12 09:53 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +    def eth_for_batch_payment(self, num_batches):
`num_batches` is confusing, it's cost for a single batch which contains multiple payments

2018-03-12 09:53 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +               self.payment_processor.ETH_BATCH_PAYMENT_BASE * num_batches
PER_PAYMENT

2018-03-15 17:28 UTC, badb commented
Part2: https://github.com/golemfactory/golem/pull/2337/

2018-03-15 17:29 UTC, badb commented on golem/transactions/ethereum/exceptions.py
> +class NotEnoughFunds(Exception):
Check how it's used in: #2337
Do you have better ideas where to put this fundslocker and this exception?

2018-03-20 09:35 UTC, Krigpl approved these changes

2018-03-20 11:45 UTC, mfranciszkiewicz approved these changes

2018-03-20 12:04 UTC, jiivan approved these changes

2018-03-20 20:57 UTC, merged