Replace GNTW with GNTB
golemfactory/clay pull request #2302
Opened 2018-03-06 16:04 UTC by Krigpl

Second commit is just search and replace so it's fine to focus on the first one.

2018-03-07 08:18 UTC, etam commented on requirements.txt
> +-e git://github.com/golemfactory/golem-smart-contracts-interface.git@6377c5a0276f32ffe936b92dee9c428f55f931e5#egg=golem_sci
Was this change under review?

2018-03-07 09:49 UTC, Krigpl commented on requirements.txt
> +-e git://github.com/golemfactory/golem-smart-contracts-interface.git@6377c5a0276f32ffe936b92dee9c428f55f931e5#egg=golem_sci
This mainly includes method/contract name changes.
Real changes are in the contracts' code which translates to bytecode in the above commit.
So the answer is not really because there's not much to review, the actual stuff has been reviewed (yet in another repo (golem-contracts)).

2018-03-07 09:56 UTC, Krigpl commented on requirements.txt
> +-e git://github.com/golemfactory/golem-smart-contracts-interface.git@6377c5a0276f32ffe936b92dee9c428f55f931e5#egg=golem_sci
You're welcome to take a look though :)
https://github.com/golemfactory/golem-smart-contracts-interface/pull/13

2018-03-07 11:15 UTC, mfranciszkiewicz requested changes
```  File "/home/mfrancis/Projects/golem/golem/ethereum/paymentprocessor.py", line 336, in get_gnt_from_faucet
    gnt_balance, _ = self.gnt_balance(True)
  File "/home/mfrancis/Projects/golem/golem/ethereum/paymentprocessor.py", line 106, in gnt_balance
    gntb_balance = self._sci.get_gntb_balance(
builtins.AttributeError: 'SCIImplementation' object has no attribute 'get_gntb_balance'
```

2018-03-07 14:14 UTC, mfranciszkiewicz approved these changes

2018-03-07 18:16 UTC, badb approved these changes

2018-03-07 18:17 UTC, badb commented on tests/golem/ethereum/test_gntconverter.py
> +        # transfer_from_fate mined, conversion done
Typo? Or not...?

2018-03-07 19:16 UTC, merged

2018-03-08 09:30 UTC, Krigpl commented on tests/golem/ethereum/test_gntconverter.py
> +        # transfer_from_fate mined, conversion done
![yesquiteindeed](https://user-images.githubusercontent.com/3904252/37143532-b7e75228-22bb-11e8-8f53-31858204c696.jpg)