Golem terms of use
golemfactory/clay pull request #2373
Opened 2018-03-15 16:05 UTC by Wiezzel

User has to accept terms of use before running Golem. If they don't the client will not connect to the network and an error message will be displayed in the logs. Terms of use can be displayed and accepted via CLI. There are RPC methods to check if terms have been accepted and to accept them. These methods could be used by the GUI to provide a more user-firendly way of accepting the terms.

Information about acceptance is stored in the databse.

There is no need to restart Golem after accepting the terms.

Issue: #2345

2018-03-15 16:27 UTC, maaktweluit requested changes
LGTM!

Can you also include the TERMS file in the golemapp pyinstaller hook?

2018-03-15 16:55 UTC, Wiezzel commented
@maaktweluit Dunno how to do it. What is "the golemapp pyinstaller hook"?

2018-03-15 16:59 UTC, maaktweluit commented
https://github.com/golemfactory/golem/blob/develop/scripts/pyinstaller/hooks/hook-golem.py

You can copy the line from the release-version file, it is included in the same way.

2018-03-15 17:03 UTC, Wiezzel commented
@maaktweluit Done.

2018-03-15 17:09 UTC, maaktweluit approved these changes

2018-03-15 17:28 UTC, mfranciszkiewicz approved these changes

2018-03-20 10:18 UTC, Krigpl requested changes
Discussed offline and requesting changes here so it doesn't get merged accidentally.
ToS check should happen before creating `Client` object.

2018-03-21 15:17 UTC, Wiezzel commented
@mfranciszkiewicz @Krigpl Please review new changes.

2018-03-21 15:44 UTC, Krigpl requested changes
Mainly versioning

2018-03-21 15:44 UTC, Krigpl commented on golem/node.py
> -                self._error('keys or docker'),
Bad comma?

2018-03-21 15:44 UTC, Krigpl commented on golem/interface/websockets.py
> +            method_map['accept_terms'] = 'golem.terms.accept'
What about `show_terms` ?

2018-03-21 15:44 UTC, Krigpl commented on golem/node.py
> +            .where(GenericKeyValue.key == self.TERMS_ACCEPTED_KEY)\
Add versioning of the terms

2018-03-21 15:47 UTC, Wiezzel commented on golem/interface/websockets.py
> +            method_map['accept_terms'] = 'golem.terms.accept'
There is no RPC call for `show_terms`.

2018-03-21 16:01 UTC, Krigpl commented on golem/node.py
> +        def wait_for_terms():
That shouldn't run for testnet

2018-03-21 16:30 UTC, Wiezzel commented on golem/node.py
> +        def wait_for_terms():
It should.

2018-03-21 16:30 UTC, Wiezzel commented on golem/node.py
> +            .where(GenericKeyValue.key == self.TERMS_ACCEPTED_KEY)\
OK.

2018-03-21 16:31 UTC, Wiezzel commented on golem/node.py
> -                self._error('keys or docker'),
Just unnecessary.

2018-03-21 16:40 UTC, Krigpl commented on golem/node.py
> -                self._error('keys or docker'),
You know it changes blame, right? So unnecessary is actually removal of this comma. And in general commas like this help preserve blame.

2018-03-21 16:42 UTC, Wiezzel commented on golem/node.py
> -                self._error('keys or docker'),
OK.

2018-03-21 17:07 UTC, Krigpl approved these changes
just one comment, I'd be happy to see you address, otherwise lgtm

2018-03-21 17:07 UTC, Krigpl commented on golem/node.py
> +    def accept_terms(self):
I wouldn't really mind if all these terms related logic would be in a separate class, since this a completely separate piece of logic. Having `TERMS_*` constants in this class feels weird.

2018-03-21 17:54 UTC, Wiezzel commented on golem/node.py
> +    def accept_terms(self):
That's a good idea, but it could be done in a separate PR. I don't want to postpone merging this one any longer.

2018-03-21 18:10 UTC, merged