Opt-in enable_talkback
golemfactory/clay pull request #2375
Opened 2018-03-15 17:57 UTC by ktomala

Allows enable_talkback in configuration, via commandline and RPC

2018-03-15 18:05 UTC, mfranciszkiewicz commented on golem/client.py
> +        except Exception as e:
`# pylint: disable=broad-exception`

2018-03-15 18:08 UTC, mfranciszkiewicz commented on golem/rpc/mapping/rpcmethodnames.py
> +    enable_talkback=        'env.enable_talkback',
Since the config file isn't updated, please remove this mapping.

2018-03-16 11:55 UTC, maaktweluit requested changes
LGTM!

Some small comments, will approve on reply

As general comment i do not see the value in `bool()` everywhere, if we make the default value False there is no other option. Saves a lot of type-casts and can be typed at the argument level

2018-03-16 11:55 UTC, maaktweluit commented on golem/client.py
> +    def enable_talkback(self, value):   # pylint: disable=no-self-use
i think `@staticmethod` is better then disable pylint

2018-03-16 11:55 UTC, maaktweluit commented on golem/client.py
> +            logger.info('%s talkback service' % msg_part)
please use logger arguments over formatting wih `%`

2018-03-16 11:55 UTC, maaktweluit commented on golem/client.py
> +            msg_part = 'Enabling' if talkback_value else 'Disabling'
msg_part can be used in the exception log as well

2018-03-16 14:25 UTC, ktomala commented on golem/client.py
> +    def enable_talkback(self, value):   # pylint: disable=no-self-use
good point, will correct it

2018-03-16 14:27 UTC, ktomala commented on golem/client.py
> +            logger.info('%s talkback service' % msg_part)
good find, will do

2018-03-16 14:28 UTC, ktomala commented on golem/client.py
> +            msg_part = 'Enabling' if talkback_value else 'Disabling'
also good point

2018-03-16 14:50 UTC, maaktweluit approved these changes

2018-03-20 10:09 UTC, merged