Monitor for testnet and mainnet (golem-monitor #35)
golemfactory/clay pull request #2466
Opened 2018-03-22 16:45 UTC by RDProjekt

Receiving and storing net (mainnet/testnet) value in the database.

2018-03-23 12:11 UTC, Wiezzel requested changes
Calling `time.sleep()` in tests must be avoided.

2018-03-23 12:11 UTC, Wiezzel commented on tests/golem/monitor/test_monitor.py
> +                time.sleep(0.005)
This is not a good way to test multi-threaded code. If you want to test `SenderThread` as well add another test case.

2018-03-23 12:11 UTC, Wiezzel commented on tests/golem/monitor/test_monitor.py
> +                    }
Test should probably be renamed if you check all these data. Now it's called `test_protocol_versions` and the docstring says `"""Test whether correct protocol versions were sent."""`.

2018-03-23 14:44 UTC, RDProjekt commented on tests/golem/monitor/test_monitor.py
> +                time.sleep(0.005)
We added functions for such test in another commit, we'll create pull request for it shortly

2018-03-26 09:42 UTC, jiivan commented on golem/monitor/test_helper.py
> +from unittest import mock, TestCase
Import ordering

2018-03-26 09:42 UTC, jiivan commented on tests/golem/monitor/test_monitor.py
> +import json
Import ordering

2018-03-26 09:42 UTC, jiivan commented on tests/golem/monitor/test_monitor.py
> +        self.monitor.start()
Where is `.shut_down()` called?

2018-03-26 09:45 UTC, Wiezzel commented on tests/golem/monitor/test_monitor.py
> +        self.monitor.start()
In `test_monitor_messages`. :stuck_out_tongue:

2018-03-26 09:45 UTC, Wiezzel commented on tests/golem/monitor/test_monitor.py
> +        self.monitor.start()
But yes, it should be called in `tearDown`.

2018-03-26 09:54 UTC, jiivan commented on tests/golem/monitor/test_monitor.py
> +        self.monitor.start()
If `.start()` is moved to `setUp()` then `.shutd_down()` should be also moved to`tearDown()`

2018-03-27 10:52 UTC, RDProjekt commented on tests/golem/monitor/test_monitor.py
> +                    }
Done

2018-03-27 10:53 UTC, RDProjekt commented on golem/monitor/test_helper.py
> +from unittest import mock, TestCase
Done

2018-03-27 10:53 UTC, RDProjekt commented on tests/golem/monitor/test_monitor.py
> +import json
Done

2018-03-27 10:54 UTC, RDProjekt commented on tests/golem/monitor/test_monitor.py
> +        self.monitor.start()
Done

2018-03-29 10:29 UTC, Wiezzel approved these changes
OK, but please remove that sleep later.

2018-03-29 12:04 UTC, merged