Set dummy loglevel to debug
golemfactory/clay pull request #2488
Opened 2018-03-23 14:12 UTC by maaktweluit

This way when they fail we can investigate more

2018-03-23 16:12 UTC, mfranciszkiewicz submitted a review, later dismissed

2018-03-26 05:56 UTC, tworec requested changes

2018-03-26 05:56 UTC, tworec commented on loggingconfig.py
> +            'formatter': 'date',
this will affect whole app, not only dummy task

2018-03-26 13:57 UTC, maaktweluit commented on loggingconfig.py
> +            'formatter': 'date',
Good one!

This is not meant to be merged, this was required to find what component is blocking

Changed title to WIP, will ping you when its ready for review again

2018-03-26 17:28 UTC, maaktweluit commented
Turned out UPNP was the problem this time...

Left some logs and added the dates in this test only.

Hope the next time dummy tests are easier to spot :)

@mfranciszkiewicz @tworec please review again!

2018-03-26 17:40 UTC, mfranciszkiewicz approved these changes

2018-03-27 06:50 UTC, tworec approved these changes

2018-03-27 06:50 UTC, tworec commented on tests/golem/task/dummy/runner.py
> +    config_desc.use_upnp = False
this is only line changed not regarding logger. This is cause of our headache? :)

2018-03-27 10:32 UTC, maaktweluit commented on tests/golem/task/dummy/runner.py
> +    config_desc.use_upnp = False
Yep, the one and only...

Hopefully the rest makes it easier to find next time

2018-03-27 10:32 UTC, merged