Improved test coverage for terms of use (#2475)
golemfactory/clay pull request #2489
Opened 2018-03-23 14:55 UTC by Wiezzel

2018-03-23 15:32 UTC, Krigpl requested changes
lgtm, just the temporary dir thing

2018-03-23 15:32 UTC, Krigpl commented on tests/golem/test_terms.py
> +        self.assertFalse(TermsOfUse.are_terms_accepted())
This and all other `self.assert*`s can be replaced with simple `assert not bool` etc which are clearer

2018-03-23 15:32 UTC, Krigpl commented on tests/golem/test_terms.py
> +    @patch('golem.terms.get_golem_path', return_value='/tmp')
use `self.tempdir`, `/tmp` won't work on Windows for instance

2018-03-23 15:39 UTC, Wiezzel commented on tests/golem/test_terms.py
> +        self.assertFalse(TermsOfUse.are_terms_accepted())
I am not a fan of using plain assertions in unit tests. `unittest.TestCase.failureException` could be changed to a different exception class than `AssertionError` and then we get different test outcomes. I advocate using plain `assert` only in core code.

2018-03-23 16:07 UTC, Wiezzel commented on tests/golem/test_terms.py
> +    @patch('golem.terms.get_golem_path', return_value='/tmp')
Fixed.

2018-03-26 08:19 UTC, Krigpl commented on tests/golem/test_terms.py
> +        with open(self.new_path / 'golem' / 'TERMS.html', mode='w') as terms:
Actually that path should also be a constant in the `Terms` class

2018-03-26 08:21 UTC, Wiezzel commented on tests/golem/test_terms.py
> +        with open(self.new_path / 'golem' / 'TERMS.html', mode='w') as terms:
Good idea.

2018-03-26 08:44 UTC, Krigpl approved these changes

2018-03-26 08:48 UTC, merged