Include lock funds in withdraw function
golemfactory/clay pull request #2510
Opened 2018-03-28 08:44 UTC by badb

2018-03-28 13:26 UTC, maaktweluit requested changes
LGTM!

One small comment question

2018-03-28 13:26 UTC, maaktweluit commented on tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
> +        # Enough total GNT
This comment seems incorrect, `not` is missing?

2018-03-28 13:47 UTC, Krigpl requested changes

2018-03-28 13:47 UTC, Krigpl commented on golem/client.py
> +        return self.transaction_system.withdraw(amount, destination, currency,
just do `amount-lock`, no need for `transaction_system.withdraw` to be aware of any "locks"

2018-03-28 13:48 UTC, Krigpl commented on tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
> +        # Enough total GNT
![yesquiteindeed](https://user-images.githubusercontent.com/3904252/38033092-7632cc92-329f-11e8-983b-f64fc40c41a2.jpg)

2018-03-29 08:18 UTC, jiivan commented on golem/client.py
> +        return self.transaction_system.withdraw(amount, destination, currency,
@Krigpl did you mean `total-lock`?

2018-03-29 08:28 UTC, Krigpl approved these changes

2018-03-29 08:28 UTC, Krigpl commented on golem/client.py
> +        return self.transaction_system.withdraw(amount, destination, currency,
Oh yeah, I realized my comment doesn't actually make any sense. The current approach is correct.

2018-03-29 08:42 UTC, jiivan approved these changes

2018-03-29 12:34 UTC, merged