Check that task_id was generated from requestor key_id in task_keeper
golemfactory/clay pull request #2539
Opened 2018-03-29 17:05 UTC by badb

* Create separate class for id generation and checking
* Check that task_id was generated from requestor key_id in task_keeper

2018-03-29 19:29 UTC, tworec approved these changes
some minor cavails ;)

2018-03-29 19:29 UTC, tworec commented on golem/core/idgenerator.py
> +def generate_id(gen: bytes, len_: int = GEN_LEN) -> str:
`len_` is redundant as uuid node must be 48 bits, which mean 6 bytes, or 12 hex'es. `GEN_LEN`  is enough.
It also would be nice to add some doc, because `gen` parameter is not so easy to understood at a glance. Maybe `seed` is a bit more intuitive.

2018-03-29 19:29 UTC, tworec commented on golem/core/idgenerator.py
> +def gen_to_node(gen: bytes, len_: int = GEN_LEN) -> int:
mark as `__private`

2018-03-29 19:29 UTC, tworec commented on golem/task/taskkeeper.py
> +                                      "owner %s", task_id, owner_id)
Encourage to use [f-strings](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498) eg. `f' Task_id {task_id} and task owner {task_owner} mismatch'`

2018-03-29 19:29 UTC, tworec commented on tests/golem/task/dummy/task.py
> +        task_id = generate_id(public_key)
👍 Hmm, how could I've missed that! :)

2018-03-29 19:29 UTC, tworec commented on apps/core/task/coretask.py
> +        return generate_id(public_key)
I'd rather move both docs to `idgenerator`

2018-03-30 17:29 UTC, mfranciszkiewicz approved these changes

2018-04-03 07:04 UTC, etam commented on golem/core/idgenerator.py
> +def generate_new_id_from_id(id_: str):
I can haz return type annotation?

2018-04-03 07:04 UTC, etam commented on golem/core/idgenerator.py
> +def check_id_seed(id_: str, gen: bytes):
I can haz return type annotation?

2018-04-03 10:26 UTC, tworec requested changes

2018-04-03 10:26 UTC, tworec commented on golem/core/idgenerator.py
> +    :returns: string uuid1 based on timestamp and given key
... --> and given seed

2018-04-03 10:26 UTC, tworec commented on golem/core/idgenerator.py
> +def check_id_seed(id_: str, gen: bytes):
here is still `gen` --> `seed`

2018-04-03 11:57 UTC, tworec approved these changes

2018-04-09 13:51 UTC, merged