Allow users to specify the public IP address and ports
golemfactory/clay pull request #2540
Opened 2018-03-29 18:03 UTC by mfranciszkiewicz

2018-03-30 12:04 UTC, maaktweluit approved these changes
LGTM!

2018-03-30 12:04 UTC, maaktweluit commented on golem/client.py
> +            self._override_node_properties(self.node)
would be nice to call this before `use_upnp` to remove that manual check there, i guess this is not possible due to the need of upnp info

2018-03-30 13:33 UTC, mfranciszkiewicz commented on golem/client.py
> +            self._override_node_properties(self.node)
I wanted to make these the true overrides. It's true that it makes little sense to force the public IP and ports with UPnP on, but now we have a `--noupnp` flag.

2018-04-03 11:59 UTC, tworec requested changes

2018-04-03 11:59 UTC, tworec commented on golem/argsparser.py
> +                raise Exception(value)
such exception w/o msg just with value would cause users/developers doubts
shouldn't we just raise `click.BadParameter` here?

2018-04-03 11:59 UTC, tworec commented on golem/client.py
> +            'pub_p2p_port': 'pub_p2p_port',
`pub_p2p_port` --> `p2p_pub_port` as in `golem/network/p2p/node.py:21`

2018-04-03 11:59 UTC, tworec commented on golem/node.py
> +                 config_args: Optional[ClientConfigDescriptor] = None) -> None:
I'd move `config_args` just after `config_desc` not being optional as it is not optional really. We always provide it within `golemapp.py`

2018-04-03 11:59 UTC, tworec commented on golem/client.py
> +            config_args: Optional[ClientConfigDescriptor] = None) -> None:
I'd move `config_args` just after `config_desc` not being optional as it is not optional really. See my comment in `golem/node.py:49`

2018-04-03 11:59 UTC, tworec commented on golemapp.py
> +            config_args=config_args,
here you just confirm my hipotesis that this is more intuitive place for that arg

2018-04-03 13:10 UTC, mfranciszkiewicz commented on golem/argsparser.py
> +                raise Exception(value)
We already do in `except`

2018-04-03 13:19 UTC, mfranciszkiewicz commented on golem/node.py
> +                 config_args: Optional[ClientConfigDescriptor] = None) -> None:
I've moved it to the end because it affects tens of tests and is not required to build the instance.

2018-04-04 08:28 UTC, tworec approved these changes

2018-04-04 08:28 UTC, tworec commented on golem/argsparser.py
> +                raise Exception(value)
I saw, but what is this raise-catch-raise for?

2018-04-04 10:46 UTC, mfranciszkiewicz commented on golem/argsparser.py
> +                raise Exception(value)
If the comparison inside the `try` block raises other exception, everything is handled in a single `except`.

2018-04-05 10:16 UTC, tworec commented on golem/argsparser.py
> +                raise Exception(value)
This is of minor importance and feel free to ignore it, but to be consistent: You are using `type=Click.INT` so `value` here has type `int`. Click lib handles non-integer input for you and prevents calling this function if input is not valid int. I can't imagine other exception in comparsion. 

I would raise `Click.BadParameter` immediately with a bit more informative msg: _'Port should be in range (1-65535)'_. If you expect other Exception, than catch it and rethrow as `Click.BadParameter`.

2018-04-05 10:35 UTC, mfranciszkiewicz commented on golem/argsparser.py
> +                raise Exception(value)
Consistency is what I did here explicitly - this function is written in the same style as other functions.

2018-04-05 12:41 UTC, tworec commented on golem/argsparser.py
> +                raise Exception(value)
All other functions raises `Click.BadParam` immediately and catches some specific exceptions not vanilla `Exception`

2018-04-05 12:42 UTC, tworec commented on golem/argsparser.py
> +                raise Exception(value)
buts lets not dive deeper into it. Its ok. We have more important problems 🚀

2018-04-05 13:11 UTC, mfranciszkiewicz commented on golem/argsparser.py
> +                raise Exception(value)
If I had a nickel for every missing exception type fix...

2018-04-05 15:23 UTC, tworec commented on golem/argsparser.py
> +                raise Exception(value)
:wink:

2018-11-21 21:00 UTC, closed without merging