Remove DB from the Client
golemfactory/clay pull request #2628
Opened 2018-04-12 13:04 UTC by Krigpl

It doesn't really belong there.

2018-04-12 13:08 UTC, Wiezzel approved these changes
OK, just one more line to delete.

2018-04-12 13:08 UTC, Wiezzel commented on tests/golem/test_client.py
>          self.client.db = None
This line should be removed as well.

2018-04-12 16:31 UTC, mfranciszkiewicz requested changes
The database has been lately moved from `Client` to `Node`, but the application (reactor) shutdown trigger is still set on `Client.quit`, which closes database connections.

2018-05-22 12:28 UTC, Krigpl commented
Maybe some other day.

2018-05-22 12:28 UTC, closed without merging