Mwu/pip freeze2
golemfactory/clay pull request #2637
Opened 2018-04-12 17:07 UTC by maaktweluit

Deja-vu, sorry i know!

This time lets merge this before anyone changes requirements :)

2018-04-13 08:22 UTC, etam commented
I think it's OK. What about requirements-lint.txt and requirements-test.txt?

2018-04-13 08:28 UTC, etam requested changes

2018-04-13 08:28 UTC, etam commented on requirements.txt
> -Crypto
What happened with `Crypto`? Build failed, because it's missing.

2018-04-13 10:23 UTC, maaktweluit commented
@etam i skipped the -test and -lint since they are not part of the build, do you think they should be frozen too?

2018-04-13 10:25 UTC, maaktweluit commented on requirements.txt
> -Crypto
its not in pypi as `Crypto`... remember this was a problem last time too, will check that branch, i fixed it there :)

2018-04-13 11:12 UTC, etam commented
> i skipped the -test and -lint since they are not part of the build, do you think they should be frozen too?

I think yes. For exactly the same reason, we're freezing golem's requirements.

2018-04-13 11:41 UTC, maaktweluit commented
@etam done, builds also seem fixed :D

2018-04-13 13:31 UTC, etam commented
`Double requirement given: six==1.11.0 (from -r requirements-test.txt (line 24)) (already in six==1.10.0 (from -r requirements.txt (line 99)), name='six')`

2018-04-13 14:12 UTC, maaktweluit commented
six and pyelleptic fixed in the new commit

2018-04-16 12:47 UTC, maaktweluit commented
@etam please check again, all errors are solved from my side :D

2018-04-16 13:50 UTC, etam approved these changes
![frozen](https://media.giphy.com/media/KaW6fNYZf6eSk/giphy.gif)

2018-04-16 17:46 UTC, mfranciszkiewicz approved these changes

2018-04-17 10:20 UTC, merged