Client.connection_status: send raw data
golemfactory/clay pull request #2702
Opened 2018-04-23 14:50 UTC by etam

This allows a RPC client to understand the network status.

This should not have any impact on electron. @mdtanrikulu please confirm.

2018-04-24 05:42 UTC, tworec requested changes

2018-04-24 05:42 UTC, tworec commented on golem/interface/client/network.py
> +            messages.append("Port {}.".format(port_statuses))
`Port` --> `Port(s):`

2018-04-24 05:42 UTC, tworec commented on tests/golem/test_client.py
> +        assert not c.connection_status()['listening']
add missing test cases:
- unknown
- Application not listening, check config file
- Port(s): [list]
- Connected / Not Connected .. check

2018-04-25 09:10 UTC, etam commented on tests/golem/test_client.py
> +        assert not c.connection_status()['listening']
Done, but in different file.

2018-04-26 10:23 UTC, tworec requested changes

2018-04-26 10:23 UTC, tworec commented on golem/client.py
> +        status = dict()
You have changed return type and value for `connection_status` and corrected its usage in `golem/interface/client/network.py` but it is used also in `NetworkConnectionPublisherService` see line 1337

https://github.com/golemfactory/golem/pull/2702/files#diff-9f351727974c5655127c6a4dc0671995R1337

I don't know the purpose of this class, but have you considered and checked consequences of your change?

2018-04-26 10:23 UTC, tworec commented on tests/golem/interface/test_client_commands.py
> +            assert "not listening" in result
why not use exact full message which we are actually expecting and no such heuristics, where you are checking for some part is in, and two otheres are not? This is not easy readable.

2018-04-26 10:23 UTC, tworec commented on tests/golem/test_client.py
> +        assert not c.connection_status()['listening']
ok, cool.
here you should test also `connection_status()['port_statuses']`  because you've added such a property

2018-06-12 12:55 UTC, etam commented on golem/client.py
> +        status = dict()
This class is periodically sending connection status as an event on rpc (on crossbar you can call a method over rpc, but you can also publish events).

So, yes, I know that my change affects both 'net.status' rpc method and 'evt.net.connection' event.

2018-06-12 12:57 UTC, etam commented on tests/golem/interface/test_client_commands.py
> +            assert "not listening" in result
To check only for important parts and not make it strictly bound to output formatting and other stuff that might appear. If someone later adds some more info to the output it won't affect the test.

2018-06-13 08:30 UTC, etam commented on tests/golem/test_client.py
> +        assert not c.connection_status()['listening']
added

2018-06-21 16:45 UTC, tworec commented on tests/golem/interface/test_client_commands.py
> +            assert "not listening" in result
do not like it, but lets go on

2018-06-21 16:45 UTC, tworec approved these changes

2018-07-13 13:11 UTC, etam commented
RPC change: `net.status` (`Client.connection_status`) is changed from string to a dictionary structure.

If golem is not listening (p2p or task port is not open)
```python
{
    'listening': False
}
```
else:
```python
{
    'listening': True,
    'connected': bool(has any connected peers),
    'port_statuses': {
        1234: "open",
        2345: "unreachable",
    }
}
```

`port_statuses` is filled on receiving data from 'ping me' service. So it might be empty shortly after starting golem.
Possible values (from https://github.com/golemfactory/golem-monitor/blob/f731eb03735f615b9a64ebcf2699874a6b113ae3/models/golemstatsmodel.js#L263):
- 'unreachable'
- 'timeout'
- 'open'

2018-08-02 17:02 UTC, mdtanrikulu approved these changes

2018-10-01 09:53 UTC, etam commented
TODO: pass the old message with the raw data

2018-10-01 15:41 UTC, etam commented
> TODO: pass the old message with the raw data

Done

2018-10-04 14:43 UTC, merged