RPC method to add nodes to block list
golemfactory/clay pull request #2717
Opened 2018-04-25 13:12 UTC by Wiezzel

2018-04-26 13:24 UTC, etam requested changes
![so close](https://media.giphy.com/media/xTiN0DvoDyWQey2B8I/giphy.gif)

2018-04-26 13:24 UTC, etam commented on golem/client.py
> +        assert isinstance(self.task_server, TaskServer)
This is too bold. Change it to return `True` on success and add printing an error message in golemcli on error.

2018-04-26 13:24 UTC, etam commented on golem/task/acl.py
> +        for node_id in node_set:
Suggestion: `in sorted(node_set)`. Otherwise it'll mix the contents every time.

2018-04-26 13:27 UTC, Wiezzel commented on golem/client.py
> +        assert isinstance(self.task_server, TaskServer)
You mean something like this?
```python
try:
    # here goes all code
    return True, None
except Exception e:
    return False, e
```

2018-04-26 14:00 UTC, etam commented on golem/client.py
> +        assert isinstance(self.task_server, TaskServer)
`return False, str(e)` in last line.

But also instead of `isinstance`, it would be more straightforward to use `if self.task_server is not None:` (it's `None` until `start_network` is called for the first time).

2018-04-26 14:06 UTC, Wiezzel commented on golem/client.py
> +        assert isinstance(self.task_server, TaskServer)
`str(e)` for sure.
But I'll keep the type assertion. It enables type-checking. Of course it would be better to declare this field as of `TaskServer` type, but that would require a bigger refactoring.

2018-04-26 14:33 UTC, etam commented on golem/client.py
> +        assert isinstance(self.task_server, TaskServer)
The type of `task_server` is `Optional[TaskServer]`. No big refactoring needed, no type checking needed.

2018-04-26 14:36 UTC, Wiezzel commented on golem/client.py
> +        assert isinstance(self.task_server, TaskServer)
Is it? I don't see any type declaration here: https://github.com/golemfactory/golem/blob/develop/golem/client.py#L156

2018-04-26 14:45 UTC, Wiezzel commented on golem/client.py
> +        assert isinstance(self.task_server, TaskServer)
I get nice hints from IDE when using type assertion:
![image](https://user-images.githubusercontent.com/9394821/39312957-0d25ce0a-4971-11e8-8c2c-84abd2138703.png)
But not with not-none check:
![image](https://user-images.githubusercontent.com/9394821/39312988-22f22882-4971-11e8-83cc-a5489e29cf2d.png)

2018-04-27 07:33 UTC, etam commented on golem/client.py
> +        assert isinstance(self.task_server, TaskServer)
> Is it? I don't see any type declaration here

You can add it.

2018-04-27 09:20 UTC, Wiezzel commented on golem/client.py
> +        assert isinstance(self.task_server, TaskServer)
OK, fixed.

2018-04-27 09:20 UTC, Wiezzel commented on golem/task/acl.py
> +        for node_id in node_set:
Fixed.

2018-04-27 12:39 UTC, etam commented on tests/golem/interface/test_client_commands.py
> +        self.client.reset_mock()
Wouldn't that reset everything that was prepared in `setUpClass`? If this is required, then it seems reasonable to create a proper `setUp` method.

2018-04-27 12:41 UTC, Wiezzel commented on tests/golem/interface/test_client_commands.py
> +        self.client.reset_mock()
Nope. It just resets calls to mocked methods. ([sauce](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.reset_mock))

2018-04-27 12:51 UTC, etam approved these changes
:+1:

2018-04-27 13:56 UTC, mfranciszkiewicz approved these changes

2018-04-27 14:43 UTC, merged