Enable concent by default on testnet
golemfactory/clay pull request #2718
Opened 2018-04-25 13:34 UTC by jiivan

fixes: #2666

2018-04-25 14:36 UTC, shadeofblue approved these changes
seems okay

2018-04-26 06:37 UTC, shadeofblue requested changes
actually, I think it would be better, instead of passing the of the variant name around, pass the resultant configuration dictionary ... it seems somewhat artificial that each component needs to know that it has to retrieve the config from the choices dictionary...

2018-04-26 06:38 UTC, shadeofblue commented on golem/client.py
> +            concent_variant_name: str = 'disabled',
so, I believe it should be just `concent_variant` here, the default value of which, should be `golem.core.variables.CONCENT_CHOICES.get('disabled')`

2018-04-26 06:38 UTC, shadeofblue commented on golem/client.py
> +            variant_name=concent_variant_name,
just `variant`

2018-04-26 06:38 UTC, shadeofblue commented on golem/client.py
> +            variant_name=concent_variant_name,
just `variant`

2018-04-26 06:39 UTC, shadeofblue commented on golem/network/concent/client.py
> +        variant: dict) -> typing.Optional[bytes]:
and I think it would be good to call this parameter `concent_variant` so that it's perfectly clear the variant of _what_ we're referring to...

2018-04-26 06:40 UTC, shadeofblue commented on golem/network/concent/client.py
> +    def __init__(self, keys_auth: keysauth.KeysAuth, variant_name='staging'):
btw, why does it default to `staging` here all of a sudden?

2018-04-26 06:42 UTC, shadeofblue commented on golem/network/concent/client.py
> +        return None not in self.variant.values()
wouldn't it be more future-proof to check just e.g. the URL? I imagine we might add some setting later on that wouldn't be crucial but could be `None` as a default and it would fail this check...

2018-04-26 06:42 UTC, shadeofblue commented on golem/network/concent/filetransfers.py
> +                 variant_name: str = 'dev') -> None:
and again, why a different default yet here?

2018-04-26 08:03 UTC, jiivan commented on golem/network/concent/client.py
> +    def __init__(self, keys_auth: keysauth.KeysAuth, variant_name='staging'):
because before this change `enabled=True` meant `staging`. :)

2018-04-26 11:55 UTC, shadeofblue approved these changes

2018-04-26 12:55 UTC, merged