requestor to check performance index before work offer acceptance
golemfactory/clay pull request #2734
Opened 2018-04-26 16:56 UTC by tworec

2018-04-26 18:01 UTC, mfranciszkiewicz commented on golem/task/taskserver.py
> +            logger.info('insufficient provider performance index: '
Could you also add `node_name`, `node_id` and `task_id` to these messages? That would provide clear information as of who and why.

2018-04-26 18:01 UTC, mfranciszkiewicz commented on golem/task/taskmanager.py
> +                logger.info('task is not active')
Please see my other comment regarding logs

2018-04-26 18:01 UTC, mfranciszkiewicz commented on golem/task/taskserver.py
> +        # if task.header.num_cores > num_cores:
Unfortunately, currently there is no such parameter.

2018-04-26 20:46 UTC, tworec commented on golem/task/taskserver.py
> +            logger.info('insufficient provider performance index: '
good point

2018-04-27 08:48 UTC, mfranciszkiewicz submitted a review, later dismissed

2018-04-27 08:50 UTC, mfranciszkiewicz commented
It looks like more tests need updating.

2018-04-27 10:25 UTC, Krigpl commented on golem/task/taskmanager.py
> -            if task.header.resource_size > (int(max_resource_size) * 1024):
Why do you remove these checks? They are still useful so the provider doesn't even bother requestor unnecessarily.

2018-04-27 10:26 UTC, mfranciszkiewicz commented on golem/task/taskmanager.py
> -            if task.header.resource_size > (int(max_resource_size) * 1024):
@Krigpl These checks have been moved to `should_accept_provider`

2018-04-27 10:28 UTC, Krigpl commented on golem/task/taskmanager.py
> -            if task.header.resource_size > (int(max_resource_size) * 1024):
I know, I'm saying that they are still useful on the provider side.

2018-04-27 10:33 UTC, Krigpl commented on golem/task/taskmanager.py
> -            if task.header.resource_size > (int(max_resource_size) * 1024):
Oh, this is still requestor side. So my point is that these checks could be beneficial on the provider side as well.

2018-04-27 10:36 UTC, Krigpl commented on golem/task/taskmanager.py
> -            if task.header.resource_size > (int(max_resource_size) * 1024):
Also, `max_resource_size` and `max_memory_size` are no longer needed in this method.
I'd also look into why `estimated_performance` and `num_cores` is needed

2018-04-27 13:22 UTC, tworec commented on golem/task/taskmanager.py
> -            if task.header.resource_size > (int(max_resource_size) * 1024):
@Krigpl thanks for feedback

2018-05-07 15:01 UTC, tworec commented
@mfranciszkiewicz @badb if we want this to be in next release please merge it.

2018-05-16 16:57 UTC, badb commented
@tworec Can you make PR to develop with this change?

2018-05-16 16:57 UTC, badb commented on golem/task/taskserver.py
> +        if requestor_perf > int(provider_perf) * int(num_cores):
Why are you multiplying it by number of cores? It's not a performance per core, but general performance for the assigned amount of cores.

2018-05-16 16:59 UTC, badb requested changes
Check the comment

2018-05-18 10:58 UTC, tworec commented on golem/task/taskserver.py
> +        if requestor_perf > int(provider_perf) * int(num_cores):
it was intentional, as we discussed. But will change, as Blender benchmark uses multi-core

2018-05-23 01:20 UTC, mfranciszkiewicz reviewed
Some details; almost approved

2018-05-23 01:20 UTC, mfranciszkiewicz commented on golem/database/schemas/015_schema.py
> +    migrator.drop_index('performance', 'environment_id')
`drop` + `add` (rebuilding) indexes isn't harmful and may even be desirable in the current state. We should implement some other machinery for that purpose, though. Could you remove these lines ?

2018-05-23 01:20 UTC, mfranciszkiewicz commented on golem/rpc/mapping/rpcmethodnames.py
> +    get_min_performance=    'comp.environment.performance.min.get',
Can i haz (in a former fashion) `comp.environment.performance.min` as `get` and `comp.environment.performance.min.update` for updating? Or does it cascade changes in GUI?

2018-05-23 01:20 UTC, mfranciszkiewicz commented on golem/database/schemas/015_schema.py
> +def migrate(migrator, *_, **__):
We've talked about this (semi) offline; could you create an issue for `setup.py develop migration` + data directory changes?

2018-05-23 01:20 UTC, mfranciszkiewicz commented on golem/client.py
> +        result = yield defer.execute(env.get_min_accepted_performance)
`yield` (+ `inlineCallbacks`) isn't required here, since `get_min_accepted_performance` is 100% synchronous. A straightforward call should suffice.

2018-05-23 01:20 UTC, mfranciszkiewicz commented on golem/client.py
> +        yield defer.execute(env.set_min_accepted_performance,
Same as above

2018-05-23 11:15 UTC, tworec commented on golem/database/schemas/015_schema.py
> +    migrator.drop_index('performance', 'environment_id')
ok

2018-05-23 11:15 UTC, tworec commented on golem/rpc/mapping/rpcmethodnames.py
> +    get_min_performance=    'comp.environment.performance.min.get',
we need to align it with @mdtanrikulu No problem from my side

2018-05-23 11:16 UTC, tworec commented on golem/database/schemas/015_schema.py
> +def migrate(migrator, *_, **__):
will do

2018-05-23 11:19 UTC, tworec commented on golem/client.py
> +        result = yield defer.execute(env.get_min_accepted_performance)
As we discussed, I've added it just for catching exceptions, because without `yield` and `inlineCallbacks` it was'nt working for me. But now seems to work ;) It was too late yesterday...

2018-05-23 14:35 UTC, badb commented on golem/client.py
> +    # TODO: hardcoded Blender just for 0.16.0
Can you create an issue for this and attach its nubmer to this TODO comment?

2018-05-23 16:24 UTC, tworec commented on golem/client.py
> +    # TODO: hardcoded Blender just for 0.16.0
since we've decided to do it more generic (see https://github.com/golemfactory/golem/issues/2771#issuecomment-391344430) this hardcode will be removed

2018-05-23 16:41 UTC, tworec commented on golem/rpc/mapping/rpcmethodnames.py
> +    get_min_performance=    'comp.environment.performance.min.get',
@mdtanrikulu agreed, so I've changed. Please check

2018-05-28 16:24 UTC, mfranciszkiewicz approved these changes

2018-05-28 16:49 UTC, merged