Allow HTTPS scheme for --geth-address
golemfactory/clay pull request #2750
Opened 2018-05-03 08:17 UTC by gcarq

This PR modifies `argparser.parse_http_addr` to accept https urls, that allows users to pass a custom geth node which is behind a https reverse proxy.

2018-05-03 08:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=2750) <br/>All committers have signed the CLA.

2018-05-16 16:54 UTC, maaktweluit approved these changes
LGTM!

One small comment, can be replied to only so i approve.

2018-05-16 16:54 UTC, maaktweluit commented on golem/argsparser.py
> +                value.replace(parsed_url.scheme + '://', '')
I liked the `val[len(x):]` more then a string replace, not sure what is more efficient / readable

2018-05-17 11:00 UTC, Krigpl requested changes
Thank you for your contribution. The change in the parser code looks good but let's improve the tests, see inline comments.

2018-05-17 11:00 UTC, Krigpl commented on tests/golem/test_opt_node.py
> -    def test_geth_address_should_be_passed_to_node(self, mock_node, *_):
Let's not change that. This test checks whether the `geth_address` argument is correctly passed down the stack, not whether the argument itself is correct.
So instead of this and adding the other test `test_geth_https_address_should_be_passed_to_node` it should remain as it is and you may add a test for the `parse_http_addr` itself. I see that the `tests/test_argsparser.py` file is missing so feel free to add it and write a test checking whether it correctly parses both http and https.

2018-05-17 11:00 UTC, Krigpl commented on tests/golem/test_opt_node.py
> -    def test_geth_address_should_be_passed_to_client(self, mock_client, *_):
Same as above, do not change it.

2018-06-01 11:25 UTC, gcarq commented
Thanks for the feedback, I will change that and solve the file conflicts

2019-05-06 08:36 UTC, Krigpl commented
@gcarq Please feel free to reopen if you decide to pick this up again.

2019-05-06 08:36 UTC, closed without merging