WIP React to `AckSubtaskResultsVerify` and upload resources + results
golemfactory/clay pull request #2763
Opened 2018-05-11 11:17 UTC by shadeofblue

- `helpers.verify_message_signature` -> uses `Message.verify_signature` instead
+ `AckSubtaskResultsVerify` handler
received_handler DRY

2018-05-24 10:50 UTC, etam commented on golem/network/concent/received_handler.py
> +                child_msg_field: str):
return type annotation?

2018-05-24 10:50 UTC, etam commented on golem/network/concent/received_handler.py
> +    def _upload_results(self, subtask_id, ftt):
type annotations?

2018-05-24 10:50 UTC, etam commented on golem/network/concent/received_handler.py
> +    def _upload_task_resources(self, task_id, ftt):
type annotations?

2018-05-24 10:54 UTC, etam commented on golem/task/taskkeeper.py
> +    def add_package_paths(self, task_id, package_paths):
type annotations?

2018-05-24 10:54 UTC, etam commented on golem/task/taskkeeper.py
> +    def get_package_paths(self, task_id):
type annotations?

2018-05-24 11:20 UTC, jiivan approved these changes

2018-05-24 11:50 UTC, etam requested changes

2018-05-24 11:50 UTC, etam commented on tests/golem/network/concent/test_filetransfers.py
> +        self._init_uploaded_file(path)
You can use `self.new_path`, which is a `pathlib.Path`. Then everything is easy:

```python
(self.new_path / "something.good").write_text('meh')
```

2018-05-24 11:50 UTC, etam commented on tests/golem/network/concent/test_filetransfers.py
> +        self._init_uploaded_file(path)
`self.new_path` like above

2018-05-25 07:15 UTC, etam requested changes

2018-05-25 07:15 UTC, etam commented on tests/golem/network/concent/test_filetransfers.py
> +    def _init_uploaded_file(self, filename: str):
return type annotation plz

2018-05-25 07:15 UTC, etam commented on golem/task/taskkeeper.py
> +    def get_package_paths(self, task_id: str) -> typing.Optional[list]:
In type annotations don't use `list`. Use `typing.List[inner_type]`.

2018-05-25 07:15 UTC, etam commented on golem/task/taskkeeper.py
> +    def add_package_paths(self, task_id: str, package_paths: list) -> None:
In type annotations don't use `list`. Use `typing.List[inner_type]`.

2018-05-25 07:33 UTC, shadeofblue commented on tests/golem/network/concent/test_filetransfers.py
> +    def _init_uploaded_file(self, filename: str):
@etam uhm this is a test, mind you...

2018-05-25 07:46 UTC, etam approved these changes
![ok](http://i0.kym-cdn.com/photos/images/original/000/362/056/c0a.jpg)

2018-05-25 07:47 UTC, etam commented on tests/golem/network/concent/test_filetransfers.py
> +    def _init_uploaded_file(self, filename: str):
No code is not worth a type annotation.

2018-05-25 09:14 UTC, merged