Automatic requestor deposit
golemfactory/clay pull request #2774
Opened 2018-05-16 13:45 UTC by jiivan

Solves requestor part of #2761 
Provider part requires additional verification.

2018-05-16 14:01 UTC, Krigpl requested changes

2018-05-16 14:01 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        return self._sci.get_deposit_value(account_address=self._sci._address)  # noqa pylint: disable=protected-access
`sci.get_eth_address` returns the address so use that instead of `sci._address`

2018-05-16 14:01 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +    def concent_balance(self) -> int:
I don't see it being used anywhere else so either make it private or just inline below since it's quite simple anyway

2018-05-16 14:01 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        gntb_balance = self.payment_processor._gnt_available()  # noqa pylint: disable=protected-access
`_gnt_available` gives you GNT+GNTB so later when you try to call `deposit_payment` it may fail because there's not enough GNTB

2018-05-16 14:01 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        self._sci.deposit_payment(max_possible_amount)
This just sends the transaction to the network and it may take some time before it gets mined - do you care about that?
This may also throw if there isn't ETH for gas

2018-05-16 14:01 UTC, Krigpl commented on golem/client.py
> +            self.transaction_system.concent_deposit(
Shouldn't it happen only when Concent is enabled ?

2018-05-16 14:02 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        return self._sci.get_deposit_value(account_address=self._sci._address)  # noqa pylint: disable=protected-access
In general any time you feel like you need to access protected member in SCI just tell me - I'll either point you to the right direction or change the API appropriately if needed.

2018-05-16 14:29 UTC, jiivan commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +    def concent_balance(self) -> int:
It'll be used in provider deposits and to verify whether other side has sufficient deposit ( #2766 ). And there no such thing as private method in python. :)

2018-05-16 14:29 UTC, jiivan commented on golem/client.py
> +            self.transaction_system.concent_deposit(
Good point.

2018-05-17 14:13 UTC, Krigpl commented on golem/client.py
> +            min_amount, opt_amount = msg_helpers.requestor_deposit_amount(
Nit picking but I find it confusing that `requestor_deposit_amount` is coming from the `golem_messages` module

2018-05-17 14:16 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        if gntb_balance < required:
Another thing: we shouldn't end up putting too much to the deposit, not to end up in a situation when we can't cover the task from the main balance. AFAICT right now you could transfer whole balance to the deposit and basically be forced to pay from the deposit instead of the usual batchTransfer

2018-05-17 14:25 UTC, jiivan commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        if gntb_balance < required:
@Krigpl isn't it covered by fundslocker?

2018-05-18 11:10 UTC, shadeofblue commented on golem/client.py
> +            transaction_hash = self.transaction_system.concent_deposit(
is this `transaction_hash` used anywhere?

2018-05-18 11:20 UTC, shadeofblue approved these changes
seems okay

2018-05-18 13:19 UTC, Krigpl requested changes
Please wait with landing this until new GNT-GNTB conversion is done.

2018-05-18 13:19 UTC, Krigpl commented on golem/client.py
> +        if self.transaction_system and self.concent_service.enabled:
`self.transaction_system` cannot be `None` anymore (same applies to the `if` above)

2018-05-18 13:19 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        gntb_balance = self._sci.get_gntb_balance(self._sci.get_eth_address())
That doesn't account for GNTB that is locked in PaymentProcessor

2018-05-18 13:19 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        transaction_id = self._sci.deposit_payment(max_possible_amount)
just put `return` here

2018-05-21 13:57 UTC, shadeofblue commented on golem/client.py
> +            min_amount, opt_amount = msg_helpers.requestor_deposit_amount(
@Krigpl I believe it's part of the protocol so indeed, it should be included in `golem_messages`...

2018-05-21 15:13 UTC, Krigpl requested changes

2018-05-21 15:13 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +    def concent_deposit(
A test for this method would be beneficial

2018-05-21 15:13 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        return self._sci.deposit_payment(max_possible_amount)  # tx_hash
Please spawn an info log message about the amount and including the tx hash

2018-05-21 15:13 UTC, Krigpl commented on apps/core/task/coretask.py
> +    def price(self) -> int:
Since you introduce this property, can you make `FundsLocker` use it in the `gnt_lock` method?

2018-05-21 15:13 UTC, Krigpl commented on golem/client.py
> +                reserved=task.price,
This has to be total amount of locked funds from `FundsLocker`
Let's say you have 100 GNT
Then create a task for 5 GNT
You lock 5 GNT in FundsLocker
You make deposit for 20 GNT
Then you create a task for 25 GNT
You lock 25 GNT in FundsLocker (with total of 30 GNT)
You want to make deposit for 80 (100 - 20), but have only 70 (100 - 5 - 25) available, so you make deposit for 70 GNT
Total deposit is 90 GNT, your balance is 10 GNT but you have tasks for 30 GNT

Please add tests for these cases.

2018-05-23 01:32 UTC, mfranciszkiewicz commented on golem/client.py
> +            min_amount, opt_amount = msg_helpers.requestor_deposit_amount(
I'm sorry to interrupt, but `golem_messages` shouldn't try to define the protocol.

2018-05-23 09:20 UTC, Krigpl commented on golem/client.py
> +            min_amount, opt_amount = msg_helpers.requestor_deposit_amount(
Maybe we should try to clarify what `golem_messages` actually is. My thinking so far was that it just provides all the messages (so simple structs basically) + some implementation helpers (like serialization), but it doesn't provide any constants/mechanisms defined by the protocol.
But looks like it's the former. I wonder whether that was intentional or just convenient, since it's a shared module between Golem and Concent.
The thing is that if these constants get changed it requires to bump the golem-messages version, since it's not backwards compatible. And that affects non Concent users even though they shouldn't be affected because the change has nothing to do with them.

2018-05-23 11:59 UTC, Krigpl approved these changes
lgtm, just minor comments

2018-05-23 11:59 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +        gntb_balance = self._sci.get_gntb_balance(self._sci.get_eth_address())
This is the same as `gntb_balance = self._gntb_balance` but without an extra request to Geth

2018-05-23 11:59 UTC, Krigpl commented on tests/golem/test_client.py
> +import golem
Why is it needed?

2018-05-23 12:42 UTC, jiivan commented on tests/golem/test_client.py
> +import golem
Ungrouped imports lint

2018-05-23 14:28 UTC, merged