Fill WantToComputeTask.concent_enabled
golemfactory/clay pull request #2790
Opened 2018-05-18 12:15 UTC by jiivan

And log reason of CannotComputeTask

2018-05-18 13:08 UTC, Wiezzel commented on golem/task/tasksession.py
> +        if msg.concent_enabled and not self.concent_service.enabled:
Shouldn't it be `not msg.concent_enabled and self.concent_service.enabled`?

2018-05-18 13:20 UTC, jiivan commented on golem/task/tasksession.py
> +        if msg.concent_enabled and not self.concent_service.enabled:
If `Provider` asks for `Concent`, but `Requestor` cannot comply he responds with `ConcentDisabled`.

2018-05-18 15:16 UTC, Wiezzel requested changes
Requestor with Concent, provider without Concent:
- Works fine (tasks get computed). :+1: 

Requestor without Concent, provider with Concent: 
- Provider displays "request rejected: ConcentDisabled" in logs. :+1: 
- Provider does not start computing. :+1: 
- Subtask is marked as "starting" and provider is assigned to it. :-1:

2018-05-23 07:46 UTC, Wiezzel approved these changes
Very nice.

2018-05-23 07:47 UTC, Wiezzel commented
`Golem-Messages 2.9.1` is not yet published.

2018-05-23 13:48 UTC, merged