New command: rpc provider state
golemfactory/clay pull request #2817
Opened 2018-05-25 13:40 UTC by etam

resolves #2704

2018-05-28 10:21 UTC, badb commented
@mdtanrikulu Please check this PR, how this changes will affect footer implementation?

2018-05-28 10:55 UTC, tworec requested changes
I have some questions...

2018-05-28 10:55 UTC, tworec commented on golem/client.py
> +    def get_provider_status(self):
nice to have return type

2018-05-28 10:55 UTC, tworec commented on golem/client.py
> +                'subtask': subtask_progress.__dict__,
do we need those details?

2018-05-28 10:55 UTC, tworec commented on golem/manager/nodestatesnapshot.py
> +class ComputingSubtaskStateSnapshot:
why do we need/want to supply all these details with state?

2018-05-28 10:55 UTC, tworec commented on golem/task/taskkeeper.py
> +        :return: either None if there are no tasks
this doc is malformed

2018-05-28 10:55 UTC, tworec commented on golem/task/taskcomputer.py
> +    def __init__(self, task_server: 'TaskServer', use_docker_manager=True) \
👍 for removing unnecessary `node_name` :)

2018-05-28 10:55 UTC, tworec commented on golemcli.py
> +    Account, incomes, payments, debug, provider_status
what is it for?

2018-05-28 11:05 UTC, etam commented on golem/client.py
> +                'subtask': subtask_progress.__dict__,
I don't know what exactly do we need. I just put there everything that seems reasonable. Keep in mind, that our GUI might not be the only RPC client interested in this data.

2018-05-28 11:07 UTC, etam commented on golemcli.py
> +    Account, incomes, payments, debug, provider_status
As the comment says, it was supposed to prevent 'unused' warnings. But since we also have proper comments for linters and stuff, probably this could be removed. If it is, I think it should go in a separate PR.

2018-05-28 13:13 UTC, tworec commented on golem/client.py
> +                'subtask': subtask_progress.__dict__,
this is not best practice. I'd rather provide minimal set of data, not maximal one. If anyone in future will need something (s)he would simply enrich this.

2018-05-28 13:17 UTC, tworec commented on golemcli.py
> +    Account, incomes, payments, debug, provider_status
i think you can remove this _preventive_ code, but need to add `, unused-import` at line 14

2018-05-28 13:18 UTC, tworec commented on golemcli.py
> +    Account, incomes, payments, debug, provider_status
this is not a blocker for me, feel free to ignore this comment

2018-05-28 13:24 UTC, etam commented on golem/client.py
> +                'subtask': subtask_progress.__dict__,
What's the minimal set of data, then? @badb @mdtanrikulu ?

2018-05-28 13:25 UTC, etam commented on golem/manager/nodestatesnapshot.py
> +class ComputingSubtaskStateSnapshot:
I don't understand your question.

2018-05-28 13:47 UTC, etam commented on golem/task/taskkeeper.py
> +        :return: either None if there are no tasks
How about `None if there are no tasks that this node may want to compute` (just removing 'either' from the beginning)?

2018-05-28 16:26 UTC, tworec commented on golem/task/taskkeeper.py
> +        :return: either None if there are no tasks
ok

2018-05-28 16:26 UTC, tworec commented on golemcli.py
> +    Account, incomes, payments, debug, provider_status
I've done it here https://github.com/golemfactory/golem/pull/2734/commits/57c36cb8410f84581757408352f1376e6d20255e

2018-05-28 16:27 UTC, tworec commented on golem/manager/nodestatesnapshot.py
> +class ComputingSubtaskStateSnapshot:
it is same Q as above regarding details

2018-05-29 07:55 UTC, etam commented on golem/client.py
> +    def get_provider_status(self):
fixed

2018-05-29 07:55 UTC, etam commented on golem/task/taskkeeper.py
> +        :return: either None if there are no tasks
fixed

2018-05-29 08:04 UTC, tworec commented on golem/client.py
> +    def get_provider_status(self):
👍

2018-05-29 08:44 UTC, tworec approved these changes
LGTM (stylistics comments only)

2018-05-29 08:44 UTC, tworec commented on golem/client.py
> +                'task_id': waiting_for_task,
the `waiting_for_task ` var holds `None` or `task_id`, hence name you've proposed for it is misleading. I know `task_computer` uses this name, but it is also misleading. Please clarify that by changing to eg. `task_id_waited_for'

2018-05-29 08:44 UTC, tworec commented on golem/interface/client/provider.py
> +def provider_status():
I would do a `provider` class/group with the `status` method/command. Than cli invocation would have form:
```
golemcli provider status
```

2018-05-29 08:44 UTC, tworec commented on golem/client.py
> +        # golem is starting
those comments are not necessary, as you provide string result saying the same

2018-05-29 08:48 UTC, tworec commented
One general comment: please do not use force push after review was made, because it hinder next review phase. Rather add new commits and push them

2018-05-29 09:42 UTC, etam commented on golem/interface/client/provider.py
> +def provider_status():
As long as there are no other `golemcli provider ...` commands, I see no reason to do this.

2018-05-29 09:46 UTC, etam commented on golem/client.py
> +        # golem is starting
Yes, but they make sections of the code more visually separated.

2018-05-29 10:10 UTC, etam commented on golem/client.py
> +                'task_id': waiting_for_task,
done

2018-05-29 14:08 UTC, tworec commented on golem/interface/client/provider.py
> +def provider_status():
to be consistent with other commands

2018-07-13 13:21 UTC, etam commented
RPC change: new method `provider.status`, takes no arguments

possible return values:

```python
{
    'status': 'golem is starting'
}
```
```python
{
    'status': 'computing',
    'subtask': ComputingSubtaskStateSnapshot as dict
}
```
```python
{
    'status': 'waiting for task',
    'task_id_waited_for': str(task_id),
}
```
```python
{
    'status': 'not accepting tasks',
}
```
```python
{
    'status': 'idle',
}
```

2018-07-13 14:59 UTC, mdtanrikulu commented
@badb I'm unable to test it. 

Whenever I try to run task from any other instance I have following error on provider node;
```
INFO     [golem.task.taskcomputer            ] Starting computation of subtask '3089a422-86a5-11e8-a5cb-ec276b3f4294' (task: '2803ddfe-86a5-11e8-a44b-ec276b3f4294', deadline: 1531526453.387266, docker images: [{'image_id': None, 'repository': 'golemfactory/blender', 'tag': '1.4'}])
WARNING  [golem.docker.task_thread           ] Task stderr:
/usr/bin/python: can't open file '/golem/work/job.py': [Errno 2] No such file or directory
```

2018-08-02 16:21 UTC, mdtanrikulu commented on golem/client.py
> +                'subtask': subtask_progress.__dict__,
None of them are necessary in `subtask_progress.__dict__` for now, but good to see what we have as information about computed task. We can consider to use at least some of them to show to providers for the future.

2018-08-02 16:26 UTC, mdtanrikulu commented
Some time ago, I implemented the same logic for `get_host_state` function here at #2788 instead of creating another RPC, maybe we can consider to move this function into that, so we can ask for the provider stats and status at the same time?

2018-08-14 15:10 UTC, etam commented
> Some time ago, I implemented the same logic for get_host_state function here at #2788 instead of creating another RPC, maybe we can consider to move this function into that, so we can ask for the provider stats and status at the same time?

Done

2018-08-20 14:07 UTC, mdtanrikulu approved these changes

2018-08-20 14:23 UTC, merged