Provider deposit for additional verification in Concent
golemfactory/clay pull request #2824
Opened 2018-05-29 14:14 UTC by jiivan

2018-05-29 14:23 UTC, shadeofblue commented on golem/task/tasksession.py
> +                    required_confs=3,
@jiivan shouldn't the `3` be some kind of a `golem.core.variables` setting? ... or something?

2018-05-29 14:24 UTC, shadeofblue approved these changes
dla mnie bomba, ale niech jeszcze @Krigpl spojrzy

2018-05-29 14:28 UTC, Krigpl requested changes

2018-05-29 14:28 UTC, Krigpl commented on golem/task/tasksession.py
> +            # pylint: disable=protected-access
Please don't do that. There's a reason for it.
Make `concent_deposit` take a callback instead.

2018-05-30 11:17 UTC, Krigpl requested changes

2018-05-30 11:17 UTC, Krigpl commented on golem/task/tasksession.py
> +            def transaction_receipt(receipt):
Since the goal is just to call `ask_for_verification` after there's enough GNT deposited I'd say you could move this one inside `concent_deposit` and hide the receipt check there.
In other words just invoke callback immediately if there's enough GNT otherwise use `on_transaction_confirmed`. And then you don't need to return `tx_hash` from `concent_deposit` as well.

The idea is that `tasksession` shouldn't really care about any blockchain implementation details, there belong in `EthereumTransactionSystem` better.

2018-05-30 12:22 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
>              max_possible_amount,
You need to divide this amount by `denoms.ether`

2018-06-07 08:52 UTC, jiivan commented on golem/transactions/ethereum/ethereumtransactionsystem.py
>              max_possible_amount,
Are you sure? Looks like it's an int value in golem_sci:
https://github.com/golemfactory/golem-smart-contracts-interface/blob/e53673630f107c3f03c185dc729a971eff71a40e/golem_sci/implementation.py#L536-L537

2018-06-07 09:05 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
>              max_possible_amount,
Yeah, this is the log message and it easier to read 1 GNT instead of 1000000000000000000

2018-06-07 09:07 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
>              max_possible_amount,
But yeah. you don't `need to`, but it's way better

2018-06-07 09:12 UTC, jiivan commented on golem/task/tasksession.py
> +            def transaction_receipt(receipt):
@Krigpl done.

2018-06-07 09:18 UTC, jiivan commented on golem/transactions/ethereum/ethereumtransactionsystem.py
>              max_possible_amount,
gotcha

2018-06-07 09:24 UTC, Krigpl requested changes
lgtm, just a bit of clean up

2018-06-07 09:24 UTC, Krigpl commented on golem/task/tasksession.py
> +            if thash is None:
You don't need that anymore, right?

2018-06-07 09:24 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +            cb=None) -> Optional[str]:
Fix return type

2018-06-07 09:24 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +                raise exceptions.TransactionFailed(receipt)
`on_transaction_confirmed` callbacks should not throw - there's no error handling for them. Just log the message (even with `critical` severity).

2018-06-07 09:53 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +            cb(receipt=receipt)
Why do you pass the receipt if it's not needed for anything ?

2018-06-07 09:57 UTC, jiivan commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +            cb(receipt=receipt)
It's needed to know whether transaction succeeded or not. See https://github.com/golemfactory/golem/pull/2824/files#diff-5f37de48e0f430b75ff1a8e5758aa86c

2018-06-07 10:02 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +            cb(receipt=receipt)
It's a test. I don't see production code using the receipt which is a code smell. Depending on what the test checks you can either assume the transaction was successful or check the deposit amount whether it increased this way knowing if it was successful.

2018-06-07 10:18 UTC, jiivan commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +            cb(receipt=receipt)
Done

2018-06-07 11:11 UTC, Krigpl approved these changes
![obama_approves](https://user-images.githubusercontent.com/3904252/41096246-4804bce4-6a54-11e8-81f3-e1f241790647.jpeg)

2018-06-07 11:48 UTC, merged