PoC firejail
golemfactory/clay pull request #2848
Opened 2018-06-05 09:21 UTC by RDProjekt

2018-06-06 14:14 UTC, Elfoniok requested changes

2018-06-06 14:14 UTC, Elfoniok commented on apps/registered_envs.ini
> +envs=apps.blender.dockerenvironment.blenderenvironment.BlenderEnvironment();
So provider need to modify this manually?

2018-06-06 14:14 UTC, Elfoniok commented on apps/blender/firejailenvironment/task_thread.py
> +            memory_limit_in_bytes = self.memory_limit * 1024
this can be double and firejail doesn't  support it

2018-06-06 14:14 UTC, Elfoniok commented on golem/environments/environmentsmanager.py
> +        envs = (e for e in self.environments_for_tasks.get(task_type, [])
why no requirements here? What are purpose of it then? Could you provide example?

2018-06-06 14:18 UTC, Elfoniok commented on golem/environments/environmentsmanager.py
> +        envs = (e for e in self.environments_for_tasks.get(task_type, [])
Shouldn't requirements from task definition be passed here instead of empty list?

2018-06-06 14:22 UTC, Elfoniok commented on golem/task/localcomputer.py
> +                .get_environment_for_task(ctd['task_type'], [])
empty requirements list?

2018-06-06 15:04 UTC, RDProjekt commented on golem/environments/environmentsmanager.py
> +        envs = (e for e in self.environments_for_tasks.get(task_type, [])
this is get() on a map, so empty list is the default value if no environments were reqistered for this type. Requirements are checked 3 lines below.

2018-06-07 11:49 UTC, RDProjekt commented on apps/registered_envs.ini
> +envs=apps.blender.dockerenvironment.blenderenvironment.BlenderEnvironment();
Yes, if the Provider wishes to prefer other environments, that list has to be modified manually. It does not affect tasks which have specific requirements not satisfied by this environment though.

2018-06-07 13:05 UTC, Elfoniok commented on apps/core/task/coretask.py
> +            requirements=task_definition.requirements,
So requirements are not passed in message?

2018-06-07 13:31 UTC, Elfoniok commented on golem/task/localcomputer.py
> +        self.environment = environment
Whats the point of passing this? Shouldn't  environments manager be used for getting environment for specific ctd?

2018-06-07 13:31 UTC, Elfoniok commented on golem/task/localcomputer.py
> +        environment = self.environment
Once again why this if we are using manager?

2018-06-07 13:34 UTC, Elfoniok commented on golem/task/localcomputer.py
> +                                      environment=environment,
why not environments manager?

2018-06-07 13:53 UTC, Elfoniok commented on golem/task/taskserver.py
> +            use_docker_manager=use_docker_manager)
What is the point of using docker manager, looks like Task Computer should be agnostic if it can use different environments, and some of them will not use docker at all.

2018-06-07 15:28 UTC, RDProjekt commented on golem/task/localcomputer.py
> +                .get_environment_for_task(ctd['task_type'], [])
As in the TODO - it's actually not clear if requirements should be passed here.

The problem is that LocalComputer is used for local computation, including verification and creating reference data. For that reason it should be able to compute given tasks.

So the question is - should it be possible to create a task that requestor cannot compute itself, e.g. require CUDA rendering engine when the requestor does not have it? We've chosen 'yes' as the answer because it makes golem way more powerful for end-users. But that means that LocalComputer should ignore requirements and select any environment for the task - at least one such environment must be present.

2018-06-07 15:34 UTC, RDProjekt commented on apps/core/task/coretask.py
> +            requirements=task_definition.requirements,
"message" as in "ctd"? No - requirements are added to TaskHeader to that providers have them at hand from the beginning and so can decide if they support the task before possibly asking for it (see TaskHeaderKeeper.checkEnvironment(header))

2018-06-07 16:46 UTC, RDProjekt commented on golem/task/taskserver.py
> +            use_docker_manager=use_docker_manager)
In general DockerManager is still required because some (most) environments require working docker setup. But I do see your point that 1. docker manager might not be required if all configured environments are not docker-based, 2. maybe TaskComputer is not the best place to have it.

Moving it out of TaskComputer would require decision on "move to where". There is no better suited place right now, so we would have to create a whole new mechanism of setting up executables based on golem's configuration.

2018-06-07 16:46 UTC, RDProjekt commented on golem/task/localcomputer.py
> +        self.environment = environment
When computation is requested straight from a task (e.g. in luxrender __generate_final_file ) there is no environments_manager reference at hand. Passing explicit environment is a workaround, as more robust solution would require quite a lot of debate and refactoring:

* environments_manager must be globally referencable, manually passing it from one entity to another doesn't work in that case.
* discussion what exactly are tasks and what should they carry - e.g. in blender verifier calculacting verification scores is done by explicitly running a docker job. But in luxrender merging flm results is done by running an artifical (created on spot, not received from external requestor) ctd with different script_src - that way it runs in the same docker as standard luxrender task.
* should tasks locally be computed the same way as global ones (i.e. including requirements) or do we allow local computation to differ. If they can differ - should local computation environment be hardcoded, configured by a separate config, or reuse environments config?

2018-06-07 16:47 UTC, RDProjekt commented on golem/task/localcomputer.py
> +        environment = self.environment
see reply above

2018-06-07 16:47 UTC, RDProjekt commented on golem/task/localcomputer.py
> +                                      environment=environment,
see reply above

2018-06-08 07:21 UTC, Elfoniok commented on golem/task/localcomputer.py
> +                .get_environment_for_task(ctd['task_type'], [])
Ok, i suspected that but this should be noted clearly.

2018-06-08 07:21 UTC, Elfoniok commented on golem/environments/environmentsmanager.py
> +        envs = (e for e in self.environments_for_tasks.get(task_type, [])
Right, thanks!

2018-06-08 07:22 UTC, Elfoniok commented on apps/registered_envs.ini
> +envs=apps.blender.dockerenvironment.blenderenvironment.BlenderEnvironment();
Ok

2018-06-08 07:55 UTC, Elfoniok commented on apps/core/task/coretask.py
> +            requirements=task_definition.requirements,
No i was asking about Tasks Message. But its all right.

2018-06-08 07:58 UTC, Elfoniok commented on golem/task/localcomputer.py
> +        self.environment = environment
Ok this is also important to note.

2018-06-08 08:00 UTC, Elfoniok commented on golem/task/taskserver.py
> +            use_docker_manager=use_docker_manager)
Ok

2018-06-08 08:02 UTC, Elfoniok commented
I will accept for slow test to run.

2018-06-08 08:03 UTC, Elfoniok approved these changes

2018-06-08 08:39 UTC, Elfoniok requested changes
First of all there are some lint errors to be fixed.

Second, this changes shouldn't break other platforms. Ignoring errors on removing files, is not a good solution. Files are not deleted and removing them raise errors because they are probably open. This wreak havoc on Mac OS with very low file descriptors.

Third there are 2 failing tests on Windows.

2018-06-12 08:29 UTC, Elfoniok approved these changes

2018-06-12 08:34 UTC, Elfoniok commented
Two offending test are due to docker images not being available on MacOs and Windows buildbots. Since DummyTaskEnvironment inherits from DockerEnvironment it is reasonable to not support those if docker images are not available, but this also force us to ci_skip this tests.

2018-06-12 09:11 UTC, RDProjekt commented
Actually we want to try mocking part of DockerEnvironment instead of using ci_skip. Failing tests do not really need Docker to run, and both of them are testing fairly important pieces of functionality, so it would be good to leave them running.

2018-06-13 08:25 UTC, Elfoniok commented
![borat](https://user-images.githubusercontent.com/662433/41339090-4952f1de-6ef4-11e8-8a84-d2ef3681256d.jpg)

2018-06-18 10:11 UTC, merged