Fix shutting down golem monitor
golemfactory/clay pull request #2852
Opened 2018-06-06 09:13 UTC by Elfoniok

2018-06-06 12:27 UTC, Krigpl commented on golem/monitor/monitor.py
> +                    msg = None
I think it makes sense to put `else time.sleep(1)` or something similar here, otherwise this loop may become wasteful active waiting loop (when `msg` is not `None` but `timeout` is not reached yet

2018-06-06 12:48 UTC, Elfoniok commented on golem/monitor/monitor.py
> +                    msg = None
Yeas actually i was thinking the same, but somehow hesitated

2018-06-06 12:56 UTC, tworec requested changes

2018-06-06 12:56 UTC, tworec commented on tests/golem/monitor/test_monitor.py
> +                time.sleep(0.05)
why do we need increasing this?

2018-06-06 13:16 UTC, jiivan reviewed
I propose a different algorithm.

2018-06-06 13:16 UTC, jiivan commented on golem/monitor/monitor.py
> +                    msg = None
I think it's proper to use `.get_nowait()`. My proposition:
```python
last_sent = 0
while not event.isSet():
    if time.time() - last_sent < self.monitor_sender_thread_timeout:
        time.sleep(veryshort)
        continue
    try:
        msg = self.queue.get_nowait()
    except queue.Empty:
        msg = self.node_info
    last_sent = time.time()
    self.sender.send(msg)
```

2018-06-06 13:50 UTC, Krigpl commented on golem/monitor/monitor.py
> +                    msg = None
@jiivan Your way changes the logic to send at most 1 message per time interval which wasn't the case before. I dunno what the requirements are for the monitor but I imagine there might be cases where we end up sending a bunch of messages at the same moment.

Another way I see is to just put `None` in the queue in the `join` method and break the above loop if we retrieve it from the queue (so 3 lines change).

2018-06-06 13:55 UTC, jiivan commented on golem/monitor/monitor.py
> +                    msg = None
@Krigpl AFAIK it's the intention.

2018-06-06 13:59 UTC, Elfoniok commented
What about ping messages?

2018-06-06 13:59 UTC, Elfoniok commented on tests/golem/monitor/test_monitor.py
> +                time.sleep(0.05)
i think because of time needed for additional logic in comparison

2018-06-07 11:37 UTC, Krigpl approved these changes
![verynicegreatsuccess](https://user-images.githubusercontent.com/3904252/41097340-dc5c93e6-6a57-11e8-97a3-7dc10dfca8b1.jpg)

2018-06-07 11:37 UTC, Krigpl commented on golem/monitor/monitor.py
> +                    continue
If you use `break` here you can remove `self.stop_request` altogether

2018-06-07 11:38 UTC, Elfoniok commented on golem/monitor/monitor.py
> +                    continue
I though about it but, i cant be sure that none is set only on exit, who nows what gets in here.

2018-06-07 11:53 UTC, jiivan commented on golem/monitor/monitor.py
> +                if not msg:
Better use `if msg is None:`, because many objects can have False boolean value. As you said it can be a future bug or feature :)

2018-06-07 12:54 UTC, jiivan approved these changes

2018-06-07 12:57 UTC, tworec approved these changes

2018-06-07 13:40 UTC, mfranciszkiewicz approved these changes

2018-06-07 14:07 UTC, merged