TaskManager.task_needs_computation
golemfactory/clay pull request #2925
Opened 2018-06-25 10:19 UTC by Wiezzel

Refactored nested function into a public method. Used it in MaskUpdateService instead of Task.needs_computation(). This will prevent updating masks for timed-out tasks.

2018-06-25 12:21 UTC, tworec requested changes

2018-06-25 12:21 UTC, tworec commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
@mfranciszkiewicz asked to put node info into logs. It helps debugging

2018-06-25 13:00 UTC, Wiezzel commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
I can add another logging command in `get_next_subtask` but not here.

2018-06-25 13:06 UTC, Wiezzel commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
Ok, there you go.

2018-06-26 10:17 UTC, tworec requested changes

2018-06-26 10:17 UTC, tworec commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
ok, but now task_id is redundantly twice...

2018-06-26 10:24 UTC, Wiezzel commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
Better now?

2018-06-26 11:13 UTC, tworec commented
![selfie-1](https://i.imgur.com/g1TB7ms.gif)

2018-06-26 11:13 UTC, tworec approved these changes

2018-06-27 08:35 UTC, jiivan commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
Please use logging function parameters for string format arguments.

https://gist.github.com/jiivan/eedb505574ccb2503af48fa2e3043036

2018-06-27 08:46 UTC, Wiezzel commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
@jiivan Actually, you didn't include the f-string method in your logtest. I did and the difference for string argument is negligible:
```
#'message'
               correct_logging: 1069.55ms
             incorrect_logging: 1213.96ms
    newstyle_incorrect_logging: 1250.48ms
         format_string_logging: 1089.07ms
```
And using f-strings is more readable than using `%s`.

2018-06-27 09:00 UTC, tworec commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
interesting comparison, I think you can post it on #developers channel on our rocket. I also like f'string readability but thought that it is much slower than 'correct logging'

2018-06-27 09:01 UTC, tworec commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
@Wiezzel create PR for @jiivan code with f'string ;)

2018-06-27 09:37 UTC, jiivan commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
@Wiezzel That's interesting, I didn't know about that. Maybe that's why linter didn't complain about f string method. Readability is subjective. I'll leave it up to you then.

2018-06-27 12:32 UTC, tworec commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
we can do a poll inside our team for readablity of f'strings and other string formatting methods !

2018-06-27 12:42 UTC, Wiezzel commented on golem/task/taskmanager.py
> +            logger.info(f'task is not active: {task_id}')
I will leave it as it is. But we surely need some explicit, team-wide coding standards.

2018-06-27 13:32 UTC, merged