Verificator refactor
golemfactory/clay pull request #2926
Opened 2018-06-25 10:39 UTC by Elfoniok

2018-06-26 10:27 UTC, etam commented
It would be easier if you wrote in advance that this is related to https://github.com/golemfactory/golem-verificator/pull/34

2018-06-26 10:42 UTC, etam requested changes

2018-06-26 10:42 UTC, etam commented on apps/blender/blender_reference_generator.py
> +import math
Not a single type annotation in this file :(

2018-06-26 10:42 UTC, etam commented on apps/blender/blender_reference_generator.py
> +import numpy
Second point of https://www.python.org/dev/peps/pep-0008/#imports

2018-06-26 10:42 UTC, etam commented on apps/blender/verification_queue.py
> +from golem.task.localcomputer import ComputerAdapter
Second point of https://www.python.org/dev/peps/pep-0008/#imports

2018-06-26 10:42 UTC, etam commented on apps/blender/verification_queue.py
> +            self._process_queue()
That's ugly. It would be better if `_run` would return `bool` and `_process_queue` would loop based on that.

2018-06-26 10:42 UTC, etam commented on apps/dummy/task/verifier.py
> +    def __init__(self, callback, verification_data=None):
Type annotations? They were here before.

2018-06-26 10:42 UTC, etam commented on apps/dummy/task/verifier.py
> +                result_data = f.read()
If we only want the size of file contents, there's no need to waste memory for that. Use `os.stat('path').st_size`

2018-06-26 10:42 UTC, etam commented on apps/dummy/task/verifier.py
> +                result_data = f.read()
Oh, `result_data` is used below outside of this loop. So it uses the value of the last result. Is that correct?

2018-06-26 11:05 UTC, mfranciszkiewicz commented on apps/blender/verification_queue.py
> +            self._process_queue()
`_process_queue` should be called only if we cannot start the verification process or the verification process has finished (via `callback`), not when `_run` returns.

2018-06-29 08:07 UTC, Elfoniok commented on apps/blender/blender_reference_generator.py
> +import numpy
Done

2018-06-29 08:37 UTC, Elfoniok commented on apps/blender/blender_reference_generator.py
> +import math
Done

2018-06-29 08:38 UTC, Elfoniok commented on apps/blender/verification_queue.py
> +from golem.task.localcomputer import ComputerAdapter
Done

2018-06-29 08:39 UTC, Elfoniok commented on apps/dummy/task/verifier.py
> +    def __init__(self, callback, verification_data=None):
Done

2018-06-29 08:48 UTC, Elfoniok commented on apps/dummy/task/verifier.py
> +                result_data = f.read()
Done

2018-06-29 09:14 UTC, etam requested changes
Tuple of what? List of what? Dict of what? Please! That's **the most** important part.
And don't forget about return types.

2018-06-29 14:12 UTC, etam commented on apps/blender/blender_reference_generator.py
> +        self.rendered_crops_results: Dict[int, [[str], float, CropContext]] = {}
`Dict[int, Union[List[str], float, CropContext]]`? Or maybe just `Dict[int, Any]`?

2018-06-29 14:15 UTC, etam commented on apps/blender/blender_reference_generator.py
> +        return [split_min, split_max]
minor: it would make more sense to return as a tuple

2018-07-02 08:25 UTC, Elfoniok commented on apps/blender/blender_reference_generator.py
> +        return [split_min, split_max]
No, list is good for now.

2018-07-02 09:56 UTC, etam commented on apps/blender/blender_reference_generator.py
> +        verify_ctx = CropContext({'paths': crops_path, 'position': crops_info},
That's the weirdest way to pass arguments I've ever seen. Why not just drop those dicts and use `path=crop_path, position=crops_info, ...`?

2018-07-02 10:16 UTC, etam approved these changes
Would be prettier if CropContext was a data class, but well, we're not there yet.

2018-07-02 10:17 UTC, Elfoniok commented
I agree hopefully we will be there soon.

2018-07-02 11:36 UTC, merged