hardware config change detection fix
golemfactory/clay pull request #2937
Opened 2018-06-28 13:11 UTC by tworec

2018-06-28 14:04 UTC, etam commented
Are you sure you want to merge it to b0.16.1?

2018-06-28 14:04 UTC, etam commented on golem/core/hardware.py
> +def cpu_cores_available() -> List:
List of what?

2018-06-28 14:13 UTC, etam requested changes
I like type annotations :)

2018-06-28 14:13 UTC, etam commented on golem/core/hardware.py
> +    return int(max(int(virtual_memory().total * 0.75) / 1024, MIN_MEMORY_SIZE))
Maybe instead of adding `int` around `max` change
`int(virtual_memory().total * 0.75) / 1024`
to
`int(virtual_memory().total * 0.75 / 1024)`
?

2018-06-28 14:13 UTC, etam commented on golem/core/hardware.py
> +def cpu_cores_available() -> List:
List of what?

2018-06-28 14:13 UTC, etam commented on golem/core/hardware.py
>      :return int: 3/4 of total available memory
While at it, you could add that it's in kilobytes.

2018-06-28 14:13 UTC, etam commented on tests/golem/core/test_hardware_presets.py
> +        # than
then

2018-06-28 14:13 UTC, etam commented on golem/core/hardware.py
> +    def caps(cls) -> dict:
`-> Dict[str, int]`?

2018-06-28 14:13 UTC, etam commented on golem/core/hardware.py
> +            -> Tuple[str, dict]:
`-> Tuple[str, Dict[str, int]]`?

2018-06-28 14:36 UTC, badb commented
@tworec Can you please make this PR to develop?

2018-06-28 16:03 UTC, tworec commented on golem/core/hardware.py
> +def cpu_cores_available() -> List:
👍

2018-06-28 16:03 UTC, tworec commented on golem/core/hardware.py
> +    return int(max(int(virtual_memory().total * 0.75) / 1024, MIN_MEMORY_SIZE))
whaa? we need to assure that it is not below MIN, how do your code achieve this?

2018-06-28 16:03 UTC, tworec commented on golem/core/hardware.py
> +    def caps(cls) -> dict:
👍

2018-06-28 16:03 UTC, tworec commented on golem/core/hardware.py
> +            -> Tuple[str, dict]:
👍

2018-06-28 16:03 UTC, tworec commented on tests/golem/core/test_hardware_presets.py
> +        # than
😄

2018-06-28 16:04 UTC, tworec commented on golem/core/hardware.py
>      :return int: 3/4 of total available memory
👍

2018-06-29 08:52 UTC, etam commented on golem/core/hardware.py
> +    return int(max(int(virtual_memory().total * 0.75) / 1024, MIN_MEMORY_SIZE))
whaa? I don't understand what are you talking about.

Lets split this one-liner a bit:

Before your changes:
```python
actual_virtual_memory_in_kb = int(virtual_memory().total * 0.75) / 1024
result = max(actual_virtual_memory_in_kb, MIN_MEMORY_SIZE)
return result
```
MIN_MEMORY_SIZE is int.

The problem here is that `actual_virtual_memory_in_kb` is a float, not int. So `result` also might be float.

What you're proposing is changing `return result` to `return int(result)`.

I propose changing calculation of `actual_virtual_memory_in_kb` so it's int instead of float.

2018-06-29 14:57 UTC, tworec commented on golem/core/hardware.py
> +    return int(max(int(virtual_memory().total * 0.75) / 1024, MIN_MEMORY_SIZE))
@etam, I'm totally sorry - it was my misunderstanding as of y-day. I didn't notice double `int(` constructor

2018-06-29 15:41 UTC, tworec commented on golem/core/hardware.py
> +    return int(max(int(virtual_memory().total * 0.75) / 1024, MIN_MEMORY_SIZE))
done

2018-07-02 07:39 UTC, etam approved these changes
![ok](https://user-images.githubusercontent.com/220752/42151227-91e5afbc-7ddc-11e8-9629-1209147d2720.gif)

2018-07-02 15:56 UTC, merged