[Concent] UC5 / Force Payment - react to  ForcePaymentCommitted #2195
golemfactory/clay pull request #2967
Opened 2018-07-04 15:13 UTC by jiivan

fixes: #2195

2018-07-09 06:43 UTC, shadeofblue commented on golem/network/concent/received_handler.py
> +        # There is no mechanism to cancel started payment.
@jiivan you mean, there's no way to abort an already-started transaction, right? or do you mean that we have no way to tell the requestor node not to send a payment that's in the waiting period?

2018-07-09 07:16 UTC, shadeofblue commented on golem/network/concent/received_handler.py
> +            incomes_keeper.update_forced(
hmm... shouldn't we somehow take the `amount_paid` and `amount_pending` into consideration here? ... and, e.g., maybe only update those incomes for which the sum of expected incomes is lower than `amount_paid`? ...

2018-07-20 15:33 UTC, Krigpl commented on golem/transactions/ethereum/ethereumincomeskeeper.py
> +                cb=self._on_forced_payment,
Missing closing bracket

2018-07-20 15:33 UTC, Krigpl commented on golem/transactions/incomeskeeper.py
> +    def received_forced_payment(self, *args, **kwargs):
Don't use `args` and `kwargs` here, they are not required and greatly reduce legibility.

2018-07-20 15:33 UTC, Krigpl commented on golem/transactions/incomeskeeper.py
> +            if amount_left < e.value:
So, if provider is expecting 3 payments 1 GNT each and will receive 1.5 GNT from the requestor and then 1.5 GNT from Concent, one of the payments will still not be marked as done.

2018-07-24 14:31 UTC, Krigpl requested changes

2018-07-24 14:31 UTC, Krigpl commented on golem/network/concent/received_handler.py
> +        payments = Payment.select().where(
Remove it, it will be taken care of when blockchain event is detected (also this `select` is quite incorrect).

2018-07-24 14:31 UTC, Krigpl commented on tests/golem/transactions/test_incomeskeeper.py
> +        kwargs = dict((str(x), x**2) for x in range(10))
What is this supposed to be ?

2018-07-26 15:18 UTC, jiivan commented on golem/transactions/incomeskeeper.py
> +    def received_forced_payment(self, *args, **kwargs):
IMO it's perfect place for `*args, **kwargs`. It clearly states that this method is just pass-through for `received_batch_transfer` and it doesn't modify arguments. Stating arguments explicitly here would reduce legibility as a reader would have to check whether all arguments are passed unchanged.

2018-07-26 15:42 UTC, Krigpl requested changes

2018-07-26 15:42 UTC, Krigpl commented on golem/transactions/incomeskeeper.py
> +    def received_forced_payment(self, *args, **kwargs):
You're doing `kwargs.get('sender', None)` below which is completely unnecessary since `sender` will always be present in the arguments and that would be obvious if the arguments would be listed explicitly. Otherwise it raises questions like "when `sender` is not in the args" with the answer "never". This is the lack of legibility I'm talking about.

2018-07-26 15:42 UTC, Krigpl commented on golem/transactions/incomeskeeper.py
> +            if e.value_expected <= 0:
There's no way it's gonna be negative.

2018-07-30 13:58 UTC, Krigpl reviewed
The migration thing would be great to have, because we may start showing it in the UI and for old tasks it would show 0.

2018-07-30 13:58 UTC, Krigpl commented on golem/database/schemas/017_schema.py
> +        value_received=model.HexIntegerField(default=0),
`value_received` should be equal to `value` for confirmed incomes (those with transaction hash set). Is it possible to make it happen in this migration?

2018-07-30 13:58 UTC, Krigpl commented on golem/transactions/ethereum/ethereumtransactionsystem.py
> +                    sender=event.sender,
The field is `requestor`, not `sender`

2018-08-13 12:57 UTC, Krigpl commented on golem/ethereum/incomeskeeper.py
> +        dispatcher.send(
This has been removed in #3165

2018-08-13 12:57 UTC, Krigpl commented on golem/network/concent/received_handler.py
> +        getattr(self, handler_name)(msg)
This magic isn't needed here, the following is imo more readable and more importantly greppable.
```
if msg.recipient_type == requestor:
  self.on_force_payment_committed_for_requestor
else:
  on_force_payment_committed_for_provider
```

2018-08-13 12:57 UTC, Krigpl commented on tests/golem/network/concent/test_received_handler.py
> +        self.client.transaction_system.incomes_keeper = IncomesKeeper()
Why is it needed?

2018-08-13 13:43 UTC, jiivan commented on golem/ethereum/incomeskeeper.py
> +        dispatcher.send(
Good catch! Thanks.

2018-08-13 13:44 UTC, jiivan commented on golem/network/concent/received_handler.py
> +        getattr(self, handler_name)(msg)
No magic here, but greppable argument sounds valid to me.

2018-08-13 13:45 UTC, jiivan commented on tests/golem/network/concent/test_received_handler.py
> +        self.client.transaction_system.incomes_keeper = IncomesKeeper()
Good catch, it was an artefact from when handler interacted with IncomesKeeper.

2018-08-13 15:57 UTC, Krigpl approved these changes
![rickandmorty_yes](https://user-images.githubusercontent.com/3904252/44043096-44cd944e-9f22-11e8-8691-f1d56c00641e.gif)

2018-08-13 18:40 UTC, merged