[WIP] Modified task cost & fee information
golemfactory/clay pull request #3032
Opened 2018-07-12 16:14 UTC by Wiezzel

* Changed `get_total_payment_for_subtasks`:
  - return `(None, None)` instead of `(0, 0)` as empty result
  - include 'sent' payments, not only 'confirmed'
  - return Nones if not all tasks are sent (no partial sums)
* Added `estimated_cost` & `estimated_fee` to `TaskStatus`

2018-07-12 16:15 UTC, Wiezzel commented
The functionality has been discussed with @jamuszyn.
I am aware that some tests are failing therefore [WIP].

2018-07-12 17:12 UTC, mdtanrikulu requested changes
If you can return fee & cost as string or divided by eth denom, that might be better to avoid application from big number issues.

2018-07-16 10:27 UTC, Wiezzel commented
@mdtanrikulu Done.
Test are fixed as well.
@mfranciszkiewicz @Krigpl Please, review.

2018-07-16 11:16 UTC, mfranciszkiewicz commented on golem/client.py
> +        # Convert wei -> eth because front-end has troubles with large numbers
Our front-end uses a bignum library, that's an issue with the RPC serializer.

2018-07-16 11:16 UTC, mfranciszkiewicz commented on golem/client.py
> +                task_dict[k] = task_dict[k] / denoms.ether
IMO `str`s would be a better option

2018-07-16 11:25 UTC, Wiezzel commented on golem/client.py
> +                task_dict[k] = task_dict[k] / denoms.ether
@mdtanrikulu do you agree?

2018-07-16 15:03 UTC, Wiezzel commented on golem/client.py
> +                task_dict[k] = task_dict[k] / denoms.ether
OK, done.

2018-07-16 15:11 UTC, mdtanrikulu approved these changes

2018-07-17 09:43 UTC, mfranciszkiewicz approved these changes

2018-07-17 09:59 UTC, Krigpl commented on golem/transactions/paymentskeeper.py
> +            -> Tuple[Optional[int], Optional[int]]:
afaict there's no way one value will be `None` while other won't, so `Optional[Tuple]` looks like a better choice

2018-07-17 10:03 UTC, Wiezzel commented on golem/transactions/paymentskeeper.py
> +            -> Tuple[Optional[int], Optional[int]]:
Returning a single `None` would make this assignment much uglier: https://github.com/golemfactory/golem/blob/6f614648d4b4d4c5be4068b22040c8cb0662cacb/golem/client.py#L936-L937
I can go with `Union[Tuple[int, int], Tuple[None, None]]` if you don't like `Tuple[Optional[int], Optional[int]]`

2018-07-17 10:09 UTC, Krigpl commented on golem/transactions/paymentskeeper.py
> +            -> Tuple[Optional[int], Optional[int]]:
```
task_dict['cost'], task_dict['fee'], *_ = \ 
self.transaction_system.get_total_payment_for_subtasks(subtask_ids), None
```
would work then, but lets not do that :p
I'm fine either way, was just nitpicking.

2018-07-17 11:55 UTC, merged