Send ForcePayment
golemfactory/clay pull request #3046
Opened 2018-07-16 10:55 UTC by jiivan

Send force payment when there are overdue incomes in database.
fixes: #2194

2018-07-17 09:18 UTC, maaktweluit approved these changes
LGTM!

Some questions, none are breaking so approved!

2018-07-17 09:18 UTC, maaktweluit commented on golem/network/history.py
> +        task_id: Optional[str] = None,  # deprecated
since the order has already changed maybe its better to put the deprecated argument last?

2018-07-17 09:18 UTC, maaktweluit commented on golem/network/history.py
>      #         https://github.com/golemfactory/golem/issues/2670
nice first step on this issue :)

so until #2670 is fully fixed `node_id` should be optional?

2018-07-17 09:18 UTC, maaktweluit commented on golem/network/history.py
> +        warnings.warn(
what is `warnings.warn` over `logger.warning`?

2018-07-17 09:18 UTC, maaktweluit commented on golem/network/history.py
> +        node_id: Optional[str] = None)\
i think its neater to add an extra space at the end: `) \`
Linter does not enforce this so can leave it :)

2018-07-17 16:31 UTC, Krigpl requested changes

2018-07-17 16:31 UTC, Krigpl commented on golem/client.py
> +        self.transaction_system.incomes_keeper.update_overdue_incomes()
This isn't necessary and it's even harmful.
It's unnecessary because the line below calls `update_overdue_incomes` in the process.
It's harmful because with two consecutive `update_overdue_incomes` calls the second will always return an empty list, so the `TRUST` below won't get updated.

2018-07-18 08:58 UTC, jiivan commented on golem/client.py
> +        self.transaction_system.incomes_keeper.update_overdue_incomes()
Thanks @Krigpl , missed that call. Although it seems clanky that `update_...()` is called as a side effect of getter method.

2018-07-18 09:02 UTC, Krigpl commented on golem/client.py
> +        self.transaction_system.incomes_keeper.update_overdue_incomes()
True, summoning @Wiezzel here

2018-07-18 09:06 UTC, jiivan commented on golem/network/history.py
> +        warnings.warn(
IMO they're better for everything that fits into [warning categories](https://docs.python.org/3/library/warnings.html#warning-categories). They can be nicely controlled by command line arg (`-W`) and programmatically. It makes it easier to find all occurences of a deprecated call by changing severity to error.

2018-07-18 09:29 UTC, Wiezzel commented on golem/client.py
> +        self.transaction_system.incomes_keeper.update_overdue_incomes()
OK, that's not a simple "getter method". You're welcome to rename it so that no one else gets confused.

2018-07-18 10:13 UTC, maaktweluit commented on golem/network/history.py
> +        warnings.warn(
Thank you for the explanation! super clear and handy

2018-07-18 14:07 UTC, jiivan commented on golem/client.py
> +        self.transaction_system.incomes_keeper.update_overdue_incomes()
It's outside of scope for this PR. I've created #3055

2018-07-19 10:15 UTC, mfranciszkiewicz approved these changes

2018-07-19 10:50 UTC, merged