expose testing tasks via cli
golemfactory/clay pull request #3062
Opened 2018-07-19 10:35 UTC by etam

Also:
- move task json validation from cli to golemapp
- rpc changes:
  - comp.task.test.status (check_test_status):
    - instead of sending serialized structure as json string, send the
      structure itself. RPC transport takes care of serialization
      already.
    - don't cleanup results.
    - if there's no error, value of "error" is None, instead of True

2018-07-19 12:12 UTC, jiivan approved these changes
LGTM

2018-07-19 12:12 UTC, jiivan commented on golem/client.py
> +        if 'name' in t_dict.keys():
`.keys()` is unnecessary

2018-08-01 14:39 UTC, mdtanrikulu requested changes
Probably while creating test task, there is no task name and it causes error from `_validate_task_dict`. So test result is always `{error: "Length of task name cannot be less than 4 or more than 24 characters." , status: "Error"}` in GUI. If I pass task name for test reason it's checking task name and everything is okay on this side. Not sure maybe it's a good idea to check task name length here.

Apart from that, test result is always from previous test. Is not waiting for the new test results most of the time.

2018-08-14 11:22 UTC, etam commented
I don't fully understand your comment

> Probably while creating test task, there is no task name and it causes error from _validate_task_dict. So test result is always {error: "Length of task name cannot be less than 4 or more than 24 characters." , status: "Error"} in GUI. If I pass task name for test reason it's checking task name and everything is okay on this side.

I moved validating of task description from golemcli into core and also added it to check test task description. What you're saying is correct. If you don't set a name for a test task, it will fail at validation. Setting any proper name should solve the problem, and I think it's a better solution than making special cases at validation.

> Not sure maybe it's a good idea to check task name length here.

Where?

> Apart from that, test result is always from previous test. Is not waiting for the new test results most of the time.

Could you elaborate more on that? Steps to reproduce or something?

2018-08-20 10:08 UTC, mdtanrikulu commented
> Not sure maybe it's a good idea to check task name length here.

Ignore this, I solved in electron side as you mentioned. 

> Could you elaborate more on that? Steps to reproduce or something?

This local task "Atv Buggy" started after "Pavillion missing" task and results are belong to "pavillion missing" when I have the results.
<img width="458" alt="screen shot 2018-08-20 at 12 00 55" src="https://user-images.githubusercontent.com/2774845/44334212-360ecf00-a471-11e8-8cb4-8b03ba9c7116.png">

Same for the other way around for "Pavillion missing" task, results belong to "Atv Buggy" one.

<img width="460" alt="screen shot 2018-08-20 at 12 01 18" src="https://user-images.githubusercontent.com/2774845/44334353-930a8500-a471-11e8-9607-8d5b123ad244.png">

You can reproduce the same thing if you have one blend project folder with missing assets and one without.

2018-09-19 12:32 UTC, mdtanrikulu approved these changes

2018-10-04 14:46 UTC, merged