Hardware presets: do not assume exact values in tests
golemfactory/clay pull request #3070
Opened 2018-07-19 16:58 UTC by mfranciszkiewicz

`test_update_config` was non deterministic

2018-07-19 19:58 UTC, tworec requested changes

2018-07-19 19:58 UTC, tworec commented on tests/golem/core/test_hardware_presets.py
> +        with mock.patch(
with those mocks, config can differ only on `name` field. This test is not testing real/prod code any more... 
I'd rather mock `cpu_cores_available()`, `memory_available()` and `free_partition_space()` methods here.

2018-07-19 19:58 UTC, tworec commented on tests/golem/core/test_hardware_presets.py
> +        cpu_cores = HardwarePresets.cpu_cores(1)
those are specially crafted values for this test to pass. 
I guess you're trying to bypass test environment limitations/characteristics here, am I right?
But in this shape you are stripping lots of logic from tested class.

2018-07-19 19:58 UTC, tworec commented on tests/golem/core/test_hardware_presets.py
> +        assert self.config.num_cores == HardwarePresets.cpu_cores(cpu_cores)
It is even better now, since we are testing `update_config` method here.
I suggest creating three additional tests for those three methods used here (mocking methods checking system resources ie. `cpu_cores_available()` for `cpu_cores()`)

2018-07-19 20:52 UTC, mfranciszkiewicz commented on tests/golem/core/test_hardware_presets.py
> +        cpu_cores = HardwarePresets.cpu_cores(1)
Those values are not constant and had to be changed. That additional logic needs to be tested elsewhere

2018-07-19 20:55 UTC, mfranciszkiewicz commented on tests/golem/core/test_hardware_presets.py
> +        with mock.patch(
But why are we then testing the same deterministic outcome 3 times? This test is assuming a bit too much about the environment.

2018-07-20 14:13 UTC, tworec commented on tests/golem/core/test_hardware_presets.py
> +        with mock.patch(
three times is abundant, 2x is enough, your're right. You can remove one invocation if you want.

This test is assuming that environment has more than one cpu core, more than 1200000KiB RAM and more than 2000000KiB / 3 * 4 disk space. When you mock methods I've enumerated above, it will be independent from actual env limitations.

2018-07-20 14:40 UTC, mfranciszkiewicz commented on tests/golem/core/test_hardware_presets.py
> +        with mock.patch(
The problem is that sometimes this test fails, because each `update_config` call reads hardware caps independently and that can change (i.e. free disk space). I made it always return the same value, which _is_ retrieved from the current hw configuration.

2018-07-20 14:41 UTC, tworec commented on tests/golem/core/test_hardware_presets.py
> +        cpu_cores = HardwarePresets.cpu_cores(1)
I think mocking same methods as I've mentioned below/above is sufficient also here. 

What additional logic are you mentioning?

2018-07-20 14:47 UTC, mfranciszkiewicz commented on tests/golem/core/test_hardware_presets.py
> +        with mock.patch(
I sincerely thought that this test was supposed to verify that applying the same hw configuration more than once won't trigger a "hardware changed" event. In production, we care only about the real environment and do not care about the values in fashion that this test is written in.

2018-07-20 14:49 UTC, mfranciszkiewicz commented on tests/golem/core/test_hardware_presets.py
> +        cpu_cores = HardwarePresets.cpu_cores(1)
The logic that tests invariance of hardware parameters.

2018-07-20 15:05 UTC, tworec commented
here is my proposition. It was easier and shorter to code it than write about it ;)

2018-07-20 16:45 UTC, mfranciszkiewicz commented
That’s another way to solve this issue :)

2018-07-20 17:59 UTC, tworec approved these changes

2018-07-20 18:00 UTC, tworec commented
So, I'm proudly approving my own solution, seeing you said it solves our problem ;)

2018-07-20 18:16 UTC, tworec commented
You've correctly interpreted my intention about `test_update_config_not_changed`.  Mocking methods that are building blocks of `update_config` reduces this test coverage, so I've proposed solution with mocking lower level functions which are responsible for reading current env limits. But reading your commend allowed me to realize that we should also add a test with changing this mocks between `update_config` calls, because this happens on prod all the time..

2018-07-20 20:22 UTC, tworec commented
Main part of this PR was merged into develop with  #3071

2018-07-23 10:14 UTC, merged