Structured local test result
golemfactory/clay pull request #3128
Opened 2018-08-06 01:15 UTC by mdtanrikulu

To apply new test result component on GUI, warning of local task result structured as json

2018-08-17 17:27 UTC, Elfoniok requested changes

2018-08-17 17:27 UTC, Elfoniok commented on apps/blender/resources/blenderloganalyser.py
> +            return_warnings = return_data.get("warnings")
This may return None

2018-08-17 17:27 UTC, Elfoniok commented on apps/blender/resources/blenderloganalyser.py
> +                return_data["warnings"]["missing_files"] = return_data.get(
Its not needed here to access list once again, use += operator or extend metohd return_data["warnings"]["missing_files"].extend(warnings['missing_files'])

2018-08-17 17:27 UTC, Elfoniok commented on apps/blender/resources/blenderloganalyser.py
> +    return list(map(dict, set(tuple(sorted(f.items())) for f in warnings)))
Cant you leave this as it was for missing files? Just store whole missing_path. Otherwise you are unnecessary doubling data storage, where it could be up to the consumer of this class to either get basename or dir name.

2018-08-17 18:24 UTC, Elfoniok commented on apps/blender/resources/blenderloganalyser.py
> +    return list(map(dict, set(tuple(sorted(f.items())) for f in warnings)))
Alternatively you can leave set, as warnings type, and apply sort when adding element to it. This way you don't need to iterate over it so many times,  and you know that you are actually sorting by keys, so this will not change anything ( baseName will always be before dirName) :)

2018-08-18 17:07 UTC, mdtanrikulu commented on apps/blender/resources/blenderloganalyser.py
> +            return_warnings = return_data.get("warnings")
While having an if condition  `if return_data.get("warnings"):` how it can return None ?

2018-08-18 17:08 UTC, mdtanrikulu commented on apps/blender/resources/blenderloganalyser.py
> +                return_data["warnings"]["missing_files"] = return_data.get(
Done, thanks!

2018-08-18 17:14 UTC, mdtanrikulu commented on apps/blender/resources/blenderloganalyser.py
> +    return list(map(dict, set(tuple(sorted(f.items())) for f in warnings)))
Oh seems like I forgot to add attribute for sorted, like 
```
sorted(f.items, key=lambda f: f['baseName'])
```
which is fixed now. 

For your first comment, this is the goal of this PR. To make data structured. We are using both information (dirName, baseName) in new local task test result as below to give user more information about the place of the data, so they can place the missing files easily; 

<img width="458" alt="screen shot 2018-08-18 at 18 47 33" src="https://user-images.githubusercontent.com/2774845/44301614-8889a780-a31a-11e8-96e2-d51cca7ee2fd.png">

2018-08-20 08:24 UTC, Elfoniok commented on apps/blender/resources/blenderloganalyser.py
> +    return list(map(dict, set(tuple(sorted(f.items())) for f in warnings)))
Ok but why don't split path on basename and dir name, right before displaying it?

2018-08-20 09:37 UTC, mdtanrikulu commented on apps/blender/resources/blenderloganalyser.py
> +    return list(map(dict, set(tuple(sorted(f.items())) for f in warnings)))
While having at least 2 different file system to check (Windows, Mac/Linux) and having built in path method already for it, I couldn't find any reason to write another function.

2018-08-20 10:22 UTC, Elfoniok commented on apps/blender/resources/blenderloganalyser.py
> +            fileInfo = (
Please explain, because i see this unjustified. Why not store whole `missing_path` and extract basename and filename where is necessary?

2018-08-20 10:42 UTC, mdtanrikulu commented on apps/blender/resources/blenderloganalyser.py
> +            fileInfo = (
I already explained it in [here](https://github.com/golemfactory/golem/pull/3128#discussion_r211081287). 
Instead of having one full path of the file, I would rather to create an english syntax for UX purposes. To do it, I needed to have file name and the directory separately. And the lines you pointed, was the best place to split path correctly for all related OS file systems. Thus, rather than writing another function to check and split different file system paths, I used built-in one without any additional effort.

2018-08-20 11:47 UTC, Elfoniok requested changes

2018-08-20 11:47 UTC, Elfoniok commented on apps/blender/resources/blenderloganalyser.py
> +    if bool(warnings):
conversion to bool is not required

2018-08-20 11:47 UTC, Elfoniok commented on apps/blender/resources/blenderloganalyser.py
> +        warnings = sorted(warnings, key=lambda t: (t[0][1]))
That is better but you could sort items before inserting them so save some iterations.

2018-08-20 11:48 UTC, jiivan commented on apps/blender/resources/blenderloganalyser.py
> +            fileInfo = (
I also feel that it's a client/frontend responsibility to split & format paths. Backend should just return unique fullpaths.

2018-08-20 11:58 UTC, mdtanrikulu commented on apps/blender/resources/blenderloganalyser.py
> +    if bool(warnings):
Done, thanks good to know.

2018-08-20 12:05 UTC, mdtanrikulu commented on apps/blender/resources/blenderloganalyser.py
> +            fileInfo = (
@jiivan I will keep the same argument, If I was doing any other string manipulations I would definitely go for it. But for the cross platform file paths, I see it more suitable.

2018-08-20 12:51 UTC, mdtanrikulu commented on apps/blender/resources/blenderloganalyser.py
> +        warnings = sorted(warnings, key=lambda t: (t[0][1]))
Done.

2018-08-20 13:48 UTC, Elfoniok approved these changes

2018-08-20 14:06 UTC, jiivan approved these changes
Some suggestions

2018-08-20 14:06 UTC, jiivan commented on apps/blender/resources/blenderloganalyser.py
> +            return_warnings = return_data.get("warnings")
```python
if warnings:
    try:
        return_data["warnings"]["missing_files"].extend(warnings["missing_files"})
    except KeyError:
        return_data["warnings"] = warnings
```

2018-08-20 14:06 UTC, jiivan commented on tests/apps/blender/task/test_blenderrendertask.py
> +                         if f['baseName'] == "f1.png"])
```python

self.assertIn({'baseName': 'f1.png', 'dirName': 'XXX'}, warnings['missing_files'])
```

2018-08-20 14:06 UTC, jiivan commented on tests/apps/blender/task/test_blenderrendertask.py
> +                "file2.png" for f in warnings['missing_files']), 1)
Would this test be necessary if you left `warnings` as set?

2018-08-20 14:47 UTC, mdtanrikulu commented on tests/apps/blender/task/test_blenderrendertask.py
> +                "file2.png" for f in warnings['missing_files']), 1)
Test was there, only thing I did is update to the new form. Who wrote the test probably wanted to be sure if there's any duplicate still, If needless, which it is with set usage, I can remove it.

2018-08-20 14:47 UTC, mdtanrikulu commented on tests/apps/blender/task/test_blenderrendertask.py
> +                         if f['baseName'] == "f1.png"])
Thanks good one.

2018-08-21 12:33 UTC, merged