3125 bump messages to 2.11.0 3
golemfactory/clay pull request #3178
Opened 2018-08-14 08:12 UTC by shadeofblue

2018-08-14 10:18 UTC, etam requested changes

2018-08-14 10:18 UTC, etam commented on golem/network/transport/session.py
> +            library.get_type(message.Hello): self._react_to_hello,  # fixme  # noqa pylint:disable=no-member
Is there a reason for registering `_react_to_hello` here? It's defined in derived classes (that's why `no-member` is required). Derived classes also register their `_react_to_hello` in `__set_msg_interpretations` methods. I think this line should be dropped.

2018-08-14 14:03 UTC, shadeofblue commented on golem/network/transport/session.py
> +            library.get_type(message.Hello): self._react_to_hello,  # fixme  # noqa pylint:disable=no-member
@etam honestly, I have no idea - I'll check if the tests pass without that line but generally, as you can see, this pull request doesn't add that reaction callback - it only updates the codes for the newer golem-messages API

2018-08-14 14:30 UTC, etam approved these changes

2018-08-16 07:29 UTC, jiivan requested changes
How about taking this opportunity to refactor out this strange int "`TYPE`" comparison and using message class for it?

```python

# using isinstance here can fail because some messages inherit from other ones
self._interpretation.get(msg.__class__)
```

I mean changing:
https://github.com/golemfactory/golem/blob/39b877ab0c37db438412716d296d9173999fb977/golem/network/transport/session.py#L74

and

https://github.com/golemfactory/golem/blob/39b877ab0c37db438412716d296d9173999fb977/golem/network/transport/session.py#L204-L221

2018-08-17 09:39 UTC, jiivan reviewed
Proper paths would look so nice here.
`message.concent.ForceReportComputedTask` instead of `message.ForceReportCOmputedTask`

2018-08-17 09:39 UTC, jiivan commented on golem/task/tasksession.py
> +        delayed_forcing_msg = message.concents.ForceReportComputedTask(
Yes, using proper path looks like a good route to take :)

2018-08-17 10:27 UTC, jiivan approved these changes

2018-08-17 12:30 UTC, merged