Check next subtask in "react to wants to compute"
golemfactory/clay pull request #3189
Opened 2018-08-16 14:20 UTC by maaktweluit

before starting handshake

This is required for the task "buffer provider requests" and is an improvement that could be merged before the next release

2018-08-21 09:30 UTC, mfranciszkiewicz approved these changes

2018-08-23 09:48 UTC, mfranciszkiewicz requested changes
2 important issues

2018-08-23 09:48 UTC, mfranciszkiewicz commented on golem/task/taskmanager.py
> +        if task.get_progress == 1.0:
Should be `task.get_progress()`

2018-08-23 09:48 UTC, mfranciszkiewicz commented on golem/task/taskmanager.py
> +            logger.error("Task already computed")
Could you add more information to this message, e.g. `task_id`, `node_id`, `node_name`?

2018-08-23 09:48 UTC, mfranciszkiewicz commented on golem/task/taskmanager.py
> +        else:
I think we should return `False` here - we're sending `WaitingForResults` instead of `CannotAssignTask` to banned nodes.

2018-08-23 09:48 UTC, mfranciszkiewicz commented on golem/task/tasksession.py
> +                ctd = None
Minor: could be simplified with `ctd` set initially to `None`

2018-08-23 09:48 UTC, mfranciszkiewicz commented on tests/golem/task/dummy/runner.py
> +            logfile = path.join(datadir, "logs", "golem.log")
Minor: code is copy-pasted, maybe a function instead?

2018-08-23 10:08 UTC, maaktweluit commented on golem/task/taskmanager.py
> +        if task.get_progress == 1.0:
Good catch, done!

2018-08-23 10:08 UTC, maaktweluit commented on golem/task/taskmanager.py
> +            logger.error("Task already computed")
added

2018-08-23 10:09 UTC, maaktweluit commented on golem/task/taskmanager.py
> +        else:
Kept that as it was, but was thinking the same

Should we fix that?

2018-08-23 10:09 UTC, maaktweluit commented on golem/task/tasksession.py
> +                ctd = None
Nice one! will clean it up

2018-08-23 10:09 UTC, maaktweluit commented on tests/golem/task/dummy/runner.py
> +            logfile = path.join(datadir, "logs", "golem.log")
like it! moved to a private function

2018-08-23 10:21 UTC, maaktweluit commented on golem/task/taskmanager.py
> +        else:
fixed

2018-08-23 10:49 UTC, mfranciszkiewicz approved these changes

2018-08-24 11:42 UTC, merged