remove working dir
golemfactory/clay pull request #3216
Opened 2018-08-23 10:12 UTC by Krigpl

It's useless.

2018-08-23 10:29 UTC, maaktweluit requested changes
LGTM!

2 small comments, will approve on reply or resolve :)

2018-08-23 10:29 UTC, maaktweluit commented on requirements.txt
> +-e git://github.com/golemfactory/golem-verificator.git@84b71eab899b7831786e642ca407a04138aca802#egg=golem_verificator
is this update related to the cleanup? else a separate PR would be nice

Should be released before merge

2018-08-23 10:29 UTC, maaktweluit commented on golem/task/taskthread.py
> -        os.chdir(os.path.join(abs_res_path,
where will taskthread work now there is no `chdir`?

2018-08-23 10:30 UTC, maaktweluit commented on requirements.txt
> +-e git://github.com/golemfactory/golem-verificator.git@84b71eab899b7831786e642ca407a04138aca802#egg=golem_verificator
should have checked the linked PR, is related :)

2018-08-23 10:39 UTC, Krigpl commented on golem/task/taskthread.py
> -        os.chdir(os.path.join(abs_res_path,
Hmmmmmm, good catch. Maybe it wasn't completely useless. Although I'm pretty sure working directory here could be simply set to `/tmp/<whatever>`, right?

2018-08-23 10:46 UTC, maaktweluit commented on golem/task/taskthread.py
> -        os.chdir(os.path.join(abs_res_path,
haha, almost useless still :P

yes, that would work

i also see a tmp_path variable available, maybe that is a good working dir to `chdir` to?

2018-08-24 07:33 UTC, Elfoniok commented on golem/task/taskthread.py
> -        os.chdir(os.path.join(abs_res_path,
/tmp/ ?  I think its always good to remove chdir (like who use that?!, what if separate threads are saving files and someone just change its working dir?). I am pretty sure that this is working dir for local test, during adding task (but better confirm this) so datadir/network_name/tmp dir ?

2018-08-24 07:33 UTC, Elfoniok approved these changes

2018-08-24 07:55 UTC, Elfoniok commented on golem/task/taskthread.py
> -        os.chdir(os.path.join(abs_res_path,
Hey i checked this, so this is base class and its never used (i tried as provider and requestor), derived class which is DockerTaskThread is used all the time and currently i don't see when one could want to use base implementation.

2018-08-29 15:13 UTC, merged