Deadline already passed
golemfactory/clay pull request #3259
Opened 2018-08-30 15:28 UTC by jiivan

fixes: #3230

1. Harden TaskServer.sync_network() to ensure that all jobs are attempted even when previous one fails
1. Use custom exception for TaskHeader validation errors and don't include their tracebacks in logs

2018-08-30 15:35 UTC, jiivan commented
It's an open question whether to additionally filter out timeouted header in `PeerSession._react_to_get_tasks()`.

2018-08-31 08:28 UTC, etam requested changes

2018-08-31 08:28 UTC, etam commented on golem/task/taskbase.py
> +            node_name = task_owner['node_name']  # type: ignore
This is wrong. Here you try to get something from `task_owner` and below you check if it's a `dict`. You should first make sure it's a `dict` and then get anything from it. It will also make mypy less angry.

2018-08-31 08:28 UTC, etam commented on golem/task/taskbase.py
> +                now=common.get_timestamp_utc(),
Get a timestamp once, assign it to a variable and use it in both places.

2018-08-31 08:31 UTC, etam commented
> It's an open question whether to additionally filter out timeouted headers in `PeerSession._react_to_get_tasks()`.

We don't want to propagate outdated tasks, so they have to be dropped somewhere. This is a good place to filter the incoming headers, so I'm OK with that.

2018-08-31 08:45 UTC, jiivan commented on golem/task/taskbase.py
> +            node_name = task_owner['node_name']  # type: ignore
It's just [EAFP](https://docs.python.org/3.6/glossary.html#term-eafp). What's wrong with that?

2018-08-31 13:01 UTC, etam commented on golem/task/taskbase.py
> +            node_name = task_owner['node_name']  # type: ignore
Me being used to C++.

But on the other hand, you can move the line `node_name = task_owner['node_name']` under `if not isinstance(task_owner, dict):` and you won't need to catch `TypeError` nor silence the type checker. Then you could replace the whole try...catch thing with `node_name = task_owner.get('task_owner', task_owner)`. Wait, what?

2018-08-31 13:04 UTC, etam commented on golem/task/taskbase.py
> +            node_name = task_owner['node_name']  # type: ignore
I don't understand this part:

```python
        except (TypeError, KeyError):
            node_name = task_owner
```
What sense does it make, if we expect `task_owner` to be a `dict`?

2018-08-31 14:22 UTC, jiivan commented on golem/task/taskbase.py
> +            node_name = task_owner['node_name']  # type: ignore
We expect `task_owner` to be a `dict` and act accordingly, but when it raises `TypeError` it means it's something else and I would like to know what it was i.e. include it in `TaskHeaderError`.

I wanted to have all exceptions raised here to contain at least `task_id` and `node_name`. Could use something generic like `<unknown>` but thought that some actual/related value would be better.

2018-09-05 08:30 UTC, etam commented on golem/task/taskbase.py
> +            node_name = task_owner['node_name']  # type: ignore
I'd change that to:
```python
try:
    node_name = task_owner.get('node_name')
except TypeError:
    ...
```
This way, if there's no `node_name` in `task_owner` it'll be handled by `if not isinstance(node_name, str):` below.

2018-09-05 10:02 UTC, etam approved these changes

2018-09-05 10:27 UTC, merged