Add tests for subtask restart
golemfactory/clay pull request #3274
Opened 2018-09-04 14:05 UTC by etam

2018-09-04 14:31 UTC, shadeofblue commented on tests/golem/test_client.py
> +        task.header.task_id = 'tid'
@etam shouldn't this go into some helper factory method so that we don't need to repeat this sequence of operations in each test?

2018-09-04 14:33 UTC, shadeofblue requested changes
please move those parts of the `test_taskmanager` tests to a common method so that code is not repeated in each of those tests...

2018-09-04 14:59 UTC, etam commented on tests/golem/test_client.py
> +        task.header.task_id = 'tid'
done

2018-09-04 15:00 UTC, etam commented
`test_taskmanager`? I changed a single line there.

2018-09-04 15:36 UTC, shadeofblue commented
@etam oops, sorry, I meant `test_client` ... my bad

2018-09-05 08:57 UTC, etam commented
I'm not sure if there is that much code repeated that makes it reasonable to pull out a common part. Such function wouldn't have even any meaningful name.

Another issue is that it's not clear what's the distinction between `TestClient` class and `TestClientRPCMethods`. The first one derives from `TestWithReactor` and the second one has a `setUp`, which is initializing a `Client` object.

2018-09-06 07:51 UTC, shadeofblue commented
> I'm not sure if there is that much code repeated that makes it reasonable to pull out a common part. Such function wouldn't have even any meaningful name.
> 
> I was thinking about moving creation of `Client` object into `setUp`, but it wouldn't work with some of test cases. Then I found that there's also a `TestClientRPCMethods` class, which is initializing a `Client` object in `setUp`, but it's not clear what's the distinction between it and `TestClient` class.

@etam well, what's stopping us from creating a new `TestClientRestartTask` TestCase? ... generally, imvho, the test cases should be separate unless there is a good reason for them to be part of the same class ... ... so, if we have more than one test that requires a similar setup, that - imvho - constitues a pretty good reason to create a common TestCase class for them...

2018-09-06 10:56 UTC, etam commented
done

2018-09-11 12:28 UTC, shadeofblue approved these changes

2018-09-11 12:29 UTC, shadeofblue commented
@etam approved -> the only issue is that we probably don't want to merge to b0.17.1 specifically...

2018-09-11 14:19 UTC, merged