[WIP] RPC support for deposit transactions
golemfactory/clay pull request #3278
Opened 2018-09-05 07:45 UTC by jiivan

fixes: #2980

2018-09-11 09:06 UTC, shadeofblue commented on golem/database/schemas/021_create_deposit_payment.py
> +        dbid = pw.PrimaryKeyField()
@jiivan is this needed? peewee should automatically create a primary key id in case none is specified... shouldn't it?

2018-09-11 09:11 UTC, shadeofblue commented on golem/ethereum/transactionsystem.py
> +    def get_deposit_payments_list(cls):
I wonder -> shouldn't we think ahead and already implement an interface for pagination? iow, add `limit` and `offset` parameters to the call, filled by default with `1000` and `0` respectively, so that we can later implement the pagination on the front-end when we decide so?

I'm mentioning that because there already are concerns about lack of pagination in our RPC calls... so maybe it would be good to stay future-proof when we implement new calls...

2018-09-11 09:12 UTC, shadeofblue commented on golem/model.py
> +    dbid = PrimaryKeyField()
(same here) I believe Peewee should add the identity field automatically...

2018-09-11 09:25 UTC, maaktweluit reviewed
LGTM!

2 small comments, can approve on reply :)

2018-09-11 09:25 UTC, maaktweluit commented on golem/ethereum/transactionsystem.py
> +            entry["pk"] = common.to_unicode(dpayment.dbid)
I thought `common.to_unicode()` was only needed for python2, or is this something peewee related?

2018-09-11 09:25 UTC, maaktweluit commented on golem/ethereum/transactionsystem.py
> +from . import exceptions
`NotEnoughFunds` is now imported twice

Maybe it is good to keep the imports consistent to make them easier to manage

2018-09-11 09:37 UTC, Krigpl requested changes
I believe I mentioned it before, but would you mind adding me to PRs touching transaction system by default?

2018-09-11 09:37 UTC, Krigpl commented on golem/model.py
> +    block_hash = BlockchainHashField(null=True)
afaict this isn't used anywhere

2018-09-11 09:37 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            tx=int(tx_hash, 16),
Transaction hashes are never conceptually used as integers so I find this counter-intuitive - they are just hex strings.

2018-09-11 09:37 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            dpayment.status = model.PaymentStatus.awaiting
That will never be retried so it's better to just remove it completely imo

2018-09-12 11:48 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +            entry["pk"] = common.to_unicode(dpayment.dbid)
Not really sure. It returns `None` for `None` but `str(value)` otherwise. I just used the same logic as in `get_payments_list()`.

2018-09-12 12:32 UTC, jiivan commented on golem/database/schemas/021_create_deposit_payment.py
> +        dbid = pw.PrimaryKeyField()
Good point. I didn't know peewee has default id field.

2018-09-12 12:32 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +from . import exceptions
:+1:

2018-09-12 12:48 UTC, jiivan commented on golem/model.py
> +    block_hash = BlockchainHashField(null=True)
Yes, `block_hash` and `block_number` are not displayed anywhere. Do you think they shouldn't be stored?

2018-09-12 13:00 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +            tx=int(tx_hash, 16),
Done (simplified to strings).

2018-09-14 12:14 UTC, Krigpl commented on golem/model.py
> +    block_hash = BlockchainHashField(null=True)
Yeah, no need for them anytime soon. And if they will ever be needed they can be obtained from tx hash anyway so there's no loss here.

2018-09-17 10:27 UTC, Krigpl requested changes

2018-09-17 10:27 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            tx=tx_hash,
`tx_hash` is 66 chars long (because of `0x` prefix) while `tx` field has `max_length=64`

2018-09-17 10:27 UTC, Krigpl commented on golem/model.py
> +class BlockchainHashField(FixedLengthHexField):
not used

2018-09-17 10:27 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +            '5e9880b3e9349b609917014690c7a0afcdec6dbbfbef3812b27b60d246ca10ae'
sci returns hashes with `0x` prefix

2018-09-17 10:27 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            entry["block_number"] = common.to_unicode(dpayment.block_number)
`block_number` doesn't exist anymore

2018-09-17 10:27 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +                tx_hash = "{:x}".format(dpayment.tx)
it's already hex, isn't it ?

2018-09-17 10:27 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            entry["pk"] = common.to_unicode(dpayment.id)
What `pk` stands for? Is it primary key? isn't it an internal stuff that doesn't need to be exposed? Transaction hash is also a primary key.

2018-09-19 11:32 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            -> Generator[defer.Deferred, TransactionReceipt, Optional[str]]:
I may just misunderstand but why the return type isn't simply `Optional[str]`?

2018-09-19 11:32 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            entry["created"] = common.datetime_to_timestamp_utc(
I don't think `created` and `modified` are used either - I know they exist in `payments_list` but probably shouldn't as well.

2018-09-19 11:32 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            entry = {}
I'd make it a structured object instead of arbitrary dict, it'd be easier to deal with. And if `to_unicode` is really needed for whatever reason then it should happen in `client` since it's related to presentation layer which doesn't belong here (same for `payments_list` of course, so it's not a perfect base to follow).

2018-09-19 12:58 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +            -> Generator[defer.Deferred, TransactionReceipt, Optional[str]]:
It's a [generator](https://docs.python.org/3.5/glossary.html#term-generator)/coroutine. [Typing specifications](https://docs.python.org/3.5/library/typing.html?highlight=typing#typing.Generator)

2018-09-19 13:20 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +            entry["created"] = common.datetime_to_timestamp_utc(
@Krigpl they'll be used in GUI: https://projects.invisionapp.com/share/ZHISL0F3TX9#/screens/297433337

2018-09-19 13:33 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +            entry = {}
IMHO db/peewee model is structured enough. I don't see a reason to create custom mapping class only for "presentation layer"/rpc.

Maybe it's good idea to move rpc formatting to `client`, but client is overbloated (1.7k lines). I think it deserves a proper refactoring to smaller modules e.g. `client.payment`, `client.account` etc. but it's totally outside of this PR.

I think this PR is big enough not to implement this refactoring, don't you?

2018-09-19 15:08 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            entry = {}
I didn't suggest any kind of refactoring here. I'm just saying that `TransactionSystem` should return structured data, just list of `model.DepositPayment` is fine and all this `to_unicode` transformations should happen in the `client`.
In other words - why would transaction system convert all values to strings by default, what's the benefit? IE.g. f you'd need to calculate the sum of all deposits you'd need to convert `value`s back to `int`.

2018-09-19 15:08 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +        deposit_value = 20 - 1
`20 - 1` looks random. I believe this is `gnt_balance - gnt_lock` so please use those values instead.

2018-09-19 15:08 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +        deposit_value = 20 - 1
ditto

2018-09-20 09:50 UTC, shadeofblue approved these changes
lgtm

2018-09-20 10:15 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +            entry = {}
I apologize. Must have misunderstood you then.

2018-09-20 12:41 UTC, Krigpl approved these changes
Looks good
![obama_approves](https://user-images.githubusercontent.com/3904252/45818887-466dd000-bce3-11e8-8929-af8a83841c76.jpeg)

2018-09-20 13:13 UTC, merged