Another possible fix for the restart issue
golemfactory/clay pull request #3280
Opened 2018-09-05 15:38 UTC by etam

Instead of making a special case for marking subtask as failed, do it early in `copy_results`

2018-09-06 09:49 UTC, shadeofblue commented
[ note ] the tests show that this fix causes the restarted tasks not to be computed by the network - needs more investigation - or maybe - even some refactoring of the task restart functionality and related RPC calls

2018-09-06 09:51 UTC, shadeofblue requested changes
make sure that any changes are tested (with the semi-automated test + ideally using normal golem nodes) before we decide to merge it

2018-09-06 13:51 UTC, etam commented
fixed

2018-09-11 12:50 UTC, shadeofblue approved these changes

2018-09-12 15:14 UTC, merged