Hyper-V support
golemfactory/clay pull request #3328
Opened 2018-09-20 14:22 UTC by Wiezzel

Known issues (to be fixed in separate PRs):
* Verification is not working.
* ~~Golem VM is restarting every time Golem starts.~~ (Fixed by #3326)
* Golem VM is not shutting down when Golem quits.

2018-09-20 14:35 UTC, maaktweluit requested changes
LGTM!

Some small comments:
- Please check info logger formatting
- Benchmark unit test is failing https://buildbot.golem.network/buildbot/#/builders/6/builds/6498/steps/5/logs/stdio

2018-09-20 14:35 UTC, maaktweluit commented on golem/docker/hypervisor/docker_machine.py
> +        logger.info(f'{self.DRIVER_NAME}: creating VM "{vm_name}"')
please use arguments for formatting logs, when the level is disabled the formatting does not need to happen.

2018-09-20 14:35 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> +        logger.info(f'Hyper-V: reconfiguration of VM "{name}" finished')
formatting

2018-09-20 14:35 UTC, maaktweluit commented on scripts/get-ip-address.ps1
> +(Get-NetIPAddress -InterfaceAlias "*$Interface*" -AddressFamily IPv4).IPAddress | Write-Output
no new line at end of file

2018-09-21 16:29 UTC, mfranciszkiewicz commented on scripts/get-ip-address.ps1
> +(Get-NetIPAddress -InterfaceAlias "*$Interface*" -AddressFamily IPv4).IPAddress | Write-Output
Does this line work properly when multiple IP addresses are assigned?

2018-09-24 08:02 UTC, Wiezzel commented on scripts/get-ip-address.ps1
> +(Get-NetIPAddress -InterfaceAlias "*$Interface*" -AddressFamily IPv4).IPAddress | Write-Output
@mfranciszkiewicz Is it possible to have two IPv4 addresses assigned to one network interface?

2018-09-24 09:05 UTC, mfranciszkiewicz commented on scripts/get-ip-address.ps1
> +(Get-NetIPAddress -InterfaceAlias "*$Interface*" -AddressFamily IPv4).IPAddress | Write-Output
@Wiezzel Yes and that's where the question originated from.

2018-09-24 12:29 UTC, Wiezzel commented on scripts/get-ip-address.ps1
> +(Get-NetIPAddress -InterfaceAlias "*$Interface*" -AddressFamily IPv4).IPAddress | Write-Output
This will be only called for `vEthernet (Golem Switch)` interface so if someone assigns another IP we could just say "Sorry, it's you fault. You are not supposed to mess up with this".

2018-09-25 15:00 UTC, Wiezzel commented
@maaktweluit @mfranciszkiewicz Please approve (or not if you thing something more is missing).

2018-09-25 15:14 UTC, maaktweluit reviewed
LGTM!

2 small comments remain:
- Newline at end of powershell script
- Duplicated log message

Can approve on reply too

2018-09-25 15:14 UTC, maaktweluit commented on golem/docker/hypervisor/docker_machine.py
> +            logger.debug(f'Hypervisor output: {e.output}')
i recently added that `self.command` logs the output as debug, this line is now duplicate

2018-09-25 16:18 UTC, mfranciszkiewicz submitted a review, later dismissed

2018-09-26 08:23 UTC, maaktweluit submitted a review, later dismissed

2018-09-26 11:16 UTC, mfranciszkiewicz approved these changes

2018-09-26 11:16 UTC, maaktweluit approved these changes

2018-09-27 08:50 UTC, merged