Concent relock, unlock and withdraw
golemfactory/clay pull request #3365
Opened 2018-10-01 10:52 UTC by jiivan

fixes: #3076

2018-10-01 11:35 UTC, Krigpl requested changes

2018-10-01 11:35 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +        self.sci.concent_timelock.return_value = 0
sci doesn't have `concent_timelock` method, make `sci::get_deposit_locked_until` return 0 and get get rid of the patch on `test_check_payments` method

2018-10-01 11:35 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +        self.concent_withdraw()
Since this is run periodically it needs to check whether there isn't already ongoing withdrawal, otherwise many unnecessary transactions will be sent

2018-10-01 11:35 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +        # because of AppVeyor issues.
what AppVeyor issues ?

2018-10-01 11:54 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +        # because of AppVeyor issues.
AppVeyor used to return different values for `time.time()` and `calendar.timegm(time.gmtime())`.

2018-10-01 14:41 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +        raise RuntimeError("Not implemented in SCI")
Upgrade sci to 1.6.1 to have this method

2018-10-01 14:44 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +        balance_mock.return_value = abs(fake.pyint()) + 1
This is the only use of `fake`, I really doubt it's beneficial instead of having some arbitrary value hardcoded

2018-10-01 14:46 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +    'golem.ethereum.transactionsystem.TransactionSystem.concent_balance',
When testing a specific class it's really better not to mock any of its method and mock dependencies instead. Just mock `sci.get_deposit_value` instead

2018-10-01 14:47 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +    'golem.ethereum.transactionsystem.TransactionSystem.concent_timelock',
Same as other comment.

2018-10-08 07:57 UTC, jiivan commented on tests/golem/ethereum/test_transactionsystem.py
> +        balance_mock.return_value = abs(fake.pyint()) + 1
I doubt it's detrimental either.

2018-10-08 08:48 UTC, Krigpl approved these changes
![rickandmorty_yes](https://user-images.githubusercontent.com/3904252/46599419-a20fca00-cae7-11e8-89dc-e1ba8f16764d.gif)

2018-10-08 09:14 UTC, merged