Unburden golem.client as a sole RPC provider
golemfactory/clay pull request #3368
Opened 2018-10-01 11:24 UTC by jiivan

* Introduce `@expose` decorator for remote procedures
* Introduce `golemcli.py debug exposed_procedures` for dynamic procedures mapping
* Remove static procedures mapping file
* Remove unused event listening logic

2018-10-01 13:40 UTC, etam commented on golem/interface/client/environments.py
> +from golem.rpc.session import ClientProxy
https://www.python.org/dev/peps/pep-0484/#runtime-or-type-checking

2018-10-01 13:40 UTC, etam commented on golem/interface/client/terms.py
> +from golem.rpc.session import ClientProxy
https://www.python.org/dev/peps/pep-0484/#runtime-or-type-checking

2018-10-01 13:52 UTC, etam commented on golem/node.py
> +        self.rpc_session.add_procedures(methods)  # type: ignore
`# type: ignore` Why?

2018-10-01 13:55 UTC, jiivan commented on golem/node.py
> +        self.rpc_session.add_procedures(methods)  # type: ignore
`Optional[Session]` has no attribute `add_procedures`. Mypy not cool? :)

2018-10-01 14:12 UTC, etam commented on golem/node.py
> +                self._keys_auth._private_key,  # noqa pylint: disable=protected-access
Maybe `_private_key` shouldn't be a private variable? After all, it's used everywhere, but not in `KeysAuth`.

2018-10-01 14:16 UTC, jiivan commented on golem/node.py
> +                self._keys_auth._private_key,  # noqa pylint: disable=protected-access
True, it may be a good candidate for next refactoring PR.

2018-10-01 14:35 UTC, etam commented on golem/node.py
> +        self.rpc_session.add_procedures(methods)  # type: ignore
If you add `if not self.rpc_session:`, like in other methods around, then `Optional` goes away and ignoring type should not be needed.

2018-10-02 11:06 UTC, etam commented on golem/node.py
> +def require_rpc_session():
```python
from typing import Any, cast, Callable, Optional, TypeVar
from functools import wraps

F = TypeVar('F', bound=Callable[..., Any])


def _require_rpc_session(f: F) -> F:
    @wraps(f)
    def wrapper(self: 'Node', *args, **kwargs):
        if self.rpc_session is None:
            self._error("RPC session is not available")  # noqa pylint: disable=protected-access
            return None
        return f(self, *args, **kwargs)
    return cast(F, wrapper)


class Node:
    ...
    @_require_rpc_session  # no '()' at the end here
    def foo():
```

Not ideal, but I think a bit better.
https://mypy.readthedocs.io/en/latest/generics.html#declaring-decorators

2018-10-02 12:13 UTC, etam commented on golem/rpc/router.py
> -from golem.rpc.cert import CertificateManager
What's wrong with that?

2018-10-02 12:30 UTC, Elfoniok approved these changes

2018-10-02 12:30 UTC, Elfoniok commented on golem/client.py
> +            mapping.update(rpc_utils.object_method_map(rpc_provider))
I am not sure if this is a good way to collect exposed methods? basically we scan all methods of providers and check if its has uri attribute?

2018-10-02 12:30 UTC, Elfoniok commented on golem/rpc/session.py
> +        for registration in self._registrations.values():
why do you need this? Is is allowed to use private fields of base class according to python conventions?

2018-10-02 12:30 UTC, Elfoniok commented on golem/rpc/session.py
> +            fn = registration.endpoint.fn
I am not sure if we don't depend here on WAMP internals? Wouldn't be a problem when updating WAMP version?

2018-10-02 12:34 UTC, etam commented on golem/rpc/session.py
> +        if mapping is None:
Maybe just use `mapping={}` default value in arguments?

2018-10-02 12:43 UTC, jiivan commented on golem/rpc/session.py
> +        if mapping is None:
Nope. Try this:
```python
def f(a=[]):
    a.append(1)
    print(a)

for x in range(100):
    f()
```

2018-10-02 12:44 UTC, jiivan commented on golem/rpc/session.py
> +        if mapping is None:
http://www.effbot.org/zone/default-values.htm

2018-10-02 13:02 UTC, etam commented on golem/rpc/session.py
> +    def __init__(self, session, timeout=2):
Can I haz sum type annotations? (for variables below too, especially `_mapping`)

2018-10-02 13:03 UTC, etam commented on golem/rpc/session.py
> +class ClientProxy():  # pylint: disable=too-few-public-methods
```python
class ClientProxy:
```

2018-10-02 13:03 UTC, etam commented on golem/rpc/session.py
> +            return super().__getattr__(name)  # pylint: disable=no-member
`super()`?

2018-10-02 13:08 UTC, etam commented on golem/rpc/session.py
> +class Publisher():  # pylint: disable=too-few-public-methods
```python
class Publisher:
```

2018-10-02 13:11 UTC, etam commented on golem/rpc/utils.py
> +        nonlocal uri
Is this `nonlocal` necessary? `uri` is not used outside of `wrapper` scope.

2018-10-02 13:11 UTC, etam commented on golem/rpc/utils.py
> +    def wrapper(f):
https://docs.python.org/3/library/functools.html#functools.wraps

2018-10-02 13:14 UTC, etam commented on golem/rpc/utils.py
> +    mapping = {}
type annotation?

2018-10-02 13:47 UTC, etam commented on golem/node.py
> +        self.rpc_session.add_procedures(methods)  # type: ignore
There's a short time between when RPC session is ready and procedures are registered. If in that time a client connects and calls something, it will get errors.

Maybe we should have a method (registered very early, returning bool) and send notification after methods are registered, so that a client could know when golem is ready?

2018-10-02 13:47 UTC, etam commented on golem/node.py
> +        self.rpc_session.add_procedures(methods)  # type: ignore
that would also require some changes from electron side

2018-10-02 13:49 UTC, etam requested changes
I like the idea! But I left some notes around...

2018-10-08 08:07 UTC, jiivan commented on golem/client.py
> +            mapping.update(rpc_utils.object_method_map(rpc_provider))
Yes, it's done once when `Node` initializes `Client`. I'm open any improvement suggestions to this one. haven't come with anything better.

2018-10-08 08:10 UTC, jiivan commented on golem/rpc/session.py
> +        for registration in self._registrations.values():
I need this, because base class doesn't implement `exposed_procedures()` method and I really want it.

2018-10-08 08:11 UTC, jiivan commented on golem/rpc/session.py
> +            fn = registration.endpoint.fn
I get your point, but I see no better solution.

2018-10-08 08:29 UTC, jiivan commented on golem/rpc/session.py
> +            return super().__getattr__(name)  # pylint: disable=no-member
yes, object.

2018-10-08 08:29 UTC, jiivan commented on golem/rpc/utils.py
> +        nonlocal uri
For linters only.

2018-10-08 08:31 UTC, jiivan commented on golem/rpc/utils.py
> +    def wrapper(f):
It would be usefull fo `inner` if defined. This function actually returns `f`.

2018-10-08 08:40 UTC, jiivan commented on golem/rpc/router.py
> -from golem.rpc.cert import CertificateManager
It was done as part of some refactoring which I don't remember, but IMHO it's always better to use namespaces. Helps to minimize local namespace pollution.

2018-10-08 09:09 UTC, jiivan commented on golem/node.py
> +def require_rpc_session():
IMHO it's really ugly, and... it doesn't work. :/ I don't want to skip one level of function nesting as it removes ability of accepting parameters of this decorator. And I really don't want to try to overcome mypy limits here.

2018-10-08 09:26 UTC, jiivan commented on golem/node.py
> +        self.rpc_session.add_procedures(methods)  # type: ignore
AFAIK electron has some grace time when golem starts to wait for registering procedures. We could minimize the time gap of this race-condition, but I don't think it's worth the effort.

2018-10-08 10:07 UTC, etam approved these changes

2018-10-08 10:09 UTC, merged