Remove Lux from sources
golemfactory/clay pull request #3382
Opened 2018-10-03 13:57 UTC by bidzyyys

2018-10-03 13:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=3382) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=3382) before we can accept your contribution.<br/><hr/>**Daniel Bigos** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=3382) it.</sub>

2018-10-03 14:08 UTC, nieznanysprawiciel approved these changes

2018-10-03 14:46 UTC, Krigpl commented on tests/golem/docker/test_docker_manager.py
> +            expected = 5                #before removing lux 6
These comments aren't useful imo

2018-10-03 14:47 UTC, Krigpl reviewed
![itshappening](https://user-images.githubusercontent.com/3904252/46418393-03bce680-c72c-11e8-87fc-e5c60b843fee.gif)

2018-10-04 08:02 UTC, magdasta commented on tests/golem/docker/test_docker_manager.py
> +            expected = 5                #before removing lux 6
+1

2018-10-04 08:18 UTC, bidzyyys commented on tests/golem/docker/test_docker_manager.py
> +            expected = 5                #before removing lux 6
Comments removed

2018-10-04 08:46 UTC, Elfoniok requested changes
Please check problem with building binaries on Windows.

2018-10-04 11:59 UTC, Elfoniok approved these changes

2018-10-05 09:11 UTC, Krigpl approved these changes
![mergeitmergeitmergeit](https://user-images.githubusercontent.com/3904252/46526729-624ea580-c88f-11e8-8aab-820073eb2b25.jpg)

2018-10-06 15:11 UTC, merged