Names refactor
golemfactory/clay pull request #3396
Opened 2018-10-05 14:51 UTC by mplebanski

It's an important step to simplify current task API. I removed mappings that caused different identifiers point to the same data/objects. 

This change requires `golem-electron` to use `subtasks_count` instead of `subtasks` when creating/getting a task through golem RPC. @mdtanrikulu

2018-10-17 10:04 UTC, mplebanski commented
I resolved the conflicts that appeared because it was hanging for over a week.

2018-10-17 10:41 UTC, jiivan requested changes
Full body of `golem/client.py` changed...

2018-10-17 10:41 UTC, jiivan commented on golem/client.py
> -# pylint: disable=too-many-lines
What happened here? Please revert this change.

2018-10-17 11:02 UTC, etam commented on golem/client.py
> -# pylint: disable=too-many-lines
Looks like change of end-of-line encoding.

@mplebanski I know we have some files with `\r\n` and some with `\n`, but we have to stick with what we have.

2018-10-17 11:32 UTC, mplebanski commented
@jiivan I fixed the line endings problem. Weird.

2018-10-17 11:36 UTC, mplebanski commented on golem/client.py
> -# pylint: disable=too-many-lines
This happened because I used github web gui to merge the golem/client.py into feature branch

2018-10-17 12:54 UTC, etam commented
@mplebanski when merging this PR (not now, obviously) please use the option to squash all commits.

2018-10-17 15:05 UTC, mplebanski commented
Can we give it a go? It's easy for this refactor to become a conflict (many files affected).

2018-10-17 15:12 UTC, Wiezzel reviewed
This seems to affect RPC (`comp.task.create`). Do we have coordinated interface changes?

2018-10-17 15:14 UTC, mplebanski commented
I only plan to do this regarding Electron client (@mdtanrikulu). Is there anything else I should take into consideration?

2018-10-17 15:21 UTC, jiivan approved these changes

2018-10-17 15:23 UTC, jiivan commented
> I only plan to do this regarding Electron client (@mdtanrikulu). Is there anything else I should take into consideration?

Yes, have a look at *golemcli*

2018-10-18 09:46 UTC, mplebanski commented
Closing due to too many conflicts

2018-10-18 09:46 UTC, closed without merging