Use default virtual network switch
golemfactory/clay pull request #3403
Opened 2018-10-08 15:49 UTC by Wiezzel

2018-10-09 12:24 UTC, maaktweluit requested changes
LGTM!

Some small comments, none are breaking. Will approve on reply

2018-10-09 12:24 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> +import os
now it `import os` and `from os import path`, maybe those 2 lines can be joined to make it cleaner?

2018-10-09 12:24 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> +    def _run_ps(cls, script, timeout=SCRIPT_TIMEOUT):
nice one! missed that in my PR!

2018-10-09 12:24 UTC, maaktweluit commented on tests/golem/docker/test_hyperv.py
> -    def test_parse_create_vnet_switch_fail(self, _):
maybe keep the failure case for better coverage?

2018-10-10 08:32 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
> +import os
Done.

2018-10-10 08:32 UTC, Wiezzel commented on tests/golem/docker/test_hyperv.py
> -    def test_parse_create_vnet_switch_fail(self, _):
Done.

2018-10-10 09:02 UTC, maaktweluit approved these changes

2018-10-10 13:38 UTC, merged