Refactor assigned_subtasks
golemfactory/clay pull request #3426
Opened 2018-10-11 09:58 UTC by Krigpl

`assigned_subtasks` was a map holding at most one value, so the refactor is self explanatory.
Golem doesn't support multiple computations at the same time.

2018-10-11 12:16 UTC, maaktweluit requested changes
LGTM!

Some small comments, will approve on reply!

2018-10-11 12:16 UTC, maaktweluit commented on golem/monitor/model/taskcomputersnapshotmodel.py
> +            task_computer.assigned_subtask['subtask_id']
what python magic is this? it looks like there is an assignment missing ( or knowledge on my side )

2018-10-11 12:16 UTC, maaktweluit commented on golem/task/taskcomputer.py
> +            logger.error("Resource colledted for a wrong task, %s", task_id)
typo, `colledted  => collected`

2018-10-11 12:16 UTC, maaktweluit commented on tests/golem/monitor/model/test_taskcomputersnapshotmodel.py
> +        computer_mock.assigned_subtask = assigned_subtask = 'test_subtask_id'
mock is not matching type, not sure if that matters: `Optional[Dict[str, Any]]`

2018-10-11 14:02 UTC, Krigpl commented on golem/monitor/model/taskcomputersnapshotmodel.py
> +            task_computer.assigned_subtask['subtask_id']
Good catch, my mistake

2018-10-11 14:27 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +        self.assigned_subtask: Dict[str, Any] = {}
I'd say that empty value should represented as `None` instead of `{}`.

2018-10-11 14:27 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +            self.assigned_subtask = {}
See prev. comment.

2018-10-11 14:27 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +            self.assigned_subtask = {}
See prev. comment.

2018-10-11 14:43 UTC, Krigpl commented on golem/task/taskcomputer.py
> +        self.assigned_subtask: Dict[str, Any] = {}
I started with that. But then it's easier to do `self.assigned_subtask.get('task_id') == task_id` when it's always a map. I can revert back to it.

2018-10-11 14:58 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +        self.assigned_subtask: Dict[str, Any] = {}
Maybe add something like this?
```python
@property
def asssigned_task_id(self) -> Optional[str]:
    return self.assigned_subtask.get('task_id') if self.assigned_subtask else None
```
And then just use `self.assigned_task_id == task_id`.

2018-10-12 10:10 UTC, Wiezzel approved these changes

2018-10-12 13:48 UTC, maaktweluit approved these changes

2018-10-12 13:53 UTC, merged