Fix accept sra
golemfactory/clay pull request #3428
Opened 2018-10-11 13:06 UTC by etam

2018-10-11 14:27 UTC, shadeofblue commented on golem/task/tasksession.py
> +        return self.task_server.keys_auth._private_key  # noqa pylint: disable=protected-access
@etam I'm unsure I understand the removal of the check here... especially since you don't seem to be checking for the possible `AttributeError` that may result from uninitialized `task_server` in any places that use this property...

2018-10-11 14:29 UTC, shadeofblue commented on golem/task/tasksession.py
> +                         "from who")
whoM ...

2018-10-11 14:30 UTC, shadeofblue commented on golem/task/tasksession.py
> +        if self.key_id is None:
on the other hand, can `self.key_id` be `None` in within a correctly initialized `TaskSession` ? isn't a session always initialized with the other party's node id?

2018-10-11 14:30 UTC, etam commented on golem/task/tasksession.py
> +        return self.task_server.keys_auth._private_key  # noqa pylint: disable=protected-access
I removed the check, because it's not possible for `self.task_server` to be `None. It was in the past, but it's not anymore. But those checks were left. So I removed them.

2018-10-11 14:32 UTC, etam commented on golem/task/tasksession.py
> +                         "from who")
done

2018-10-11 14:34 UTC, etam commented on golem/task/tasksession.py
> +        if self.key_id is None:
`self.key_id` is set in `_react_to_hello`.

https://github.com/golemfactory/golem/blob/158d31afecd59ff850d507a819aa11ea4edd4e2c/golem/task/tasksession.py#L879

2018-10-11 14:41 UTC, shadeofblue commented on golem/task/tasksession.py
> +            logger.error("received SubtaskResultsAccepted, but I don't know "
@etam in that case, I think this message it not really useful... it should rather say e.g.

`SubtaskResultsAccepted` received within an improperly intialized `TaskSession` - `key_id` is empty.

or something like that ... otherwise, it's completely unclear what the meaning is without looking at the specific line of code here...

2018-10-11 14:47 UTC, etam commented on golem/task/tasksession.py
> +            logger.error("received SubtaskResultsAccepted, but I don't know "
My idea was, in higher level of abstraction, that if someone connects and don't send `hello` message, then golem doesn't know who he is.

2018-10-11 14:49 UTC, shadeofblue commented on golem/task/tasksession.py
> +        if not transaction_system.is_income_expected(
@etam @Krigpl correct me if I'm wrong but I don't think we can completely eliminate the `check_requestor_for_subtask` and just replace it with `is_income_expected` since we specifically modified Golem _not_ to generate the `Income` record before `SRA` is issued... so this is mostly a fix for _older_ awaiting transactions for which the `comp_task_keeper` record has already been removed ... but for the currently processed subtasks, we should still rely on that check and not on existence of the expected payment... Am I right, @Krigpl ?

2018-10-11 14:50 UTC, shadeofblue commented on golem/task/tasksession.py
> +            logger.error("received SubtaskResultsAccepted, but I don't know "
yep, but that requires extensive knowledge of `TaskSession`s internal functioning... and won't tell anything to a less informed user...

2018-10-11 14:56 UTC, Krigpl requested changes

2018-10-11 14:56 UTC, Krigpl commented on golem/task/tasksession.py
> +        if self.key_id is None:
I believe `self.key_id` will always be set - `SRA` message has to be verified, before reacting to it, and verification uses `self.key_id`. So this `if` won't happen. Similar for other messages in general.

2018-10-11 14:56 UTC, Krigpl commented on golem/task/tasksession.py
> +            logger.error("Unexpected income from %r for subtask %r",
I dunno if it's an error - provider can't prevent from receiving these messages and can't do anything about it. Malicious requestor shouldn't generate error messages on the provider side.

2018-10-11 14:56 UTC, Krigpl commented on golem/task/tasksession.py
> +                payer_address=pubkeytoaddr(self.key_id)
I think `SRA` has `task_to_compute` property which has `requestor_ethereum_address` property which should be used here.

2018-10-11 14:56 UTC, Krigpl commented on golem/ethereum/incomeskeeper.py
> +        return Income.select().where(
fwiw, I find
```
.where(
  cond1,
  cond2,
)
```
more legible than spamming with parentheses.

2018-10-11 15:00 UTC, Krigpl commented on golem/task/tasksession.py
> +        if not transaction_system.is_income_expected(
I think so, yes. Imo the `is_income_expected` check should live inside `check_requestor_for_subtask`'s if body.

2018-10-12 07:51 UTC, etam commented on golem/task/tasksession.py
> +            logger.error("received SubtaskResultsAccepted, but I don't know "
Actually, a "less informed user" wouldn't be much more informed by a message "key_id uninitialized".

2018-10-12 08:28 UTC, etam commented on golem/task/tasksession.py
> +        if self.key_id is None:
I had to somehow silence `mypy` complaining about `self.key_id` being `Optional[str]`.
Should I put `assert self.key_id is not None` then?

2018-10-12 08:45 UTC, Krigpl commented on golem/task/tasksession.py
> +        if self.key_id is None:
If you apply my comment from line 788 you won't have this issue at all

2018-10-12 09:43 UTC, etam commented on golem/ethereum/incomeskeeper.py
> +        return Income.select().where(
done

2018-10-12 09:43 UTC, etam commented on golem/task/tasksession.py
> +        if self.key_id is None:
So `assert` it is.

2018-10-12 09:44 UTC, etam commented on golem/task/tasksession.py
> +            logger.error("received SubtaskResultsAccepted, but I don't know "
Anyway, the message is gone now.

2018-10-12 09:44 UTC, etam commented on golem/task/tasksession.py
> +        if not transaction_system.is_income_expected(
done

2018-10-12 09:44 UTC, etam commented on golem/task/tasksession.py
> +            logger.error("Unexpected income from %r for subtask %r",
changed to debug

2018-10-12 09:45 UTC, etam commented on golem/task/tasksession.py
> +                payer_address=pubkeytoaddr(self.key_id)
done

2018-10-12 10:21 UTC, Krigpl approved these changes
![waffle](https://user-images.githubusercontent.com/3904252/46864027-60e62580-ce19-11e8-98fe-c5da6968f715.gif)

2018-10-12 10:21 UTC, Krigpl commented on golem/task/tasksession.py
> +            msg.verify_owners(
Why did you add this?

2018-10-12 10:21 UTC, Krigpl commented on golem/task/tasksession.py
> +        if (
Woah, this `if` is ugly

2018-10-12 10:31 UTC, etam commented on golem/task/tasksession.py
> +        if (
Yes, it is. I spent a minute with jiivan trying to find a way that's readable and acceptable by pylint.

2018-10-12 10:38 UTC, etam commented on golem/task/tasksession.py
> +            msg.verify_owners(
To make sure the message is properly signed? Or is it checked anywhere else?

2018-10-12 10:43 UTC, Krigpl commented on golem/task/tasksession.py
> +            msg.verify_owners(
I imagine this should happen for all messages and not just this particular one and should be moved to some other place, somewhere before calling `react_to_*` methods. Afaict this is not the case right now, but I wouldn't add this check here now.
Unless @shadeofblue or @jiivan have something planned for that already.

2018-10-12 10:45 UTC, Krigpl commented on golem/task/tasksession.py
> +            msg.verify_owners(
> To make sure the message is properly signed?

Also checking whether message is properly signed is already done before reaching here. This is for something else.

2018-10-12 10:54 UTC, shadeofblue commented on golem/task/tasksession.py
> +            msg.verify_owners(
indeed, it's not to check whether the message itself is properly signed - that's done during the deserialization - but rather whether the whole message chain is correct and that all messages belong to the expected parties

2018-10-12 11:03 UTC, shadeofblue approved these changes
I believe it's okay

2018-10-12 11:53 UTC, merged