Handle 16 bits images
golemfactory/clay pull request #3444
Opened 2018-10-15 11:55 UTC by bidzyyys

2018-10-16 10:12 UTC, Elfoniok requested changes

2018-10-16 10:12 UTC, Elfoniok commented on apps/rendering/resources/imgrepr.py
> +        cv2.imwrite(path, self.img)
Can this throw exception?

2018-10-16 10:12 UTC, Elfoniok commented on apps/rendering/resources/renderingtaskcollector.py
> -    def finalize_exr(self, exr_repr):
well as far as i know we are still supporting writing to EXR format, could you check this with badb or blue?

2018-10-16 10:12 UTC, Elfoniok commented on apps/rendering/resources/renderingtaskcollector.py
> +            img_y, res_x = img.shape[:2]
Some error handling would be nice :)

2018-10-16 19:47 UTC, magdasta reviewed
Before merging, we have to manually check if Golem still correctly assembles images:
*PNGs
*JPEGs
*EXRs
in both 8- and 16-bits.

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +import numpy as np
I prefer simply importing "numpy" over importing it as "np" (but it's totally subjective - I'm suggesting a change, not insisting on it)

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +class OpenCVImgRepr:
Should inherit from `ImgRepr`

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +    def __enter__(self):
I think we don't need `__enter__` and `__exit__`

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +    def get_shape(self):
this method is used only in tests

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +    def get_dtype(self):
this method is used only in tests

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +    def save_fullname(self, path):
please rename to `save`

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +    def save(self, path, output_format):
Please rename to `save_with_extension`

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +        return self.img.shape[1], self.img.shape[0]
Do we really need both `size` and `get_size` methods?

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/renderingtaskcollector.py
>  import os
This import is unused, you can remove it on the occasion of working on this file :)

2018-10-16 19:47 UTC, magdasta commented on apps/rendering/resources/renderingtaskcollector.py
> -    def finalize_exr(self, exr_repr):
Opencv supports EXRs, collector should now transparently handle them

2018-10-17 13:30 UTC, bidzyyys commented on apps/rendering/resources/imgrepr.py
> +        cv2.imwrite(path, self.img)
It isn't mentioned in the official docs.

2018-10-17 13:35 UTC, bidzyyys commented on apps/rendering/resources/imgrepr.py
> +class OpenCVImgRepr:
ImgRepr has some abstract methods that we don't want to implement.

2018-10-17 13:36 UTC, bidzyyys commented on apps/rendering/resources/imgrepr.py
> +    def __enter__(self):
It's required for ```with``` statement.

2018-10-17 13:40 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +    def __enter__(self):
my bad, I didn't notice the `with` which uses it

2018-10-17 13:42 UTC, magdasta commented on apps/rendering/resources/imgrepr.py
> +        cv2.imwrite(path, self.img)
Let's leave it for now, we'll see in the future if we should add error handling

2018-10-18 13:53 UTC, Elfoniok approved these changes

2018-10-30 14:31 UTC, Elfoniok commented
It works well for PNG, although blender scripts will have to be extended at some point, for example
bpy.context.scene.render.image_settings.color_depth = '16'
Otherwise blender will simply use whatever is set in the scene file, but if it is 16 bit, then collecting images save it in 16 bit format.

2018-10-31 11:05 UTC, Elfoniok commented
EXR and JPEG are assembled well as well.

2018-10-31 11:07 UTC, merged