Marketplace: statistics, requestor side
golemfactory/clay pull request #3459
Opened 2018-10-17 16:52 UTC by mfranciszkiewicz

2018-11-07 14:56 UTC, Krigpl commented on golem/ethereum/incomeskeeper.py
> +                    delay=time.time() - datetime_to_timestamp(e.created_date),
It might be more accurate to use transaction's timestamp in place of `time.time()` - especially when transaction gets mined when client was off

2018-11-07 14:56 UTC, Krigpl commented on golem/ethereum/incomeskeeper.py
> +            dispatcher.send(
I think that should happen iff `inserted`

2018-11-07 14:56 UTC, Krigpl commented on golem/ethereum/paymentprocessor.py
> +            delay=delay,
Same, `delay` might not be accurate

2018-11-07 15:08 UTC, mfranciszkiewicz commented on golem/ethereum/incomeskeeper.py
> +            dispatcher.send(
You're right, this happened due some external changes

2018-11-08 10:13 UTC, Krigpl requested changes

2018-11-08 10:13 UTC, Krigpl commented on golem/database/schemas/023_schema.py
> +        requestor_paid_sum=pw.IntegerField(default=0),
These should be `HexIntegerField`

2018-11-08 10:13 UTC, Krigpl commented on golem/ethereum/incomeskeeper.py
> +                reference_ts = e.settled_ts or e.accepted_ts
Just use `accepted_ts`, settled is not reliable is only Concent specific.

2018-11-08 10:13 UTC, Krigpl commented on golem/ethereum/paymentprocessor.py
> +        delay = payment.processed_ts - \
`processed_ts` is set just after payment is created, so this isn't what you want. `on_batch_confirmed`'s `receipt` argument has timestamp field, use it instead.

2018-11-08 11:22 UTC, maaktweluit approved these changes
LGTM!

2018-11-09 11:10 UTC, Krigpl commented on golem/ethereum/incomeskeeper.py
> +                delay = e.accepted_ts - datetime_to_timestamp(e.created_date)
This measures how long verification process took.
I think you're looking for `block.timestamp - e.accepted_ts`

2018-11-09 11:53 UTC, mfranciszkiewicz commented on golem/ethereum/incomeskeeper.py
> +                delay = e.accepted_ts - datetime_to_timestamp(e.created_date)
I've removed the `delay` from this branch (requestor stats) and will cover the issue in provider's one

2018-11-13 09:25 UTC, Krigpl approved these changes

2018-11-16 14:26 UTC, merged