Added warning on cli and app net mismatch
golemfactory/clay pull request #3540
Opened 2018-11-09 15:42 UTC by zakaprov

#3414
Note: this PR does not fully resolve the issue - the logic for acquiring a lock on data dir should be moved outside of `client.py` (most likely to `node.py`). This way it will be possible to detect a running instance prior to authentication. I'll open a separate PR for that change.

This adds a check in golemcli which attempts to detect whether an
instance of golem app is running on the system with a different target
chain (e.g. CLI is started with --mainnet flag, but there's a golem
instance running on testnet).

2018-11-16 10:11 UTC, etam commented on golem/core/simpleenv.py
> +def get_local_datadir(name=None, root_dir=None, env_suffix=None) -> str:
Type annotations for arguments plz.

2018-11-16 12:17 UTC, etam commented on golemcli.py
> +    net_to_check = 'rinkeby' if cli_in_mainnet else 'mainnet'
you have those names defined in `golem.config.active.DATA_DIR`

2018-11-16 12:19 UTC, etam commented
Please add tests.

2018-11-16 12:26 UTC, etam commented on golemcli.py
> +    net_to_check = 'rinkeby' if cli_in_mainnet else 'mainnet'
I'm a bit confused. Why do you need to pass 'rinkeby' or 'mainnet' to `get_local_datadir` as additional `env_suffix` argument? What's wrong with `from golem.config.active import DATA_DIR` that was in there?

2018-11-16 12:33 UTC, etam requested changes
Try to make `mainnet.py` and `testnet.py` in `golem/config/environments/` stateless.

2018-11-16 12:35 UTC, zakaprov commented on golemcli.py
> +    net_to_check = 'rinkeby' if cli_in_mainnet else 'mainnet'
That's because the environment needs to be cross-checked here - when we're running on mainnet, we want to inspect the datadir for testnet (and vice versa).

2018-11-16 12:36 UTC, zakaprov commented
Okay, will take a look.

2018-11-19 14:59 UTC, etam approved these changes
![ok](https://media.giphy.com/media/XreQmk7ETCak0/giphy.gif)

2018-11-21 10:29 UTC, jiivan commented on golemapp.py
> +    """
I would prefer this to be a function that takes `(mainnet, net, concent)` as arguments and returns `datadir`. Then I would call this in `@lock_datadir`

2018-11-21 10:29 UTC, jiivan commented on golemapp.py
> -    # Import AFTER the active configuration has been set
I would leave some comment in the new version, explaining why import is not global (at top of the file)

2018-11-21 10:29 UTC, jiivan commented on golemcli.py
> +from portalocker import lock, unlock, LOCK_EX, LOCK_NB, LockException
Maybe just `import portalocker` to avoid namespace pollution?

2018-11-21 10:29 UTC, jiivan commented on golemcli.py
> +        lock_file = open(lock_path, 'w')
`with open(lock_path, 'w') as lock_file:` might be more readable and there won't be a need to close file in `finally` block. Maybe `lock` could also be used as a context manager?

2018-11-21 10:29 UTC, jiivan commented on tests/golem/interface/test_golemcli.py
> +            assert logger.warning.called
`logger.warning.assert_called()`

2018-11-21 10:29 UTC, jiivan commented on tests/golem/interface/test_golemcli.py
> +            assert 'adding' in args[0]
`self.assertIn('adding', args[0])`

2018-11-21 10:29 UTC, jiivan commented on tests/golem/interface/test_golemcli.py
> +            assert 'removing' in args[0]
`self.assertIn('removing', args[0])`

2018-11-22 15:52 UTC, zakaprov commented on golemcli.py
> +        lock_file = open(lock_path, 'w')
Good idea, will do

2018-11-22 16:00 UTC, zakaprov commented on golemapp.py
> +    """
Alright, I guess it makes sense since `@lock_datadir` depends on environment being set anyway.

2018-11-23 13:26 UTC, jiivan approved these changes

2018-11-23 14:10 UTC, merged