Add status filter for golemcli incomes | payments | deposit_payments
golemfactory/clay pull request #3542
Opened 2018-11-12 09:12 UTC by dybi

resolves: #3105

2018-11-12 14:12 UTC, marmistrz requested changes

2018-11-12 14:12 UTC, marmistrz commented on tests/golem/interface/test_client_commands.py
> +            assert isinstance(result, CommandResult)
Please use `self.assertEquals` instead of `assert` n tests. It produces more informative output if the assertion fails.

2018-11-12 14:12 UTC, marmistrz commented on golem/interface/client/payments.py
> +@command(arguments=(sort_payments, status_filter,),
I think you don't need the trailing comma after `status_filter`

2018-11-12 14:19 UTC, dybi commented on tests/golem/interface/test_client_commands.py
> +            assert isinstance(result, CommandResult)
sure. BTW: Do you have defined convention for `assertEquals`:
- `assertEquals(expected, result)` or
- `assertEquals(result, expected)` ?

2018-11-12 14:19 UTC, dybi commented on golem/interface/client/payments.py
> +@command(arguments=(sort_payments, status_filter,),
ok

2018-11-13 07:59 UTC, shadeofblue commented on tests/golem/interface/test_client_commands.py
> +            assert isinstance(result, CommandResult)
@dybi I use the latter but I'm unsure if that's a organization-wide rule

2018-11-14 08:28 UTC, jiivan approved these changes

2018-11-14 10:19 UTC, merged