Add 'current' option for `golemcli tasks show` to display only current (ongoing) tasks
golemfactory/clay pull request #3543
Opened 2018-11-12 15:41 UTC by dybi

resolves: https://github.com/golemfactory/golem/issues/3106

2018-11-12 15:43 UTC, dybi commented
@jamuszyn - could you please check what format is displayed in GUI for status, ie.:
"notStarted" or "Not started", "waiting" or "Waiting", etc.

2018-11-13 14:22 UTC, etam commented on golem/interface/client/tasks.py
> +    current_task_states = [
`TaskStatus` has `is_completed` method. Maybe you could add a new, similar one, and use it instead?

2018-11-14 07:39 UTC, dybi commented on golem/interface/client/tasks.py
> +    current_task_states = [
I was wondering if it would be ok to do this. Sure :+1:

2018-11-14 07:57 UTC, dybi commented on golem/interface/client/tasks.py
> +    current_task_states = [
done

2018-11-14 10:30 UTC, etam approved these changes
![ok](https://user-images.githubusercontent.com/220752/48476972-b8085d00-e800-11e8-8bf0-56e81af6ae3d.gif)

2018-11-14 10:33 UTC, Wiezzel commented on golem/interface/client/tasks.py
> +                result = [t for t in result
`result or []` in line 89 suggests that `result` might be `None`. It should be handled here as well.

2018-11-14 11:08 UTC, etam commented on golem/interface/client/tasks.py
> +                result = [t for t in result
Or line 80 can be changed to `result = sync_wait(deferred) or []`

2018-11-14 11:09 UTC, etam requested changes
@Wiezzel had a good point

2018-11-14 11:35 UTC, dybi commented on golem/interface/client/tasks.py
> +                result = [t for t in result
quite frankly, it shouldn't be; if you thoroughly analyze `def get_tasks(self, task_id: Optional[str] = None)` from `golem.client`, you will see that `None` can be returned only when `task_id` has `True` value in boolean context. But when this is the case, whole `if` from line 82 is skipped. 

So it seems that `or []` from line 89 should be removed.
If you insist, I can add handling of `None`, but so far I feel more inclined towards removing `or []`. @Wiezzel, what would be your preference here?

Anyway, thanks for pointing this out :)

2018-11-14 12:54 UTC, Wiezzel commented on golem/interface/client/tasks.py
> +                result = [t for t in result
If you're sure this won't happen, just remove the `or None`. I'm fine with this.

2018-11-14 14:41 UTC, dybi commented on golem/interface/client/tasks.py
> +                result = [t for t in result
@Wiezzel @etam removed; also I have added a unit test to make sure we will notice if logic connected with `None` ever changes

2018-11-14 15:20 UTC, etam approved these changes

2018-11-15 07:40 UTC, merged