Chore update processing subtask results accepted after it contains rct
golemfactory/clay pull request #3556
Opened 2018-11-15 07:59 UTC by dybi

resolves: https://github.com/golemfactory/golem/issues/3544

I hope I did not miss anything... Unit tests do pass.

2018-11-15 10:18 UTC, jiivan requested changes

2018-11-15 10:18 UTC, jiivan commented on golem/task/tasksession.py
>                  message_class_name='TaskToCompute',
Please update `message_class_name`

2018-11-15 10:52 UTC, zakaprov commented on requirements.txt
> +--editable git://github.com/golemfactory/golem-messages.git@5df6478c22cf10ab8f0fbe37e2f6e1745277d6ac#egg=Golem_Messages
Reminder: make sure to update this once changes to messages are merged

2018-11-15 16:12 UTC, dybi commented on requirements.txt
> +--editable git://github.com/golemfactory/golem-messages.git@5df6478c22cf10ab8f0fbe37e2f6e1745277d6ac#egg=Golem_Messages
:+1:

2018-11-16 13:33 UTC, dybi commented on golem/task/tasksession.py
>                  message_class_name='TaskToCompute',
done

2018-11-16 14:06 UTC, etam commented
Is this related? https://github.com/golemfactory/golem-messages/pull/279/

2018-11-16 17:21 UTC, jiivan commented on requirements.txt
> +--editable git://github.com/golemfactory/golem-messages.git@5df6478c22cf10ab8f0fbe37e2f6e1745277d6ac#egg=Golem_Messages
`2.17.0` is ready

2018-11-16 17:25 UTC, jiivan commented on requirements.txt
> +--editable git://github.com/golemfactory/golem-messages.git@5df6478c22cf10ab8f0fbe37e2f6e1745277d6ac#egg=Golem_Messages
Please also update `requirements_to-freeze.txt` so tests will (hopefully) pass

2018-11-22 12:29 UTC, jiivan approved these changes

2018-11-22 13:05 UTC, merged