Simplify price in CompTaskInfo
golemfactory/clay pull request #3560
Opened 2018-11-15 14:17 UTC by Krigpl

`price` setter and getter ain't no used

2018-11-15 15:42 UTC, maaktweluit requested changes
LGTM!

One small q, approve on reply!

2018-11-15 15:42 UTC, maaktweluit commented on golem/task/taskkeeper.py
> -        # TODO Add concent communication timeout. Issue #2406
Is this also no longer needed? Is the issue closed?

2018-11-15 18:57 UTC, Krigpl commented on golem/task/taskkeeper.py
> -        # TODO Add concent communication timeout. Issue #2406
This isn't relevant to this PR and I didn't touch that, the issue is not closed (as you can check by yourself) and I dunno if it's still needed. I might have missed the point of your question :P

2018-11-16 09:55 UTC, maaktweluit commented on golem/task/taskkeeper.py
> -        # TODO Add concent communication timeout. Issue #2406
my question was: "Why is this removed"

Now i see its moved.. /shy

No questions remain ;)

2018-11-16 09:55 UTC, maaktweluit approved these changes

2018-11-16 10:53 UTC, merged