Tweaked docker-machine settings:
golemfactory/clay pull request #3589
Opened 2018-11-23 13:11 UTC by maaktweluit

- disk size default is now 5gb, was 20gb
 - VirtualQuantity now max_mem instead of min_mem

2018-11-26 09:16 UTC, Wiezzel commented on golem/docker/manager.py
> +            max_mem_in_mb = psutil.virtual_memory().free // 1024 // 1024
Shouldn't we use `available` instead of `free`? Psutil docs state that:
>available: the memory that can be given instantly to processes without the system going into swap. This is calculated by summing different memory values depending on the platform and it is supposed to be used to monitor actual memory usage in a cross platform fashion.

2018-11-26 09:16 UTC, Wiezzel commented on golem/docker/manager.py
> +                max_mem_in_mb += self.hypervisor.constraints()['memory_size']
I'm afraid we might get tricked here since we're using the dynamic memory feature. Imagine the following scenario:
1. The host machine has 8 GB of RAM.
1. There's a VM running with 6 GB memory limit.
1. The VM is not running any computations so the OS allocates only 1 GB of RAM to it.
1. Other processes on the machine are using 2 GB of RAM.
I suspect that in such case we would get information about 6 GB of free memory from `psutil.virtual_memory()` and 6 GB from `hypervisor.constraints()` thus ending up with `max_mem_in_mb` equal to 12 GB.

I am not sure if this would actually happen but it needs to be checked and somehow rectified if true.

2018-11-26 09:16 UTC, Wiezzel commented on golem/docker/hypervisor/docker_machine.py
>      env golem | Invoke-Expression
Point 2. is deprecated as well. And actually, I believe that this message should be somewhere else.

2018-11-26 09:16 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
> +        mem = (mem // 128) * 128
Wouldn't this cause the hypervisor try to change the memory every single time Golem starts? Since the actual memory limit would be different than the config value I believe that it would.

As far as I remember this was why I put this line in `DockerManager` and not in `HyperVHypervisor`:
```python
memory_size = memory_size // 2 * 2
```

2018-11-26 09:16 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
> +    # TODO: Fix override!
Let me know if I get this right. Is this a bug in `os-win` that we're fixing by overriding?

2018-11-26 10:25 UTC, maaktweluit commented on golem/docker/manager.py
> +            max_mem_in_mb = psutil.virtual_memory().free // 1024 // 1024
Good one, will look into this!

2018-11-26 11:22 UTC, maaktweluit commented on golem/docker/manager.py
> +                max_mem_in_mb += self.hypervisor.constraints()['memory_size']
I think you are right.. i need to move this code to "start_vm" so will adopt it accordingly to this case.

2018-11-26 11:26 UTC, maaktweluit commented on golem/docker/hypervisor/docker_machine.py
>      env golem | Invoke-Expression
agree, will fix it or make an issue out of it :)

2018-11-26 11:31 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> +        mem = (mem // 128) * 128
good one! will move it up.

Thought it was nice to only make this 128 rule inside windows

2018-11-26 11:33 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> +    # TODO: Fix override!
i am not sure.

i think some machines might be able to dynamicaly change "GuestVisibleMemory". so for them OS-win works now.

For our docker it does not change, once set to 1GB it stays 1GB, so we need this to be as high as we can.

os-win people are super nice, so will make an issue when this branch is working again

2018-11-26 11:34 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
> +        mem = (mem // 128) * 128
> Thought it was nice to only make this 128 rule inside windows

Agreed. Maybe try to get the best of both worlds by introducing some new method like `pad_memory` in the `Hypervisor` abstract class?

2018-11-26 12:35 UTC, maaktweluit commented on golem/docker/manager.py
> +            max_mem_in_mb = psutil.virtual_memory().free // 1024 // 1024
done

2018-11-26 12:36 UTC, maaktweluit commented on golem/docker/manager.py
> +                max_mem_in_mb += self.hypervisor.constraints()['memory_size']
stopped the VM while building config for now, open to better solves :)

2018-11-26 12:36 UTC, maaktweluit commented on golem/docker/hypervisor/docker_machine.py
>      env golem | Invoke-Expression
done

2018-11-26 12:37 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> +        mem = (mem // 128) * 128
nice idea! move it up now, will move like you proposed once it works

2018-11-26 14:17 UTC, Wiezzel commented on golem/docker/manager.py
> +                max_mem_in_mb += self.hypervisor.constraints()['memory_size']
Stopping the VM looks fine to me. It would be stopped anyway a moment later when the config is applied.

2018-11-28 09:56 UTC, Wiezzel commented
@maaktweluit Could you explain the recent changes?

2018-11-28 17:33 UTC, maaktweluit commented
@Wiezzel sure!

- Reverted dynamic memory, it brought more edge cases then it solved
- Catch errors on `start_vm` and try to start the VM with the minimum constrains

2018-11-29 12:01 UTC, mfranciszkiewicz requested changes

2018-11-29 12:01 UTC, mfranciszkiewicz commented on golem/docker/manager.py
> +            vmem = psutil.virtual_memory()
Can we move this code to the Hyper-V hypervisor class? This workaround will also affect macOS.

2018-11-29 12:03 UTC, maaktweluit commented on golem/docker/manager.py
> +            vmem = psutil.virtual_memory()
good idea!

2018-11-29 12:07 UTC, Wiezzel commented on golem/docker/manager.py
> +            vmem = psutil.virtual_memory()
That's weird. I thought it was already moved to `pad_memory` method.

2018-11-29 12:29 UTC, Wiezzel approved these changes
OK

2018-11-29 12:37 UTC, maaktweluit commented on golem/docker/manager.py
> +            vmem = psutil.virtual_memory()
Now it is, first try! ;)

2018-11-29 12:39 UTC, mfranciszkiewicz approved these changes

2018-11-29 12:52 UTC, merged