Change params.py to params.json
golemfactory/clay pull request #3632
Opened 2018-12-04 16:07 UTC by Krigpl

Replace `params.py` with `params.json` so it isn't so Python-centric and could be used by other technologies as well.

2018-12-04 16:36 UTC, maaktweluit requested changes
LGTM!

Will approve when `Golem-Verificator` is updated.

2018-12-04 16:36 UTC, maaktweluit commented on apps/dummy/resources/scripts/docker_dummytask.py
> +with open('/golem/work/params.json', 'r') as params_file:
Should this also use the same const `WORK_DIR` as in the file above?

2018-12-04 16:40 UTC, mfranciszkiewicz commented on apps/blender/resources/scripts/docker_blendertask.py
> +WORK_DIR = '/golem/work'
`WORK_DIR` is exported as an environment variable (see `docker/job.py`)

2018-12-05 10:50 UTC, Krigpl commented on apps/blender/resources/scripts/docker_blendertask.py
> +WORK_DIR = '/golem/work'
Also it is explicitly set during container creation so this is not needed at all

2018-12-06 13:38 UTC, maaktweluit approved these changes

2019-01-02 13:16 UTC, merged