Empty process' working sets to try and free some memory
golemfactory/clay pull request #3647
Opened 2018-12-06 15:42 UTC by mfranciszkiewicz

2018-12-06 15:49 UTC, Wiezzel submitted a review, later dismissed
Please restore `Cargo.lock`

2018-12-06 15:49 UTC, Wiezzel commented on .gitignore
> +rust/golem/Cargo.lock
This should **not** be ignored but committed. ([Ref](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries))

2018-12-06 16:07 UTC, mfranciszkiewicz commented
@Wiezzel I'm unsure how the conditional dependencies will be handled on other OSes though

2018-12-06 16:31 UTC, maaktweluit approved these changes
LGTM!

2 small comments, will approve on reply

2018-12-06 16:31 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
>          constr = self.constraints()
this can be done first, so it is only done once

`empty_..()` will not change the VM configuration so 1x is enough

2018-12-06 16:31 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> -    def pad_memory(self, memory: int) -> int:
is this meant to be no longer done on `build_config`?

2018-12-06 16:31 UTC, maaktweluit requested changes
Oops, selected the wrong option by accident

2018-12-06 22:08 UTC, mfranciszkiewicz commented on golem/docker/hypervisor/hyperv.py
> -    def pad_memory(self, memory: int) -> int:
Well, it's clearer when `pad_memory` doesn't do more than its name says. Besides, I can see no benefit in storing a volatile configuration - it will almost always differ from user's settings and cause a VM restart.

Actually, there is one more thing to do for comparing configurations - to make them aware of padding.

2018-12-07 10:52 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> -    def pad_memory(self, memory: int) -> int:
fully agree

and since start_vm is called after build_config the free check is still done

resolved

2018-12-07 11:36 UTC, maaktweluit approved these changes

2018-12-07 11:41 UTC, Wiezzel reviewed
I have some doubts about naming conventions used in the Rust code.

2018-12-07 11:41 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
>          max_mem_in_mb = self._get_max_memory()
I dunno how costly it is to call `_get_max_memory()` but if it takes long we could get rid of this call (we already retrieve the max memory in `_check_memory()`). This however would probably make our code uglier so only if `_get_max_memory()` is really costly.

2018-12-07 11:41 UTC, Wiezzel commented on rust/golem/src/os/windows.rs
> +        let lpid_process = &mut self.array[0];
This name is kinda cryptic. Why not simply `process_ids`?

2018-12-07 11:41 UTC, Wiezzel commented on rust/golem/src/os/windows.rs
> +        // The size of the pProcessIds array, in bytes
What is `pProcessIds` array? Do you mean `lpid_process`?

2018-12-07 11:41 UTC, Wiezzel commented on rust/golem/src/os/windows.rs
> +        let lpcb_needed: LPDWORD = &mut cb_needed;
Can't we just use `cb_needed`? Creating a separate variable for the reference kinda obscures the code for me.

2018-12-07 11:41 UTC, Wiezzel commented on rust/golem/src/os/windows.rs
> +        let lpid_process = &mut self.array[0];
Okay, I see now that this is WinAPI's Hungarian convention. But do we really need to follow it? It's totally confusing for me.

2018-12-07 11:41 UTC, Wiezzel commented on rust/golem/src/os/windows.rs
> +    pub fn enumerate(&mut self) -> Result<(), OSError> {
`enumerate` seems like a name of a function that returns some iterator. Maybe just `init`? Or even put this in `new`?

2018-12-07 11:41 UTC, Wiezzel commented on rust/golem/src/os/windows.rs
> +    pub fn open(&self, idx: usize) -> HANDLE {
I'd go with a name like `get_process_handle` instead of `open`.

2018-12-07 11:41 UTC, Wiezzel commented on rust/golem/src/os/windows.rs
> +                PROCESS_QUERY_INFORMATION | PROCESS_VM_READ | PROCESS_ALL_ACCESS,
Doesn't `PROCESS_ALL_ACCESS` cover all permissions? If so why use the other two flags?

2018-12-07 11:41 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
> +            try:
Maybe add some `logger.info()` here to inform about the performed operation?

2018-12-07 11:41 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
> +                logger.error('Unable to free memory: %r', e)
Using `logger.exception()` you don't need to pass the error explicitly. Just a convenience.

2018-12-07 11:41 UTC, Wiezzel commented on rust/golem/src/os/windows.rs
> +const MAX_PROCESS_COUNT: usize = 2048;
What will happen if there are more? Will `EnumProcesses` fail or just limit the result?

2018-12-07 11:48 UTC, mfranciszkiewicz commented on rust/golem/src/os/windows.rs
> +        // The size of the pProcessIds array, in bytes
Taken straight from ms docs, will update

2018-12-07 11:50 UTC, mfranciszkiewicz commented on rust/golem/src/os/windows.rs
> +const MAX_PROCESS_COUNT: usize = 2048;
It will limit the result

2018-12-07 11:55 UTC, mfranciszkiewicz commented on golem/docker/hypervisor/hyperv.py
>          max_mem_in_mb = self._get_max_memory()
I don't believe it's something we should optimize for, even if it takes 20ms.

2018-12-07 11:55 UTC, mfranciszkiewicz commented on rust/golem/src/os/windows.rs
> +        let lpcb_needed: LPDWORD = &mut cb_needed;
I cannot see why it obscures code since it strictly follows the API and naming conventions.

2018-12-07 11:57 UTC, mfranciszkiewicz commented on rust/golem/src/os/windows.rs
> +    pub fn enumerate(&mut self) -> Result<(), OSError> {
Sure, I can rename it. It's called `enumerate` because the main thing it does is call `EnumProcesses`

2018-12-07 11:57 UTC, mfranciszkiewicz commented on rust/golem/src/os/windows.rs
> +    pub fn open(&self, idx: usize) -> HANDLE {
Same as above - it calls `OpenProcess`

2018-12-07 11:58 UTC, Wiezzel commented on rust/golem/src/os/windows.rs
> +        let lpcb_needed: LPDWORD = &mut cb_needed;
I just meant that maybe we don't need a separate variable just to hold a reference to another variable. We could inline it. But if you feel like it's necessary feel free to ignore this remark.

2018-12-07 12:38 UTC, Wiezzel approved these changes

2018-12-07 13:14 UTC, merged