[WIP] Speed up Golem startup
golemfactory/clay pull request #3648
Opened 2018-12-06 15:57 UTC by Wiezzel

### Use saving VM state to speed up Golem startup

If possible make use of saving/restoring VM state. Otherwise, fall back to regular start/stop. Restoring a suspended Hyper-V machine is about 10x faster then running `docker-machine start`.

2018-12-06 16:05 UTC, mfranciszkiewicz commented
Is it possible to change the amount of memory assigned?

2018-12-07 08:45 UTC, Wiezzel commented
@mfranciszkiewicz No. This is why we still use `stop_vm()` and `start_vm()` in `restart_ctx()`.

2018-12-07 10:35 UTC, maaktweluit requested changes
LGTM!

I removed the save state last PR all together because it will lock the full RAM amount on the host disk in a save-state file. 
Is this worth that amount of disk space?
If the answer is yes, maybe we also need to check disk space before starting like memory.

Some questions, will approve on reply

2018-12-07 10:35 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> +                host_shutdown_action=HOST_SHUTDOWN_ACTION_SAVE,
This is the default option, so it could be removed too, both is fine for me

2018-12-07 10:35 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> +    def save_vm(self, vm_name: Optional[str] = None) -> None:
Since stop action is now save_state, maybe we do not have to manually save it.

I think it is worth to test the difference to make sure

2018-12-07 10:39 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
> +    def save_vm(self, vm_name: Optional[str] = None) -> None:
I believe `host_shutdown_action` is the action triggered when host OS is being shut down. We still need to do it ourselves when shutting Golem.

2018-12-07 10:47 UTC, maaktweluit commented on golem/docker/hypervisor/hyperv.py
> +    def save_vm(self, vm_name: Optional[str] = None) -> None:
makes total sense!

ok, then this is the way to go

2018-12-07 10:48 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
> +                host_shutdown_action=HOST_SHUTDOWN_ACTION_SAVE,
I'll leave explicit.

2018-12-10 11:30 UTC, Wiezzel commented
Update: Test show that suspending VMs also prevents IP changes. Which kinda makes sense because the VM would only make DHCP request during boot.

2018-12-12 12:34 UTC, Wiezzel commented
Running `docker-machine start` actually makes **three** SSH connections to the VM after it is started:
1) To check if SSH is available:
https://github.com/docker/machine/blob/eae38c196a2e10e4e11cc7b8d6dfe8863fb60519/libmachine/provision/provisioner.go#L104-L107
2) To check what OS is running inside them VM so that appropriate provisioner class could be chosen:
https://github.com/docker/machine/blob/eae38c196a2e10e4e11cc7b8d6dfe8863fb60519/libmachine/provision/provisioner.go#L109-L114
3) To check if docker daemon is listening:
https://github.com/docker/machine/blob/7a9ce457496353549916e840874012a97e3d2782/libmachine/provision/utils.go#L257-L258

A single `docker-machine ssh` command takes ~12 seconds. This is quite suspicious but still none of these ssh connections is really necessary. To check if Docker daemon is running one can simply scan the appropriate port from outside the VM (if the env is set properly a simple `docker info` will do).

2018-12-14 16:37 UTC, Wiezzel commented
@maaktweluit @mfranciszkiewicz 
This PR is ready for final review. I updated the description to cover all the changes.

2018-12-17 11:59 UTC, maaktweluit approved these changes
LGTM!

2018-12-17 12:34 UTC, mfranciszkiewicz approved these changes

2018-12-19 12:07 UTC, merged