Move TaskHeader to golem-messages
golemfactory/clay pull request #3655
Opened 2018-12-07 16:07 UTC by jiivan

fixes: #3557 
depends on: https://github.com/golemfactory/golem-messages/pull/285

2018-12-12 09:18 UTC, etam reviewed
Why are you changing all timeouts from ints to floats?

2018-12-12 09:18 UTC, etam commented on apps/core/task/coretask.py
> +            max_price=int(task_definition.max_price),
Why is this cast required? From glancing quickly at the code it seems to me that it should always be int. If it's not, then I think it's a bug and should be corrected elsewhere.

2018-12-12 13:56 UTC, etam requested changes

2018-12-12 13:56 UTC, etam commented on apps/rendering/task/renderingtaskstate.py
>          return self.resolution[0] * self.resolution[1] / self._pixel_to_seconds
Everywhere else timeouts were ints. They come from task definition in format "hh:mm:ss" and are converted to ints.

I think you should add here conversion to int and revert all conversions to floats you did in this PR.

2018-12-12 14:24 UTC, jiivan commented on apps/rendering/task/renderingtaskstate.py
>          return self.resolution[0] * self.resolution[1] / self._pixel_to_seconds
I generally agree that decimal precision is not needed in timestamps, but would like to get another opinion.
Also about:
 1. `deadline`
 1. `subtask_timeout`
 1. `timestamp`

2018-12-12 14:31 UTC, jiivan commented on apps/rendering/task/renderingtaskstate.py
>          return self.resolution[0] * self.resolution[1] / self._pixel_to_seconds
This default value influenced my decision to float conversion: https://github.com/golemfactory/golem/pull/3655/files#diff-798280b9faa873b5f61d16829c133666L68

2018-12-12 14:35 UTC, etam commented on apps/rendering/task/renderingtaskstate.py
>          return self.resolution[0] * self.resolution[1] / self._pixel_to_seconds
`timeout` and `subtask_timeout` are given by requesting user and are a relative number of seconds. Therefore ints.

`timestamp` and `deadline` are absolute timestamp values. On the one hand I think that we don't need sub-second granularity and int would be sufficient, but on the other hand `time.time()` and our `get_timestamp_utc` are returning floats, so I'm willing to accept status quo.

2018-12-13 09:48 UTC, jiivan commented on apps/core/task/coretask.py
> +            max_price=int(task_definition.max_price),
Fixed

2018-12-17 10:02 UTC, etam approved these changes
![ok](https://media.giphy.com/media/3uwclrlVzE6dO/giphy.gif)

2018-12-17 11:29 UTC, kmazurek approved these changes

2018-12-17 13:43 UTC, merged

2018-12-17 14:07 UTC, prekucki commented
$ golemcli network show
Exception: success return value from invoked procedure \\"net.peers.connected\\" could not be serialized: WAMP message serialization error: unsupported type: <class \'golem_messages.datastructures.p2p.Node\'>

2018-12-17 14:51 UTC, jiivan commented
> $ golemcli network show
> Exception: success return value from invoked procedure \"net.peers.connected\" could not be serialized: WAMP message serialization error: unsupported type: <class 'golem_messages.datastructures.p2p.Node'>

https://github.com/golemfactory/golem/pull/3676