when creating task with concent enabled, make sure deposit is locked
golemfactory/clay pull request #3682
Opened 2018-12-18 13:43 UTC by etam

resolves #3612

2018-12-19 14:32 UTC, jiivan requested changes

2018-12-19 14:32 UTC, jiivan commented on golem/task/rpc.py
> +        client.transaction_system.concent_relock()
This shouldn't be called here.

2018-12-19 14:34 UTC, etam commented on golem/task/rpc.py
> +        client.transaction_system.concent_relock()
Why?

2018-12-19 15:20 UTC, etam commented
I've force-pushed a completely new change, so you can safely ignore what was before.

2018-12-20 07:54 UTC, jiivan approved these changes
![trisie3](https://user-images.githubusercontent.com/293058/50271349-c87daa00-0434-11e9-999b-298c3979cbfc.gif)

2018-12-20 11:49 UTC, merged