Hide withdraw in golecli account if not mainnet
golemfactory/clay pull request #3684
Opened 2018-12-18 14:24 UTC by dybi

resolves: https://github.com/golemfactory/golem/issues/3012

2018-12-20 14:29 UTC, shadeofblue commented on golem/interface/cli.py
> +def adapt_children(children: Dict[Text, Callable]) -> Dict[Text, Callable]:
@dybi  ... on the surface, this function seems generic but really it's only applicable to a very specific case and hardly reusable... wouldn't it make sense to just get rid of that key specifically in the `_build_parser` without having a separate function for this task?

2018-12-21 05:56 UTC, dybi commented on golem/interface/cli.py
> +def adapt_children(children: Dict[Text, Callable]) -> Dict[Text, Callable]:
@shadeofblue, you've got a point - the name of the function is too generic. However, I would be for having it separated from the rest of the code for the sake of better modularity and unit-testing.

2018-12-21 08:48 UTC, shadeofblue commented on golem/interface/cli.py
> +    new_children = {k: v for k, v in children.items()}
wouldn't `copy.deepcopy` seem more natural here?

2019-01-02 09:21 UTC, Krigpl requested changes

2019-01-02 09:21 UTC, Krigpl commented on golem/interface/cli.py
> +    from golem.config.active import IS_MAINNET
Please import and use `WITHDRAWALS_ENABLED` instead

2019-01-02 11:04 UTC, shadeofblue approved these changes
looks good as far as I can tell.

@Krigpl , could you confirm?

2019-01-02 11:11 UTC, jiivan reviewed
IMHO it would be nice to explicitly disable a method in `golem.interface.client.account.Account.withdraw()`. Possibly by adding a modifier to `@command` decorator.

2019-01-03 10:32 UTC, dybi commented
@jiivan the problem with the proposed approach is that `@group` and `@command` decorators are evaluated at import and whether we are running on miannet or not is determined later (after arguments are parsed)

2019-01-03 10:35 UTC, jiivan commented on golem/interface/command.py
> +            filtered.append((name, m))
`if getattr(m, 'enabled', False):`

2019-01-03 10:35 UTC, jiivan commented on golem/interface/command.py
> +            filtered.append((name, m))
`return [(name, m) for name, m in methods if getattr(m, 'enabled', False)]`
I'm not sure if this list comprehension is worthy of a separate function. I would just use it in `CommandHelper.get_methods()`

2019-01-03 12:40 UTC, dybi commented on golem/interface/command.py
> +            filtered.append((name, m))
it is no longer there - as stated above: 
> `@group` and `@command` decorators are evaluated at import and whether we are running on miannet or not is determined later (after arguments are parsed)

2019-01-03 14:24 UTC, jiivan approved these changes
Yeah, `CommandHelper` needs major refactoring, but it's not top priority right now.

2019-01-04 10:09 UTC, merged