Move validations from enqueue_new_task method before it in create_task
golemfactory/clay pull request #3715
Opened 2019-01-08 05:41 UTC by pawelkisielewicz

Resolves https://github.com/golemfactory/golem/issues/3643x

2019-01-08 05:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=3715) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=3715) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=3715) it.</sub>

2019-01-08 12:48 UTC, dybi reviewed
Seems legit, but some polish would be appreciated.

2019-01-08 12:48 UTC, dybi commented on tests/golem/ethereum/test_fundslocker.py
> +        fl.transaction_system.get_available_gnt.return_value = 10000000000000
please first setup the mock, and then feed it to `FundsLocker`

2019-01-08 12:48 UTC, dybi commented on tests/golem/ethereum/test_fundslocker.py
> +        x = 'Not enough GNT available. Required: 0.000050, available: 0.000010'
please use f-strings and the values above (as a variables)

2019-01-08 12:48 UTC, dybi commented on tests/golem/task/test_rpc.py
> +        assert result == (None, 'Not enough GNT available. Required: '
please use `self.assertEqual`

2019-01-08 12:48 UTC, dybi commented on tests/golem/task/test_rpc.py
> +    def test_create_task_fail_if_not_enough_gnt_available(self, *_):
you could also check, that the mock was actually called

2019-01-09 08:19 UTC, pawelkisielewicz commented on tests/golem/ethereum/test_fundslocker.py
> +        fl.transaction_system.get_available_gnt.return_value = 10000000000000
done

2019-01-09 09:55 UTC, pawelkisielewicz commented on tests/golem/ethereum/test_fundslocker.py
> +        x = 'Not enough GNT available. Required: 0.000050, available: 0.000010'
done

2019-01-09 09:58 UTC, pawelkisielewicz commented on tests/golem/task/test_rpc.py
> +        assert result == (None, 'Not enough GNT available. Required: '
changed. I did it like this at first, but in all other tests there is `assert result ==` so I decided to unify. But changed :)

2019-01-09 10:10 UTC, pawelkisielewicz commented on tests/golem/task/test_rpc.py
> +    def test_create_task_fail_if_not_enough_gnt_available(self, *_):
done

2019-01-09 10:19 UTC, Krigpl requested changes
Please include me as a reviewer anytime you touch payments/transaction system/ethereum/etc

2019-01-09 10:19 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> -        if gnt > self.get_available_gnt():
Leave these checks, `lock_funds_for_payments` can be called from wherever and if should still do the validation.

2019-01-09 10:19 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +            fl = FundsLocker(transaction_system=self.ets)
revert this

2019-01-09 10:19 UTC, Krigpl commented on tests/golem/ethereum/test_fundslocker.py
> +        required = 50000000000000
use smaller numbers or `denoms.ether`

2019-01-09 10:19 UTC, Krigpl commented on golem/ethereum/fundslocker.py
> +    def validate_lock_funds_possibility(
Remove this method from `FundsLocker` - it doesn't use any FundsLocker's internals, just the transaction system.

2019-01-09 10:42 UTC, jiivan submitted a review, later dismissed
Please fix typo in description url

2019-01-09 10:42 UTC, jiivan commented on golem/task/rpc.py
> -    if client.config_desc.in_shutdown:
What happens when `in_shutdown` was `False` during create task, and became true in async function? race condition

2019-01-09 10:42 UTC, jiivan commented on golem/task/rpc.py
> +        validate_client(self.client)
What about other places `enqueue_new_task` is called

2019-01-09 10:42 UTC, jiivan commented on golem/task/rpc.py
> -            force=force,
Why?

2019-01-10 11:51 UTC, pawelkisielewicz commented on golem/ethereum/transactionsystem.py
> -        if gnt > self.get_available_gnt():
right, done

2019-01-10 12:21 UTC, pawelkisielewicz commented on tests/golem/ethereum/test_fundslocker.py
> +        required = 50000000000000
done

2019-01-10 12:21 UTC, pawelkisielewicz commented on golem/ethereum/fundslocker.py
> +    def validate_lock_funds_possibility(
done, moved to `rpc.py` as inner function

2019-01-11 07:46 UTC, pawelkisielewicz commented on tests/golem/ethereum/test_transactionsystem.py
> +            fl = FundsLocker(transaction_system=self.ets)
reverted and added assert for function validating possibility of locking founds

2019-01-14 09:22 UTC, pawelkisielewicz commented on golem/task/rpc.py
> -    if client.config_desc.in_shutdown:
yes... right. I left this check before calling `enqueue_new_task` as well, there is very high possibility that in this case it will be caught before. But it is called also in `enqueue_new_task` to prevent race condition

2019-01-14 09:24 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +        validate_client(self.client)
:+1: added to other places

2019-01-14 09:33 UTC, pawelkisielewicz commented on golem/task/rpc.py
> -            force=force,
It is used to check possibility to lock founds. In "first" version I moved this validation out of `concent_deposit`, it was the reason. Now it is back and this parameter has to stay

2019-01-14 12:10 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +from golem.task.rpc import _validate_lock_funds_possibility
Nope, `test_transactionsystem` which tests `TransactionSystem` shouldn't test a method from a different module, move it to an appropriate test file.

2019-01-14 12:11 UTC, Krigpl requested changes

2019-01-14 12:11 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +    @patch(
Don't patch methods from a class that is being tested, patch external dependencies instead.

2019-01-15 08:29 UTC, pawelkisielewicz commented on tests/golem/ethereum/test_transactionsystem.py
> +from golem.task.rpc import _validate_lock_funds_possibility
moved to `test_rpc.py`

2019-01-15 08:32 UTC, pawelkisielewicz commented on tests/golem/ethereum/test_transactionsystem.py
> +    @patch(
after moving to `test_rpc.py` there is no need to patch any more. Thanks for comment anyway

2019-01-15 09:47 UTC, Krigpl commented
Payments stuff looks good, leaving the rest to @jiivan

2019-01-16 15:12 UTC, jiivan commented on golem/task/rpc.py
> +            force=force
```suggestion
            force=force,
```

2019-01-16 15:12 UTC, jiivan commented on golem/task/rpc.py
> +        validate_client(self.client)
Maybe `validate_client()` should be called before `prepare_and_validate...`?

2019-01-16 15:12 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +        if self.gas_price >= self._sci.GAS_PRICE:  # type: ignore
```suggestion
        if self.gas_price >= self.gas_price_limit:
```

2019-01-16 15:12 UTC, jiivan commented on tests/golem/task/test_rpc.py
> +def _raise_not_enough_funds(*_, **__):
No need to define function only to raise exception. SEE: https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock

> Alternatively side_effect can be an exception class or instance. In this case the exception will be raised when the mock is called.

2019-01-16 15:12 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +    def validate_concent_deposit_possibility(
Should this method check for `required - self.concent_balance()`?

2019-01-16 15:12 UTC, jiivan commented on golem/task/rpc.py
> +        self.client.transaction_system.validate_concent_deposit_possibility(
What if concent is disabled for this task?

2019-01-17 06:25 UTC, pawelkisielewicz commented on tests/golem/task/test_rpc.py
> +def _raise_not_enough_funds(*_, **__):
:+1: thanks. Removed

2019-01-17 06:29 UTC, pawelkisielewicz commented on golem/ethereum/transactionsystem.py
> +        if self.gas_price >= self._sci.GAS_PRICE:  # type: ignore
done

2019-01-17 09:10 UTC, jiivan commented on golem/task/rpc.py
> +            task.get_total_tasks(),
You could use `task.price`
https://github.com/golemfactory/golem/blob/fd77534db079df22eb68090dddab5ad38bb8bf1e/golem/task/taskbase.py#L118-L120

2019-01-18 09:41 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +            force=force
done

2019-01-18 09:52 UTC, pawelkisielewicz commented on golem/ethereum/transactionsystem.py
> +    def validate_concent_deposit_possibility(
It should. Changed

2019-01-18 10:15 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +        self.client.transaction_system.validate_concent_deposit_possibility(
Check added to `_validate_enough_founds_to_pay_for_task`

2019-01-18 10:32 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +            task.get_total_tasks(),
OK, thanks, didn't know about this. `task.subtask_price`. But `task.get_total_tasks()` has to stay to check ETH

2019-01-24 11:26 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +        eth_to_put_deposit = self.gas_price * self._sci.GAS_TRANSFER_AND_CALL
You can now use `transaction_system.eth_for_deposit()`

2019-01-24 11:38 UTC, pawelkisielewicz commented on golem/task/tasksession.py
> +                    tasks_num=1,
While restarting subtask we should ensure eth for batch transfer for only one task. Is it correct?

2019-01-24 13:19 UTC, pawelkisielewicz commented on golem/ethereum/transactionsystem.py
> +        eth_to_put_deposit = self.gas_price * self._sci.GAS_TRANSFER_AND_CALL
done

2019-02-06 17:26 UTC, kmazurek requested changes

2019-02-06 17:26 UTC, kmazurek commented on golem/ethereum/transactionsystem.py
> +        required_deposit_difference = required - current_concent_deposit
`current_concent_deposit` is not used anywhere else but here, just do: `required_deposit_difference = required - self.concent_balance()`.

2019-02-06 17:26 UTC, kmazurek commented on golem/task/rpc.py
> +    def _validate_enough_founds_to_pay_for_task(
founds -> funds

2019-02-06 17:26 UTC, kmazurek commented on golem/task/rpc.py
> +        transaction_system: TransactionSystem,
Passing the transaction system here is redundant, you can just refer to `self.client.transaction_system` directly.

2019-02-06 17:26 UTC, kmazurek commented on golem/task/rpc.py
> +    eth = transaction_system.eth_for_batch_payment(number_of_tasks)
This should be moved to after the check for available GNT (next to where `eth_available` is initialised).

2019-02-06 17:26 UTC, kmazurek commented on golem/task/rpc.py
> +        min_amount, _ = msg_helpers.requestor_deposit_amount(
Please merge this into a single line

2019-02-06 17:26 UTC, kmazurek commented on golem/task/rpc.py
> +            required_deposit_for_task=min_amount,
There is no such kwarg in `validate_concent_deposit_possibility`, either change this to `required` or rename the expected argument.

2019-02-06 17:26 UTC, kmazurek commented on golem/task/rpc.py
> +                required_deposit_for_task=min_amount,
See previous comment on this, this method expects a different argument name.

2019-02-06 17:26 UTC, kmazurek commented on golem/task/tasksession.py
> +                    required_deposit_for_task=amount,
Same as above, this method expects a different argument name.

2019-02-06 17:26 UTC, zakaprov commented on golem/task/tasksession.py
> +                    tasks_num=1,
Sounds correct, but is this part related to restarting subtasks?

2019-02-08 07:37 UTC, pawelkisielewicz commented on golem/task/tasksession.py
> +                    tasks_num=1,
checking if client has enough ETH for deposit is and was related. Now it is additionally checked gas for transfer, so by restarting I assume that there is one task.

2019-02-08 07:39 UTC, pawelkisielewicz commented on golem/ethereum/transactionsystem.py
> +        required_deposit_difference = required - current_concent_deposit
done

2019-02-08 07:40 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +    def _validate_enough_founds_to_pay_for_task(
done

2019-02-08 08:09 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +        transaction_system: TransactionSystem,
done, converted from function to method

2019-02-08 08:12 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +    eth = transaction_system.eth_for_batch_payment(number_of_tasks)
done

2019-02-08 08:13 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +        min_amount, _ = msg_helpers.requestor_deposit_amount(
done

2019-02-08 08:14 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +            required_deposit_for_task=min_amount,
good catch, done

2019-02-08 08:16 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +                required_deposit_for_task=min_amount,
done

2019-02-08 08:16 UTC, pawelkisielewicz commented on golem/task/tasksession.py
> +                    required_deposit_for_task=amount,
done

2019-02-08 13:33 UTC, kmazurek approved these changes
lgtm

2019-02-08 13:50 UTC, Krigpl approved these changes

2019-02-08 15:11 UTC, Krigpl approved these changes

2019-02-08 15:17 UTC, merged