Don't ask for gntdeposit function when deposit address is unknown
golemfactory/clay pull request #3750
Opened 2019-01-14 12:56 UTC by jiivan

fixes: #3601

2019-01-14 13:04 UTC, Krigpl requested changes
I'd really rather expect these functions not to be called at all when Concent is not supported - this is more direct approach. Returning `None` which has unknown meaning is hacky. Throwing is more sensible as that's what you'd expect when trying to use a service which is offline.

2019-01-16 11:16 UTC, jiivan commented
> I'd really rather expect these functions not to be called at all when Concent is not supported - this is more direct approach. Returning `None` which has unknown meaning is hacky. Throwing is more sensible as that's what you'd expect when trying to use a service which is offline.

OK @Krigpl , now exception is raised. Also concent is disabled when deposit contract is unavailable.

2019-01-17 09:55 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +        try:
Let's just check whether concent is available and only then subscribe to concent events (inside `_subscribe_to_events` method)

2019-01-17 09:55 UTC, Krigpl commented on golem/client.py
> +        if not transaction_system.deposit_contract_available:
When do you expect this will be triggered? My understanding is that the transaction system will have concent address iff it's not disabled, so when can that happen?

2019-01-17 10:15 UTC, jiivan commented on golem/client.py
> +        if not transaction_system.deposit_contract_available:
I believe that traceback from https://github.com/golemfactory/golem/issues/3601 answers your question. :) We don't have contract on mainnet.

2019-01-17 10:19 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +        try:
This would require `TransactionSystem` to learn about either `Client` or `ConcentClientService` (get them in `__init__`). I don't think it's justified.

Now it's just [EAFP](https://docs.python.org/3/glossary.html?highlight=eafp#term-eafp)

2019-01-17 13:49 UTC, Krigpl approved these changes

2019-01-17 13:49 UTC, Krigpl commented on golem/client.py
> +        if not transaction_system.deposit_contract_available:
Does it mean that it can go away once the contract is deployed on mainnet? If so please annotate this with such comment (or file an issue).

2019-01-17 13:49 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +        try:
At this point in the code you are able to just check `if self.deposit_contract_available` so no need for any external dependencies. But I'm not insisting.

2019-01-18 09:34 UTC, merged