deleted geth_address
golemfactory/clay pull request #3760
Opened 2019-01-16 15:44 UTC by ANDREYDEN

Solution to [this](https://github.com/golemfactory/golem/issues/3758) issue.

2019-01-16 15:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=3760) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=3760) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=3760) it.</sub>

2019-01-16 16:10 UTC, Krigpl requested changes
Hi, thank you for your contribution. This is what the issue is about but please fix the tests as well, so they are passing on buildbots.

2019-01-16 16:12 UTC, zakaprov commented
FYI:
```
$ grep -nr "geth_address" .
./node.py:85:                 geth_address: Optional[str] = None,
./node.py:138:            geth_address=geth_address,
./client.py:104:            geth_address: Optional[str] = None,
```

2019-01-22 11:30 UTC, Krigpl commented
Scope has changed, see linked issue for details.

2019-01-22 11:30 UTC, closed without merging