Add additional subtask info
golemfactory/clay pull request #3873
Opened 2019-02-11 12:44 UTC by pawelkisielewicz

Resolves https://github.com/golemfactory/golem/issues/3850

2019-02-11 13:24 UTC, shadeofblue commented on tests/golem/task/test_taskmanager.py
> +        subtask_states['old_subtask_id1'].node_name = 'abcabc'
@pawelkisielewicz could we have `'abcabc'` defined in one place instead of two?

2019-02-11 14:20 UTC, kmazurek requested changes
#3850 was not merged into develop yet and it contains some changes to this code which might be relevant. Please update this once the merge is done.

2019-02-11 14:20 UTC, zakaprov commented on golem/task/rpc.py
> +            address=client.node.pub_addr,
This is not the expected behaviour - the address here should not be the requestor's own address. Now that I think if it, this field should probably stay empty - the state will be updated anyway once the subtask is assigned to a provider and there's no added value in knowing the address of the provider who previously failed on the subtask.

2019-02-11 14:20 UTC, zakaprov commented on golem/task/taskmanager.py
> +            subtask_states: SubtaskState = next(iter(
There's a mapping between new and old subtasks available, you should use it here. please see `subtasks_to_copy` above.

2019-02-12 08:04 UTC, pawelkisielewicz commented on tests/golem/task/test_taskmanager.py
> +        subtask_states['old_subtask_id1'].node_name = 'abcabc'
I thought about it, but didn't want to create a new variable. Changed :+1:

2019-02-12 08:12 UTC, pawelkisielewicz commented on golem/task/rpc.py
> +            address=client.node.pub_addr,
OK, removed. But please check the rest of flow in this function. `address` is used only in `self.__add_subtask_to_tasks_states` and **only in logger:**
```python
logger.debug('add_subtask_to_tasks_states(%r, %r, %r, %r)',
                     node_name, node_id, ctd, address)
```
Do we want to keep this and always log empty string? In this case I think that `address` should be simply removed.

2019-02-12 10:14 UTC, pawelkisielewicz commented on golem/task/taskmanager.py
> +            subtask_states: SubtaskState = next(iter(
OK, I have only question about it. `subtasks_to_copy` is empty unless I pass `subtask_id` as `subtask_ids_to_copy`. And in this case subtask state if Failure. Please give me some more info how to do this. And how should it be called in test:
```python
self.tm.copy_results('old_task_id', 'new_task_id', ['some_subtask_id1 ?? '])
```
or 
```python
self.tm.copy_results('old_task_id', 'new_task_id', [])
```
as previous?

2019-02-12 10:27 UTC, zakaprov commented on golem/task/rpc.py
> +            address=client.node.pub_addr,
Ok, I think that in this case it's fine to remove the `address` parameter.

2019-02-12 11:47 UTC, zakaprov commented on golem/task/taskmanager.py
> +            subtask_states: SubtaskState = next(iter(
You can create a mapping analogous to `subtasks_to_copy` based on the `start_task` field, but for all other subtasks of the original task. Then, for each of the new subtasks created (after the call to `query_extra_data`, which assigns the value of `start_task`) you can try accessing the old subtask state. If that fails for some reason, just put in empty strings as defaults.

2019-03-14 20:50 UTC, shadeofblue commented
@zakaprov @pawelkisielewicz  do you have any idea on the status of this pull request?

2019-03-15 11:26 UTC, zakaprov commented
@shadeofblue There are still some changes left to be done in order for this to work (see the most recent comments from the discussions here).

2019-04-30 14:07 UTC, closed without merging