Merge video
golemfactory/clay pull request #3901
Opened 2019-02-18 07:53 UTC by bidzyyys

2019-02-18 12:27 UTC, weaselix requested changes
- please add some logs (on info and debug level) about merge process
- lines are longer than 80 characters (please make it shorter)
- please add test for the case where one of the chunks is invalid.

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/resources/ffmpeg-scripts/m3u8_utils.py
> +    playlists = [os.path.join('/golem/resources', f) for f in chunks if f.endswith('_TC.m3u8')]
'/golem/resources' -> use `DirManager`

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +        except OSError:
We have no specific handler for OSError here. Just catch Exception (instead of OSError)

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +            raise ffmpegException('Result file does not exist')
We don't know that file does not exist. Try to get that information, please.

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +            resources_dir = task_dir
It appears that it uses `<task_id>/tmp` directory. For my eye it is ok.

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +                                                '/golem/resources'),
- Don't use the constant 'golem/resources'. Use DirManager instead. 
- I suggest not to replace prefix by "string replace method". Construct that path by: `os.path.join(_get_golem_resources(), filename)`. For my eye it is more clear. However, it is my personal opinion.

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +            raise FileNotFoundError
We don't know what file is missing here. We want to know it.

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +            copy2(file, new_path)
We just cannot copy files. Please note that chunk video files can be large.

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +def collect_files(dir, files):
Why it is not private method in StreamOperator?

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +    def prepare_merge_job(task_dir, chunks):
private method?

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +            'output_stream': os.path.join('/golem/output', filename),
'/golem/output' <- probably we can replace it with DirManager.

2019-02-18 12:27 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +    def _specify_dir_mapping(output, temporary, resources, logs, work):
What is the purpose for that you wrapped `DockerTaskThread.specify_dir_mapping`?

2019-02-18 12:27 UTC, rkondziolka commented on tests/apps/ffmpeg/task/test_fmmpegtranscoding.py
> +        with self.assertRaises(OSError):
Perhaps should we wrap catch exception and re-raise it as (for example) TranscondingException?

2019-02-18 12:27 UTC, rkondziolka commented on apps/transcoding/task.py
> +        copy2(path, self.task_definition.output_file)
We cannot copy it. Can we mount specific directories to the container instead?

2019-02-18 17:14 UTC, bidzyyys commented on apps/transcoding/ffmpeg/utils.py
> +def collect_files(dir, files):
It is suggested by PyCharm. Have you thought about benefits from rewriting it to private method?

2019-02-18 17:15 UTC, bidzyyys commented on apps/transcoding/ffmpeg/utils.py
> +            'output_stream': os.path.join('/golem/output', filename),
`/golem/output` is a directory inside docker container

2019-02-18 17:21 UTC, bidzyyys commented on apps/transcoding/ffmpeg/utils.py
> +            copy2(file, new_path)
We should have all video chunks in a single directory that is mounted as `/golem/resources/`. If you are sure that they are collected in the same place, I'll change it.

2019-02-18 17:25 UTC, bidzyyys commented on apps/transcoding/ffmpeg/utils.py
> +                                                '/golem/resources'),
Here I prepare list of video chunks for docker container --- to make them visible I replace the real directory should be replaced by `/golem/resources`

2019-02-18 17:27 UTC, bidzyyys commented on apps/transcoding/ffmpeg/resources/ffmpeg-scripts/m3u8_utils.py
> +    playlists = [os.path.join('/golem/resources', f) for f in chunks if f.endswith('_TC.m3u8')]
`DirManger` does not know anything about `/golem/resources/` (it is path inside docker with video chunks).

2019-02-18 17:33 UTC, bidzyyys commented on apps/transcoding/ffmpeg/utils.py
> +            raise ffmpegException('Result file does not exist')
It is raised by `collect_files` method.

2019-02-18 17:38 UTC, bidzyyys commented on apps/transcoding/ffmpeg/resources/ffmpeg-scripts/m3u8_utils.py
> +    playlists = [os.path.join('/golem/resources', f) for f in chunks if f.endswith('_TC.m3u8')]
I will define constant docker's paths (output, resources and work).

2019-02-18 17:42 UTC, bidzyyys commented on apps/transcoding/ffmpeg/utils.py
> +        except OSError:
I can change it, but `OSError` can be raised by `os.makedis`, no other exception is expected here.

2019-02-19 06:29 UTC, rkondziolka commented on apps/transcoding/ffmpeg/utils.py
> +def collect_files(dir, files):
> Have you thought about benefits from rewriting it to private method?

Yes. In that way you hide implementation details. Your function `collect_files` is a specific  function and should not be available in the interface. You put it in an interface. What is the purpose?

> IMO Python is not strictly object-oriented language
Yes, it is not. And what about it in our specific case?

2019-02-19 06:36 UTC, rkondziolka commented on apps/transcoding/ffmpeg/utils.py
> +            copy2(file, new_path)
I am not sure, but I think you can check it.

2019-02-19 06:37 UTC, rkondziolka commented on apps/transcoding/ffmpeg/resources/ffmpeg-scripts/m3u8_utils.py
> +    playlists = [os.path.join('/golem/resources', f) for f in chunks if f.endswith('_TC.m3u8')]
Yes, you right.

2019-02-19 06:38 UTC, rkondziolka commented on apps/transcoding/ffmpeg/utils.py
> +            raise ffmpegException('Result file does not exist')
Yes, but we would like to know what file is missing (like 'Not found /tmp/test_file.mp4')

2019-02-19 06:39 UTC, rkondziolka commented on apps/transcoding/ffmpeg/utils.py
> +                                                '/golem/resources'),
You right

2019-02-19 06:57 UTC, rkondziolka commented on apps/transcoding/ffmpeg/utils.py
> +            'output_stream': os.path.join('/golem/output', filename),
You can use `DockerJob.RESOURCES_DIR` (instead of `DirManager`- I was wrong here)

2019-02-19 07:28 UTC, rkondziolka commented on apps/transcoding/task.py
> +        if self.num_tasks_received == self.total_tasks:
You need the acquired lock here.

2019-02-19 09:59 UTC, bidzyyys commented on apps/transcoding/ffmpeg/resources/ffmpeg-scripts/m3u8_utils.py
> +    playlists = [os.path.join('/golem/resources', f) for f in chunks if f.endswith('_TC.m3u8')]
Nice, I haven't seen this :+1:

2019-02-19 11:59 UTC, bidzyyys commented on apps/transcoding/task.py
> +        copy2(path, self.task_definition.output_file)
We mount one directory as `/golem/resources/`, so I will check if each file has proper path (and raise `ffmpegException`)

2019-02-19 12:01 UTC, bidzyyys commented on apps/transcoding/ffmpeg/utils.py
> +    def _specify_dir_mapping(output, temporary, resources, logs, work):
To enable specifying custom directories, see `merge_video`

2019-02-19 14:06 UTC, bidzyyys commented on apps/transcoding/ffmpeg/resources/ffmpeg-scripts/m3u8_utils.py
> +    playlists = [os.path.join('/golem/resources', f) for f in chunks if f.endswith('_TC.m3u8')]
Btw this is executed inside docker

2019-02-20 06:53 UTC, weaselix commented on apps/transcoding/ffmpeg/utils.py
> +    def _specify_dir_mapping(output, temporary, resources, logs, work):
Yes, but I can not understand why do you create wrapping method instead using just: `DockerTaskThread.specify_dir_mapping`. I suggest to remove that method (it is redundant).

2019-02-20 06:57 UTC, weaselix commented on apps/transcoding/task.py
> +        copy2(path, self.task_definition.output_file)
If I understand correctly `path` points to the result file (a merged video). Can we move it to the destination instead of copying?

2019-02-20 07:05 UTC, weaselix requested changes
* Some lines are still longer than 80 characters

2019-02-20 14:05 UTC, merged