Identify unit tests that leave temporary data behind and add clean up
golemfactory/clay pull request #3920
Opened 2019-02-21 22:20 UTC by rwrzesien

Resolves https://github.com/golemfactory/golem/issues/3890.

2019-02-22 09:46 UTC, Krigpl reviewed
That looks like the majority of the leftover files comes from the production code that doesn't clean them up rather than anything specific to tests - so it'd be better to look into how to improve production code.

2019-02-22 09:46 UTC, Krigpl commented on tests/apps/blender/task/test_blenderrendertask.py
> +        _, self.blender_file_path = tempfile.mkstemp('.blend')
that could just use `self.tmp_dir` and get cleaned automatically

2019-02-22 09:46 UTC, Krigpl commented on tests/apps/blender/benchmark/test_blenderbenchmark.py
> +            os.remove(self.bb.task_definition.output_file)
that doesn't feel like the right solution here - in production code we still leave this temp file.  imo benchmark classes should clean up after themselves

2019-02-22 09:46 UTC, Krigpl commented on tests/apps/dummy/benchmark/test_dummybenchmark.py
> +            shutil.rmtree(self.db._task_definition.tmp_dir)
same as above

2019-02-22 09:46 UTC, Krigpl commented on tests/golem/docker/test_docker_job.py
> +        self.main_dir = get_local_datadir('tests-' + str(uuid.uuid4()))
Why not just use `self.tmp_dir` here and below ?

2019-02-22 12:53 UTC, rwrzesien commented
@Krigpl 
> That looks like the majority of the leftover files comes from the production code that doesn't clean them up rather than anything specific to tests - so it'd be better to look into how to improve production code.

Probably yes, but a separate issue should be created for that. This one is specifically about cleaning after what unit tests run leaves.

2019-02-22 12:53 UTC, rwrzesien commented on tests/apps/dummy/benchmark/test_dummybenchmark.py
> +            shutil.rmtree(self.db._task_definition.tmp_dir)
See https://github.com/golemfactory/golem/pull/3920#issuecomment-466386794.

2019-02-22 12:53 UTC, rwrzesien commented on tests/apps/blender/benchmark/test_blenderbenchmark.py
> +            os.remove(self.bb.task_definition.output_file)
See https://github.com/golemfactory/golem/pull/3920#issuecomment-466386794.

2019-02-22 12:54 UTC, rwrzesien commented on tests/apps/blender/task/test_blenderrendertask.py
> +        _, self.blender_file_path = tempfile.mkstemp('.blend')
I don't want to modify any existing tests that I am not aware what they are doing and what they suppose to really test.

2019-02-22 12:54 UTC, rwrzesien commented on tests/golem/docker/test_docker_job.py
> +        self.main_dir = get_local_datadir('tests-' + str(uuid.uuid4()))
I don't want to modify any existing tests that I am not aware what they are doing and what they suppose to really test.

2019-02-22 13:43 UTC, Krigpl requested changes
These tests expose an issue with production code and I'm not fine with just applying some bandaid solution to improve tests while sweeping the real problem under the rug.
Please modify `test_docker_job` and `test_blenderrendertask` as suggested, remove all the benchmark related hacks and create an issue to fix leftover benchmarks files.

2019-03-12 16:19 UTC, Krigpl commented
Any progress on that?

2019-05-07 08:10 UTC, mplebanski commented
Can we close this?

2019-05-07 11:23 UTC, squark commented
If the solution for the problem explicitly described as test related in the issue is not acceptable, it should be closed and a new issue opened for fixing production code instead of tests itself.

2019-06-14 09:46 UTC, Krigpl commented
rip [*]

2019-06-14 09:46 UTC, closed without merging