Disabled virtualization check on Linux platforms
golemfactory/clay pull request #3949
Opened 2019-03-04 16:56 UTC by zakaprov

Resolves: #3937

This change skips the virtualization check on Linux systems, always returning positive support status.

2019-03-05 10:13 UTC, mfranciszkiewicz commented on golem/core/virtualization.py
> +        return True
Virtualization is not enabled per se, it's simply not required. I'd treat this fix as temporary. Maybe this call should be simply skipped by the UI?

2019-03-05 10:20 UTC, zakaprov commented on golem/core/virtualization.py
> +        return True
I agree, hence the comment I left there. Another option would be to change this RPC / create a new one specific to the use case (i.e. checking for Docker support).

2019-03-05 10:40 UTC, etam commented on golem/core/virtualization.py
> +        return True
I agree with mfranciszkiewicz. This change makes a weird exception to the simple question "is virtualization enabled?". Instead of complicating the answer, we should fix GUI who asks the bogus question.

2019-03-05 10:42 UTC, etam requested changes
I agree with mfranciszkiewicz. This change makes a weird exception to the simple question "is virtualization enabled?". Instead of complicating the answer, we should fix GUI which asks the wrong question.

2019-03-05 12:42 UTC, zakaprov commented
@shadeofblue: what's your take on this?

2019-03-06 09:47 UTC, shadeofblue commented
sigh... okay @zakaprov please change the name of the function to `is_virtualization_satisfied` or `is_virtualization_requirement_satisfied` ...

2019-03-06 10:30 UTC, etam approved these changes
![ok](https://i.kym-cdn.com/entries/icons/original/000/027/838/Untitled-1.jpg)

2019-03-06 14:13 UTC, merged