Add GLambda app
golemfactory/clay pull request #3978
Opened 2019-03-08 13:30 UTC by mplebanski

RASPA2 use-case related app. Allows user to submit arbitrary python code for provider side execution. It's called RASPA2 because docker environment that executes the script has RASPA2 installed along with python bindings. Therefore it's possible to compute molecular dynamics using python3 + RASPA2 (inspired by [RASPA2 workflow](https://github.com/numat/RASPA2/wiki/Workflow).

2019-04-23 12:59 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +    class VerificationMethod():
Would Enum class not be useful here? Or the string representation is needed for serialisation?

2019-04-23 13:00 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +    MAX_PENDING_CLIENT_RESULTS = 1
Why 1? Could you add a comment explaining the current limitations?

2019-04-23 13:03 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +                 max_pending_client_results=MAX_PENDING_CLIENT_RESULTS,
Hmm, so we have here `MAX_PENDING_CLIENT_RESULTS` as a `const`/`static`, and yet not only can it be overridden in the constructor via `max_pending_client_results` kwarg but we do not check whether `max_pending_client_results` is smaller or equal to `MAX_PENDING_CLIENT_RESULTS`. Looks somewhat counter-intuitive to me.

Should we not either: 1) check if `max_pending_client_results` is indeed less than `MAX_PENDING_CLIENT_RESULTS`, or 2) remove the kwarg altogether?

2019-04-23 13:08 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +        super(GLambdaTask, self).__init__(task_definition, owner,
Is it a mixin that it requires to specify parent in the constructor?

2019-04-23 13:12 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +    def _get_next_task(self) -> Optional[int]:
OK, this method is really confusing. The name would suggest that I'd actually receive the next task (BTW, I think it should use subtask rather than task in the name), but some I receive `Optional[int]`. Also, the fact that you alter `self.last_task` and `self.num_failed_subtasks` doesn't help. Would you care to explain what is the purpose of this method?

2019-04-23 13:14 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +        self.subtasks_given[subtask_id]['start_task'] = start_task
Perhaps unlikely, but still it is possible that `start_task` will be `None`. I'm not sure how well `CoreTask` will handle this :thinking: Perhaps we should throw an exception if we poll for more than there is? At the very least, the message in the error logs should then be more readable :man_shrugging:

2019-04-23 13:17 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +            shutil.move(
What is happening here? Are you moving entire subdirs here?

2019-04-23 13:19 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +        verif_cb()
Hmm, accepting results *before* verifying them? Will this not result in scheduling payment to the provider regardless of the verification status?

2019-04-23 13:23 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +            self.subtasks_given[subtask_id]['verif_cb'] = verification_finished
This will probably result in a serialisation exception, as the base class will want to save its state and `verification_finished` callback is not serialisable.

2019-04-23 13:25 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +        verif_cb()
NVM, I see the invocation path now.

2019-04-23 13:33 UTC, kubkon commented on golem/config/environments/testnet.py
> -    deposit_contract_address = CONCENT_CHOICES[  # type: ignore  #wth mypy?
What happened here? Linting?

2019-04-23 13:45 UTC, kubkon commented on golem/node.py
> +    @rpc_utils.expose('comp.task.result')
As far as I can see (prove me if I'm wrong please!), this allows now to pull results for a task via RPC, yeah?

2019-04-23 13:46 UTC, kubkon commented on golem/node.py
> +    def query_subtask_results(self, task_id, subtask_id):
Does this allow us to pull subtask's results over RPC? If so, why `query_` and not `get_` like in the method below?

2019-04-23 13:47 UTC, kubkon commented on golem/node.py
> +        return 'results-{task_id}'.format(task_id=task_id)
Where does this reside? Is it relative to `pwd`?

2019-04-23 13:51 UTC, kubkon commented on golem/task/result/resultpackage.py
> +            disk_files = self._prepare_file_dict(disk_files)
Did you test what happens when `disk_files` is `None`?

2019-04-23 13:52 UTC, kubkon commented on golem/task/taskmanager.py
> +        self.notice_task_updated(task_id,
How come that is here?

2019-04-23 13:53 UTC, kubkon commented on golem/task/taskmanager.py
> +        logger.warning("external_verify_subtask. subtask_id=%r",
Why warning and not info?

2019-04-23 13:54 UTC, kubkon commented on golem/task/taskmanager.py
> +            return self.tasks[task_id].external_verify_subtask(subtask_id,
Funny, without #4104 this actually might fail -> task closed before the last subtask, and then `task_id` is `None` :grin:

2019-04-23 13:56 UTC, kubkon commented on golem/tools/remotefs.py
> +    def __init__(self, _fs, upload_ctrl):
`_fs` as the input arg? Is that a standard naming convention in Python?

2019-04-23 14:00 UTC, kubkon commented on golem/tools/uploadcontroller.py
> +            'chunk_size': 131072*4,
Why 131072 * 4? Could you add a note explaining that particular choice for chunk size?

2019-04-23 14:01 UTC, kubkon commented on golem/tools/uploadcontroller.py
> +    def download(self, _id):
Again, `_id` as arg.

2019-04-23 14:01 UTC, kubkon commented on golem/tools/uploadcontroller.py
> +    def upload(self, _id, data):
Again, `_id` as arg.

2019-04-23 14:07 UTC, kubkon requested changes
LGTM, just a couple of things!

2019-04-24 08:36 UTC, jiivan commented
@kubkon https://docs.pylint.org/en/1.9/faq.html#i-have-a-callback-function-where-i-have-no-control-over-received-arguments-how-do-i-avoid-getting-unused-argument-warnings

2019-04-29 12:44 UTC, jiivan reviewed
Looks good. What is left is only my nitpicking. :)

2019-04-29 12:44 UTC, jiivan commented on Installer/Installer_Linux/install.sh
>  CURRENT_VERSION="0.1.0"
Shouldn't it be bumped up?

2019-04-29 12:44 UTC, jiivan commented on apps/glambda/benchmark/benchmark.py
> +        return self._task_definition
IMO this is just obfuscation. Setting `self.task_definition` in `__init__` would be enough.

2019-04-29 12:44 UTC, jiivan commented on apps/glambda/benchmark/benchmark.py
> +        return self._normalization_constant
I assume your intent was to make `_normalization_constant` RO, but in reality it's just obfuscation that adds some computational effort while accessing this attribute.

2019-04-29 12:44 UTC, jiivan commented on apps/glambda/resources/images/Dockerfile
> +    git clone https://github.com/numat/RASPA2.git && \
Maybe explicit commit or tag would be more stable?

2019-04-29 12:44 UTC, jiivan commented on apps/glambda/resources/scripts/job.py
> +from __future__ import print_function
Is it executed under PY2?

2019-04-29 12:44 UTC, jiivan commented on apps/glambda/task/glambdatask.py
> +        super(GLambdaTask, self).__init__(task_definition, owner,
```suggestion
        super().__init__(task_definition, owner,
```

2019-04-29 12:44 UTC, jiivan commented on apps/glambda/task/glambdatask.py
> +        if self.last_task != self.total_tasks:
```suggestion
        if self.last_task < self.total_tasks:
```

2019-04-29 12:44 UTC, jiivan commented on golem/client.py
> +    def verify_sutbask(self, subtask_id, verdict):
Please expose it in `task_manager` and remove it from client.

2019-04-29 12:44 UTC, jiivan commented on golem/tools/uploadcontroller.py
> +    # TODO add size control logic
Please link github issue in this comment

2019-05-06 09:37 UTC, mplebanski commented on apps/glambda/task/glambdatask.py
> +    MAX_PENDING_CLIENT_RESULTS = 1
In current version we have 1 to 1 task - subtask relation, this is subject to change when introducing usage market. Is this explanation clear?

2019-05-06 09:38 UTC, mplebanski commented on apps/glambda/task/glambdatask.py
> +    class VerificationMethod():
String in JSON is more readable for debugging. This is no overhead since this message is exchanged only once per subtask result.

2019-05-06 09:39 UTC, mplebanski commented on apps/glambda/task/glambdatask.py
> +        super(GLambdaTask, self).__init__(task_definition, owner,
Are you asking about `GLambdaTask` class name?

2019-05-06 09:41 UTC, mplebanski commented on apps/glambda/task/glambdatask.py
> +                 max_pending_client_results=MAX_PENDING_CLIENT_RESULTS,
Good point. I will take the second approach and remove kwarg from `GLambdaTask` constructor.

2019-05-06 10:09 UTC, mplebanski commented on apps/glambda/task/glambdatask.py
> +    def _get_next_task(self) -> Optional[int]:
I will refactor this method. Historically I've taken it from CoreTask, but it's true that it is a bit confusing.

2019-05-06 11:32 UTC, mplebanski commented on apps/glambda/task/glambdatask.py
> +        self.subtasks_given[subtask_id]['start_task'] = start_task
This will be changed in get_next_task refactoring effort.

2019-05-06 11:39 UTC, mplebanski commented on apps/glambda/task/glambdatask.py
> +            shutil.move(
I renamed the method to `_move_subtask_results_to_task_output_dir` and added an appropriate comment. Please see if this is clear now.

2019-05-06 11:41 UTC, mplebanski commented on golem/config/environments/testnet.py
> -    deposit_contract_address = CONCENT_CHOICES[  # type: ignore  #wth mypy?
Yes exactly. For all linter related changes there is a separate commit in this PR.

2019-05-06 11:46 UTC, mplebanski commented on golem/node.py
> +    @rpc_utils.expose('comp.task.result')
Yes, everything that is listed in `state.outputs` of the task.

2019-05-06 11:47 UTC, mplebanski commented on golem/node.py
> +    def query_subtask_results(self, task_id, subtask_id):
Fixed.

2019-05-06 11:52 UTC, mplebanski commented on golem/node.py
> +        return 'results-{task_id}'.format(task_id=task_id)
RemoteFS class uses TempFS (see how it's instantiated in `node.py`) from (pyfilesystem)[https://docs.pyfilesystem.org/en/latest/]. It's a path in the root of your concrete FS implementation. For TempFS, a memory FS provided by the library, it resides in `/tmp`.

2019-05-06 11:55 UTC, mplebanski commented on golem/task/taskmanager.py
> +        self.notice_task_updated(task_id,
It informs everyone subscribed to subtask related about subtask entering verification state. Before this addition it was a silent state change.

2019-05-06 11:56 UTC, mplebanski commented on golem/task/result/resultpackage.py
> +            disk_files = self._prepare_file_dict(disk_files)
Yes it works just fine. An empty resources is created. Why?

2019-05-06 11:57 UTC, mplebanski commented on golem/task/taskmanager.py
> +        logger.warning("external_verify_subtask. subtask_id=%r",
Fixed.

2019-05-06 12:03 UTC, mplebanski commented on golem/tools/remotefs.py
> +    def __init__(self, _fs, upload_ctrl):
Renaming it to `fs_` as per "Descriptive naming styles" of PEP8.

2019-05-06 12:03 UTC, mplebanski commented on golem/tools/uploadcontroller.py
> +    def download(self, _id):
Renaming it to `id_` as per "Descriptive naming styles" of PEP8.

2019-05-06 12:04 UTC, mplebanski commented on golem/tools/remotefs.py
> +    def __init__(self, _fs, upload_ctrl):
Renaming it to `filesystem`.

2019-05-06 12:27 UTC, mplebanski commented on golem/tools/uploadcontroller.py
> +            'chunk_size': 131072*4,
This is 512kB, big enough chunk size that I found (bisected) to be working with autobahn.

2019-05-06 12:29 UTC, mplebanski commented on Installer/Installer_Linux/install.sh
>  CURRENT_VERSION="0.1.0"
This thing has not been changed in the installation script for 3 years now. What do you suggest?

2019-05-06 13:36 UTC, kubkon commented on apps/glambda/task/glambdatask.py
> +        super(GLambdaTask, self).__init__(task_definition, owner,
Nvm, I've misinterpreted it!

2019-05-06 13:40 UTC, kubkon commented on golem/node.py
> +    @rpc_utils.expose('comp.task.result')
Great!

2019-05-06 13:41 UTC, kubkon commented on golem/task/result/resultpackage.py
> +            disk_files = self._prepare_file_dict(disk_files)
Just checking!

2019-05-06 13:42 UTC, kubkon commented on golem/tools/uploadcontroller.py
> +            'chunk_size': 131072*4,
Hmm, I still believe it'd be good to add a comment explaining exactly that.

2019-05-06 13:51 UTC, mplebanski commented on apps/glambda/benchmark/benchmark.py
> +        return self._task_definition
`task_definition` and `normalization_constant` are two abstract methods that must be implemented in derived class. That's why they are defined here. Based on what I said can it be resolved?

2019-05-06 13:52 UTC, mplebanski commented on apps/glambda/benchmark/benchmark.py
> +        return self._normalization_constant
Same comment as for `task_definition`.

2019-05-06 13:52 UTC, mplebanski commented on apps/glambda/resources/images/Dockerfile
> +    git clone https://github.com/numat/RASPA2.git && \
Will do.

2019-05-06 16:26 UTC, mplebanski commented on golem/client.py
> +    def verify_sutbask(self, subtask_id, verdict):
Done.

2019-05-06 16:26 UTC, mplebanski commented on apps/glambda/resources/scripts/job.py
> +from __future__ import print_function
Not really, good point.

2019-05-06 16:26 UTC, mplebanski commented on apps/glambda/task/glambdatask.py
> +        super(GLambdaTask, self).__init__(task_definition, owner,
Done.

2019-05-07 09:12 UTC, mplebanski commented on golem/tools/uploadcontroller.py
> +            'chunk_size': 131072*4,
Done.

2019-05-07 09:13 UTC, mplebanski commented on golem/task/taskmanager.py
> +        self.notice_task_updated(task_id,
Any more questions regarding that?

2019-05-07 09:13 UTC, mplebanski commented on apps/glambda/task/glambdatask.py
> +    def _get_next_task(self) -> Optional[int]:
Done.

2019-05-07 09:23 UTC, mplebanski commented on golem/tools/uploadcontroller.py
> +    # TODO add size control logic
Done.

2019-05-07 10:40 UTC, kubkon commented on golem/task/taskmanager.py
> +        self.notice_task_updated(task_id,
Nah, looks good!

2019-05-07 10:57 UTC, kubkon approved these changes

2019-05-08 10:42 UTC, jiivan commented on Installer/Installer_Linux/install.sh
>  CURRENT_VERSION="0.1.0"
Prolly just ignore this.

2019-05-08 10:46 UTC, jiivan approved these changes
![dygnij](https://user-images.githubusercontent.com/293058/57369961-41389500-718f-11e9-8c21-9ee7789e52b0.gif)

2019-05-08 11:09 UTC, kubkon approved these changes

2019-05-08 11:11 UTC, kubkon approved these changes

2019-05-08 11:47 UTC, kubkon approved these changes

2019-05-08 12:00 UTC, kubkon approved these changes

2019-05-08 15:10 UTC, kubkon approved these changes

2019-05-08 15:13 UTC, kubkon approved these changes

2019-05-09 13:14 UTC, kubkon approved these changes

2019-05-09 13:29 UTC, mbenke commented on apps/glambda/resources/scripts/job.py
> +import cloudpickle
why cloudpickle?

2019-05-09 13:31 UTC, mplebanski commented on apps/glambda/resources/scripts/job.py
> +import cloudpickle
```Among other things, cloudpickle supports pickling for lambda functions along with functions and classes defined interactively in the __main__ module```

2019-05-09 13:32 UTC, mbenke approved these changes

2019-05-09 13:55 UTC, kubkon approved these changes

2019-05-09 14:46 UTC, mfranciszkiewicz commented
`control_build` was successful: https://buildbot.golem.network/buildbot/#/builders/2/builds/4270

2019-05-09 15:11 UTC, mplebanski commented
```
python -m pytest --runslow tests
1617 passed, 12 skipped in 374.41 seconds.
```

2019-05-09 15:12 UTC, mplebanski commented
@mfranciszkiewicz Thanks for the control_build

2019-05-09 15:14 UTC, merged