Refactor simplify classes in terms of verification data usage
golemfactory/clay pull request #3982
Opened 2019-03-11 11:33 UTC by pawelkisielewicz

Resolves first part of https://codepoets.atlassian.net/browse/GF-76 - pass `verification_data` in constructor

2019-03-13 08:28 UTC, dybi reviewed
Generally, I would suggest not to keep whole `verification_data`, but to use it to initialize
 ```python
self.subtask_info = verification_data['subtask_info']
        self.resources = verification_data['resources']
        self.results = verification_data['results']`
```

2019-03-13 08:28 UTC, dybi commented on golem/verificator/core_verifier.py
> +        self.subtask_info = self.verification_data['subtask_info']
please mov it to `__init__()`

2019-03-13 08:28 UTC, dybi commented on golem/verificator/rendering_verifier.py
> +        subtask_info = self.verification_data['subtask_info']
once it is in `CoreVerivier.__init__()`, it can be deleted from here

2019-03-14 13:25 UTC, pawelkisielewicz commented on golem/verificator/core_verifier.py
> +        self.subtask_info = self.verification_data['subtask_info']
done

2019-03-14 13:25 UTC, pawelkisielewicz commented on golem/verificator/rendering_verifier.py
> +        subtask_info = self.verification_data['subtask_info']
done

2019-03-15 14:56 UTC, dybi requested changes
the tests are failing - you haven't changed `TestBlenderVerifier` tests;
please fetch and merge `origin/verifier-cleanup/master` into your branch and make sure tests and lint pass
NOTE:
don't forget to run "slowtests": `pytest   --runslow tests/golem/verificator/`

2019-03-15 14:56 UTC, dybi commented on tests/apps/blender/task/test_blenderrendertask.py
> +            result['extra_data']['results'] = list(self.bt.results.values())[0]
it looks like the type was changed here. Can you explain?

2019-03-18 07:53 UTC, pawelkisielewicz commented on tests/apps/blender/task/test_blenderrendertask.py
> +            result['extra_data']['results'] = list(self.bt.results.values())[0]
no, the type is the same. It was `string` and is `string` now

2019-03-18 09:55 UTC, dybi approved these changes

2019-03-18 09:56 UTC, merged