Simplify overriding structure
golemfactory/clay pull request #3986
Opened 2019-03-12 12:56 UTC by pawelkisielewicz

Resolves second (last) part of https://codepoets.atlassian.net/browse/GF-76

2019-03-19 09:25 UTC, dybi requested changes
There is some doubts to clarify and some small improvements to be made.

2019-03-19 09:25 UTC, dybi commented on tests/golem/verificator/test_renderingverifier.py
> +        self.assertFalse(result)
please adhere to the existing style of asserts:
```suggestion
        assert result is False
```

2019-03-19 09:25 UTC, dybi commented on tests/golem/verificator/test_renderingverifier.py
> +        self.assertFalse(result)
please adhere to the existing style of asserts:
```suggestion
        assert result is False
```

2019-03-19 09:25 UTC, dybi commented on tests/golem/verificator/test_renderingverifier.py
> +        self.assertFalse(result)
please adhere to the existing style of asserts:
```suggestion
        assert result is False
```

2019-03-19 09:25 UTC, dybi commented on tests/golem/verificator/test_renderingverifier.py
> +        self.assertTrue(rendering_verifier.simple_verification())
please change assert style so it is coherent with the rest of the cod ein this module

2019-03-19 09:25 UTC, dybi commented on tests/golem/verificator/test_renderingverifier.py
> -        # Result is not a file
:+1:

2019-03-19 09:25 UTC, dybi commented on tests/golem/verificator/test_renderingverifier.py
> -        # Result is not an image
:+1:

2019-03-19 09:25 UTC, dybi commented on tests/golem/verificator/test_core_verifier.py
> +        self._check_state(False)
please use it with explicit keyword argument (`self._check_state(expected_result=False)`) - the intent becomes more obvious

2019-03-19 09:25 UTC, dybi commented on tests/golem/verificator/test_core_verifier.py
> +        self.assertIs(result, expected_result)
again, please use existing assertions style

2019-03-19 09:25 UTC, dybi commented on golem/verificator/core_verifier.py
> +        self.results = verification_data['results']
it seems that after adding `self.results` and `self.subtask_info` fields, `self.verification_data` is not needed anymore...

2019-03-19 09:25 UTC, dybi commented on golem/verificator/rendering_verifier.py
> +        for _ in self.results:
you don't need this `for` loop - tou iterate over results within `_are_image_sizes_correct()`

2019-03-19 09:25 UTC, dybi commented on golem/verificator/rendering_verifier.py
> +        self.resources = verification_data['resources']
it seems that `self.resources` are not used anywhere... neither in this class nor in `CoreVerifier`

2019-03-19 09:25 UTC, dybi commented on golem/verificator/rendering_verifier.py
>              if not self.check_size(image, resolution_x, resolution_y):
in `check_size()` only x dimension is checked... what about y?

2019-03-19 09:25 UTC, dybi commented on tests/golem/verificator/test_core_verifier.py
> +        self.core_verifier.simple_verification()
why is it called (and result is ignored)?

2019-03-20 09:34 UTC, pawelkisielewicz commented on tests/golem/verificator/test_renderingverifier.py
> +        self.assertFalse(result)
done

2019-03-20 09:34 UTC, pawelkisielewicz commented on tests/golem/verificator/test_renderingverifier.py
> +        self.assertFalse(result)
done

2019-03-20 09:34 UTC, pawelkisielewicz commented on tests/golem/verificator/test_renderingverifier.py
> +        self.assertFalse(result)
done

2019-03-20 09:35 UTC, pawelkisielewicz commented on tests/golem/verificator/test_renderingverifier.py
> +        self.assertTrue(rendering_verifier.simple_verification())
done

2019-03-20 09:35 UTC, pawelkisielewicz commented on tests/golem/verificator/test_renderingverifier.py
> -        # Result is not a file
:)

2019-03-20 09:38 UTC, pawelkisielewicz commented on tests/golem/verificator/test_core_verifier.py
> +        self._check_state(False)
done

2019-03-20 09:39 UTC, pawelkisielewicz commented on tests/golem/verificator/test_core_verifier.py
> +        self.assertIs(result, expected_result)
done

2019-03-20 09:48 UTC, pawelkisielewicz commented on golem/verificator/core_verifier.py
> +        self.results = verification_data['results']
It was used, but it was easy to change this to other fields and don't use any more. Good catch :+1:

2019-03-20 09:54 UTC, pawelkisielewicz commented on golem/verificator/rendering_verifier.py
> +        for _ in self.results:
good catch, done

2019-03-20 09:56 UTC, pawelkisielewicz commented on golem/verificator/rendering_verifier.py
> +        self.resources = verification_data['resources']
done

2019-03-20 10:47 UTC, pawelkisielewicz commented on golem/verificator/rendering_verifier.py
>              if not self.check_size(image, resolution_x, resolution_y):
good question, didn't payd attention to it. Fixed

2019-03-20 10:49 UTC, pawelkisielewicz commented on tests/golem/verificator/test_core_verifier.py
> +        self.core_verifier.simple_verification()
it was used before, but after final changes is not required any more. Deleted

2019-03-20 11:19 UTC, pawelkisielewicz commented on golem/verificator/rendering_verifier.py
>              if not self.check_size(image, resolution_x, resolution_y):
After this change there is failing test `TestBlenderFrameTask.test_computation_failed_or_finished`. I investigated this and problem is that method `_get_part_size` in blender_verifier returns resolution y = 0. @dybi you recently wrote tests for this method. Could you run this tests and help me top investigate, where is the problem?

2019-03-25 10:50 UTC, pawelkisielewicz commented on golem/verificator/rendering_verifier.py
>              if not self.check_size(image, resolution_x, resolution_y):
as discussed, done in separate commit

2019-03-25 10:51 UTC, dybi approved these changes
![bapprove](https://user-images.githubusercontent.com/36961162/54913979-42ba4080-4ef4-11e9-9505-d9d11867d07e.gif)

2019-03-25 10:51 UTC, dybi commented on golem/verificator/blender_verifier.py
> +        # subtask_info = self.verification_data['subtask_info']
please remove comment

2019-03-25 10:51 UTC, dybi commented on golem/verificator/core_verifier.py
> -        self.state = SubtaskVerificationState.VERIFIED
Was it deleted accidentally or else what would be the reason?

2019-03-25 10:51 UTC, dybi commented on golem/verificator/rendering_verifier.py
> -        self.state = SubtaskVerificationState.VERIFIED
same here - shouldn't it stay?

2019-03-25 10:51 UTC, dybi commented on tests/golem/verificator/test_core_verifier.py
> +        assert result == expected_result
```suggestion
        assert result is expected_result
```

2019-03-25 10:53 UTC, pawelkisielewicz commented on golem/verificator/blender_verifier.py
> +        # subtask_info = self.verification_data['subtask_info']
done

2019-03-25 10:55 UTC, pawelkisielewicz commented on golem/verificator/core_verifier.py
> -        self.state = SubtaskVerificationState.VERIFIED
state `VERIFIED` is set in `start_verification` after positive result of `simple_verification`. It should be deleted from here

2019-03-25 10:56 UTC, pawelkisielewicz commented on golem/verificator/rendering_verifier.py
> -        self.state = SubtaskVerificationState.VERIFIED
no, explanation is above

2019-03-25 10:57 UTC, pawelkisielewicz commented on tests/golem/verificator/test_core_verifier.py
> +        assert result == expected_result
right, done

2019-03-25 10:58 UTC, merged