Fixed virtualization detection on Windows
golemfactory/clay pull request #4025
Opened 2019-03-20 11:08 UTC by zakaprov

Adds handling of a scenario where Hyper-V is installed, but has been
manually disabled by the user. Additionally, this removes the call to
WMI, since when Hyper-V is on it reports hardware virtualization as disabled.

2019-03-20 12:56 UTC, Wiezzel reviewed
Is the new version intended to work for Hyper-V only? What about DockerToolbox support?

2019-03-20 13:11 UTC, zakaprov commented
@Wiezzel I did not take Docker Toolbox into account, but that's also true for the previous version of this script. My understanding is that the script should return true if either Hyper-V or Docker Toolbox is available. Is that correct?

2019-03-20 13:14 UTC, Wiezzel commented
According to my knowledge the new version of the script will return `False` even if DockerToolbox is installed and virtualization enabled in BIOS.

2019-03-20 13:18 UTC, zakaprov commented
Ok, understood - let me bring back that check.

2019-03-20 13:57 UTC, Wiezzel approved these changes
Seems OK now.

2019-03-20 14:21 UTC, Wiezzel requested changes

2019-03-20 14:21 UTC, Wiezzel commented on golem/docker/hypervisor/hyperv.py
> +                script=os.path.join(
Please, extract this path into a constant like `GET_VSWITCH_SCRIPT_PATH `.

2019-03-21 08:19 UTC, Wiezzel approved these changes
Alright now.

2019-03-21 08:43 UTC, merged