[WIP] Multinode integration tests
golemfactory/clay pull request #4058
Opened 2019-03-29 15:48 UTC by etam

This refactoring will allow having more nodes in integration tests.

Porting status:
- concent
  - [ ] additional_verification
  - [ ] force_accept
  - [ ] force_download
  - [ ] force_payment
  - [ ] force_report
- golem
  - [x] exr
  - [x] jpeg
  - [x] jpg
  - [x] no_concent
  - [x] regular_run
  - [x] regular_run_stop_on_reject
  - [x] restart_frame
  - [ ] rpc_test
  - [ ] task_timeout
  - [ ] zero_price

2019-03-29 15:50 UTC, etam commented on scripts/node_integration_tests/params.py
> +from copy import copy
Don't pay much attention to this file. It will be deleted.

2019-03-29 15:51 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> -from pathlib import Path
This file was renamed to `playbook_base.py`. It was so much changed, that github doesn't count this as a rename and edit, but deletion and addition of files.

2019-03-29 15:53 UTC, etam commented on scripts/node_integration_tests/playbooks/golem/restart_frame.py
> +        requestor_config_2 = deepcopy(requestor_config)
I'm not quite happy with how it turned out. See `test_base.py` for more comments.

2019-03-29 15:56 UTC, etam commented on scripts/node_integration_tests/playbooks/test_base.py
> +                        'GOLEM_REQUESTOR_RPC_PORT', '61000')),
Where are those env variables used?

I'm not quite happy with this, because it discourages creating `NodeConfig` instances in tests and encourages editing those created here.

2019-03-29 17:41 UTC, shadeofblue commented on scripts/node_integration_tests/helpers.py
> +def _params_from_dict(d: typing.Dict[str, typing.Any]) -> typing.List[str]:
@etam couldn't we have used `params_from_dict` from `node_integration_tests.params`?

2019-03-29 17:44 UTC, shadeofblue commented on scripts/node_integration_tests/helpers.py
> +def run_golem_node(node_type: str, args: typing.Dict[str, typing.Any]) \
@etam why exactly have we gotten rid of the `nodes_root` parameter?

2019-03-29 17:46 UTC, shadeofblue commented on scripts/node_integration_tests/params.py
> +from copy import copy
@etam could you elaborate on why?

2019-03-29 17:48 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> -from pathlib import Path
@etam still, why rename the file for the sake of renaming? even if github treats that the same?

2019-03-29 17:52 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/golem/regular_run_stop_on_reject.py
> +class RegularRun(DebugTest):
@etam could you elaborate on exact reason for such a deep rewrite? plus, haven't you considered discussing any rewrites of similar magnitude before actually emarking on such a quest? ... I know somehow almost complete rewrites are needed but it's not okay if they're done with no prior discussion et al .. especially that this change WILL cause conficts with branches containing test not migrated to the new structure

2019-03-29 17:56 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/test_base.py
> +                        'GOLEM_REQUESTOR_RPC_PORT', '61000')),
@etam I'm unsure what `NodeConfig` is but those tests are designed so they can work with existing golem installations and those env variables allow that

2019-03-29 18:00 UTC, shadeofblue commented
I'm generally unconvinced that such a deep rewrite was indeed _required_ to satisfy the original premise... and especially that a complete, conflict-prone and backwards-incompatible refactoring of each and every playbook is justified for the sake of a single test...

2019-03-29 18:02 UTC, shadeofblue commented
plus @etam if you really think that adding type hints for the sake of adding type hints is indeed needed, please do so in a _separate_ pull request ...

2019-04-01 09:02 UTC, etam commented
we agreed to make as separate PRs:
- excessive type annotations
- separate config from internal state of NodeTestPlaybook and convert `params.py` into config.

and restore `nodes_root`

2019-04-01 09:04 UTC, etam commented
Ideas to explore:
- Rename `Test` to `TestConfig` and merge it with `Config`.
- Keep playbook and config in separate files. If test has only config, then it could be a single file. Otherwise they should be in a subfolder.

2019-04-04 15:39 UTC, etam commented
Separation of config from playbook: #4088

2019-04-23 10:56 UTC, kmazurek commented on scripts/node_integration_tests/playbooks/base.py
> +        if not opts:
I think it could be worth printing a message about the lack of options in this case.

2019-04-23 10:56 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/base.py
>              if len(result) > 1:
Does this still apply in the case of multinode tests?

2019-04-23 13:52 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +        if not opts:
Maybe? The lack of options is a default value, so it would be an unnecessary noise. If you have options, you get a success or failure message. You know what your `opts` are, so you know what to expect.

2019-04-23 13:53 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
>              if len(result) > 1:
No. Apparently I need to create a simple multinode test and make sure it works.

2019-04-23 14:14 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/base.py
>              if len(result) > 1:
Got it.

2019-04-23 14:16 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/base.py
> +        if not opts:
Right, I missed the fact it's the default. Never mind then, let's leave that as it is.

2019-04-24 06:58 UTC, shadeofblue commented on scripts/node_integration_tests/README.md
> +default configuration for tests. But it is possible to define any number of
```suggestion
default configuration for tests. If needed, it is possible to define any number of
```

2019-04-24 07:02 UTC, shadeofblue commented on scripts/node_integration_tests/run_test.py
> +class DictAction(argparse.Action):
comment required on how this works as it's not obvious at first glance

2019-04-24 07:03 UTC, shadeofblue commented on scripts/node_integration_tests/run_test.py
> +        '--datadir',
what's the `--help` output here?

2019-04-24 08:46 UTC, etam commented on scripts/node_integration_tests/run_test.py
> +        '--datadir',
```
  --datadir NODE PATH   override datadir path for given node
```

2019-04-24 09:56 UTC, etam commented on scripts/node_integration_tests/run_test.py
> +class DictAction(argparse.Action):
done

2019-04-24 11:26 UTC, etam commented on scripts/node_integration_tests/run_test.py
> +        '--datadir',
I've also updated README

2019-04-26 09:43 UTC, kmazurek approved these changes
![nod](https://media.giphy.com/media/tsgNNs93oIbwk/giphy.gif)

2019-04-26 09:43 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/golem/multinode_regular_run/playbook.py
> +    initial_steps: typing.Tuple = (
Idea: change playbook steps to a list instead of a tuple to allow for generating repetitive steps (e.g. common initial steps for tests of a certain type).

2019-04-26 10:42 UTC, etam commented on scripts/node_integration_tests/playbooks/golem/multinode_regular_run/playbook.py
> +    initial_steps: typing.Tuple = (
I like the idea. I'll make a separate PR, once this is merged.

2019-04-29 12:28 UTC, kmazurek approved these changes

2019-04-30 12:46 UTC, shadeofblue commented on scripts/node_integration_tests/README.md
> +            [--datadir NODE PATH] [--mainnet] test_path
@etam please provide a usage example for a test that uses more than one node so that it's more clear of how exactly the roles and their datadirs should be specified

2019-04-30 12:46 UTC, shadeofblue commented on scripts/node_integration_tests/README.md
> +  --datadir NODE PATH   override datadir path for given node
maybe we should mention the "standard" node names here?

2019-04-30 12:56 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +        return repr(self.current_step_method)
hmm - won't it result in:

```
<bound method Playbook.some_method of <__main__.Playbook object at 0x7f4ef7ac8b38>>
```

?

2019-04-30 12:57 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +        return repr(self.current_step_method)
or alternatively - what's the motivation behind this change?

2019-04-30 12:59 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def _success(self):
why suddenly hidden?

2019-04-30 13:01 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_get_node_key(self, node_id: NodeId):
@etam I guess, generally, we could just remove `_node` from those step names as, usually, they all refer to some activity against one node or another...

2019-04-30 13:02 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +                print(f"{node_id.value}'s port: {port}")
@etam why have we removed all the other ports?

2019-04-30 13:06 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_ensure_node_network(self, node_id: NodeId):
hmm... @etam how is this method different than `step_get_node_network_info` after refactoring?

2019-04-30 13:11 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +                    print(f"Expected peer: {expected_peer_key} not in connected"
I think the check (and the message) should rather verify if there aren't any _unexpected_ nodes connected ...

I can imagine a situation when we're waiting for several nodes to connect and they are unable to do that all immediately resulting in some joining right away and some of them after a short delay ... it wouldn't be an issue for the test as a whole if someone was still not connected after the first one succeeded ... but it _would_ be an issue if a completely unexpected node from outside the test network connected here...

2019-04-30 13:16 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_get_known_tasks(self, node_id: NodeId):
actually, here, when in almost _all_ cases this will be used against a requestor, I think the default for `node_id` should be `NodeId.requestor` and then, the step could be defined without `partial` in the list below and only ever overridden if indeed it needs to be called for a different node

2019-04-30 13:18 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +        return repr(self.current_step_method)
The motivation is that `partial` object has no `__name__`

2019-04-30 13:19 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_create_task(self, node_id: NodeId):
same here:

```suggestion
    def step_create_task(self, node_id: NodeId = NodeId.requestor):
```

2019-04-30 13:19 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_get_task_id(self, node_id: NodeId):
and here

2019-04-30 13:19 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_get_task_status(self, node_id: NodeId):
ditto

2019-04-30 13:19 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_wait_task_finished(self, node_id: NodeId):
+

2019-04-30 13:20 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +        return repr(self.current_step_method)
and it will result in:
```
<function Foo.foo at 0x7fa5b44aaa60>
functools.partial(<function Foo.foo at 0x7fa5b44aaa60>, i=5)
```

2019-04-30 13:22 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/concent/concent_base.py
> +    def step_ensure_node_concent_on(self, node_id: NodeId):
again, I think `_node` is superfluous

2019-04-30 13:24 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/golem/multinode_regular_run/playbook.py
> +    initial_steps: typing.Tuple = (
pls, don't do that - I believe it is a good part of those playbooks readability that those steps are rather explicit

2019-04-30 13:29 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +    def _success(self):
I made a separate commit for this: 02052aafa86f881ce00e159e9801045216db1700

Observation 1: All tests are composed of steps. If all steps are successful, then the whole test is successful.
Observation 2: When writing tests it caught me by surprise, that the tests was ending at one step, that wasn't the last one. It turned out that it was calling `success`, what was terminating the test.

Conclusion: I changed the logic, that every step calls `next`. If a step was the last one, `_success` is called from inside `next`.

2019-04-30 13:30 UTC, shadeofblue requested changes
comments added

2019-04-30 13:37 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +        return repr(self.current_step_method)
@etam ugh... and no better way to present that so that it outputs just `foo` ?

2019-04-30 13:38 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def _success(self):
:+1: 

ah, so yeah, we need to remove the "ran out of steps" check in `run`

2019-04-30 14:34 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +    def _success(self):
done

2019-04-30 14:38 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +                print(f"{node_id.value}'s port: {port}")
Which other ports?

2019-04-30 14:50 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_ensure_node_network(self, node_id: NodeId):
The same as before refactoring. `step_get_node_network_info` saves port number in `self.nodes_ports`. `step_ensure_node_network` just checks if any port is returned.

So yes, they are very similar and `step_ensure_node_network` could be deleted.

2019-04-30 14:51 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_get_known_tasks(self, node_id: NodeId):
:+1:

2019-05-06 08:00 UTC, etam commented on scripts/node_integration_tests/README.md
> +            [--datadir NODE PATH] [--mainnet] test_path
done

2019-05-06 08:00 UTC, etam commented on scripts/node_integration_tests/README.md
> +  --datadir NODE PATH   override datadir path for given node
done

2019-05-06 08:24 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +        return repr(self.current_step_method)
okay, maybe ... 

```
method = self.current_step_method
if hasattr(method, 'func'):
    method = getattr(method, 'func')
return getattr(method, '__name__', '')
```

2019-05-06 08:30 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +                print(f"{node_id.value}'s port: {port}")
@etam ??? ... those that you removed from the previous output

2019-05-06 08:31 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_ensure_node_network(self, node_id: NodeId):
so yeah, please unify them

2019-05-06 08:31 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +                    print(f"Expected peer: {expected_peer_key} not in connected"
@etam ^ ?

2019-05-06 08:32 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_get_node_key(self, node_id: NodeId):
@etam ^

2019-05-06 08:37 UTC, shadeofblue commented on scripts/node_integration_tests/README.md
> +nodes. Example: `run_test.py --datadir requestor /tmp/foo --datadir provider /tmp/bar`.
:+1:

2019-05-06 08:39 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/concent/concent_base.py
> +    def step_ensure_node_concent_on(self, node_id: NodeId):
@etam ^

2019-05-06 11:43 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +                print(f"{node_id.value}'s port: {port}")
https://www.youtube.com/embed/f5d8pVg3Qtg?start=215&end=232

2019-05-06 11:52 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +                print(f"{node_id.value}'s port: {port}")
@etam I really have no way to better ask than to point to that line before the change: https://github.com/golemfactory/golem/pull/4058/files#diff-cb2db76beee60d6f1a9a0c95e70f717cL216

2019-05-06 12:38 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_get_node_key(self, node_id: NodeId):
done

2019-05-06 12:38 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +                print(f"{node_id.value}'s port: {port}")
done

2019-05-06 12:38 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +    def step_ensure_node_network(self, node_id: NodeId):
done

2019-05-06 12:39 UTC, etam commented on scripts/node_integration_tests/playbooks/concent/concent_base.py
> +    def step_ensure_node_concent_on(self, node_id: NodeId):
done

2019-05-06 13:36 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +        return repr(self.current_step_method)
how about now?
For my examples above the outputs now are:
```
foo
foo(i=5)
```

2019-05-06 15:22 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +                    print(f"Expected peer: {expected_peer_key} not in connected"
Good catch. Actually I totally borked the logic in this step.

2019-05-06 15:46 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +                    print(f"Expected peer: {expected_peer_key} not in connected"
done

2019-05-07 08:58 UTC, etam commented on scripts/node_integration_tests/playbooks/golem/multinode_regular_run/playbook.py
> +    initial_steps: typing.Tuple = (
I did this and it looks like this:
```python
    initial_steps: typing.Tuple = \
        tuple(helpers.map_partial(step_get_node_key,
                                  node_id=[NodeId.provider, NodeId.requestor]))
    + tuple(helpers.map_partial(step_configure_node,
                                node_id=[NodeId.provider, NodeId.requestor]))
    + (
        partial(step_get_node_network_info, node_id=NodeId.provider),
        partial(step_ensure_node_network, node_id=NodeId.requestor),
        partial(step_connect_nodes, node_id=NodeId.requestor,
                target_node=NodeId.provider),
        partial(step_verify_peer_connection, node_id=NodeId.requestor,
                target_node=NodeId.provider),
        partial(step_wait_node_gnt, node_id=NodeId.requestor),
        partial(step_get_known_tasks, node_id=NodeId.requestor),
    )
```
so I think I agree with blue that this is not better.

2019-05-08 12:12 UTC, shadeofblue approved these changes

2019-05-08 13:50 UTC, kmazurek approved these changes

2019-05-08 13:57 UTC, etam commented
Yay! Now I'm gonna cleanup git history and rebase onto develop after #4160 is merged.

2019-05-08 15:55 UTC, merged