Feature improve cli
golemfactory/clay pull request #4070
Opened 2019-04-02 10:14 UTC by dybi

resolves: https://github.com/golemfactory/golem/issues/3015

2019-04-02 11:01 UTC, Jakub89 approved these changes
Wouldn't hurt if we could sneak in CP style in function calls to improve readability.
```
func(
    arg1,
    arg2,
    arg3
)
```
![tenor](https://user-images.githubusercontent.com/20682491/55397809-59414700-5547-11e9-852d-bd146d9c59d7.gif)

2019-04-02 11:01 UTC, Jakub89 commented on golem/interface/cli.py
> +                                                   started)
Maybe, we could sneak in some CP style?
```suggestion
        result = process_hardcoded_settings_output(
            result, 
            args, 
            namespace,
            started
        )
```

2019-04-04 07:21 UTC, pawelkisielewicz approved these changes

2019-04-08 10:43 UTC, shadeofblue requested changes

2019-04-08 10:43 UTC, shadeofblue commented on golem/ethereum/transactionsystem.py
> +            return f"Sent {amount} {currency} to: {destination}. " \
@dybi I'm unconvinced that changing the function signature to return an informational string (human-readable output) instead of a meaningful value (transaction hash) is a good idea here... 

maybe the function here should return a dict and the human readable string should be constructed where it's actually needed instead?

2019-04-08 11:21 UTC, dybi commented on golem/ethereum/transactionsystem.py
> +            return f"Sent {amount} {currency} to: {destination}. " \
ok, you've got a point here... fixed!

2019-04-15 20:53 UTC, shadeofblue commented on golem/interface/client/environments.py
> +    @customize_output('envs perf_mult_set to {}', ['multiplier'],
@dybi missing a `.` at the end of the message.

2019-04-15 20:55 UTC, shadeofblue commented on golem/interface/client/network.py
> +    @customize_output('Connected with IP:{} port: {}', ['ip', 'port_'],
@dybi although unspecified, I think it would also be good to add a `.` here at the end to standardize the output...

2019-04-15 21:02 UTC, shadeofblue commented on golem/interface/client/network.py
> +    @customize_output('Connected with IP:{} port: {}', ['ip', 'port_'],
hmm... @dybi this command always returns "Connected with [IP], port []" even if no connection has been made ... please ensure that an error message is indeed output when no connection could have been made and only output a confirmatory message when actual connection is possible

2019-04-15 21:04 UTC, shadeofblue commented on golem/interface/client/network.py
> +    @customize_output('{} blocked.', ['node_id'], include_call_time=True)
same here ... I also believe this command outputs a "nodeid blocked" even if no such node exists

2019-04-15 21:10 UTC, shadeofblue commented on golem/interface/cli.py
> +        'accept_tasks': lambda v: f'Your node will{" not" * (int(v) == 0)} accept'  # noqa
There is no message whatsoever when the value is set to something else entirely... There should be a clear indication that the value was not accepted and, ideally, a suggested acceptable range of values communicated to the user

2019-04-15 21:16 UTC, shadeofblue commented on golem/interface/cli.py
> +    output_map = {
@dybi actually, for any values that are mis-specified (wrong type or value) it should be conveyed to the user ... it happens when someone provides the wrong key but not when a wrong value type is specified...

please ensure an error message and a list of suggested types/values is provided on error ... ideally, if the key is correct, it should only output the requirements for that key ... but if that's too much, at minimum, the same output should be displayed as is in the case of a wrong key

2019-04-15 21:17 UTC, shadeofblue requested changes
generally, for each modified command output, please ensure that _false_ _positives_ are _not_ displayed and that a user is made aware that there has been an error

2019-04-15 21:20 UTC, shadeofblue commented
well, before this pull request, the user had no idea what happened besides an information that something happened ... but now, they're informed of a correct execution of a command even if no such thing happened ... it doesn't sound like a change for better ... I'd rather "know that I know nothing" than be assured that everything went a-okay even if there was an actual error ...

2019-04-16 06:35 UTC, dybi commented on golem/interface/client/network.py
> +    @customize_output('Connected with IP:{} port: {}', ['ip', 'port_'],
My output:
```bash
>> network connect 192.169.1.1 178452
Cannot connect to 192.169.1.1:178452: Port out of range (1 .. 65535): 178452 Completed in 0.00 s
>> network connect 192.169.1.1 8452
Cannot connect to 192.169.1.1:8452: connect not mapped Completed in 0.00 s
>> 

```

2019-04-16 07:22 UTC, dybi commented on golem/interface/client/network.py
> +    @customize_output('{} blocked.', ['node_id'], include_call_time=True)
My output:
```bash
✔≻ golemcli network block 123
[09:22:14.525270] ERROR: Exception: block_node not mapped Completed in 0.00 s
```

2019-04-16 08:06 UTC, dybi commented on golem/interface/cli.py
> +    output_map = {
My output
```bash
✔≻ golemcli settings set non_existing_key 777
Invalid key

    Available settings:

	node_name                                        non-empty string	Node name
	accept_tasks                                          flag {0, 1}	Accept tasks
	max_resource_size                                    int > 0 [kB]	Maximal resource size
	getting_tasks_interval                                int > 0 [s]	Interval between task requests
	getting_peers_interval                                int > 0 [s]	Interval between peer requests
	task_session_timeout                                  int > 0 [s]	Task session timeout
	p2p_session_timeout                                   int > 0 [s]	P2P session timeout
	requesting_trust                                  float [-1., 1.]	Minimal requestor trust
	computing_trust                                   float [-1., 1.]	Minimal provider trust
	min_price                                              float >= 0	Min GNT/h price (provider)
	max_price                                              float >= 0	Max GNT/h price (requestor)
	use_ipv6                                              flag {0, 1}	Use IPv6
	opt_peer_num                                              int > 0	Number of peers to keep
	send_pings                                            flag {0, 1}	Send ping messages to peers
	pings_interval                                            int > 0	Interval between ping messages
	max_memory_size                    16036916 > int >= 1048576 [kB]	Max memory size
	num_cores                                           8 >= int >= 1	Number of CPU cores to use
	enable_talkback                                       flag {0, 1}	Enable error reporting with talkback service
```

2019-04-24 14:29 UTC, Krigpl requested changes
I stated that before but I'll repeat - please add me to *any* changes touching transaction system and payments in general.

2019-04-24 14:29 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +                'destination': destination,
Returning unchanged amount, currency and destination is completely useless - please remove that.

2019-04-26 10:54 UTC, tworec commented
Y-day we (@shadeofblue, @jamuszyn and me) agreed to move this initiative into a newly created work stream called `golem-client`: 

The recommendation is to finish what is started, but not start anything new. So pls report what is started and rest should be moved into a new issue in https://github.com/golemfactory/golem-client

@shadeofblue can you report status of this PR in #3015?

2019-05-08 15:38 UTC, tworec commented
We (@shadeofblue @prekucki and me) have decided to abandon this PR.
Changes will be adressed within golemfactory/golem-client#25

2019-05-08 15:38 UTC, closed without merging