[WIP] separate config class for integration tests
golemfactory/clay pull request #4088
Opened 2019-04-04 15:38 UTC by etam

Porting status:
- concent
  - [ ] additional_verification
  - [ ] force_accept
  - [ ] force_download
  - [ ] force_payment
  - [ ] force_report
- golem
  - [x] exr
  - [x] jpeg
  - [x] jpg
  - [x] no_concent
  - [x] regular_run
  - [x] regular_run_stop_on_reject
  - [x] restart_frame
  - [x] rpc_test
  - [ ] task_timeout
  - [ ] zero_price

Looking at `golem.zero_price` test gave me idea, that I should also move `task_dict` to `TestConfigBase`.

2019-04-07 12:09 UTC, yang980 approved these changes

2019-04-10 10:37 UTC, shadeofblue requested changes

2019-04-10 10:37 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/test_config_base.py
> +    node_config.password = os.environ.get(f'GOLEM_{role}_PASSWORD', 'dupa.8')
'dupa.8' is already defined as a default in `NodeConfig` so no need to specify that here ... 
```suggestion
    node_config.password = os.environ.get(f'GOLEM_{role}_PASSWORD', node_config.password)
```

2019-04-10 10:37 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/test_config_base.py
> +        int(os.environ.get(f'GOLEM_{role}_RPC_PORT', 61000 + counter))
if we're allowing the ports to be potentially different from test to test, we need to output them alongside the data directories currently in use (to e.g. facilitate connections through e.g. `golemcli`)

2019-04-10 10:37 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/test_config_base.py
> +    node_config.concent = os.environ.get('GOLEM_CONCENT_VARIANT', 'staging')
```suggestion
    node_config.concent = os.environ.get('GOLEM_CONCENT_VARIANT', node_config.concent)
```

2019-04-10 10:37 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +        assert provider_config is not None
I'd rather not have naked `assert`s here but rather appropriate `.fail()` calls with informative failure messages ... 

*) where `informative failure messages` meaning that some suggestion is made on how to address the issue

2019-04-10 10:37 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +        assert requestor_config is not None
same here (re: `.fail()` + informative msg)

2019-04-10 10:37 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +        self.config.next_nodes()
`next_nodes` sounds awkward-ish ... but my ideas are not much better ... `replace_nodes`, `bump_nodes`... maybe @zakaprov would have something better? ...

2019-04-10 10:37 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +        assert requestor_config is not None
same here -> please add an appropriate `.fail()` call with an informative message

2019-04-10 10:37 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +        assert provider_config is not None
same here -> please add an appropriate .fail() call with an informative message

2019-04-10 10:37 UTC, shadeofblue commented on scripts/node_integration_tests/run_test.py
> -        required=False,
"explicit is better than implicit"

2019-04-10 10:41 UTC, etam commented on scripts/node_integration_tests/run_test.py
> -        required=False,
Should I also specify all other arguments, even if they have default value?

2019-04-10 10:51 UTC, shadeofblue commented on scripts/node_integration_tests/run_test.py
> +        def override_datadir(
why introduce an inner function when it doesn't make use of the outside context? separate functions are usually more readable in such a case...

2019-04-10 10:52 UTC, shadeofblue commented on scripts/node_integration_tests/run_test.py
> +        def override_datadir(
or, "simple is better than complex"

2019-04-10 10:52 UTC, shadeofblue commented on scripts/node_integration_tests/run_test.py
> +        def override_datadir(
and "readability counts"

2019-04-10 10:54 UTC, shadeofblue commented on scripts/node_integration_tests/run_test.py
> +        def override_datadir(
or actually "flat is better than nested" ... choose yours ;)

2019-04-10 10:55 UTC, shadeofblue commented on scripts/node_integration_tests/run_test.py
> +        def override_datadir(
bottom line is - please don't create inner functions when just plain functions or methods can do the same job just as well

2019-04-10 11:13 UTC, etam commented on scripts/node_integration_tests/run_test.py
> -        required=False,
https://docs.python.org/3.6/library/argparse.html#required says:
> In general, the argparse module assumes that flags like -f and --bar indicate optional arguments, which can always be omitted at the command line. To make an option required, True can be specified for the required= keyword argument to add_argument()

> Required options are generally considered bad form because users expect options to be optional, and thus they should be avoided when possible.

My conclusion: adding `required=False` is stating the obvious and should be avoided.

2019-04-10 11:37 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/base.py
> +        if not provider_config.opts:
Bikeshedding: I know this comes from the name of the RPC (`env.opts.update`), but I still find the field name `opts` unnecessarily cryptic. IMO even `options` or `settings` (while still generic) would be more readable. Your thoughts on this?

2019-04-10 11:37 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/base.py
> +            print("Provider data directory: %s" % provider_config.datadir)
Idea: perhaps we should pretty-print all the args (or the config) when starting a node?

2019-04-10 11:37 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/test_config_base.py
> +    node_config.password = os.environ.get(f'GOLEM_{role}_PASSWORD', 'dupa.8')
I bet repeating it is about making a statement.

2019-04-10 11:41 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/base.py
> +        self.config.next_nodes()
`move_to_next_nodes`? Verbose, but it would be good for the name to imply the potential change.

2019-04-11 07:03 UTC, shadeofblue commented on scripts/node_integration_tests/run_test.py
> -        required=False,
okay...

2019-04-11 13:15 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +        if not provider_config.opts:
![thoughts](https://i.imgur.com/MLQx2kD.gif)

2019-04-11 13:53 UTC, etam commented on scripts/node_integration_tests/playbooks/test_config_base.py
> +        int(os.environ.get(f'GOLEM_{role}_RPC_PORT', 61000 + counter))
done

2019-04-11 13:54 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +        assert provider_config is not None
done

2019-04-11 13:54 UTC, etam commented on scripts/node_integration_tests/run_test.py
> +        def override_datadir(
done

2019-04-11 13:54 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +            print("Provider data directory: %s" % provider_config.datadir)
done

2019-04-11 14:11 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +        if not provider_config.opts:
My thoughts are: I see no big difference between `opts`, `options` or `settings`. As you pointed out, `opts` refers to rpc method name, which distinguishes it from other forms of options, like those passed as arguments to `golemapp`.

2019-04-11 14:13 UTC, etam commented on scripts/node_integration_tests/playbooks/base.py
> +        self.config.next_nodes()
`use_next_nodes`?

2019-04-11 14:27 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/base.py
> +        if not provider_config.opts:
Okay, fair enough. Let's keep this as `opts` then.

2019-04-11 14:27 UTC, zakaprov commented on scripts/node_integration_tests/playbooks/base.py
> +        self.config.next_nodes()
Ok, sounds good to me, @shadeofblue?

2019-04-16 09:32 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +            self.fail("provider is not defined")
```suggestion
            self.fail("provider node config is not defined")
```

2019-04-16 09:32 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +            self.fail("requestor is not defined")
```suggestion
            self.fail("requestor node config is not defined")
```

2019-04-16 09:33 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +            self.fail("requestor is not defined")
```suggestion
            self.fail("requestor node config is not defined")
```

2019-04-16 09:33 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/base.py
> +            self.fail("provider is not defined")
```suggestion
            self.fail("provider node config is not defined")
```

2019-04-16 09:34 UTC, shadeofblue approved these changes

2019-04-16 10:04 UTC, kmazurek approved these changes
![lgtm](https://media.giphy.com/media/5xaOcLGm3mKRQuDYCgU/giphy.gif)

2019-04-16 10:34 UTC, merged