Brass Marketplace paper linked in docs + naming fix for thirst
golemfactory/clay pull request #4152
Opened 2019-05-06 11:08 UTC by tworec

resolves golemfactory/golem-model#74

2019-05-06 12:18 UTC, Krigpl requested changes

2019-05-06 12:18 UTC, Krigpl commented on .gitignore
> +# rust
There's a `Rust` section already
Also see https://github.com/golemfactory/golem/pull/3647#pullrequestreview-182303798, we keep `Cargo.lock` in the repo

2019-05-06 12:18 UTC, Krigpl commented on golem/task/timer.py
> +    def profit_factor(self):
Since you link the doc everywhere and the doc mentions `thirst` and doesn't mention `profit_factor`, what is this change for?

2019-05-06 15:01 UTC, tworec commented on .gitignore
> +# rust
> There's a `Rust` section already
ok, didn't noticed bc of case sensitive search ;)

> Also see [#3647 (review)](https://github.com/golemfactory/golem/pull/3647#pullrequestreview-182303798), we keep `Cargo.lock` in the repo

I'm restoring. It keeps bothering me to be changed after each `setup.py develop` invocation. Why do you want to keep it in repo? I'm just curious.

2019-05-06 15:04 UTC, tworec commented on golem/task/timer.py
> +    def profit_factor(self):
read [the paper](https://docs.golem.network/About/img/Brass_Golem_Marketplace.pdf) carefully and you'll notice that `thrist` is `t_2 - t_1` and here is calculated profit factor. This name is proposed by @mbenke, see https://github.com/golemfactory/golem-model/issues/74#issuecomment-488568824

2019-05-07 08:55 UTC, Krigpl approved these changes

2019-05-07 08:55 UTC, Krigpl commented on golem/task/timer.py
> +    _INITIAL_PROFIT_FACTOR = 0.2
typehint

2019-05-07 08:57 UTC, Krigpl commented on .gitignore
> +# rust
Does it change really? Just tried and it didn't.

2019-05-07 11:09 UTC, tworec commented on .gitignore
> +# rust
it was adding two lines, maybe it's because I have newer rust version
I've committed them 56e6e00

2019-05-07 11:19 UTC, Krigpl commented on .gitignore
> +# rust
Right, so not every time, just once because of the newer compiler version. This isn't something to be bothered by.

2019-05-07 11:26 UTC, tworec commented on .gitignore
> +# rust
ok, I've reverted, because buildbot complained about not stashed changes after cargo changed lock.

I'm asking by pure educational purposes: why do you want `Cargo.lock` in repo?

2019-05-07 11:58 UTC, mfranciszkiewicz commented on golem/task/timer.py
>  class ThirstTimer(ActionTimer):
Should probably be renamed

2019-05-07 12:11 UTC, Krigpl commented on .gitignore
> +# rust
The reason is included in the link I posted - Golem is a binary, not a library, thus Cargo.lock is meant to be in the version control.

2019-05-07 12:21 UTC, merged

2019-05-07 12:52 UTC, tworec commented on .gitignore
> +# rust
oops, I didn't see hidden/resolved comment, thx

2019-05-07 12:53 UTC, tworec commented on golem/task/timer.py
>  class ThirstTimer(ActionTimer):
nope, timer is measuring thirst (in seconds) but we are transforming thirst into profit factor. 

see  https://github.com/golemfactory/golem-model/issues/74#issuecomment-488568824

2019-05-07 13:03 UTC, mfranciszkiewicz commented on golem/task/timer.py
>  class ThirstTimer(ActionTimer):
But it effectively measures the profit factor. Since `thirst` has been renamed, it does much more than measuring idle time.

2019-05-07 13:18 UTC, tworec commented on golem/task/timer.py
>  class ThirstTimer(ActionTimer):
it does not measure the `profit factor`, it *calculates* it based on `thirst`, which is the measured value. But feel free to rename it. I was also willing to name it as you're proposing but rethought and for me now it is ok.