Wamp serialization error fix: huge unsigned int
golemfactory/clay pull request #4236
Opened 2019-05-24 14:08 UTC by mdtanrikulu

2019-05-24 14:30 UTC, Krigpl requested changes

2019-05-24 14:30 UTC, Krigpl commented on golem/ethereum/exceptions.py
> +    required: any
Don't change that. This is supposed to hold ints, period. See comment below.

2019-05-24 14:30 UTC, Krigpl commented on golem/ethereum/exceptions.py
> +            [MissingFunds._make([str(item) for item in entry])._asdict()
Don't create a new `MissingFunds` object, instead call `entry._asdict()` and then convert the values to string. And even better do that conversion here: https://github.com/golemfactory/golem/pull/4138/files#diff-cfa6ad63fdbdae4250cf225821638922R400, since there's no reason `to_dict` method should convert any ints to strings.

2019-05-26 22:58 UTC, mdtanrikulu commented on golem/ethereum/exceptions.py
> +            [MissingFunds._make([str(item) for item in entry])._asdict()
![Reverted](https://media.giphy.com/media/m4aNskYL5oQqQ/giphy.gif)

2019-05-27 09:02 UTC, Krigpl requested changes

2019-05-27 09:02 UTC, Krigpl commented on golem/task/rpc.py
> +        tempDict = rpc_utils.big_int_to_string(e.to_dict())
Let convert all `int`s to strings, it's awkward that the same field might be sometimes an integer and sometimes a string.
Also no camelCase in Python.

2019-05-27 09:02 UTC, Krigpl commented on golem/rpc/utils.py
> +    def _big_int_to_string(v):
This helper function is not needed. Just add another `elif` condition on line 61 to check against `int` and that's it. (and change argument name to `v`)

2019-05-27 11:58 UTC, mdtanrikulu commented on golem/rpc/utils.py
> +    def _big_int_to_string(v):
Make sense. 👍

2019-05-27 11:58 UTC, mdtanrikulu commented on golem/task/rpc.py
> +        tempDict = rpc_utils.big_int_to_string(e.to_dict())
Fixed

2019-05-27 12:22 UTC, Krigpl approved these changes
![obama_approves](https://user-images.githubusercontent.com/3904252/58419439-e5c13f00-808a-11e9-8f9d-c92a182c8a7b.jpeg)

2019-05-27 14:24 UTC, merged