Migrate Payments to TaskPayment
golemfactory/clay pull request #4240
Opened 2019-05-27 14:27 UTC by jiivan

fixes: #4197 
additionally fixes: #2457

2019-05-30 09:59 UTC, zakaprov commented on golem/client.py
> +                p.wallet_oepration.amount for p in subtasks_payments
typo: `wallet_operation`

2019-05-30 09:59 UTC, zakaprov commented on golem/model.py
> +    node = CharField(null=False)
Opinion: suffixing these three field names (`node`, `task`, `subtask`) with `_id` would remove ambiguity on the values they store. What do you think?

2019-05-30 09:59 UTC, zakaprov commented on golem/model.py
> -    def __repr__(self) -> str:
`__repr__` is missing on both of the newly introduced classes, is that intentional?

2019-05-30 09:59 UTC, zakaprov commented on golem/model.py
> -        self.block_hash = block_hash
Shouldn't we keep these (i.e. `block_hash` and `block_number`) for the sake of bookkeeping? Or are they considered redundant?

2019-05-30 10:24 UTC, jiivan commented on golem/model.py
> +    node = CharField(null=False)
Yes, I like suffixing in this case, but all other models have fields without them. For the sake of consistency I would keep it as is.

2019-05-30 10:25 UTC, jiivan commented on golem/model.py
> -        self.block_hash = block_hash
It's not needed anywhere that's why I removed them.

2019-05-30 10:28 UTC, Krigpl requested changes

2019-05-30 10:28 UTC, Krigpl commented on golem/ethereum/paymentprocessor.py
> +            task_header: dt_tasks.TaskHeader,
Don't make this module depend on golem-messages just because you need two values from this struct.
Just provide node_id and task_id explicitly.

2019-05-30 10:28 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            task_header: dt_tasks.TaskHeader,
ditto

2019-05-30 10:28 UTC, Krigpl commented on golem/model.py
> +    def processed_ts(self) -> int:
I'd really prefer to have this property set explicitly using the same logic as the batch transfer uses to have a guarantee this works as expected. and afaict `time.time()` is not defined to return the UTC timestamp. Please revert back to the previous approach of using common function is those two places, you're not gaining much by making this a property anyway.

2019-05-30 10:39 UTC, jiivan commented on golem/model.py
> +    def processed_ts(self) -> int:
Please look here:
https://github.com/golemfactory/golem/blob/402a22a2daa76cdd250cf9637df383310ea47c75/golem/model.py#L46-L61

This guarantees that `created_date` is in UTC. Only function of this property is to translate datetime to integer timestamp. Do you think there is an incentive in duplicating this value?

2019-05-30 13:58 UTC, Krigpl commented on golem/model.py
> +    def processed_ts(self) -> int:
But during batch transfer you use `time.time()` which doesn't have to generate the same values as `created_date`. I think it's reasonable to make this very explicit that `processed_ts` and `closure_time` originate from the same place considering this is payments related, so we'd rather not risk introducing any bugs or implicit assumption here.

2019-05-30 14:05 UTC, jiivan commented on golem/ethereum/paymentprocessor.py
> +            task_header: dt_tasks.TaskHeader,
`[too-many-arguments] Too many arguments (6/5)`
I'll stay with pylint in this case. Moved the dependency into `TYPE_CHECKING` branch.

2019-05-30 14:09 UTC, jiivan commented on golem/client.py
> +                p.wallet_oepration.amount for p in subtasks_payments
Thanks, fixed

2019-05-30 14:19 UTC, jiivan commented on golem/model.py
> +    def processed_ts(self) -> int:
Good point. I'll update batch transfer to use plain utc datetimes.

2019-05-31 14:31 UTC, Krigpl requested changes

2019-05-31 14:31 UTC, Krigpl commented on golem/ethereum/paymentprocessor.py
> +            task_header: 'dt_tasks.TaskHeader',
That's really not what I meant, it doesn't change dependencies at all. There are exactly zero reasons transaction system should be aware of the existence of the `TaskHeader`. Please do what I suggested earlier.

2019-05-31 14:31 UTC, Krigpl commented on golem/ethereum/paymentprocessor.py
> +        now = int(time.time())
Still not a consistent way with the `processed_ts` values.

2019-05-31 14:59 UTC, jiivan commented on golem/model.py
> -    def __repr__(self) -> str:
Maybe we'll add them, when they're needed?

2019-06-03 09:02 UTC, Krigpl requested changes
Please, no unnecessary `golem-messages` dependencies in the `ethereum` module.

2019-06-03 09:02 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +from golem_messages.datastructures import p2p as dt_p2p
The same applies to the transaction system and the whole `ethereum` directory in general - don't make it depend on message-related structures from `golem_messages`

2019-06-03 09:02 UTC, Krigpl commented on tests/golem/ethereum/test_paymentprocessor.py
> +from golem_messages.factories.datastructures import tasks as dt_tasks_factory
The same applies to the tests. Since the module doesn't use structures from `golem-messages`, the tests should not use factories from it as well.

2019-06-03 09:02 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +from golem_messages.factories.datastructures import tasks as dt_tasks_factory
ditto, obviously

2019-06-03 09:10 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +from golem_messages.datastructures import p2p as dt_p2p
Sure, but in this case is it better to manually construct a dict? IMHO it's better to use `node.to_dict()`.

https://github.com/golemfactory/golem/blob/5914e62e02ce9251f1328bbe8fff8ae06b28b873/golem/ethereum/transactionsystem.py#L86-L94

2019-06-03 09:34 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +from golem_messages.datastructures import p2p as dt_p2p
That's the thing - it wouldn't be a problem if I was made aware of the previous set of changes, the ones that moved all the rpc calls directly to this module. This was not the right move. This module is not supposed to do random formatting and returning arbitrary dicts as in e.g. `get_incomes_list`. It also is not supposed to be aware of what `node_id` is connected to (the Node structure), because it doesn't care about that. This kind of things should happen outside of this module and then we wouldn't have this kind of unnecessary dependencies.

This kind of mess happens when you don't include module maintainers in your PRs. I'm really not happy about this.

2019-06-03 11:19 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +from golem_messages.datastructures import p2p as dt_p2p
Moved to separate module.

2019-06-03 11:51 UTC, Krigpl reviewed
Thanks, that looks muuuch better. Mostly lgtm but have a couple of questions inline.

2019-06-03 11:51 UTC, Krigpl commented on golem/model.py
> +    status = StringEnumField(enum_type=STATUS, default=STATUS.awaiting.value)
Do we need the default value here? It's not clear to me whether `awaiting` is still a good default value

2019-06-03 11:51 UTC, Krigpl commented on golem/model.py
> +    amount = HexIntegerField(null=True)
When can it be `null`?

2019-06-03 12:29 UTC, jiivan commented on golem/model.py
> +    amount = HexIntegerField(null=True)
When it's an income (direction incoming). It's null until we receive confirmation from SCI.

2019-06-03 14:26 UTC, jiivan commented on golem/model.py
> +    status = StringEnumField(enum_type=STATUS, default=STATUS.awaiting.value)
We could set status explicitly every time. But I'm not sure whether `awaiting` is a bad default.

2019-06-03 15:34 UTC, Krigpl commented on tests/golem/ethereum/test_paymentprocessor.py
> +            node_id='00adbeef' + 'deadbeef' * 15,
Did you mean `0x` prefix?

2019-06-03 15:34 UTC, Krigpl commented on golem/model.py
> +    status = StringEnumField(enum_type=STATUS, default=STATUS.awaiting.value)
Because there's only one case where we set `awaiting` during object creation.
Withdrawals will set `sent`
Top ups will set `confirmed`
Deposit operations will also not use `awaiting` anywhere

`awaiting` is only used for incoming task payments, that's why I don't see why it is a good enough reason to make it a default.

2019-06-04 09:21 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +    from golem_messages.datastructures import tasks as dt_tasks
That's not used anymore

2019-06-05 08:59 UTC, Krigpl approved these changes

2019-06-05 08:59 UTC, Krigpl commented on golem/ethereum/paymentprocessor.py
> +            tz=datetime.timezone.utc
There's `get_timestamp_utc` in `golem.core.common`, might be cleaner to use it

2019-06-05 08:59 UTC, Krigpl commented on golem/ethereum/paymentprocessor.py
> +        processed_ts_deadline = datetime.datetime.now(
rename to `created_ts_deadline` for consistency

2019-06-05 09:08 UTC, jiivan commented on golem/ethereum/paymentprocessor.py
> +            tz=datetime.timezone.utc
Unfortunately it returns float, not datetime.

2019-06-05 09:44 UTC, merged