node_integration_tests - use granary for key reuse
golemfactory/clay pull request #4276
Opened 2019-06-05 10:13 UTC by maaktweluit

- Separated out the key reuse feature in its own file ( commit 1 )
- Extended it to pick between local files and the remote granary by specifying the granary hostname ( commit 2).

The granary is disabled by default.

2019-06-07 10:18 UTC, etam requested changes
Added some comments. Nothing critical though.

2019-06-07 10:18 UTC, etam commented on scripts/node_integration_tests/key_reuse.py
> +    provider = None
Type annotations plz

2019-06-07 10:18 UTC, etam commented on scripts/node_integration_tests/key_reuse.py
> +        print("NodeKeyReuseLocalFolder.end_test() called.")
`if logging:`?

2019-06-07 10:18 UTC, etam commented on scripts/node_integration_tests/key_reuse.py
> +    def get(cls, test_dir: Path):
Not critical: If you call this second time, with different `test_dir` you might get a bit surprising results.

2019-06-07 10:18 UTC, etam commented on scripts/node_integration_tests/key_reuse.py
> +        if _logging:
redundant if

2019-06-07 10:18 UTC, etam commented on scripts/node_integration_tests/key_reuse.py
> +        print("NodeKeyReuseGranary.end_test() called.")
`if _logging`?

2019-06-07 10:18 UTC, etam commented on scripts/node_integration_tests/key_reuse.py
> +        print("_save_private_key")
`if _logging`?
also, those 2 prints can be 1

2019-06-07 10:18 UTC, etam commented on tests/factories/granary.py
> +        random.seed()
I don't think this is required.

2019-06-07 10:18 UTC, etam commented on tests/factories/granary.py
> +        if _logging:
redundant if

2019-06-07 10:18 UTC, etam commented on tests/factories/granary.py
> +        if completed.stdout:
Suggested flow:
```
if something unusual happened:
    handle error

do the expected stuff
```

2019-06-07 10:20 UTC, etam commented
Is the Granary code available somewhere?

2019-06-07 10:24 UTC, maaktweluit commented
@etam thanks for the comments! will look into them :)

the granary is available here: https://github.com/golemfactory/golem-granary

2019-06-07 10:40 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +    provider = None
added

2019-06-07 10:40 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        print("NodeKeyReuseLocalFolder.end_test() called.")
added

2019-06-07 10:40 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        if _logging:
removed

2019-06-07 10:40 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        print("NodeKeyReuseGranary.end_test() called.")
added

2019-06-07 10:41 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        print("_save_private_key")
added and merged

2019-06-07 10:41 UTC, maaktweluit commented on tests/factories/granary.py
> +        if _logging:
removed

2019-06-07 10:41 UTC, maaktweluit commented on tests/factories/granary.py
> +        if completed.stdout:
good one! updated the flow

2019-06-07 10:42 UTC, maaktweluit commented on tests/factories/granary.py
> +        random.seed()
removed, think this was for an old "feature" to generate a key when none was available.

This is the responsibility of the `golemapp` now ( and maybe later `golem-granary` )

2019-06-07 10:46 UTC, etam commented on scripts/node_integration_tests/key_reuse.py
> +        raise Exception("Not implemented")
https://docs.python.org/3/library/exceptions.html#NotImplementedError

2019-06-07 13:31 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        raise Exception("Not implemented")
fixed :)

2019-06-07 14:32 UTC, etam commented on scripts/node_integration_tests/key_reuse.py
> +    instance: Optional[SelfType] = None
When referencing self type in type annotations, put it in quotes.
https://stackoverflow.com/a/33533514

2019-06-10 09:35 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +    instance: Optional[SelfType] = None
Nice! fixed

2019-06-11 09:30 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +PASSWORD = 'dupa.8'
Uhm, please change this

2019-06-11 09:30 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +            if _logging:
Is it possible to move this `if` + `print` to a function (e.g. `log`) in a shared module (unless `_logging` has to be local).

2019-06-11 09:30 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +        for i, node_id in enumerate(self.datadirs):
`enumerate` is not needed here

2019-06-11 09:30 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +        for i, node_id in enumerate(self.datadirs):
`enumerate` is not needed here

2019-06-11 09:30 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +            if account is not None:
If it is, a log message might be valuable

2019-06-11 09:30 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +                keystore = f.read()
```suggestion
                keystore = json.load(f)
```

2019-06-11 09:30 UTC, mfranciszkiewicz commented on tests/factories/granary.py
> +    def __init__(self, raw_key, ts):
Could you add type annotations, please? It's not obvious that `ts` is a string containing JSON.

2019-06-11 09:30 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +class NodeKeyReuseBase():
Could you maybe provide some kind of distinction for this base class / child classes? Because `NodeKeyReuseBase` is not a parent of `NodeKeyReuse` but of `NodeKeyReuseLocalFolder` and `NodeKeyReuseGranary`

2019-06-11 11:36 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +PASSWORD = 'dupa.8'
This has been moved here from somewhere else in the code, but will change it :)

2019-06-11 11:40 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +            if _logging:
Tried `logger` first but this does not work on `tearDown` in pytest :(

Will make it a private function for now

2019-06-11 11:41 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        for i, node_id in enumerate(self.datadirs):
why not? we need a counter,`i`, for this loop
otherwise it will give `node_id, data_dir` ( i think )

2019-06-11 11:42 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +            if account is not None:
good one! 
it will be just a warning but good to have a heads up the key is not from granary

2019-06-11 11:50 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +                keystore = f.read()
done

2019-06-11 11:54 UTC, maaktweluit commented on tests/factories/granary.py
> +    def __init__(self, raw_key, ts):
done

2019-06-11 11:59 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +class NodeKeyReuseBase():
- Added comments on all classes
- Renamed `NodeKeyReuse` -> `NodeKeyReuseConfig`

2019-06-11 12:21 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +                keystore = f.read()
This does not work, `json.load` returns a dict not a string

I think its overkill to use `json.dumps(json.load(f))` so reverted the change for now

2019-06-11 12:27 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +                keystore = f.read()
Wait, i see it broke because of the `json.loads()` later in the code, running another test on this

2019-06-11 12:27 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +        for i, node_id in enumerate(self.datadirs):
`for node_id in self.datadirs` will iterate over keys

2019-06-11 12:28 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +class NodeKeyReuseBase():
Thank you! :)

2019-06-11 12:29 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +                keystore = f.read()
works! /shy

2019-06-11 13:03 UTC, maaktweluit commented
@mfranciszkiewicz thanks for the review, great comments!

I have addressed all of them and resolved the simple fixes, please resolve your other comments when happy with the fixes

2019-06-11 13:05 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        for i, node_id in enumerate(self.datadirs):
but we need the index(/counter), node_id and datadir in this loop to make the storage folders independent of the node_id's used for this test

2019-06-11 13:17 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/key_reuse.py
> +        for i, node_id in enumerate(self.datadirs):
`i` is not used here at all. You're probably thinking about a different method.

2019-06-11 13:28 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +    def get(cls, test_dir: Path):
fixed!

Protected our future selves from this by splitting the functions and adding asserts

Please resolve if you like the fix ( only last commit )

2019-06-11 13:34 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        for i, node_id in enumerate(self.datadirs):
haha /facepalm

you are right, fixed, testing now

2019-06-11 13:59 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        for i, node_id in enumerate(self.datadirs):
fixed

2019-06-11 13:59 UTC, maaktweluit commented on scripts/node_integration_tests/key_reuse.py
> +        for i, node_id in enumerate(self.datadirs):
works

2019-06-12 13:58 UTC, etam approved these changes

2019-06-12 14:03 UTC, mfranciszkiewicz approved these changes

2019-06-13 08:49 UTC, mfranciszkiewicz approved these changes

2019-06-13 14:06 UTC, merged