Add should_accept_client with description
golemfactory/clay pull request #4319
Opened 2019-06-12 09:54 UTC by mplebanski

Open to comments/research on what else should be done.

2019-06-12 10:08 UTC, kubkon commented on apps/wasm/task.py
> +        max_finishing = self.max_pending_client_results
Would we put the verification logic here as well?

2019-06-12 10:19 UTC, mbenke requested changes

2019-06-12 10:19 UTC, mbenke commented on apps/wasm/task.py
> +        not computing the same task twice, because we want a redundancy on both computation and computation provider.
```suggestion
        not computing the same subtask twice, because this would not provide the desired computation provider redundancy.
```

2019-06-12 10:19 UTC, mbenke commented on apps/wasm/task.py
> +        By "The same task twice" I mean two redundant jobs of the same task.
```suggestion
        By "The same subtask twice" I mean two redundant jobs of the same subtask.
```

2019-06-14 14:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=4319) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=4319) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=4319) it.</sub>

2019-06-14 15:03 UTC, mplebanski commented on apps/wasm/task.py
> +        s_ids = [s_id for s_id in subtask.instances]
```suggestion
        s_ids = subtask.instances.keys()
```

2019-06-14 15:03 UTC, mplebanski commented on apps/wasm/task.py
> +        for s_id in subtask.instances:
```suggestion
        for s_id in s_ids:
```

2019-06-14 15:05 UTC, mplebanski commented on apps/wasm/task.py
> +            WasmTask.CALLBACKS[s_id]
Please remove callbacks

2019-07-01 09:16 UTC, mplebanski commented
Continued in https://github.com/golemfactory/golem/pull/4319

2019-07-01 09:16 UTC, closed without merging