Persistent topups
golemfactory/clay pull request #4345
Opened 2019-06-14 14:34 UTC by jiivan

2019-06-24 13:52 UTC, Krigpl requested changes

2019-06-24 13:52 UTC, Krigpl commented on .gitignore
> +apps/rendering/resources/taskcollector/Release/*
it's already there 2 lines below

2019-06-24 13:52 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +            if gas_price is None:
Please move this at the top of the function and remove lines 622-623 as well.
This will also prevent the case where gas price changes between sending the transaction and querying it here.

2019-06-24 13:52 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +                gas_cost=gas_price * self._sci.GAS_GNT_TRANSFER,
This is the upper bound, the final cost is known after it's mined.

2019-06-24 13:52 UTC, Krigpl commented on golem/ethereum/paymentskeeper.py
> +        except model.WalletOperation.DoesNotExist:
When do you expect this will happen?

2019-06-24 13:52 UTC, Krigpl commented on golem/ethereum/paymentskeeper.py
> +    def sent_transfer(
To be puristic `PaymentsKeeper`, as the description mentions, is about subtask payments, and this method is not.

2019-06-24 13:52 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +                status=model.WalletOperation.STATUS.sent,
I think you don't ever confirm this transaction.

2019-06-25 09:54 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +                status=model.WalletOperation.STATUS.sent,
It's confirmed in `PaymentsKeeper.sent_transfer()`

2019-06-25 09:57 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +                gas_cost=gas_price * self._sci.GAS_GNT_TRANSFER,
Is accessible in a `receipt` of a callback provided to `sci.subscribe_to_gnt_transfers()`?

2019-06-25 09:59 UTC, jiivan commented on golem/ethereum/paymentskeeper.py
> +        except model.WalletOperation.DoesNotExist:
If transaction is triggered outside of golem (manually by user) or before this PR is merged.

2019-06-25 10:00 UTC, jiivan commented on golem/ethereum/paymentskeeper.py
> +    def sent_transfer(
Should I move this to `TransactionSystem` or update the docstring?

2019-06-25 10:12 UTC, Krigpl commented on golem/ethereum/paymentskeeper.py
> +    def sent_transfer(
Just update the docstring for now, since I ideally would aim into not having database operation directly in the TS

2019-06-25 10:12 UTC, Krigpl commented on golem/ethereum/paymentskeeper.py
> +        except model.WalletOperation.DoesNotExist:
> transaction is triggered outside of golem (manually by user)

This invalidates a lot of assumptions in the TS and we assume this won't ever happen.

> before this PR is merged

Not good enough reason to keep it imo.

2019-06-25 10:12 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +                gas_cost=gas_price * self._sci.GAS_GNT_TRANSFER,
Unfortunately, Ethereum doesn't provide gas cost in the receipt and we need to issue a request for it separately (there's SCI method for that).

2019-06-25 10:12 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +                status=model.WalletOperation.STATUS.sent,
Right, I missed that.

2019-06-25 10:12 UTC, Krigpl commented on golem/ethereum/paymentskeeper.py
> +                    model.WalletOperation.tx_hash == tx_hash,
`tx_hash` is enough to clearly identify the instance, so the rest of the `where` clause doesn't change anything.

2019-06-26 08:35 UTC, Krigpl requested changes

2019-06-26 08:35 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +                    gas_amount=self.get_withdraw_gas_cost(
Use `receipt.gas_cost`

2019-06-26 08:35 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +                    gas_price=self._sci.get_transaction_gas_price(
You know the gas price here, it's `gas_price` so you don't need to use that method (which issues an RPC request).

2019-06-26 08:35 UTC, Krigpl commented on golem/ethereum/paymentskeeper.py
> +    def sent_transfer(tx_hash: str, gas_amount: int, gas_price: Optional[int]):
maybe `confirm_transfer` would be more appropriate? I got confused about what this method does since there's also `sent` status.

2019-06-26 08:35 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +                gas_amount=self._sci.GAS_GNT_TRANSFER,
That should get the transaction receipt and retrieve `gas_used` field from it. Unfortunately, web3 doesn't include this stuff in the event log object.

2019-06-26 08:35 UTC, Krigpl commented on golem/ethereum/paymentskeeper.py
> +    def sent_transfer(tx_hash: str, gas_amount: int, gas_price: Optional[int]):
afaict you already always provide `gas_price` (as it should be), so maybe just provide a non-optional `gas_cost` and that's it.

2019-06-26 08:35 UTC, Krigpl commented on golem/ethereum/incomeskeeper.py
> +    def received_eth_transfer(
Those two methods are identical, so maybe DRY?

2019-06-27 15:13 UTC, jiivan commented on golem/ethereum/paymentskeeper.py
> +    def sent_transfer(tx_hash: str, gas_amount: int, gas_price: Optional[int]):
`self._sci.get_transaction_gas_price()` can return `None`.

2019-06-27 16:16 UTC, Krigpl commented on golem/ethereum/paymentskeeper.py
> +    def sent_transfer(tx_hash: str, gas_amount: int, gas_price: Optional[int]):
Not for mined transactions so you're safe here

2019-06-28 09:40 UTC, Krigpl commented on tests/golem/ethereum/test_paymentskeeper.py
> +    def test_sent_transfer(self):
update method name

2019-07-02 11:53 UTC, Krigpl approved these changes
![rickandmorty_yes](https://user-images.githubusercontent.com/3904252/60510847-c0020800-9cd0-11e9-8674-fcf2736b3b28.gif)

2019-07-02 11:53 UTC, Krigpl commented on tests/golem/ethereum/test_incomeskeeper.py
> +    def test_received_eth_transfer(self):
Those two tests do not test different things the way they are implemented right now.
So either remove one of them or introduce some more assertions.

2019-07-02 12:32 UTC, merged