Wasm vbr draft 0
golemfactory/clay pull request #4348
Opened 2019-06-17 14:07 UTC by mplebanski

2019-06-17 20:56 UTC, kubkon commented on apps/glambda/glambdaenvironment.py
> +            environment={'HOME': '/home/user'} if is_linux() else {}
How did `glambda` specifics creep in here? 😬

2019-06-18 08:10 UTC, mbenke requested changes

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +            redundancy_factor, WasmTask._cmp_results, 0)
```suggestion
            redundancy_factor, WasmTask._cmp_results, referee_count=0)
```

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        self.verifier.add_result(self.subtasks[s_id]["actor"], task_result)
This may throw an exception. Do we care?

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +class VbrSubtask:
Description needed

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        for actor, result, verdict in self.verifier.get_verdicts():
what if `verifier.get_verdicts` returns `None`?

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        for r1, r2 in zip(result_list_a, result_list_b):
Are we sure the files are in the same order on both lists?

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +                    logger.info("Verification of task failed")
This log message seems slightly misleading

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        logger.info("Verification of task was successful")
Ditto

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        logger.info("Called in WasmTask")
This should probably eventually go away (or at least be changed to a better message)

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +                    logger.info("Accepting results for subtask %s", s_id)
Maybe add provider id here

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +                    logger.info("Rejecting results for subtask %s", s_id)
Maybe add provider id here

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +                    self.subtasks_given[s_id]['status'] = SubtaskStatus.failure
Is it the whole subtask, or its computation by one provider? If the former, this is dubious in the presence of referees.

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +            for actor, verdict in verdicts:
In this loop, we change subtask status many times, potentially to different values; this smells.

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        s_ids = [s_id for s_id in subtask.get_instances()]
Better name than `s_ids` needed, `instance_ids` maybe?

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +            WasmTask.CALLBACKS.pop(s_id)()
A comment on what is going on here might be helpful

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        return ( WasmTask.REDUNDANCY_FACTOR + 1 ) * len(self.subtasks)
We need to check what the intended semantics of this method is.

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        return 0
why?

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        return 0
why?

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        return dict()
why?

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        logger.info("progress: %f", num_finished / num_total)
this will probably log incorrect progress

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/task.py
> +        dictionary['subtasks_count'] = (WasmTask.REDUNDANCY_FACTOR + 1) * len(dictionary['options']['subtasks'])
This needs reconsideration

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/vbr.py
> +            UnknownActorError - raised when caller deliver an actor that was not previously reported by `add_actor` call.
may also raise `ValueError`

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/vbr.py
> +            tuples (result reference, actor, verification_result) is returned. A None is returned
```suggestion
            tuples (actor, result reference, verification_result) is returned. A None is returned
```

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/vbr.py
> +with a possible third if no decision can be reached based on the first 2."""
This comment is copied from another class and not really accurate

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/vbr.py
> +        print(f'add_actor: {len(self.actors)} actors, {len(self.results)} results, {len(self.buckets)} buckets')
This debug message should go away.

```suggestion
```

2019-06-18 08:10 UTC, mbenke commented on apps/wasm/vbr.py
> +class SimpleSubtaskVerifier(VerificationByRedundancy):
This class is not used (and implements a different API anyway - int comparator rather than bool comparator`).
I would remove it (or replace with correct version).

2019-06-18 09:13 UTC, mplebanski commented on apps/glambda/glambdaenvironment.py
> +            environment={'HOME': '/home/user'} if is_linux() else {}
Well I rebased to b0.20 and that was conflicted with our branch.

2019-06-18 09:16 UTC, mplebanski commented on apps/wasm/task.py
> +        self.verifier.add_result(self.subtasks[s_id]["actor"], task_result)
I believe crashing hard is what we actually want in this case. Giving a wrong actor or a result for not reported actor is not what we intend.

2019-06-18 09:17 UTC, mplebanski commented on apps/wasm/task.py
> +        for actor, result, verdict in self.verifier.get_verdicts():
`VbrSubtask` has method `is_finished` to make sure it never happens.

2019-06-18 09:18 UTC, mplebanski commented on apps/wasm/task.py
> +        for r1, r2 in zip(result_list_a, result_list_b):
I don't know. @kubkon ?

2019-06-18 09:19 UTC, mplebanski commented on apps/wasm/vbr.py
> +            UnknownActorError - raised when caller deliver an actor that was not previously reported by `add_actor` call.
Yeah I see that API description is not aligned to implementation comments. I will remove impl comments and update API.

2019-06-18 12:07 UTC, mplebanski commented on apps/wasm/vbr.py
> +class SimpleSubtaskVerifier(VerificationByRedundancy):
Removed.

2019-06-18 12:20 UTC, mplebanski commented
@mbenke I modified `add_actor` but then reverted the changes. There was a problem that two instances of an Actor class with the same uuid were not equal (which is expected, but we forgot about it), thus duplicated actor was not detected. I added __eq__ and __hash__ operations to Actor class.

2019-06-19 09:14 UTC, mbenke commented on apps/wasm/vbr.py
> +        return id(self)
Why not 
```suggestion
        return hash(self.uuid)
```

2019-06-19 09:16 UTC, mbenke commented on apps/wasm/task.py
> +        for actor, result, verdict in self.verifier.get_verdicts():
..and if `is_finished ` is not checked, we crash with a `TypeError`

2019-06-24 08:52 UTC, kubkon commented on apps/wasm/task.py
> +        for r1, r2 in zip(result_list_a, result_list_b):
AFAIK, yep, they ought to be unless something went horribly wrong in one Golem node; e.g., computation failed, etc.

2019-06-24 08:55 UTC, kubkon commented on apps/wasm/task.py
> +        for actor, result, verdict in self.verifier.get_verdicts():
IMHO any redundant checks in `get_verdicts` are not strictly required. All we need is to document the use-case in the docs, as in "call `is_finished` before calling `get_verdicts`".

2019-06-24 08:55 UTC, kubkon commented on apps/glambda/glambdaenvironment.py
> +            environment={'HOME': '/home/user'} if is_linux() else {}
Ah, ok. We can fix that later then.

2019-06-24 08:56 UTC, kubkon commented on apps/wasm/task.py
> +                    logger.info("Verification of task failed")
It's a remnant of the old code. But I agree, we should iron it out. Also, it probably should be `debug` log rather than `info`.

2019-06-24 08:56 UTC, kubkon commented on apps/wasm/task.py
> +        logger.info("Verification of task was successful")
See above.

2019-06-24 08:57 UTC, kubkon commented on apps/wasm/task.py
> +        logger.info("Called in WasmTask")
Again, see above. I've used it to trace calls through Golem. Not as easy as it looks :grin:

2019-06-24 08:57 UTC, kubkon commented on apps/wasm/task.py
> +                    logger.info("Accepting results for subtask %s", s_id)
That's a good idea. We should probably also change from `info` to `debug`.

2019-06-24 08:58 UTC, kubkon commented on apps/wasm/task.py
> +                    self.subtasks_given[s_id]['status'] = SubtaskStatus.failure
I'm not sure I understand your question. Could you elaborate?

2019-06-24 09:00 UTC, kubkon commented on apps/wasm/task.py
> +        s_ids = [s_id for s_id in subtask.get_instances()]
Perhaps, although is that strictly necessary here? IHMO, it's debatable whether it improves the code hygiene here even.

2019-06-24 09:01 UTC, kubkon commented on apps/wasm/task.py
> +            for actor, verdict in verdicts:
We do? I'm not sure I can see that here. Could you explain?

2019-06-24 09:04 UTC, kubkon commented on apps/wasm/task.py
> +        logger.info("progress: %f", num_finished / num_total)
Good catch!

2019-06-24 09:05 UTC, kubkon commented on apps/wasm/task.py
> +        dictionary['subtasks_count'] = (WasmTask.REDUNDANCY_FACTOR + 1) * len(dictionary['options']['subtasks'])
Agreed! We need to agree whether we want this to be transparent wrt the redundancy; i.e., whether Golem should or shouldn't be aware of verification by redundancy at all.

2019-06-24 12:22 UTC, mplebanski commented on apps/wasm/task.py
> +class VbrSubtask:
Resolved

2019-07-01 09:24 UTC, mplebanski commented on apps/wasm/task.py
> +        logger.info("Called in WasmTask")
I removed it. There are other more informative logs left though.

2019-07-01 13:12 UTC, kubkon approved these changes

2019-07-02 09:11 UTC, mplebanski commented
@mbenke @kubkon Please approve for control build.

2019-07-02 09:14 UTC, maaktweluit commented
@mplebanski it has an approval so it should build, strange.. hit the rebuild to check https://buildbot.golem.network/buildbot/#/builders/12/builds/10804

2019-07-15 13:41 UTC, kubkon commented
Closing as it's been superseded by #4475.

2019-07-15 13:41 UTC, closed without merging