Add run_benchmark to environments
golemfactory/clay pull request #4372
Opened 2019-06-21 09:01 UTC by Krigpl

And create `cpu_benchmark` Docker image which uses an existing minilight benchmark.

2019-06-21 13:51 UTC, maaktweluit approved these changes

2019-06-24 07:47 UTC, Wiezzel requested changes
I think using stdout would be better than a JSON file in this case. Keep in mind that sharing directories is quite messy on Windows. If the shared directory is not a subdirectory of `CoputerRes` than a pop-up will appear asking for admin permissions (!). And here you're using a temporary directory.

2019-06-24 07:47 UTC, Wiezzel commented on golem/envs/docker/benchmark/Dockerfile
> +ENTRYPOINT ["python3", "/golem/entrypoint.py"]
Line feed missing.

2019-06-24 07:47 UTC, Wiezzel commented on golem/envs/docker/cpu.py
> +    def wait_until_stopped(self) -> Deferred:
Maybe move this up in class hierarchy and make a part of `Runtime` interface?

2019-06-24 10:05 UTC, Wiezzel commented on golem/envs/docker/cpu.py
> +    SHARED_DIR_PATH: ClassVar[str] = '/golem/work'
Is this consistent with Task API?

2019-06-24 10:19 UTC, Krigpl commented on golem/envs/docker/cpu.py
> +    SHARED_DIR_PATH: ClassVar[str] = '/golem/work'
While it's not documented atm, this is what Blender assumes, so I guess this should be added as part of the Task API.

2019-06-24 10:32 UTC, Wiezzel reviewed
A suggestion to move picking the first line and converting to float after `clean_up()` so that the container get cleaned up if something goes wrong with the output.

2019-06-24 10:32 UTC, Wiezzel commented on golem/envs/docker/cpu.py
> +        score = float(list(runtime.stdout('utf-8'))[0])
```suggestion
        stdout = list(runtime.stdout('utf-8'))
```

2019-06-24 10:32 UTC, Wiezzel commented on golem/envs/docker/cpu.py
> +        return score
```suggestion
        return float(stdout[0])
```

2019-06-24 10:42 UTC, Wiezzel commented on golem/envs/docker/cpu.py
> +    def wait_until_stopped(self) -> Deferred:
Maybe *the implementation* could be moved as well? It's not Docker-specific after all.

2019-06-24 10:52 UTC, Krigpl commented on golem/envs/docker/cpu.py
> +    def wait_until_stopped(self) -> Deferred:
I dunno, I'm still considering using `docker.wait()` method since I'm not happy with this kind of active waiting and wouldn't want it to become the default implementation for all envs. Not insisting tho.

2019-06-24 11:04 UTC, Wiezzel commented on golem/envs/docker/cpu.py
> +    def wait_until_stopped(self) -> Deferred:
OK, we don't have any other envs for now. We can reconsider this once we have some more.

2019-06-24 11:04 UTC, Wiezzel approved these changes

2019-06-24 13:24 UTC, merged