Fixed rpc tests after disabling concent
golemfactory/clay pull request #4393
Opened 2019-06-27 09:14 UTC by maaktweluit

Caused by #4370 

- Mainnet was missing the balance check override
- Disabled key-reuse on mainnet test
- Testnet was still using the old concent override in playbook
- Moved old concent playbook to `test_rpc/concent`

2019-06-27 10:00 UTC, mfranciszkiewicz commented on scripts/node_integration_tests/playbooks/golem/rpc_test/concent/playbook.py
> +                print("Unexpected result: %s" % result)
Shouldn't we call `self.fail()` if the result is incorrect?

2019-06-27 10:04 UTC, maaktweluit commented on scripts/node_integration_tests/playbooks/golem/rpc_test/concent/playbook.py
> +                print("Unexpected result: %s" % result)
i think it should retry, but concent is not my strongest side of golem.
In case of retry there is a sleep missing...

@shadeofblue what do you think? sleep or fail here?

2019-06-27 12:08 UTC, shadeofblue commented on scripts/node_integration_tests/playbooks/golem/rpc_test/concent/playbook.py
> +                print("Unexpected result: %s" % result)
I think it should `fail` ... this is an artifact of the change that @etam made that changed the way playbooks are run (earlier, it would just run out of steps in this case)

2019-06-27 12:22 UTC, shadeofblue requested changes
@maaktweluit it's strange that the _base_ playbook is the one that defines the empty step... I think it should be the other way round ... 

especially, that with your changes here, `concent` playbook is actually never used ...

2019-06-27 12:23 UTC, maaktweluit commented on scripts/node_integration_tests/playbooks/golem/rpc_test/concent/playbook.py
> +                print("Unexpected result: %s" % result)
fixed

2019-06-27 12:27 UTC, shadeofblue commented on scripts/node_integration_tests/tests/test_golem.py
>          self._run_test('golem.rpc_test')
with your changes in place, `golem.rpc_test.concent` must be used here

2019-06-27 13:23 UTC, maaktweluit commented on scripts/node_integration_tests/tests/test_golem.py
>          self._run_test('golem.rpc_test')
added it as a separate test

2019-06-27 13:26 UTC, maaktweluit commented
@shadeofblue the "base" playbook is the default mode to run, `testnet + no concent`, i see this could also be the other way around but as discussed we leave it for now.

Resolved your other comment by adding the test

2019-06-28 10:35 UTC, mfranciszkiewicz approved these changes

2019-07-01 11:52 UTC, merged