Asyncio reactor
golemfactory/clay pull request #4417
Opened 2019-07-02 15:47 UTC by mfranciszkiewicz

2019-07-04 15:07 UTC, maaktweluit requested changes
LGTM!

Some small comments

2019-07-04 15:07 UTC, maaktweluit commented on golem/node.py
> +        from autobahn.wamp import ApplicationError
maybe add a comment why this import is local only

2019-07-04 15:07 UTC, maaktweluit commented on golem/node.py
> +                    """.format(error_message)
nicer to use native logger formatting, but since its ERROR not so important

2019-07-04 15:07 UTC, maaktweluit commented on golem/rpc/__init__.py
> +    cert_dir = os.path.join(data_dir, CROSSBAR_DIR)
should we add `os.path` vs `pathlib` to the styleguide? would prefer to use only one

2019-07-04 15:07 UTC, maaktweluit commented on golem/rpc/router.py
> +        self.node._config = self.config  # noqa # pylint: disable=protected-access
```suggestion
        self.node.load_config(None, self.config)
```

2019-07-04 15:07 UTC, maaktweluit commented on golemapp.py
> -# Python flags, needed by crossbar (package only)
yay, cleanup!

2019-07-04 15:17 UTC, mfranciszkiewicz commented on golem/rpc/__init__.py
> +    cert_dir = os.path.join(data_dir, CROSSBAR_DIR)
This is code has been moved from another file, probably from before we started using `pathlib`

2019-07-04 15:19 UTC, mfranciszkiewicz commented on golem/node.py
> +        from autobahn.wamp import ApplicationError
It doesn't need to be, it's just used in this one single place

2019-07-04 15:21 UTC, mfranciszkiewicz commented on golem/rpc/__init__.py
> +    cert_dir = os.path.join(data_dir, CROSSBAR_DIR)
It's a good idea to add this to the guidelines

2019-07-04 15:27 UTC, maaktweluit commented on golem/node.py
> +        from autobahn.wamp import ApplicationError
ok, then no comment needed

2019-07-04 15:27 UTC, maaktweluit commented on golem/rpc/__init__.py
> +    cert_dir = os.path.join(data_dir, CROSSBAR_DIR)
ok, lets leave it for now and add it to the guidelines

2019-07-04 15:27 UTC, maaktweluit approved these changes

2019-07-05 09:37 UTC, zakaprov commented
I don't think I'm the right person to review these changes. I'd ask for a second opinion from someone more experienced with twisted and asyncio (@jiivan perhaps?).

2019-07-05 10:02 UTC, jiivan approved these changes
Looks good :+1: Have you tried running integration tests on this branch?

2019-07-05 16:07 UTC, mfranciszkiewicz commented
`scripts/node_integration_tests/tests/test_golem.py` pass on macOS and Linux

@maaktweluit reported an issue occurring with the older version of Twisted (reactor trying to register multiple readers for the same file descriptor) but I'm unable to reproduce it

2019-07-09 09:55 UTC, mfranciszkiewicz commented
I re-ran the suite multiple times on macOS and Linux and still cannot observe the reported issue. Tested with Python 3.6.4, 3.6.5 and 3.6.8.

The integration tests on buildbots behave similarly to the `develop` branch. Thus, the issue is most probably a local one.

Awaiting QA approval.

2019-07-23 15:14 UTC, mfranciszkiewicz commented
Golem seems to be stable, though the error still appears from time to time:
```
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 136, in _readOrWrite
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/abstract.py", line 271, in doWrite
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/abstract.py", line 430, in stopWriting
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 237, in removeWriter
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 352, in remove_writer
    return self._remove_writer(fd)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 326, in _remove_writer
    self._selector.modify(fd, mask, (reader, None))
  File "/usr/lib/python3.6/selectors.py", line 261, in modify
    key = self.register(fileobj, events, data)
  File "/usr/lib/python3.6/selectors.py", line 405, in register
    key = super().register(fileobj, events, data)
  File "/usr/lib/python3.6/selectors.py", line 241, in register
    .format(fileobj, key.fd))
KeyError: '65 (FD 65) is already registered'
```

2019-07-23 16:21 UTC, mfranciszkiewicz commented
`removeWriter` seems to be a subject of a race condition. I've committed a patch suppressing the error.

2019-07-24 14:40 UTC, Wiezzel commented on golem/core/common.py
> +    asyncioreactor.install()
```suggestion
    asyncioreactor.install(asyncio.get_event_loop())
```

2019-07-25 16:45 UTC, merged