Better names for frames
golemfactory/clay pull request #442
Opened 2016-06-30 15:11 UTC by banasiakadam60

Change padding in filenames

2016-07-18 22:53 UTC, chfast commented
You can link PR with issues by:
Closes #398.

2016-08-19 14:08 UTC, badb commented on gnr/customizers/renderingmainwindowcustomizer.py
> +                                   str(frame_num).zfill(len(str(len(definition.renderer_options.frames)))), ext)
Uhm, it's not a very good approach. You're taking into account only the number of frames which may have nothing in common with frames numbers. For example we may have 3 frames with numbers [11232, 13134, 23131]. 
So we should take into account the maximum numer frame, not number of frames. 
And the best approach is to allow user to define this format (number of leading zeros).

2016-08-19 14:17 UTC, badb commented on gnr/task/scripts/docker_blendertask.py
> +                 params.frames, params.output_format, params.total_tasks if params.total_tasks else 4)
Also name total tasks may be very misleading here. It may have nothing in common with number of frames.

2016-09-08 12:27 UTC, badb commented
It's very unclear what new options does. Some explanations and better default value is a must. 
Additionally, it's a very specific options strongly connected with "frame render tasks". So it should be in task specific options (and only for Blender). Also leading zero should not be part of task_definition but element in options (renderer_options) in definition.

2016-09-08 14:59 UTC, banasiakadam60 commented
OK, but what should be the default value? At this moment it set to 0 and defined as `max(definition.leading_zeros, max(frame_numbers))` in case of default (0) or incorrect (too low) value.

2016-09-08 16:14 UTC, badb commented
I'm not sure (3 or 4)? My problem with default 0 is that I'm not sure if I should write "000" or "3". 
Potential problem with `max(definition.leading_zeros, max(frame_numbers))` is that you're calling it two times: in customizer (ok) and in blender task script. Blender task script works only on small subset of frames, so it this two methods may generate completelly different results.
It may not be a problem - there's a chance that blender finds max frame number in the full scene, so the final file will have proper name, but please check it.

2016-09-08 16:26 UTC, banasiakadam60 commented
I've checked it yesterday and it looks fine. But ofc I'll check it one more time :)
Maybe I'll add some additional checkbox to determine whether the user wants to define padding, or wants it to be generated automaticly (basing on the frames numbers)?

2016-09-12 16:17 UTC, badb commented
As you wish. I don't like the idea of additional checkbox, but I'm not sure what's better.

2016-09-13 10:55 UTC, badb commented
Ok, checkbox looks nice. One additional suggestion: maybe you can change name 'leading zeros' to 'pad to length' or something like that? 
Problems:

- Subtasks results are named properly, but final pictures have old names. For example part of the subtask result has name frame_5_00005.exr, but final picture has names frame005.exr. 
- Subtasks numbers in final frame numbers are unnecessary (and sometimes plain wrong), so output file name for that task should be frame_00005.exr and not frame_5_00005.exr. This subtask number is only userd to distinct different part of frames received from computing nodes.

2016-09-29 16:17 UTC, badb requested changes
Now it's another way around. Whole frame has proper name, but part of the frames are named as a whole frame and therefore override one another producing final empty frame. To reproduce: choose more subtasks than frames, eg. frames 3-4, number of subtasks 10.

2016-10-04 16:22 UTC, badb commented on gnr/customizers/renderingmainwindowcustomizer.py
> +        return "{}_{}_{}{}".format(output_name, num, str(frame_num).zfill(padding), ext)
Final frame have name just like "abc_00007.png". Frame is saved correctly, but in the GUI it's displayed like "abc_0_00007.png" which doesn't exist.

2016-10-04 16:22 UTC, badb commented on gnr/ui/BlenderWidget.ui
> +        <string>Set number of leading zeros in frames name</string>
I still have a feeling that this description is misleading. More precisely we're padding the frame number in frame name with leading zeros to the given width.

2016-10-11 14:09 UTC, badb commented
I have a few more ideas how to improve it (maybe we can replace padding GUI elements with Blender-like "#" notation in output names. I'll try them out soon.

2016-10-24 21:23 UTC, badb submitted a review, later dismissed

2016-10-25 12:29 UTC, badb commented
Alternative approach. User define output file name for frames with "#", ex. "output_image_#####_ver_1.PNG". It's compatibile with Blender approach, so it may be more natural for the users. If you don't like it and prefare previous version with GUI, feel free to reverse the last commit.

2016-10-26 18:37 UTC, mfranciszkiewicz approved these changes

2016-11-25 15:21 UTC, merged