[WIP] Confirm outgoing GNT
golemfactory/clay pull request #4458
Opened 2019-07-11 15:01 UTC by jiivan

2019-07-15 08:48 UTC, Krigpl requested changes

2019-07-15 08:48 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +        tx_hash = f'0x{receipt.tx_hash}'
tx_hash from the receipt has `0x` already

2019-07-15 08:48 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +    def on_confirmed(
make it protected

2019-07-15 08:48 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
>          def on_confirmed(_receipt) -> None:
drop `_` since now it's used

2019-07-15 09:08 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +        tx_hash = f'0x{receipt.tx_hash}'
No it doesn't
```python
In [10]: raw_receipt
Out[10]: 
{'blockHash': b"\xcb\xcaI\xfb,u\xba/\xad\xa5ln\xa7\xdfYyDA'\xd2\x9bkN\x93\xa7y}\xc2.\x979\x9c",
 'blockNumber': 2940769,
 'gasUsed': 21000,
 'status': 1,
 'transactionHash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}

In [11]: golem_sci.structs.TransactionReceipt(raw_receipt).tx_hash
Out[11]: '0000000000000000000000000000000000000000000000000000000000000000'
```

2019-07-15 09:27 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +        tx_hash = f'0x{receipt.tx_hash}'
It does. `raw['transactionHash']` is not simply bytes, it's a special struct from web3 that when called `.hex()` on it, it generates a hex value with `0x` prefix.

2019-07-15 09:59 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +        tx_hash = f'0x{receipt.tx_hash}'
:-0

2019-07-15 12:41 UTC, Krigpl requested changes

2019-07-15 12:41 UTC, Krigpl commented on golem/ethereum/transactionsystem.py
> +        unconfirmed_query = model.WalletOperation.select() \
It'd be great to have this query somewhere else, like PaymentsKeeper

2019-07-15 12:41 UTC, Krigpl commented on golem/ethereum/paymentskeeper.py
> -    def confirmed_transfer(
imo it's worth it to keep this method - thus keeping all the operations on models here and outside the transaction system

2019-07-15 12:41 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +        self.ets._gntb_balance = 100
Please use the `_refresh_balances` approach as in other tests.

2019-07-15 12:41 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +        self.ets._on_confirmed(self.receipt)
Assert that `sci.on_transaction_confirmed` has been called and call the provided callbacks instead of invoking this function manually.

2019-07-15 12:41 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +        self.ets._on_confirmed(self.receipt)
ditto

2019-07-15 12:41 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +        raw_receipt={
Imo there's no reason for this function to be implemented this way, you could instead use `Mock(spec=TransactionReceipt)` and set fields you are interested in.
Especially that `blockHash` is still buggy just like `transactionHash` has been (raw bytes).

2019-07-15 13:37 UTC, jiivan commented on tests/golem/ethereum/test_transactionsystem.py
> +        raw_receipt={
It a simple struct. Why should I mock it?

2019-07-15 15:20 UTC, Krigpl commented on tests/golem/ethereum/test_transactionsystem.py
> +        raw_receipt={
To avoid the kind of bugs that you already introduced (incorrect types in the raw_receipt).

2019-07-16 09:52 UTC, Krigpl approved these changes

2019-07-17 09:08 UTC, jiivan commented on tests/golem/ethereum/test_transactionsystem.py
> +        raw_receipt={
I got your point. But reason I introduced that function was exactly that. I wasn't sure what was the correct type. Once this function is bug-free it will be a good factory for all tests here. Better than mock IMO.

2019-07-17 09:55 UTC, merged