New ResourceManager class
golemfactory/clay pull request #4490
Opened 2019-07-16 16:15 UTC by mfranciszkiewicz

[CLAY-384]

A `ResourceManager` class that delegates all resource management to `simple-transfer`.
- shares only a single file per call
- downloads only a single file per call
- uses an in-memory cache for shared files

2019-07-17 08:55 UTC, Krigpl requested changes
Not sure about the timeout thing.

2019-07-17 08:55 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +        return deferred
Let's use inline callbacks for clarity

2019-07-17 08:55 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +        cached = self._cache.get(resolved_path)
afaik simple transfer deletes the files after some time out (3 days?)
meaning it can happen that the file will be deleted from simple transfer but you will return the invalid cached value.
maybe there should be an API call to simple transfer that asks whether given resource ID is still valid.

2019-07-17 08:55 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +        return deferred
inline callbacks

2019-07-17 08:55 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +        resolved_path = directory.resolve(strict=False)
maybe also throw if path is a file and not a directory

2019-07-17 09:10 UTC, mfranciszkiewicz commented on golem/resource/resourcemanager.py
> +        cached = self._cache.get(resolved_path)
IMO this timeout should be controlled by Golem, not simple-transfer. It forgets the files after restarting anyway.

2019-07-17 09:12 UTC, mfranciszkiewicz commented on golem/resource/resourcemanager.py
> +        resolved_path = directory.resolve(strict=False)
Or simply forward the call and fail with simple-transfer

2019-07-17 09:21 UTC, mfranciszkiewicz commented on golem/resource/resourcemanager.py
> +        resolved_path = directory.resolve(strict=False)
Or it may just be handled by simple-transfer, less extra management here

2019-07-17 09:22 UTC, mfranciszkiewicz commented
I'd like to hear more voices on replacing the deferred's with inlineCallbacks

2019-07-17 09:23 UTC, Krigpl commented
> I'd like to hear more voices on replacing the deferred's with inlineCallbacks

What are the cons of doing that?

2019-07-17 09:28 UTC, mfranciszkiewicz commented
@Krigpl There’s nothing wrong with implementing inlineCallbacks. It’s a matter of spending time refactoring vs doing something else.

2019-07-17 10:34 UTC, Wiezzel commented on golem/resource/client.py
> +        del recursive, kwargs
This `del` looks hacky. Why is it needed?

2019-07-17 10:34 UTC, Wiezzel commented on golem/resource/client.py
> +        filepath = kwargs['filepath']
Maybe you could just change the signature in `IClient` to include `filepath`? Passing argument like this is obscure and kinda ugly.

2019-07-17 10:34 UTC, Wiezzel commented on golem/resource/resourcemanager.py
> +            peers=None,
Type of`peers`?

2019-07-17 10:34 UTC, Wiezzel commented on golem/resource/resourcemanager.py
> +            an assigned resource ID or a client-specific error """
From [our styleguide](https://github.com/golemfactory/styleguide/blob/gh-pages/pyguide.md#382-functions-and-methods):

> The docstring should be imperative ("""Fetch rows from a Bigtable.""") rather than descriptive ("""Fetches rows from a Bigtable.""").

2019-07-17 10:34 UTC, Wiezzel commented on golem/resource/client.py
> +            files: Dict,
`Dict[str,str]` ?

2019-07-17 10:44 UTC, mfranciszkiewicz commented on golem/resource/client.py
> +        del recursive, kwargs
Oh, it’s a way of handling unused variables from our new guidelines.

2019-07-17 10:46 UTC, Wiezzel commented
I'm also in favor of using `inlineCallbacks`. It makes code easier to understand because it mimics typical synchronous code. And you wouldn't need things like returning arguments back from `_shared()` or `_downloaded()`.

2019-07-17 10:49 UTC, Wiezzel commented on golem/resource/client.py
> +        del recursive, kwargs
Do think it's reasonable? Maybe we should adjust the guidelines? If not, just please put some comment (`#  unused arguments`).

2019-07-17 10:56 UTC, Wiezzel commented on golem/resource/client.py
> +        del recursive, kwargs
Actually, I thought that `pylint` won't complain at all about unused arguments if they are added for compatibility with superclass interface.

2019-07-17 11:42 UTC, mfranciszkiewicz commented on golem/resource/client.py
> +        del recursive, kwargs
In general: `del` makes sure that arguments marked as unused in a different way cannot be used at all (e.g. `_recrusive`). It's simply unusual for our codebase.

> Actually, I thought that pylint won't complain at all about unused arguments if they are added for compatibility with superclass interface.

And here you can see it explicitly.

2019-07-17 11:47 UTC, Wiezzel commented on golem/resource/client.py
> +        del recursive, kwargs
Well, ok.

2019-07-17 11:49 UTC, mfranciszkiewicz commented on golem/resource/client.py
> +        del recursive, kwargs
I actually wanted to create a PR regarding unused arguments but in the end I think it does make sense. It's not about keeping `pylint` happy but enforcing the promise of not using the arguments at all.

2019-07-17 13:37 UTC, Krigpl requested changes

2019-07-17 13:37 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +        cached = self._cache.get(resolved_path)
It's still an issue if Golem runs for more than 3 days at the moment.

2019-07-17 13:37 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +    ):
return type

2019-07-17 13:37 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +            return a future which resolves to Tuple[ResourceId, Path]
resource_id is unchanged from the argument so no need to return it, just the filepath is fine.

2019-07-17 13:37 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +            return a future which resolves to a ResourceId or
not valid anymore

2019-07-17 13:37 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +    Client = HyperdriveAsyncClient
Just make a `Client` instance a dependency in the constructor. There's no reason for this approach, and it will also make testing much easier.

2019-07-17 13:40 UTC, mfranciszkiewicz commented on golem/resource/resourcemanager.py
> +    ):
It's a `GeneratorType` type with no subtype which I consciously omitted here. If I put the expected return type, the linter complains.

2019-07-17 13:43 UTC, Wiezzel commented on golem/resource/resourcemanager.py
> +    ) -> None:
I'd suggest renaming to `add_to_cache` or (even better) inlining this methods as it's only used once if see correctly.

2019-07-17 13:43 UTC, Wiezzel commented on golem/resource/resourcemanager.py
> +    ) -> None:
I'd suggest renaming to `remove_from_cache` or (even better) inlining this methods as it's only used once if see correctly.

2019-07-17 13:45 UTC, mfranciszkiewicz commented on golem/resource/resourcemanager.py
> +    Client = HyperdriveAsyncClient
> There's no reason for this approach

There's also no reason for providing the client instance in the constructor since there is actually only one `Client` used in Golem.

> it will also make testing much easier

One line was required to change the tested `Client` class.

2019-07-17 13:47 UTC, mfranciszkiewicz commented on golem/resource/resourcemanager.py
> +        cached = self._cache.get(resolved_path)
And will patching `simple-transfer` solve the discussed issue?

2019-07-17 13:57 UTC, maaktweluit reviewed
LGTM!

Some nitty comments, will approve on reply

I see a few more functions where the signature fits on one line, can mark them all if you want :)

2019-07-17 13:57 UTC, maaktweluit commented on golem/resource/client.py
> +from typing import Optional, Dict, Iterable, Tuple
it used to be alphabetically sorted, but makes more sense to do module imports after the system ones

maybe move the whitespace from line 11 up as well to group `twisted` and `requests`

2019-07-17 13:57 UTC, maaktweluit commented on golem/resource/client.py
> +    ) -> str:
this seems to fit on one line

2019-07-17 13:59 UTC, mfranciszkiewicz commented on golem/resource/client.py
> +    ) -> str:
It's for the sake of consistency

2019-07-17 14:03 UTC, mfranciszkiewicz commented on golem/resource/client.py
> +    ) -> str:
But I can make them fit in one line if you will.

2019-07-17 14:07 UTC, maaktweluit commented on golem/resource/client.py
> +    ) -> str:
haha, was looking for consistency and then saw the `__init__`..

I do not mind, both are OK with me :)

2019-07-17 14:09 UTC, Wiezzel commented on golem/resource/client.py
> +    ) -> str:
Actually, our guidelines encourage one parameter per line.

2019-07-17 14:15 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +    Client = HyperdriveAsyncClient
Please familiarize yourself with the benefits of dependency injection pattern.
I wouldn't consider mocking private methods in tests as a good approach when a simpler and cleaner alternative exists.
By injecting the Client you'll be able to mock the instance appropriately and avoid code like this: 
``` with mock.patch.object(
            self.resource_manager._client,
            'add_async',
            wraps=self.resource_manager._client.add_async
        ) as add_async:```

> There's also no reason for providing the client instance in the constructor since there is actually only one Client type used in Golem.

This is the case now, there's no reason to believe it'll always be the case and then it'll have to be refactored.

2019-07-17 14:22 UTC, mfranciszkiewicz commented on golem/resource/resourcemanager.py
> +    Client = HyperdriveAsyncClient
> Please familiarize yourself with the benefits of dependency injection pattern.

This assumption here was truly not needed.

> I wouldn't consider mocking private methods in tests as a good approach when a simpler and cleaner alternative exists.

It wouldn't be `DummyClient` that I would replace the `Client` with, just some other implementation. This code has nothing to do with passing a client instance in the argument. I simply didn't create a new one.

> This is the case now, there's no reason to believe it'll always be the case and then it'll have to be refactored.

And yet somehow it is always discouraged in the reviews.

2019-07-17 14:38 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +    Client = HyperdriveAsyncClient
In the `TestResourceManager` we wanna test the functionality of the `ResourceManager` class that it makes expected calls to the some `Client` instance and we're not interested how the `Client ` instance is in fact implemented.

Thus if we simply change the constructor to
```
    def __init__(
            self,
            client: HyperdriveAsyncClient,
    ) -> None:
        self._client = client
        self._cache_rev: Dict[ResourceId, Path] = dict()
```
we sacrifice absolutely nothing but we gain:
- ability to write clean unit tests. We can just pass a Mock object here and assert in the tests that expected methods have been called in different scenarios - exactly what we want to test.
- flexibility to have two ResourceManager instances with different clients in ever needed in the future for free
- no need for unnecessary DummyClient and DummyResourceManager

2019-07-18 09:00 UTC, Krigpl reviewed
Thanks, this looks super clear and easy now imo.

2019-07-18 09:00 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +        cached = self._cache.get(resolved_path)
Yeah, making the `timeout` a param of the `upload` command would be the best solution imo.

2019-07-18 09:00 UTC, Krigpl commented on tests/golem/resource/test_resourcemanager.py
> +        assert sample_path in self.resource_manager._cache
The way to test `drop` without accessing protected members would be to call `share`, then `drop`, then `share` again and assert that the second `share` calls a method on the client.

2019-07-18 09:00 UTC, Krigpl commented on tests/golem/resource/test_resourcemanager.py
> +        assert self.resource_manager._cache[sample_path] == result
`test_share_cached` asserts exactly that but without accessing the protected member so I'd say this test is redundant.

2019-07-18 09:12 UTC, mfranciszkiewicz commented on golem/resource/resourcemanager.py
> +        cached = self._cache.get(resolved_path)
`timeout` is a part of `ClientOptions`, the problematic part is the enforced sweep, which also breaks the current implementation.

2019-07-18 09:21 UTC, mfranciszkiewicz commented on tests/golem/resource/test_resourcemanager.py
> +        assert sample_path in self.resource_manager._cache
That's true if we really do not want to access protected members in unit tests. But it hides the intent behind the test and this is more explicit.

2019-07-18 09:31 UTC, Krigpl commented on golem/resource/resourcemanager.py
> +        cached = self._cache.get(resolved_path)
Oh okay, I didn't realize there are two kinds of timeouts here.

2019-07-18 09:32 UTC, Krigpl approved these changes

2019-07-18 09:52 UTC, Wiezzel approved these changes
👍

2019-07-22 15:12 UTC, Krigpl commented
fwiw I'm fine with merging it as is and patching simple-transfer later if this is what's blocking this PR.

2019-07-22 15:30 UTC, mfranciszkiewicz commented
`simple-transfer` has been updated but not released. I'll introduce the required changes in a separate PR.

2019-07-22 15:31 UTC, merged