Introduce RequestorBrassMarketStrategy
golemfactory/clay pull request #4512
Opened 2019-07-19 10:15 UTC by mplebanski

2019-07-23 10:14 UTC, Krigpl requested changes
fwiw, removing twisted from marketplace and adjusting tasksession should be one PR and the rest of the refactoring another one. Keep PRs modular.

2019-07-23 10:14 UTC, Krigpl commented on golem/task/tasksession.py
> +                  current_task.header.max_price, msg.price, self)
Most of the times when you feel like passing `self` to a constructor of a different object there's huge probability there's an issue with the design. This is the case here, the way `context` is used is completely unnecessary. Just do `self._offer_chosen` on line 320.

2019-07-23 10:14 UTC, Krigpl commented on golem/task/tasksession.py
> +            from twisted.internet import reactor
There's `golem.deferred.call_later` for that.

2019-07-23 10:54 UTC, mplebanski commented on golem/task/tasksession.py
> +                  current_task.header.max_price, msg.price, self)
@Krigpl Unfortunately If I call `self._offer_chosen` on line 320 it will be all done in a context of a single provider. Glad you looked into it, we are looking for a solution that would not require us to pass `self` to another object.

2019-07-23 11:07 UTC, Krigpl commented on golem/task/tasksession.py
> +                  current_task.header.max_price, msg.price, self)
Quite. Then one way would be to simply replace context with the generic callback function
(which is effectively same as the previous approach with deferreds).

2019-07-23 11:10 UTC, mfranciszkiewicz commented on golem/task/tasksession.py
> +                  current_task.header.max_price, msg.price, self)
@mplebanski The task session object should not be required at all - we have a task session message queue in place. Besides, it would be a better idea to store `weakref`s to session if truly needed.

2019-07-23 12:04 UTC, mplebanski commented on golem/task/tasksession.py
> +                  current_task.header.max_price, msg.price, self)
@mfranciszkiewicz Could you elaborate on `task session object should not be required at all`?

2019-07-24 09:53 UTC, mplebanski commented
> fwiw, removing twisted from marketplace and adjusting tasksession should be one PR and the rest of the refactoring another one. Keep PRs modular.

I am closing this in order to open a PR for refactor only.

2019-07-24 09:53 UTC, closed without merging