Modify decorator removing test files to remove them by default
golemfactory/clay pull request #4528
Opened 2019-07-23 15:43 UTC by cameel

This is a simple change that flips the meaning of the `@remove_temporary_dirtree_if_test_passed` decorator (now called `@keep_temporary_dirtree_if_test_failed`). Now temporary files are automatically deleted unless you use the decorator. And even then we only keep them if the test fails.

### Dependencies
This pull request is based on #4515 and should be merged after it.

**NOTE**: I have set the base branch of this pull request to `transcoding-all-files-codecs-framerates-resolutions` (#4515) rather than `CGI/transcoding/master`. Please remember to change the base branch back to `CGI/transcoding/master` before you merge.

2019-10-02 14:19 UTC, nieznanysprawiciel requested changes
remove_temporary_dirtree_if_test_passed is still present in some tests in test_ffmpegintegration.py

2019-10-02 14:19 UTC, nieznanysprawiciel commented on golem/testutils.py
>          # will set this variable to True on the end of test.
Comment not updated

2019-10-02 15:57 UTC, nieznanysprawiciel commented
> remove_temporary_dirtree_if_test_passed is still present in some tests in test_ffmpegintegration.py

Ok I changed it already

2019-10-03 05:18 UTC, pawelkisielewicz commented on golem/testutils.py
>          # will set this variable to True on the end of test.
Sorry for this, already updated

2019-10-03 08:33 UTC, nieznanysprawiciel approved these changes

2019-10-08 21:27 UTC, cameel commented
OK. Great. This pull request sits right on top of `CGI/transcoding/master` so it can be merged right way.

I have changed the base of this pull request to `CGI/transcoding/master` since the `transcoding-all-files-codecs-framerates-resolutions` has already been merged.

Sorry for the old decorator name. Looks like we did not update this pull request after we added new tests in a pull request below it.

2019-10-29 15:21 UTC, nieznanysprawiciel commented
Will be merged together with https://github.com/golemfactory/golem/pull/4835

2019-10-29 15:21 UTC, closed without merging