Remove Twisted from OfferPool
golemfactory/clay pull request #4533
Opened 2019-07-24 09:53 UTC by mplebanski

Closes #4521

2019-07-24 14:52 UTC, mplebanski commented
@Krigpl  @mfranciszkiewicz Do you have any idea why this single concent test is still failing?

2019-07-25 10:14 UTC, Krigpl reviewed
@mplebanski It's nature of the Concent tests to fail in the least expected situations.

2019-07-25 10:14 UTC, Krigpl commented on golem/marketplace/offerpool.py
> +            offer {Any} -- offer can be a composite (tuple,
But why? What's wrong with just having concrete `Offer` struct here?

2019-07-25 10:14 UTC, Krigpl commented on golem/marketplace/offerpool.py
> +    def clear_offers_for_task(cls, task_id):
This isn't used by production code, meaning most likely it shouldn't exist.

2019-07-25 10:25 UTC, mplebanski commented on golem/marketplace/offerpool.py
> +            offer {Any} -- offer can be a composite (tuple,
It's a work around for not passing a callback or context to OfferPool. This class main responsibility is sorting, that's why I decided to create an API that looks similiar to sort.

2019-07-25 10:36 UTC, Krigpl commented on golem/marketplace/offerpool.py
> +            offer {Any} -- offer can be a composite (tuple,
I see. Not a big fan of this though.
Neater way (but more verbose) would be make `Offer` an interface that requires properties like `reputation, price, quality` and make the caller provide an object that implements that interface. This way the caller can pass an object that also contains the callbacks but `OfferPool` is completely agnostic to it.

2019-07-25 14:36 UTC, mplebanski commented
![sad panda](https://media.giphy.com/media/7p3e2WCM0VEnm/giphy.gif)

2019-07-25 15:17 UTC, Krigpl requested changes

2019-07-25 15:17 UTC, Krigpl commented on tests/golem/task/test_concent_logic.py
> +        while send_mock.call_args is None:
Nope. `OfferPool::add` is mocked at the top of this test class, adjust it accordingly and do not introduce this sleep.

2019-07-25 15:17 UTC, Krigpl commented on golem/marketplace/offerpool.py
> +    def reset(cls):
That's also not used by the production code.

2019-07-25 15:17 UTC, Krigpl commented on golem/task/tasksession.py
> +            deferred.call_later(
That still needs some error handling (like it was previously).

2019-07-25 15:17 UTC, Krigpl commented on tests/golem/marketplace/test_offerpool.py
> +        OfferPool.reset()
Is it really needed here? I don't think tests interfere with each other.

2019-07-25 15:20 UTC, Krigpl commented on tests/golem/task/test_concent_logic.py
> +        while send_mock.call_args is None:
And by that, I mean something like mocking the `defer_later` call to call instantly.

2019-07-25 15:27 UTC, mplebanski commented on tests/golem/task/test_concent_logic.py
> +        while send_mock.call_args is None:
@Krigpl Where is OfferPool:aadd mocked?

2019-07-25 15:28 UTC, mbenke commented on golem/marketplace/offerpool.py
> +    def reset(cls):
Actually `reset` should be probably called by `Tasks.client.purge_tasks`

2019-07-25 15:33 UTC, mplebanski commented on tests/golem/task/test_concent_logic.py
> +        while send_mock.call_args is None:
And what is `TestWithReactor` for? And it's method `_sleep`?

2019-07-25 15:35 UTC, Krigpl commented on tests/golem/task/test_concent_logic.py
> +        while send_mock.call_args is None:
> at the top of this test class

I mean, before you removed it https://github.com/golemfactory/golem/blob/develop/tests/golem/task/test_concent_logic.py#L391

2019-07-25 15:38 UTC, mplebanski commented on tests/golem/task/test_concent_logic.py
> +        while send_mock.call_args is None:
Also I can not mock `defer_later` with an in place call since code in `react_to_want_to_compute_task` relies on calling it later (it adds offer to the pool only after scheduling resolution).

2019-07-25 15:40 UTC, mplebanski commented on tests/golem/task/test_concent_logic.py
> +        while send_mock.call_args is None:
Maybe that could be changed. I'll take a look at it tomorrow.

2019-07-25 15:46 UTC, Krigpl commented on tests/golem/task/test_concent_logic.py
> +        while send_mock.call_args is None:
> Also I can not mock defer_later with an in place call since code in react_to_want_to_compute_task relies on calling it later (it adds offer to the pool only after scheduling resolution).

In this case, you call still mock it, get the recorded call and invoke the callback manually from the test.

2019-07-25 16:46 UTC, Krigpl reviewed
lgtm, nitpicking mostly

2019-07-25 16:46 UTC, Krigpl commented on golem/marketplace/offerpool.py
> +    def get_task_offer_count(cls, task_id: str):
typehint

2019-07-25 16:46 UTC, Krigpl commented on tests/golem/marketplace/test_offerpool.py
> +        with pytest.raises(KeyError):
I think the preferred way is to use `with self.assertRaises`

2019-07-25 16:46 UTC, Krigpl commented on golem/task/tasksession.py
> +            def __init__(self, scaled_price, reputation, quality, callback):
typehints

2019-07-25 16:46 UTC, Krigpl commented on tests/golem/marketplace/test_offerpool.py
> +        OfferPool.add('aaa', offer)
put `aaa` into a named variable to avoid random magic strings all over the tests

2019-07-25 16:46 UTC, Krigpl commented on tests/golem/marketplace/test_offerpool.py
> +        self.assertEqual(len(result), 2)
This line moved to the test above eliminates the need for this whole test, so I dunno if it's worth keeping this one.

2019-07-25 16:46 UTC, Krigpl commented on tests/golem/task/test_concent_logic.py
> +            mock.Mock(return_value=_fake_get_efficacy()))
Why a simple `Mock` as it used to be doesn't work anymore?

2019-07-25 16:46 UTC, Krigpl commented on tests/golem/task/test_tasksession.py
> +        ts.task_server.config_desc.offer_pooling_interval = 1
This test is like an integration test? I'd put smaller value like 0 or 0.1, because why wait for a whole second anyway.

2019-07-29 09:53 UTC, mplebanski commented on tests/golem/marketplace/test_offerpool.py
> +        self.assertEqual(len(result), 2)
I like the fact that test name tells you exactly what is tested.

2019-07-29 09:57 UTC, mplebanski commented on tests/golem/task/test_concent_logic.py
> +            mock.Mock(return_value=_fake_get_efficacy()))
In this version OfferPool.add is not mocked in the same way and an actual offer sorting takes place. The question is whether we want it tested here or not.

2019-07-30 08:40 UTC, mplebanski commented on golem/task/tasksession.py
> +            deferred.call_later(
OK. Since this is a response handler to WTCT I leave twisted internal errors unhandled, which is fine because of short handler context. I will add exceptions logging on each `_offer_chosen`.

2019-07-30 12:32 UTC, Krigpl approved these changes

2019-07-30 12:32 UTC, Krigpl commented on golem/task/tasksession.py
> +            def __init__(self,
Incorrect code style.

2019-07-30 12:32 UTC, Krigpl commented on golem/task/tasksession.py
> +from typing import (
Incorrect code style.

2019-07-31 09:23 UTC, mplebanski commented on golem/task/tasksession.py
> +            def __init__(self,
I understand this is incorrect according to our new codestyle, right?

2019-07-31 09:24 UTC, Krigpl commented on golem/task/tasksession.py
> +            def __init__(self,
Correct.

2019-07-31 11:20 UTC, merged