[O1] Ignore problematic files and parameters in transcoding tests
golemfactory/clay pull request #4573
Opened 2019-08-01 16:42 UTC by cameel

This set of changes adds special handling for several special cases in transcoding tests. These are cases that we think do not represent implementation bugs and can be ignored.

This includes the following cases:
- A) Ignoring FPS change for `standalone-tra3106[mjpeg...].avi` (concat demuxer changes the FPS from 29.97 to 30 for this file).
- C) Ignoring `standalone-lion[mpeg1video...].mpeg` (the file has `mp2` audio and for some reason it still has an audio track at the transcoding step even though ffmpeg is supposed to remove it).
- D) Ignoring `sample-bigbuckbunny[mpeg4...].mkv` (missing frames after conversion).
- E) Ignoring FPS change for `standalone-catherine[wmv3...].wmv` (bad FPS in metadata which results in ffmpeg sometimes doubling the frame count).

The following are not included:
- B) Ignoring frame count change for `standalone-p6090053[mjpeg,...].mov` (converting it to `mpeg2video/mpeg` changes FPS without changing the number of frames).
    - Actually no change was needed here because we already ignore frame count changes in all the frame rate change tests.
- F) Ignoring: `audio.frame_count` for all files
    - This is already done in #4515.
- G) Ignoring ffmpeg's automatic conversion from 12.5 to 12 FPS when converting to `mpeg2video`.
    - This requires changes in validations and will be submitted in a pull request that adds validations of the source FPS (O3).
- H) Ignoring automatic conversion to 60 FPS for `mpeg1video` when the input FPS is higher than that.
    - This will also be included in the pull request for O3.

### Dependencies
This pull request is based on #4515 and should be merged after it.

For the code to work you also need a `golemfactory/ffmpeg-experimental` image built with https://github.com/golemfactory/ffmpeg-tools/pull/9. Tests in the CI won't pass until it's released on DockerHub.

**NOTE**: I have set the base branch of this pull request to `transcoding-all-files-codecs-framerates-resolutions` (#4515) rather than `CGI/transcoding/master`. Please remember to change the base branch back to `CGI/transcoding/master` before you merge.

2019-10-02 13:40 UTC, nieznanysprawiciel requested changes
Running test gives us error:
(Note that CI didn't run slow tests for some reason:( )
______________________________________ TestFfmpegIntegration.test_split_and_merge_with_codec_change_017_from_h264_mp4_to_mpeg2video_mpeg _______________________________________

a = (<test_ffmpegintegration.TestFfmpegIntegration testMethod=test_split_and_merge_with_codec_change_017_from_h264_mp4_to_mpeg2video_mpeg>,)

    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)

../../../.virtualenvs/GolemEnv/lib/python3.6/site-packages/parameterized/parameterized.py:518: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
golem/testutils.py:199: in wrapper
    fun(self, *args, **kwargs)
tests/apps/ffmpeg/task/test_ffmpegintegration.py:288: in test_split_and_merge_with_codec_change
    self.assertEqual(diff, [])
E   AssertionError: Lists differ: [{'location': 'format', 'attribute': 'dura[350 chars]: 0}] != []
E   
E   First list contains 2 additional elements.
E   First extra element 0:
E   {'location': 'format', 'attribute': 'duration', 'actual_value': FuzzyDuration(17.72, 1), 'expected_value': FuzzyDuration(20.0, 1), 'reason': 'Different attribute values'}
E   
E   + []
E   - [{'actual_value': FuzzyDuration(17.72, 1),
E   -   'attribute': 'duration',
E   -   'expected_value': FuzzyDuration(20.0, 1),
E   -   'location': 'format',
E   -   'reason': 'Different attribute values'},
E   -  {'actual_stream_index': 0,
E   -   'actual_value': FuzzyDuration(17.72, 1),
E   -   'attribute': 'duration',
E   -   'expected_stream_index': 0,
E   -   'expected_value': FuzzyDuration(20.0, 1),
E   -   'location': 'video',
E   -   'reason': 'Different attribute values'}]

2019-10-02 13:40 UTC, nieznanysprawiciel commented on tests/apps/ffmpeg/task/test_ffmpegintegration.py
> +        if filename in self._IGNORED_ATTRIBUTES_OF_BROKEN_FILE:
Code for ignoring should be hidden in separate function because it is duplicated across all tests. But it can be done later with refactor task that I requested in previous PRs.

2019-10-02 18:09 UTC, cameel commented on tests/apps/ffmpeg/task/test_ffmpegintegration.py
> +        if filename in self._IGNORED_ATTRIBUTES_OF_BROKEN_FILE:
I specifically wanted it to be in the open so that it's easier to notice that there are some specific, hard-coded special cases. But it if you think it's not an issue, sure, we'll change it during refactoring.

2019-10-02 18:15 UTC, cameel commented
As for the test: looks like there's a file where the difference in duration is actually pretty significant. I'll take a closer look tomorrow. Weird because this should have happened when running tests on my machine but I did not get it.

2019-10-03 08:31 UTC, nieznanysprawiciel commented on tests/apps/ffmpeg/task/test_ffmpegintegration.py
> +        if filename in self._IGNORED_ATTRIBUTES_OF_BROKEN_FILE:
Make function that will do it. Name of function will tell reader that there are special cases.

2019-10-08 20:36 UTC, cameel commented on tests/apps/ffmpeg/task/test_ffmpegintegration.py
> +        if filename in self._IGNORED_ATTRIBUTES_OF_BROKEN_FILE:
OK. That's a good idea.

2019-10-08 21:14 UTC, cameel commented
The test passes on my machine. I stopped in the debugger to compare the durations:
``` python
(Pdb) _input_report
FfprobeFormatReport(stream_types: {'video': 1}, program_count: None, duration: 20.0[+/-1], format_name: mov,mp4,m4a,3gp,3g2,mj2. Streams: [FfprobeVideoStreamReport(resolution: [320, 240], relative_start_time: 0.0[+/-0.1], codec_type: video, codec_name: h264, frame_count: 500, frame_rate: 25.0, pixel_format: yuv420p, duration: 20.0[+/-1], bitrate: 17848[+/-5%] )])
(Pdb) _output_report
FfprobeFormatReport(stream_types: {'video': 1}, program_count: None, duration: 19.16[+/-1], format_name: mpeg. Streams: [FfprobeVideoStreamReport(resolution: [320, 240], relative_start_time: 0.0[+/-0.1], codec_type: video, codec_name: mpeg2video, frame_count: None, frame_rate: 25.0, pixel_format: yuv420p, duration: 19.16[+/-1], bitrate: None )])
```

So mine is 19.16s long while yours is just 17.72s. This is very strange. I hope that the encoder or muxer is not non-deterministic that way. That would totally suck. I ran it several times and I always get the same duration. So at least on the same machine it does not change.

I'll need to be able to reproduce the failure or at least get a result with a different duration to be able to debug it. I'm going to try and see how it behaves when I run it on a different machine.

Just for the sake of sanity, could you check if we're running the same ffmpeg version? It's in the image so it should be exactly the same but still, I want to be sure:
```
ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.4.0 (Alpine 6.4.0)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
```

2019-10-08 21:21 UTC, closed without merging