[P6a] Audio channel layout validations
golemfactory/clay pull request #4575
Opened 2019-08-01 17:42 UTC by cameel

A simple change required to make transcoding validations work after https://github.com/golemfactory/ffmpeg-tools/pull/12. `validate_transcoding_params()` now requires access to video metadata.

### Dependencies
This pull request is based on #4574 and should be merged after it. This is just for ease or development - It does not really depend on that base pull request and could be merged without it if rebased.

For the code to work you also need a `golemfactory/ffmpeg-experimental` image built with https://github.com/golemfactory/ffmpeg-tools/pull/12. Tests in the CI won't pass until it's released on DockerHub.

**NOTE**: I have set the base branch of this pull request to `transcoding-allow-transcoding-to-any-resolution-with-same-aspect-ratio` (#4574) rather than `CGI/transcoding/master`. Please remember to change the base branch back to `CGI/transcoding/master` before you merge.

2019-10-02 15:43 UTC, nieznanysprawiciel requested changes

2019-10-02 15:43 UTC, nieznanysprawiciel commented on apps/transcoding/task.py
> +            )
If we require video_metadata to validate transcoding, we should remove src_params parameter from this function. All these parameters are created from metadata anyway.

2019-10-08 20:23 UTC, cameel commented on apps/transcoding/task.py
> +            )
OK. Good point. Would it be fine to just move the `meta.create_params()` call into `validate_transcoding_params()` or would you prefer to go even further and not create this dict at all and make `validate_transcoding_params()` always get values directly from `video_metadata`?

2019-10-16 09:50 UTC, nieznanysprawiciel commented on apps/transcoding/task.py
> +            )
Moving meta.create_params seems to be the easiest way

2019-10-17 06:48 UTC, pawelkisielewicz commented on apps/transcoding/task.py
> +            )
Fixed. Please see also changes in ffmpeg-tools, it was required because of this change:
https://github.com/golemfactory/ffmpeg-tools/pull/12

2019-10-29 15:21 UTC, nieznanysprawiciel commented
Will be merged together with https://github.com/golemfactory/golem/pull/4835

2019-10-29 15:21 UTC, closed without merging