Cgi/verifier/scripts for addional tests
golemfactory/clay pull request #4584
Opened 2019-08-05 16:13 UTC by nieznanysprawiciel

2019-10-16 09:59 UTC, nieznanysprawiciel commented
Please, make sure, that we will not add workaround for database problem added in this commit: https://github.com/golemfactory/golem/commit/aa2959b165b0df7c9dbc0eb5c0ac79becd3fa42f.

Problem is already solved on develop.

2019-10-22 15:31 UTC, bidzyyys approved these changes

2019-10-24 12:49 UTC, magdasta approved these changes

2019-10-25 09:55 UTC, etam requested changes

2019-10-25 09:55 UTC, etam commented on apps/blender/resources/images/entrypoints/scripts/verifier_tools/verifier.py
> +    json_as_string = pformat(params)
`pformat` does not produce json. It's not intended to do so. Use `json` module instead.

2019-10-25 09:55 UTC, etam commented on golem/testutils_app_integration.py
> +            self.files = files
This could be a dataclass:
```python
from dataclasses import dataclass

[...]

@dataclass
class Result:
    files: List[str]
```

2019-10-25 09:55 UTC, etam commented on golem/testutils_app_integration.py
> +        return os.path.isdir(dir_path)
Does this really improve readability? I don't think so.

2019-10-25 09:55 UTC, etam commented on golem/testutils_app_integration.py
> +        pass
?

2019-10-25 09:55 UTC, etam commented on golem/verifier/blender_verifier.py
> +                                                timeout=self.timeout)
why?

2019-10-25 09:55 UTC, etam commented on tests/apps/blender/task/test_blenderintegration.py
> +    def check_outputs_existance(self, task: Task):
```suggestion
    def check_outputs_existence(self, task: Task):
```

2019-10-25 09:55 UTC, etam commented on tests/apps/blender/task/test_blenderintegration.py
> +@ci_skip
:+1:

2019-10-25 09:55 UTC, etam commented on golem/verifier/blender_verifier.py
> +                1])
:+1:

2019-10-25 09:55 UTC, etam commented on tests/apps/blender/task/test_blenderintegration.py
> +        self.check_outputs_existance(task)
```suggestion
        self.check_outputs_existence(task)
```

2019-10-25 09:55 UTC, etam commented on tests/apps/blender/task/test_blenderintegration.py
> +        self.check_outputs_existance(task)
```suggestion
        self.check_outputs_existence(task)
```

2019-10-25 09:55 UTC, etam commented on tests/apps/blender/task/test_blenderintegration.py
> +        self.check_outputs_existance(task)
```suggestion
        self.check_outputs_existence(task)
```

2019-10-25 09:55 UTC, etam commented on tests/golem/verifier/blenderverifier_ext_test_script.py
> +    def _print_failes(self):
```suggestion
    def _print_fails(self):
```

2019-10-25 09:55 UTC, etam commented on tests/golem/verifier/blenderverifier_ext_test_script.py
> +        self._print_failes()
```suggestion
        self._print_fails()
```

2019-10-25 09:55 UTC, etam commented on tests/golem/verifier/blenderverifier_ext_test_script.py
> +        return self.report
That's not The Way of Python.

I mean, just use the `report` object, where you need it. This method adds nothing.

2019-10-25 09:55 UTC, etam commented on tests/golem/verifier/blenderverifier_ext_test_script.py
> +            return json.loads(content)
```python
return json.load(file)
```

2019-10-25 10:40 UTC, nieznanysprawiciel commented on golem/testutils_app_integration.py
> +        return os.path.isdir(dir_path)
Right. These were some leftovers from previous implementations

2019-10-25 10:41 UTC, nieznanysprawiciel commented on golem/testutils_app_integration.py
> +        pass
Leftovers :P

2019-10-25 14:16 UTC, nieznanysprawiciel commented on golem/verifier/blender_verifier.py
> +                                                timeout=self.timeout)
I don't know :P

2019-10-29 08:30 UTC, shadeofblue commented on apps/blender/resources/images/entrypoints/scripts/verifier_tools/verifier.py
> +    json_as_string = pformat(params)
seconded

2019-10-29 08:41 UTC, shadeofblue commented on golem/testutils.py
> +def keep_testdir_on_fail(fun):
wouldn't it be better to have an optional command line argument instead of a decorator for this purpose instead?

2019-10-29 08:42 UTC, shadeofblue commented on golem/testutils_app_integration.py
> +                timeouted = not self.condition_var.wait(timeout=timeout)
technically, it's "timed out", not "timeouted" ...

2019-10-29 08:48 UTC, shadeofblue commented on golem/testutils_app_integration.py
> +    def _execute_subtask(self, task: Task, ctd: dict):
is there a reason some of those methods here are public and some are private? are any of them called from outside the test class?

2019-10-29 11:03 UTC, nieznanysprawiciel commented on golem/testutils.py
> +def keep_testdir_on_fail(fun):
I prefere this solution, because cmdline switch would enable it for all test cases. They produce a lot of garbage and is is a lot harder to find results of only one specific test

2019-10-29 11:19 UTC, nieznanysprawiciel commented on golem/testutils_app_integration.py
> +    def _execute_subtask(self, task: Task, ctd: dict):
Some of them are designed to be called outside of TestTaskIntegration and some of them are not. But not all of them are used yet.

2019-11-04 09:33 UTC, etam approved these changes
![ok](http://giphygifs.s3.amazonaws.com/media/7MZ0v9KynmiSA/giphy.gif)

2019-11-05 11:54 UTC, shadeofblue approved these changes
![mckayla okayish](https://user-images.githubusercontent.com/7963044/68205785-6a65a100-ffcb-11e9-8e34-705e7ee6d085.jpeg)

2019-11-05 14:12 UTC, merged