Introduce RequestorWasmMarketStrategy
golemfactory/clay pull request #4587
Opened 2019-08-06 08:47 UTC by mplebanski

2019-08-13 13:34 UTC, mplebanski commented
I changed the status to `Ready for review` because of the `could not parse object bug`.

2019-08-13 14:50 UTC, mplebanski commented
`ResultMetadata` in TaskBase and `add_subtask_metadata` in TaskServer are a part of a temporary solution, one that use wall clock time as a mock for provider side usage reporting. This is because we wanted to proceed in parallel with https://github.com/golemfactory/golem/pull/4602 and https://github.com/golemfactory/golem/pull/4559 . This mocking will be removed once we merge changes added by Brass.

2019-08-14 14:04 UTC, mbenke approved these changes

2019-08-27 13:41 UTC, mbenke requested changes

2019-08-27 13:41 UTC, mbenke commented on apps/wasm/task.py
> +                     task_result.stats.cpu_stats.cpu_usage.total_usage)
* `cpu_usage` seems to be a dictionary
* `total_usage` seems to be in ns

```suggestion
                     task_result.stats.cpu_stats.cpu_usage['total_usage'] / 1e9 )
```

2019-08-27 13:41 UTC, mbenke commented on apps/wasm/task.py
> +            for s_id in subtask.get_instances():
In this loop, it seems every instance gets the same usage

2019-09-03 16:07 UTC, mplebanski commented
Ready for review.

2019-09-26 10:29 UTC, mbenke approved these changes

2019-09-30 13:22 UTC, maaktweluit requested changes
LGTM!

Mainly nitty comments, some are nice to fix, none are breaking (as far as i can see ) :)

2019-09-30 13:22 UTC, maaktweluit commented on apps/wasm/task.py
> +# pylint: disable=too-many-public-methods
this will disable it for the rest of the file, would be nicer to add it at the end of the line below

2019-09-30 13:22 UTC, maaktweluit commented on apps/wasm/task.py
> +                     cpu_stats.cpu_usage['total_usage'] / 1e9)
if `1e9` is used more often it should be a constant, the less magic numbers the better :)

2019-09-30 13:22 UTC, maaktweluit commented on apps/wasm/task.py
> +        logger.debug("WASM subtask price: %d", sub_price)
the log will show category `apps.wasm.task` so WASM is redundant here ( nit comment, can ignore )

2019-09-30 13:22 UTC, maaktweluit commented on apps/wasm/task.py
> +            cpu_usage: float = float(golem.model.Performance.get(
one line one thought would split this in 2 lines, the query and the float cast

Also the query selects `*` and only uses `cpu_usage` might as well only select that one ( nit )

2019-09-30 13:22 UTC, maaktweluit commented on apps/wasm/task.py
> +            cpu_usage: float = 1.0 * 1e9
magic numbers!

2019-09-30 13:22 UTC, maaktweluit commented on apps/wasm/task.py
> +        self.REQUESTOR_MARKET_STRATEGY.set_my_usage_benchmark(cpu_usage / 1e9)
3 times the charm?

2019-09-30 13:22 UTC, maaktweluit commented on golem/ethereum/paymentprocessor.py
> +            "Adding payment for %s to %s (%.8f GNTB)",
8 digits seems a bit much for a non debug log, why was this chosen?

2019-09-30 13:22 UTC, maaktweluit commented on golem/marketplace/marketplace.py
> +    def get_payment_computer(cls, task: 'Task', subtask_id: str)\
please line break the arguments like the styleguide proposes:
https://github.com/golemfactory/styleguide/blob/gh-pages/pyguide.md#3192-line-breaking

2019-09-30 13:22 UTC, maaktweluit commented on golem/marketplace/wasm_marketplace.py
> +        logger.info("RWMS: set_my_usage_benchmark %.3f", benchmark)
looks more like a debug log

2019-09-30 13:22 UTC, maaktweluit commented on golem/marketplace/wasm_marketplace.py
> +    # pylint: disable-msg=line-too-long
disable for the rest of the file?

2019-09-30 13:22 UTC, maaktweluit commented on golem/marketplace/wasm_marketplace.py
> +            logger.info(
debug?

2019-09-30 13:22 UTC, maaktweluit commented on golem/marketplace/wasm_marketplace.py
> +                offer.price/10**9,
Seems like the same magic number as `1e9` above? maybe we can use the same const?

2019-09-30 13:22 UTC, maaktweluit commented on golem/marketplace/wasm_marketplace.py
> +    def report_subtask_usages(cls,
linebreaks not like styleguide

2019-09-30 13:22 UTC, maaktweluit commented on golem/marketplace/wasm_marketplace.py
> +    def get_payment_computer(cls, task: 'Task', subtask_id: str)\
linebreaks

2019-09-30 13:22 UTC, maaktweluit commented on golem/task/taskbase.py
> +    # pylint: disable=no-self-use
why not make it a `@staticmethod`?

Seems like my comment about the whole file was wrong before.. ( resolving it, not deleting )

2019-09-30 13:22 UTC, maaktweluit commented on golem/task/tasksession.py
> +            ProviderPerformance(msg.cpu_usage / 1e9),
const?

2019-09-30 13:22 UTC, maaktweluit commented on tests/apps/wasm/test_task.py
> +    @mock.patch("golem.model.Performance.get",
patch also has kwarg `return_value` IIRC

2019-09-30 13:22 UTC, maaktweluit commented on tests/golem/marketplace/test_wasm_marketplace.py
> +        RequestorWasmMarketStrategy.reset()
maybe move the reset to the SetUp code?

2019-09-30 14:56 UTC, mbenke commented on golem/marketplace/wasm_marketplace.py
> +    def get_payment_computer(cls, task: 'Task', subtask_id: str)\
This linebreak is due to linter complaint.  How would you do it?

2019-09-30 15:00 UTC, mbenke commented on golem/task/taskbase.py
> +    # pylint: disable=no-self-use
It's not static in general, just in the base class. In subclasses it may depend on `self`.

2019-09-30 15:03 UTC, mbenke commented on tests/apps/wasm/test_task.py
> +    @mock.patch("golem.model.Performance.get",
It doesn't seem so: https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch

2019-09-30 15:06 UTC, mbenke commented on apps/wasm/task.py
> +            cpu_usage: float = 1.0 * 1e9
fixed

2019-09-30 15:06 UTC, mbenke commented on apps/wasm/task.py
> +            cpu_usage: float = float(golem.model.Performance.get(
done

2019-09-30 15:06 UTC, mbenke commented on apps/wasm/task.py
> +        logger.debug("WASM subtask price: %d", sub_price)
fixed

2019-09-30 15:06 UTC, mbenke commented on apps/wasm/task.py
> +                     cpu_stats.cpu_usage['total_usage'] / 1e9)
done

2019-09-30 15:07 UTC, mbenke commented on apps/wasm/task.py
> +# pylint: disable=too-many-public-methods
done (actually moved it one class lower)

2019-09-30 15:39 UTC, maaktweluit commented on golem/marketplace/wasm_marketplace.py
> +    def get_payment_computer(cls, task: 'Task', subtask_id: str)\
Maybe it needs 4 extra spaces inside, but something like this:
```suggestion
    def get_payment_computer(
        cls, task: 'Task', 
        subtask_id: str
    )
```

2019-09-30 15:50 UTC, maaktweluit commented on tests/apps/wasm/test_task.py
> +    @mock.patch("golem.model.Performance.get",
You are correct! i recalled wrong, sorry!

2019-09-30 15:50 UTC, maaktweluit approved these changes

2019-10-01 10:14 UTC, merged