Add TaskResult class
golemfactory/clay pull request #4612
Opened 2019-08-13 18:41 UTC by mplebanski

2019-08-14 09:21 UTC, Krigpl requested changes
Please, *do* provide a description that summarizes the motivation and reasoning behind the changes in the PR.

2019-08-14 09:21 UTC, Krigpl commented on golem/task/taskbase.py
> +    files: List[str] = []
You can't do default values like that with lists and dicts - they'll always be the same object. Use `dataclass.field` with factory instead.

2019-08-14 11:14 UTC, mbenke commented on golem/task/taskbase.py
> +    files: List[str] = []
Done in 96c2800

2019-08-14 13:29 UTC, Krigpl approved these changes

2019-08-15 17:33 UTC, mbenke approved these changes

2019-08-16 06:45 UTC, merged