Mwu/requested taskmanager
golemfactory/clay pull request #4632
Opened 2019-08-22 10:49 UTC by maaktweluit

Implementation of the new `RequestedTaskManager`

- [x] Does not use pickles, but models from #4340 
- [x] Uses CoreTask only statically when needed
- [x] Implements all app_client calls
- [ ] Manages starting and stopping of app_clients ( WIP )
  - [ ] Make `quit()` function async over Deferred
  - [ ] Make `_get_task_api_service()` a shared fn with taskcomputer?
- [ ] Calls required components like old taskmanager does with `self.notice_task_updated(task_id, op=TaskOp.STARTED)`
- [ ] Handles task masks

Open ends from FIXME's:
- `# FIXME: Blender creates preview files here`
- `# FIXME: Where to put resources in database`? Added new field for now
- `# FIXME: Where to put app_params in database`? Added new field for now
- golem_params.max_subtasks: `# FIXME: This is a separate argument now, delete here?`

2019-08-22 11:19 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +        self._dir_manager = DirManager(root_path)
I don't think we should use `DirManager` here - the directory structure is defined by Task API and this class doesn't know anything about that.

2019-08-22 11:19 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            task_id=CoreTask.create_task_id(self._public_key),
Just use `idgenerator.generate_id(public_key)` directly, it's awkward that this class depends on `CoreTask`.

2019-08-22 11:19 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            asdict(task_params),
`app_params` should be here, the whole `task_params` variable is invalid here

2019-08-22 12:00 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        self._dir_manager = DirManager(root_path)
Good one, fully agree! will replace it with a TaskApiDirManager or smth

2019-08-22 12:06 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            task_id=CoreTask.create_task_id(self._public_key),
nice, updated

2019-08-22 12:06 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            asdict(task_params),
thanks, that makes the function a lot smaller, updated

2019-08-22 13:49 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +        return subtask
This isn't a `SubtaskDefinition`

2019-08-22 13:49 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +    async def _get_app_client(self, env_id: EnvId) -> RequestorAppClient:
This should cache app clients per app id, not env id.

2019-08-22 13:56 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        return subtask
i was thinking of replacing the `SubtaskDefenition` with `model.RequestedSubtask` since they have a some fields in common.

Do you think using `SubtaskDefenition` has added value here?

2019-08-22 13:59 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +    async def _get_app_client(self, env_id: EnvId) -> RequestorAppClient:
At first i had it as `app_id`, not sure why i changed it..

Will put it back, thanks!

2019-08-22 14:13 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +        return subtask
Better encapsulation. `SubtaskDefinition` is supposed to contain just the data needed for the correct computation while `model.RequestedSubtask` is `RequestedTaskManager`s implementation detail, can contain whatever data it's needed for any reasons and thus shouldn't be a part of the public interface.

2019-08-22 14:56 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        return subtask
thanks, updated :)

2019-08-23 13:39 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            if finished_subtasks >= task.max_subtasks:
This is incorrect. `max_subtasks` is the upper bound for the number of subtasks and the application is free to create fewer subtasks than that.
Currently, the right way to check whether a task is finished is to check whether all subtasks are finished + there no pending subtasks.

2019-08-23 14:21 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            if finished_subtasks >= task.max_subtasks:
boohoo, it looked so nice and simple :P

Updated the check :)

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +    def __init__(self, env_manager: EnvironmentManager, public_key, root_path):
Plz add type annotations for all parameters and reformat to one param per line.

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +            # concent_enabled = BooleanField(null=False, default=False),
Let's be explicit that concent is not supported for Task API.
```suggestion
            concent_enabled=False,
```

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        )
`RequestorAppClient.create()` should return env_id and prerequisites dict. We probably need a task for this.

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +            environment=golem_params.environment,
Why is this in `golem_params`? This should be returned from `RequestorAppClient.create()`.

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        result = await app_client.verify(task.task_id, subtask_id)
A try/catch would be nice here (setting failure status).

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        # self.notice_task_updated(task_id, op=TaskOp.ABORTED)
Shouldn't the app be notified about task getting aborted? If so, we probably need a task for this as well.

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        # this fixes it, but is it the right way?
This is kinda :nauseated_face: 
Maybe you can use `get_event_loop` from `golem.core.golem_async`? (see #4629)

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        # FIXME: make async not Deferred?
Yep, totally. All other methods are async, so this should be as well. We should avoid having mixed asyncio/twisted interfaces.

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +            {"image": "blenderapp", "tag": "latest"}  # FIXME: hardcoded :(
No worry, that would be implemented in `AppManager` soon.

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        shared_dir = self._dir_manager.root_path
Most probably this not the path you want to share. Each app should have its subdirectory.

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +    ) -> None:
```suggestion
    ) -> int:
```

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +    def _get_pending_subtasks(task_id: TaskId) -> None:
Fix return type annotation.

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +            RequestedTask.status.in_([
Maybe `not_in_` would be shorter?

2019-08-26 12:15 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +        app_client = ProviderAppClient.create(service=task_api_service)
That's been fixed in #4634

2019-08-26 13:03 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +    def __init__(self, env_manager: EnvironmentManager, public_key, root_path):
done

2019-08-26 13:04 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        )
does this belong to the task `start/stop client`? then i'll pick this up in the next PR ( using this one only for the app_client calls)

2019-08-26 13:06 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            environment=golem_params.environment,
i added the missing fields as input param's for now, will get it from the create() in the next PR

2019-08-26 13:10 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        result = await app_client.verify(task.task_id, subtask_id)
Good one, added

2019-08-26 13:11 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        # self.notice_task_updated(task_id, op=TaskOp.ABORTED)
Good thought!

Was thinking the shutdown would suffice for now..

Will make a task about adding abort notification to the app

2019-08-26 13:13 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            {"image": "blenderapp", "tag": "latest"}  # FIXME: hardcoded :(
nice, will leave it for now then :)

2019-08-26 13:13 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        # FIXME: make async not Deferred?
:) will add this in the start / stop PR too

2019-08-26 13:14 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        shared_dir = self._dir_manager.root_path
good one, will add this to the new DirManager that was proposed earlier in this PR

2019-08-26 13:14 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +    ) -> None:
added

2019-08-26 13:16 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            RequestedTask.status.in_([
what do you mean?
there are 8 total TaskStatus'es so listing 3 seems shorter

2019-08-26 13:16 UTC, maaktweluit commented on golem/task/taskcomputer.py
> +        app_client = ProviderAppClient.create(service=task_api_service)
will rebase over it :)

2019-08-26 13:22 UTC, maaktweluit reviewed
@Wiezzel thanks for your comments, added / fixed all but:
- Dir manager related ( fixing in this PR )
- Start / stop related ( will move this code to a new PR )

2019-08-26 13:23 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +    def _get_pending_subtasks(task_id: TaskId) -> None:
fixed

2019-08-26 13:32 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        )
I don't think so. Start/stop client cares about *requestor* env and prerequisites and I mean the *provider* part here.

2019-08-26 13:33 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +            RequestedTask.status.in_([
OK, nvm.

2019-08-26 13:34 UTC, Krigpl reviewed
This is looking good - my integration script is mostly happy already expect for the directory management.

2019-08-26 13:34 UTC, Krigpl commented on golem/task/taskcomputer.py
> +    @defer.inlineCallbacks
Why do you touch this file in this PR?

2019-08-26 13:34 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +        # FIXME: make async not Deferred?
Considering this method is introduced here but nowhere called I'd say either implement it properly or leave it completely out of this PR. There's no value in having a partially implemented non used method.

2019-08-26 13:34 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +        # this fixes it, but is it the right way?
Since this class is not designed to be thread safe, the caller of this method, if calling from a different thread should take care of that issue, not the class.

2019-08-26 13:34 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            computing_node: ComputingNode
I'd be inclined not to use `molde.ComputingNode` here, since again, I consider models to be implementation detail and not part of the interface. i.e. changing underlying database shouldn't affect the interface imo.

2019-08-26 13:39 UTC, maaktweluit commented on golem/task/taskcomputer.py
> +    @defer.inlineCallbacks
whoops, this was supposed to be reverted, will clean it up

2019-08-26 13:42 UTC, maaktweluit commented
@Krigpl thanks for the comments, it does not give a text box to reply to them separately so will do it here:
- `quit()` will remove from this PR and split out to the next one where it should be used
- `threads` agree, will also be moved and ( hopefully ) fixed in the next PR
- `model.*` as argument: good comment, will fix this in this PR

Will still add a new DirManager before un-drafting this PR

2019-08-26 14:38 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        )
Ok, could you make a task for it? think you can describe it better then me

2019-08-26 14:48 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        # FIXME: make async not Deferred?
Reverted it for this PR, will bring it back and fix it next one

2019-08-26 14:49 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            computing_node: ComputingNode
updated to use a local dataclass instead

2019-08-27 09:28 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +class ComputingNodeDefenition:
typo

2019-08-27 09:28 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +        deadline = subtask.start_time \
That should be `min`'d with task's deadline, I think.

2019-08-27 09:28 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +class TestRequestedTaskManager(DatabaseFixture, TwistedTestCase):
`RequestedTaskManager` doesn't use Twisted at all, why do you want to use it for tests? Just use `pytest`'s `asyncio` plugin.

2019-08-27 11:30 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +        self._dir_manager.prepare_task_dir(task.app_id, task_id)
That needs to go into `create_task` since we need resources dir to put the resources into before calling `create` on task api.

2019-08-27 11:46 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +class TestRequestedTaskManager(DatabaseFixture, TwistedTestCase):
This is for the using the `DatabaseFixture`, since its based off `unittest.TestCase` it does not work with `@pytest.mark.asyncio`

Tried to fix it quickly but it opened a whole new can of worms, so moving these fixes to a separate PR.

2019-08-27 11:48 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +class ComputingNodeDefenition:
fixed

2019-08-27 11:54 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        deadline = subtask.start_time \
i agree! added it

2019-08-27 11:54 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +    async def has_pending_subtasks(self, task_id: TaskId) -> bool:
I think this should first check whether the task is still active before issuing the rpc call. Otherwise this may spawn the runtime that won't be shutdown anywhere later.

2019-08-27 11:56 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        self._dir_manager.prepare_task_dir(task.app_id, task_id)
good one, moved!

2019-08-27 11:58 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +    async def has_pending_subtasks(self, task_id: TaskId) -> bool:
you are right, the check was already in `get_next_subtask(` so i moved it here.

2019-08-27 12:05 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +class TestRequestedTaskManager(DatabaseFixture, TwistedTestCase):
https://github.com/golemfactory/golem/pull/4648

2019-08-27 12:05 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        shared_dir = self._dir_manager.root_path
new DirManager is added, please check again

2019-08-27 12:06 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        self._dir_manager = DirManager(root_path)
New DirManager is in place

2019-08-27 12:21 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +class TestRequestedTaskManager(DatabaseFixture, TwistedTestCase):
Alternatively, just use `pytest`'s `tmpdir` fixture for the temporary directory.

2019-08-27 12:30 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            raise RuntimeError(
I'm not sure that should throw - if the task is not active it doesn't have any pending subtasks, so simple `False` is fine imo.

2019-08-27 12:33 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +class TestRequestedTaskManager(DatabaseFixture, TwistedTestCase):
good one, will update the `testutils` to use this too in the linked PR.

Would like to keep this PR as is for now so we can merge it

2019-08-27 12:38 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            raise RuntimeError(
haha, raise them all!

good point, the next_subtask can raise but here False is good enough

2019-08-27 12:39 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +class TestRequestedTaskManager(DatabaseFixture, TwistedTestCase):
sure, sounds good

2019-08-27 15:29 UTC, Krigpl reviewed
Looks good - couple of comments regarding cleaner tests tho.

2019-08-27 15:29 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +        RequestedSubtask.delete().execute()
I don't think you need that. Each test will work on its own fresh DB.

2019-08-27 15:29 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +        result.resources = '[]'
These shouldn't be strings.

2019-08-27 15:29 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +        mock_client = Mock(spec=RequestorAppClient)
Try to use this approach for dealing with mocking async methods https://github.com/golemfactory/task-api/blob/master/python/tests/test_integration.py#L14

I think it'll be cleaner than those verbose mock futures and `_patch_async`s.

2019-08-28 14:51 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        )
Done.

2019-08-28 15:53 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +class DirManager:
Maybe `RequestorDirManager` to be more specific? We already have one `DirManager` and maybe could use another one for management of provider directories.

2019-08-28 15:53 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +    def get_network_resources_dir(self, app_id, task_id):
Let's go with the subtask inputs/subtask outputs naming since as I think we agreed upon it.

2019-08-28 15:53 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +            raise RuntimeError(f"Task not started. task_id={task_id}")
Why is this check done after creating the subtask? Wouldn't it leave application in an invalid state?

2019-08-28 15:53 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +                if not self._get_pending_subtasks(task_id):
Why are both checks needed?

2019-08-28 15:53 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        # FIXME: Stolen from golem/task/taskcomputer.py:_get_task_api_service()
There's no more `_get_task_api_service()`  in `taskcomputer`

2019-08-28 15:53 UTC, Wiezzel commented on golem/task/taskserver.py
> +            root_path=TaskServer.__get_task_manager_root(client.datadir),
Fun fact: this returns the same path as `self.get_task_computer_root()`

2019-08-28 15:53 UTC, Wiezzel commented on tests/golem/task/test_requestedtaskmanager.py
> +        assert row.start_time < default_now()
I know it's boring but I'd put some more assertions on row attributes here. Maybe check if the task directory was initialized as well?

2019-08-29 07:25 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +class DirManager:
fwiw I'm not sure if it's even worth making it a separate class, just moving the functions to the RTM would be fine imo. This class won't be used anywhere else and getters like `get resources dir/network_resources dir/network results dir` are simple redirections.
Not insisting tho.

2019-08-29 07:27 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +class DirManager:
(since effectively the only functionality here is the `prepare_task_dir` method)

2019-08-29 11:57 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +class DirManager:
Actually, I think this class belongs to the Task API repository. And know what? That logic is already there:
https://github.com/golemfactory/task-api/blob/2dccb9f4cb237e2f1676caecaa83ced2ea9da9a6/python/golem_task_api/testutils/tasklifecycleutil.py#L100-L114

2019-09-02 09:46 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            {"image": "blenderapp", "tag": "latest"}  # FIXME: hardcoded :(
AppManager is not in develop so let's do it properly.

2019-09-02 10:33 UTC, Krigpl requested changes

2019-09-02 10:33 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +        assert row.start_time < default_now()
```
__________________ TestRequestedTaskManager.test_create_task __________________
self = <tests.golem.task.test_requestedtaskmanager.TestRequestedTaskManager testMethod=test_create_task>
    def test_create_task(self):
        # given
        golem_params = self._build_golem_params()
        app_params = {}
        # when
        task_id = self.rtm.create_task(golem_params, app_params)
        # then
        row = RequestedTask.get(RequestedTask.task_id == task_id)
        assert row.status == TaskStatus.creating
>       assert row.start_time < default_now()
E       AssertionError: assert datetime.datetime(2019, 9, 2, 9, 45, 14, 217336, tzinfo=datetime.timezone.utc) < datetime.datetime(2019, 9, 2, 9, 45, 14, 217336, tzinfo=datetime.timezone.utc)
E        +  where datetime.datetime(2019, 9, 2, 9, 45, 14, 217336, tzinfo=datetime.timezone.utc) = <golem.model.RequestedTask object at 0x0000022568380208>.start_time
E        +  and   datetime.datetime(2019, 9, 2, 9, 45, 14, 217336, tzinfo=datetime.timezone.utc) = default_now()
tests\golem\task\test_requestedtaskmanager.py:65: AssertionError
```
Please use freeze_gun when testing time sensitive stuff.

2019-09-02 10:37 UTC, Wiezzel commented on tests/golem/task/test_requestedtaskmanager.py
> +        assert row.start_time < default_now()
Good remark. However, I'm not sure if `freeze_gun` works correctly with `TwistedTestCase`.

2019-09-03 08:51 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +class DirManager:
haha, yeah, i copied it from there ;)

Sounds like its best to move the dirmanager to task-api ( since we should not use `testutils`) in production code

will have a try at this

2019-09-03 08:52 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +    def get_network_resources_dir(self, app_id, task_id):
good one, did not think of changing the given interface but will do it :D

2019-09-03 08:57 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            raise RuntimeError(f"Task not started. task_id={task_id}")
this can only happen when `start_time` is `None` and should never happen, its a safety check to remove optional, maybe we can just assert it or remove the check all together?

2019-09-03 09:02 UTC, maaktweluit commented on golem/task/taskserver.py
> +            root_path=TaskServer.__get_task_manager_root(client.datadir),
yep, i think i had even more options to pick where to get the same dir :P iirc i picked this one since it was most purpose specifically named ( task manager )

2019-09-03 09:02 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        assert row.start_time < default_now()
good one! the dir-manager was extracted later so did not add test asserts for it yet

2019-09-03 09:03 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        assert row.start_time < default_now()
will try it, if it does not work i'll make the assert `<=` ;)

2019-09-03 09:03 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        mock_client = Mock(spec=RequestorAppClient)
thanks, was looking for a solve like this :D

2019-09-03 09:04 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        result.resources = '[]'
iirc they are also strings as default values in the models, what should they be? dict and list? will update them :)

2019-09-03 09:05 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        RequestedSubtask.delete().execute()
i think i made a mistake in a test and needed this, you are probably correct, will try to remove ot

2019-09-03 09:10 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        RequestedSubtask.delete().execute()
you are right, removed

2019-09-03 09:15 UTC, Krigpl commented on golem/task/taskserver.py
> +            root_path=TaskServer.__get_task_manager_root(client.datadir),
imo RTM shouldn't share the directory with the old tm

2019-09-03 09:20 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +        result.resources = '[]'
I dunno about the model and this isn't a struct from the model - this is task api struct and params is a dict and resources is a list.

2019-09-03 09:24 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        mock_client = Mock(spec=RequestorAppClient)
will postpone this fix to the other PR with the `tempdir` fixes, it was the last missing part of getting that to work and do not want to open that can of worms in this PR again

2019-09-03 09:26 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +                if not self._get_pending_subtasks(task_id):
one asks the app, the other asks the local database, they should always be in sync but you never know, maybe it can have some better error handling when they are out of sync

2019-09-03 09:27 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        # FIXME: Stolen from golem/task/taskcomputer.py:_get_task_api_service()
:( but still stolen it from there :P will check if there is a new place to link to, otherwise i'll link to the SHA it was stolen from ;)

2019-09-03 09:28 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        # FIXME: Stolen from golem/task/taskcomputer.py:_get_task_api_service()
updated fn name :)

2019-09-03 09:32 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +            raise RuntimeError(f"Task not started. task_id={task_id}")
If it should never occur I'd go with simple assert.

2019-09-03 09:34 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +                if not self._get_pending_subtasks(task_id):
OK, let's leave it like this.

2019-09-03 09:34 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        assert row.start_time < default_now()
added a test

2019-09-03 09:54 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        assert row.start_time < default_now()
`freezegun` installed

2019-09-03 09:59 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            raise RuntimeError(f"Task not started. task_id={task_id}")
ok, fixed

2019-09-03 10:01 UTC, maaktweluit commented on golem/task/taskserver.py
> +            root_path=TaskServer.__get_task_manager_root(client.datadir),
i think it should for now, since the docker shares are all configured to only be available in this directory

Due to the structure the RTM will always use other sub-directories so it is still somehow separated

2019-09-03 10:02 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        result.resources = '[]'
thanks! i used the database models first for these objects, after refactoring i did not change the values

Updated now

2019-09-03 11:14 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +class DirManager:
i started looking into this and the change became too big, since it also requires re-release and testing of the task-api and blenderapp packages.

Made a new issue for this improvement, linking to this comment.
We can discuss it in refinement tomorrow and pick it up separately

2019-09-03 11:18 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +    def get_network_resources_dir(self, app_id, task_id):
done

2019-09-03 11:20 UTC, maaktweluit commented
@Krigpl @Wiezzel Thanks for the reviews! solved most comments, moved 2 bigger things to the next issues and linked to the comments for our future selves :)

Please check again

2019-09-03 11:23 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +        mock_client = Mock(spec=RequestorAppClient)
I insist. This is how much you gain, it's much simpler: https://github.com/golemfactory/golem/compare/mwu/requested-taskmanager...rtm_tests_async?expand=1
Feel free to just merge it to this branch.

2019-09-03 11:28 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            {"image": "blenderapp", "tag": "latest"}  # FIXME: hardcoded :(
@maaktweluit  This ain't no done :)

2019-09-03 12:07 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        mock_client = Mock(spec=RequestorAppClient)
haha, ok if you insist...

This does not remove the `_patch_async`, but indeed looks a lot cleaner

Your branch does give a warning now: any idea where that is from? 

``` 
tests/golem/task/test_requestedtaskmanager.py::TestRequestedTaskManager::test_init_task
  /Users/mwu-gol/src/golem-project/golem/tests/golem/task/test_requestedtaskmanager.py:85: RuntimeWarning: coroutine 'AsyncMock.__call__' was never awaited
    assert mock_client.create_task.called_once_with(
```

2019-09-03 12:08 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            {"image": "blenderapp", "tag": "latest"}  # FIXME: hardcoded :(
ahh, didnt see it was on develop

2019-09-03 12:27 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            {"image": "blenderapp", "tag": "latest"}  # FIXME: hardcoded :(
fixed! so many comments missed this one :)

2019-09-03 12:41 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +        assert mock_client.create_task.called_once_with(
```suggestion
        mock_client.create_task.assert_called_once_with(
```
And the warning disappears (I dunno why, tho).

2019-09-03 12:47 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        assert mock_client.create_task.called_once_with(
thanks, that solved it :) merged your branch into this one

2019-09-03 13:16 UTC, Krigpl commented on golem/task/taskserver.py
> +            root_path=TaskServer.__get_task_manager_root(client.datadir),
That is not true actually - only the directory from the `get_task_computer_root` is available in docker. So we need to change the docker config to include RTM's directory too. And then it could be a separate one.

2019-09-03 13:19 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            env_id: EnvId
You don't need the env param anymore since it's determined by the app.

2019-09-03 13:20 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            environment=golem_params.environment,
But @Wiezzel is still right that `environment` doesn't belong in golem_params, so please remove it from there.

2019-09-03 14:01 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            env_id: EnvId
good one, fixed!

should have added a fixme, remember thinking about this before

2019-09-03 14:13 UTC, maaktweluit commented on golem/task/taskserver.py
> +            root_path=TaskServer.__get_task_manager_root(client.datadir),
What is not true?

Both `__get_task_manager_root` and `get_task_computer_root` return the same folder ( 2x hardcoded :( ) and this is the one shared by docker

Sharing on windows is quite a pain, so changing the docker config would be a separate issue. I'm not sure if its worth it to make multiple shares since the new tasks will replace the old, leaving only one share in the end.

2019-09-03 14:21 UTC, Krigpl commented on golem/task/taskserver.py
> +            root_path=TaskServer.__get_task_manager_root(client.datadir),
Ok, I didn't realize that those two methods return the same directory...

2019-09-03 14:36 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            # FIXME: Where to move resources?
Create the directories earlier and copy the resources.

2019-09-03 14:36 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            # FIXME: add app_params?
What is this FIXME about?

2019-09-03 14:40 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            # FIXME: add app_params?
was a reminder to double check if it was OK to add the app_params in the database like this, think its OK, shall i remove the fixme?

2019-09-03 14:42 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            # FIXME: Where to move resources?
this was also about the field in the database, not sure if we need this anymore

2019-09-03 15:07 UTC, Wiezzel approved these changes

2019-09-03 15:11 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            # FIXME: Where to move resources?
We still need to copy the resources, but I doubt we need the inputs in the DB.

2019-09-03 15:11 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            # FIXME: add app_params?
Yeah

2019-09-03 15:21 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +        super().tearDown()
Not really needed

2019-09-03 15:26 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            # FIXME: Where to move resources?
removed inputs from DB, added copy

2019-09-03 15:26 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            # FIXME: add app_params?
done

2019-09-03 15:27 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        super().tearDown()
pylint kept telling me this too, i kept thinking it might be useful some day..

removed!

2019-09-03 15:31 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            # Concent is explicitly enabled for task_api for now...
Disabled : )

2019-09-03 15:40 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            # Concent is explicitly enabled for task_api for now...
fixed

2019-09-04 08:46 UTC, Krigpl commented on golem/database/schemas/035_requestor_models.py
> +        prerequisites = pw.JsonField(default='[]')
This is duplicated with line 31. Also what is this field for?

2019-09-04 08:59 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +class TestRequestedTaskManager(DatabaseFixture, TwistedTestCase):
Not necessarily in this PR (although please do not forget), but try to just use `async_test` decorator like https://github.com/golemfactory/golem/blob/develop/tests/golem/task/task_api/test_task_api_service.py#L39
I created it specifically to integrate async tests with `unittest.TestCase` and works just fine.

2019-09-04 09:05 UTC, Wiezzel commented on golem/database/schemas/035_requestor_models.py
> +        prerequisites = pw.JsonField(default='[]')
Line 31 is correct. It should be a dict. These are serialized provider prerequisites.

2019-09-04 09:21 UTC, maaktweluit commented on golem/database/schemas/035_requestor_models.py
> +        prerequisites = pw.JsonField(default='[]')
removed line 38 :)

2019-09-04 10:54 UTC, Krigpl approved these changes

2019-09-04 11:49 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +class TestRequestedTaskManager(DatabaseFixture, TwistedTestCase):
added it to the list of the asyncio conversion PR :) 
https://github.com/golemfactory/golem/pull/4648

2019-09-04 12:00 UTC, merged