Make RequestedTaskManager tests use asyncio over Twisted
golemfactory/clay pull request #4648
Opened 2019-08-27 12:02 UTC by maaktweluit

in progress

Change base to develop after the other PR is merged

2019-08-27 12:03 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +        patcher = monkeypatch(name, *args, **kwargs)
progress ended here, `addCleanup` does not exist in pytest land, seems they use fixtures and `monkeypatch`

2019-09-05 11:26 UTC, Wiezzel approved these changes
That `monkeypatch` thing isn't very beautiful but OK.

2019-09-05 11:26 UTC, Wiezzel commented on golem/testutils.py
> +                                 db_dir=tmpdir)
That's not how we format our code at Golem.

2019-09-05 11:29 UTC, maaktweluit commented on golem/testutils.py
> +                                 db_dir=tmpdir)
old habits die hard ;)

updating..

2019-09-05 11:41 UTC, Krigpl commented on golem/testutils.py
> +class AsyncDatabaseFixture():
It's more like `PytestDatabaseFixture` since this class has nothing to do with async stuff.
And considering this is pytest fixture you could make it a proper fixture then (so injectable, not a class).

2019-09-05 11:52 UTC, maaktweluit commented on golem/testutils.py
> +                                 db_dir=tmpdir)
Updated!

2019-09-05 11:53 UTC, maaktweluit commented
@Wiezzel made some improvements to the `monkeypatch` usage, please check again

2019-09-05 11:53 UTC, maaktweluit commented on golem/testutils.py
> +class AsyncDatabaseFixture():
good one! will see if i can make it a proper pytest fixture

2019-09-05 12:10 UTC, maaktweluit commented on golem/testutils.py
> +class AsyncDatabaseFixture():
updated

2019-09-05 12:35 UTC, Krigpl commented on tests/golem/task/test_requestedtaskmanager.py
> +    @pytest.mark.usefixtures('mock_client')
Why do you use this approach here vs direct fixture in other tests?

2019-09-05 12:36 UTC, Wiezzel commented on tests/golem/task/test_requestedtaskmanager.py
> +    @pytest.mark.usefixtures('mock_client')
Probably to avoid unused arg.

2019-09-05 12:37 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +    @pytest.mark.usefixtures('mock_client')
the `mock_client` parameter is not used in these tests and i can not make it `_mock_client` to shut up the linter

2019-09-05 12:37 UTC, Wiezzel commented on tests/golem/task/test_requestedtaskmanager.py
> +    def _add_next_subtask_to_client_mock(_mock_client):
How about `client_mock`? `mock_client` sounds more like a function name (unless you mean something like client-for-the-mock)

2019-09-05 12:39 UTC, Wiezzel approved these changes
That's some nice pytests fixturing here.

2019-09-05 12:47 UTC, maaktweluit commented on tests/golem/task/test_requestedtaskmanager.py
> +    def _add_next_subtask_to_client_mock(_mock_client):
i like, updated :)

2019-09-05 12:48 UTC, Krigpl requested changes
```
tests/golem/task/test_requestedtaskmanager.py::TestRequestedTaskManager::()::test_init_task
  /home/admin_imapp/venv/golem/lib/python3.6/site-packages/_pytest/python.py:196: RuntimeWarning: coroutine 'TestRequestedTaskManager.test_init_task' was never awaited
    testfunction(**testargs)

tests/golem/task/test_requestedtaskmanager.py::TestRequestedTaskManager::()::test_init_task_wrong_status
  /home/admin_imapp/venv/golem/lib/python3.6/site-packages/_pytest/python.py:196: RuntimeWarning: coroutine 'TestRequestedTaskManager.test_init_task_wrong_stat' was never awaited
    testfunction(**testargs)

tests/golem/task/test_requestedtaskmanager.py::TestRequestedTaskManager::()::test_start_task
  /home/admin_imapp/venv/golem/lib/python3.6/site-packages/_pytest/python.py:196: RuntimeWarning: coroutine 'TestRequestedTaskManager.test_start_task' was never awaited
    testfunction(**testargs)

tests/golem/task/test_requestedtaskmanager.py::TestRequestedTaskManager::()::test_has_pending_subtasks
  /home/admin_imapp/venv/golem/lib/python3.6/site-packages/_pytest/python.py:196: RuntimeWarning: coroutine 'TestRequestedTaskManager.test_has_pending_subtasks' was never awaited
    testfunction(**testargs)

tests/golem/task/test_requestedtaskmanager.py::TestRequestedTaskManager::()::test_get_next_subtask
  /home/admin_imapp/venv/golem/lib/python3.6/site-packages/_pytest/python.py:196: RuntimeWarning: coroutine 'TestRequestedTaskManager.test_get_next_subtask' was never awaited
    testfunction(**testargs)

tests/golem/task/test_requestedtaskmanager.py::TestRequestedTaskManager::()::test_verify
  /home/admin_imapp/venv/golem/lib/python3.6/site-packages/_pytest/python.py:196: RuntimeWarning: coroutine 'TestRequestedTaskManager.test_verify' was never awaited
    testfunction(**testargs)

tests/golem/task/test_requestedtaskmanager.py::TestRequestedTaskManager::()::test_verify_failed
  /home/admin_imapp/venv/golem/lib/python3.6/site-packages/_pytest/python.py:196: RuntimeWarning: coroutine 'TestRequestedTaskManager.test_verify_failed' was never awaited
    testfunction(**testargs)

tests/golem/task/test_requestedtaskmanager.py::TestRequestedTaskManager::()::test_abort
  /home/admin_imapp/venv/golem/lib/python3.6/site-packages/_pytest/python.py:196: RuntimeWarning: coroutine 'TestRequestedTaskManager.test_abort' was never awaited
    testfunction(**testargs)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
```
I don't think any of these tests are run properly.
I put `asd` at the beginning of one test and it didn't fail. Please make sure the tests are run.

2019-09-05 12:50 UTC, maaktweluit commented
@Krigpl i think you did not install requirements, i got this error too and added `pytest-asyncio` to solve it

2019-09-05 13:07 UTC, Krigpl commented
@maaktweluit Quite indeed, thank you. I would somewhat expect a different outcome when the pytest plug-in is missing :)

2019-09-05 13:09 UTC, maaktweluit commented
same here, maybe we can make it break in `conftest.py` when missing plugins

i think adding this plugin enabled a bunch of other tests too, since the coverage is up and i did not change / add any test

2019-09-05 13:13 UTC, Krigpl approved these changes
![obama_approves](https://user-images.githubusercontent.com/3904252/64344944-b9a14c80-cfef-11e9-9c11-a0a726931ba3.jpeg)

2019-09-05 13:43 UTC, merged