Task API integration test script
golemfactory/clay pull request #4664
Opened 2019-08-30 15:54 UTC by Krigpl

Couple of TODOs and FIXMEs left - dependencies on proper app management and bugs in task API.

2019-09-02 13:31 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +            time.sleep(2)
😿

2019-09-02 13:31 UTC, Wiezzel commented on golem/task/task_api/__init__.py
> +        await self._runtime.clean_up().asFuture(loop)
How about this?
```python3
try:
    await self._runtime.wait_until_stopped().asFuture(loop)
finally:
    await self._runtime.clean_up().asFuture(loop)
```

2019-09-02 13:31 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +        time.sleep(2)
😿

2019-09-02 13:31 UTC, Wiezzel commented on scripts/task_api_tests/basic_integration.py
> +# logging.basicConfig(level=logging.DEBUG)
Plz, remove commented line. Also the import order looks weird.

2019-09-02 13:31 UTC, Wiezzel commented on scripts/task_api_tests/basic_integration.py
> +        b'',
Better pass parameters by keywords here because this empty string looks obscure.

2019-09-04 11:58 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            time.sleep(2)
Dunno what to do about it right now, tbh

2019-09-04 12:07 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +            time.sleep(2)
Me neither, but this makes me sad.

2019-09-04 12:17 UTC, Wiezzel commented on scripts/task_api_tests/basic_integration.py
> +    return Deferred.fromFuture(asyncio.ensure_future(f))
Plz, use `golem.core.deferred_from_future`
https://github.com/golemfactory/golem/blob/239d47d5953832d287302b2aad1bb210df29fa69/golem/core/deferred.py#L67-L68

2019-09-04 12:17 UTC, Wiezzel commented on scripts/task_api_tests/basic_integration.py
> +    return Deferred.fromFuture(asyncio.ensure_future(f))
Actually, you can modify `golem.core.deferred_from_future` to accept any `Awaitable` object by putting `ansycio.ensure_future()` there.

2019-09-04 14:25 UTC, maaktweluit requested changes
LGTM!

Only the deferred q is important, the others are minor.

I know this is not using `pytest` now, but think it would be nice to share common components between tests.

2019-09-04 14:25 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            time.sleep(2)
Also makes me sad, maybe we can at least use asyncio?

```suggestion
            await asyncio.sleep(2)
```

2019-09-04 14:25 UTC, maaktweluit commented on golem/task/taskcomputer.py
> +        time.sleep(2)
same as the other sleep:
:( and async?

2019-09-04 14:25 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    await deferred_from_future(rtm.init_task(task_id))
why do you need a deferred here? i think `await rtm.init_task(..)` would work to

2019-09-04 14:25 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    work_dir = Path(tempfile.mkdtemp())
maybe we can use `tmp_path` fixture from pytest here too?

2019-09-04 14:25 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    db = database.Database(
we can use `AsyncDatabaseFixture` for this too https://github.com/golemfactory/golem/pull/4648/files#diff-70d60ac05925af68aa36648b86338e99R181

2019-09-04 14:38 UTC, Krigpl commented
@maaktweluit The reason I didn't use pytest is that it needs to take command lint arguments to run. Does pytest support that?

2019-09-04 14:41 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            time.sleep(2)
Maybe let's just move it to the Task API repo since it's an issue there.

2019-09-04 14:47 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            time.sleep(2)
👍

2019-09-04 14:49 UTC, maaktweluit commented
@Krigpl yes 
you need to add them to the options in `conftest.py`, like https://github.com/golemfactory/golem/blob/develop/scripts/node_integration_tests/conftest.py#L39

2019-09-04 15:10 UTC, mfranciszkiewicz commented on golem/task/requestedtaskmanager.py
> +            time.sleep(2)
Server health check may help here https://github.com/golemfactory/task-api/pull/36

2019-09-05 09:33 UTC, Wiezzel commented on scripts/task_api_tests/basic_integration.py
> +    await deferred_from_future(rtm.init_task(task_id))
Yea, this is a very good point. Why do you even need deferreds when the method is `async`?

2019-09-05 09:45 UTC, Krigpl commented on scripts/task_api_tests/basic_integration.py
> +    await deferred_from_future(rtm.init_task(task_id))
This is some magic related to incorporating twisted and asyncio together.
I followed this article https://meejah.ca/blog/python3-twisted-and-asyncio
It doesn't work without converting to deferred.
tl;dr; of the article is that you need to be aware of what context are you really in when inside an async function - twisted vs asyncio.

2019-09-05 09:48 UTC, Krigpl commented
@maaktweluit I find it a little awkward to introduce global flag available for 1k+ tests for the sake of a single test. Can still do it if you think it's worth it.

2019-09-05 09:50 UTC, Krigpl commented
Also this isn't meant to be run together with the rest of the test suite. It just doesn't make much sense to me to use pytest here.

2019-09-05 09:52 UTC, Wiezzel commented
> Also this isn't meant to be run together with the rest of the test suite. It just doesn't make much sense to me to use pytest here.

This is a fair point. It was meant to be a tool for developing apps, not for testing the Golem codebase.

2019-09-05 10:54 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    await deferred_from_future(rtm.init_task(task_id))
ahh, clear, had that fight a few times too the last weeks

maybe we can remove twisted from this test, would be nice to have it native asyncio

2019-09-05 11:01 UTC, maaktweluit commented
@Krigpl agree with that, but the conftest.py file can also be applied locally ( like the linked sample for `node_integration_tests` )

I do not mind if we use pytest here or not, the main point of my comment was to be able to re-use test utilities, since `tempdir` and `DatabaseFixture` are implemented again in this file.

2019-09-05 11:34 UTC, Krigpl commented on scripts/task_api_tests/basic_integration.py
> +    await deferred_from_future(rtm.init_task(task_id))
I doubt we can remove twisted here completely considering the dependent components still use it, i.e. twisted reactor still has to be installed for some golem components to work properly.

2019-09-05 11:36 UTC, Krigpl commented
@maaktweluit Right, but another thing is that I am considering making `work_dir` a flag, since it can't be tmpdir in Windows (because of docker mounts) and whether to remove it automatically also configurable by a flag. Thus not reusable from pytest anymore.

2019-09-05 12:58 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    await deferred_from_future(rtm.init_task(task_id))
ok, that is a bummer, lets leave it then for now :)

2019-09-05 13:00 UTC, maaktweluit approved these changes
lets leave it without pytest and with twisted for now

if we want to move there later the `tmpdir` is also a flag there

2019-09-05 13:10 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            time.sleep(2)
that will solve it :)

2019-09-09 13:47 UTC, merged