ACL Database
golemfactory/clay pull request #4701
Opened 2019-09-09 13:23 UTC by mdtanrikulu

Moves ACL deny/allow list from text file to database to keep persistence.
`node_name` parameter added to the list, to provide clear recognition for users.

2019-09-09 21:04 UTC, prekucki requested changes
I do not see data migration from deny.txt. what is your plan ? special script during installation ?

2019-09-10 16:45 UTC, mdtanrikulu commented
> I do not see data migration from deny.txt. what is your plan ? special script during installation ?

Thanks! It was a good reminder.

Here is the migration script as @mfranciszkiewicz suggests, I moved it from database migration schema to node.py.

https://github.com/golemfactory/golem/pull/4701/files#diff-1bef601c50a4151f88f0ecda16e1aa10R141

2019-09-11 14:38 UTC, shadeofblue commented on golem/node.py
> +        migrate_txt(Path(datadir))
I strongly disagree with putting migration code inside Golem's code component ... 

migrations are _exactly_ for this purpose and the code performing them should be included there

what if we wanted to have a _reverse_ migration? you can't do that with a solution like this one ...

2019-09-11 16:24 UTC, mfranciszkiewicz commented
The basis for my suggestion was the separation of schema and data migrations. Schema changes are orthogonal to locating and parsing configuration files and simply should be done separately. I understand the desire to mix those two together since the current migrator class is not flexible enough to allow that.
What I missed is that data migration won't be performed at the same stage as the newly introduced migration script and would require extra maintenance.

@mdtanrikulu Please move the `migrate_txt` function back to the schema script. Sorry for all the fuss caused.

2019-09-11 16:26 UTC, mdtanrikulu commented on golem/node.py
> +        migrate_txt(Path(datadir))
> The basis for my suggestion was the separation of schema and data migrations. Schema changes are orthogonal to locating and parsing configuration files and simply should be done separately. I understand the desire to mix those two together since the current migrator class is not flexible enough to allow that.
> What I missed is that data migration won't be performed at the same stage as the newly introduced migration script and would require extra maintenance.
> 
> @mdtanrikulu Please move the `migrate_txt` function back to the schema script. Sorry for all the fuss caused.

👍 done.

2019-09-17 08:13 UTC, prekucki approved these changes

2019-09-17 08:42 UTC, shadeofblue approved these changes

2019-09-17 09:05 UTC, merged