RequestedTaskManager - Start and stop the envs
golemfactory/clay pull request #4710
Opened 2019-09-10 14:32 UTC by maaktweluit

Added quit method to RTM to shutdown all running app clients.

Mocked the `TaskServer.quit()` where needed to ensure these tests do not need asyncio

2019-09-10 14:58 UTC, Krigpl requested changes

2019-09-10 14:58 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +        env = auto_setup(self._env_manager.environment(env_id))
This isn't needed, the environment is already registered as `auto_setup`.

2019-09-10 14:58 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            await app_client.Shutdown()
Isn't the method called `shutdown` with non capital `s`?

2019-09-10 14:58 UTC, Krigpl commented on golem/task/taskserver.py
> +        yield deferred_from_future(quit_f)
`deferred_from_future` already calls `ensure_future` inside

2019-09-10 14:58 UTC, Krigpl commented on golem/task/taskserver.py
> +    @inlineCallbacks
Not ideal but I think keeping this method synchronous would eliminate 90% changes from this PR, which I'd consider lesser evil since most of these changes look hacky to make the tests work.

2019-09-10 15:33 UTC, maaktweluit commented on golem/task/taskserver.py
> +        yield deferred_from_future(quit_f)
old habbits die hard, forgot you added it

2019-09-10 15:40 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        env = auto_setup(self._env_manager.environment(env_id))
nice, didnt know that, fixed :)

2019-09-10 15:40 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            await app_client.Shutdown()
🙈

fixed

2019-09-11 11:53 UTC, maaktweluit commented on golem/task/taskserver.py
> +    @inlineCallbacks
Made this call sync, it removed some hacks but added ( less ) new ones :)

2019-09-11 12:04 UTC, Krigpl commented on tests/golem/task/test_taskserver.py
> +            # Uncomment when this test works with asyncio
I think you can just mock RTM in the `setUp` method just like `TaskComputerAdapter` is being mocked and this won't be necessary.

2019-09-11 12:04 UTC, Krigpl commented on tests/golem/test_client.py
> +        # Only call taskcomputer.quit, TaskServer.quit now requires asyncio
Similar, I think you could just patch RTM during the `mock_client` call.

2019-09-11 12:04 UTC, Krigpl commented on tests/golem/test_client.py
> +    def test_collect_gossip(self, gossip_mock, *_):
Where did that come from?

2019-09-11 12:04 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +            await app_client.shutdown()
Maybe put that into a try/catch block so that failing to shut down a single app doesn't interfere with others.

2019-09-11 12:04 UTC, Krigpl commented on golem/task/taskserver.py
> +        self.disconnect()
Is this fine that there's no `connect` in the corresponding `resume` method?

2019-09-11 12:04 UTC, Krigpl commented on tests/golem/task/test_rpc.py
> +from twisted.trial.unittest import TestCase as TwistedTestCase
How come any changes are needed in this file?

2019-09-11 12:24 UTC, maaktweluit commented on tests/golem/test_client.py
> +    def test_collect_gossip(self, gossip_mock, *_):
one of the old hacks, forgot to revert this part

2019-09-11 12:25 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +            await app_client.shutdown()
good one, will add this

2019-09-11 12:26 UTC, maaktweluit commented on golem/task/taskserver.py
> +        self.disconnect()
i copied this from the `client.py` since it was the only place it was called, there is no `connect` in the resume there so i think its fine.

2019-09-11 13:09 UTC, maaktweluit commented on tests/golem/task/test_rpc.py
> +from twisted.trial.unittest import TestCase as TwistedTestCase
the first change was no longer needed, it was related to the client getting `inlineCallbacks` methods

The second is still needed, using sync_wait here will time out

2019-09-11 13:28 UTC, maaktweluit commented on tests/golem/task/test_taskserver.py
> +            # Uncomment when this test works with asyncio
Tried this but the call still errors, either the sync_wait times out or the new Mocked call does not work with `defer_from_future()`

2019-09-11 13:28 UTC, maaktweluit commented on tests/golem/test_client.py
> +        # Only call taskcomputer.quit, TaskServer.quit now requires asyncio
tried this one too, same problems as above

2019-09-11 13:52 UTC, Krigpl commented on tests/golem/task/test_taskserver.py
> +            # Uncomment when this test works with asyncio
Notice that this branch is not based on newest develop, and `defer_from_future` doesn't actually call `ensure_future` inside.

2019-09-11 14:02 UTC, Krigpl commented on tests/golem/task/test_taskserver.py
> +            # Uncomment when this test works with asyncio
Either way, I also can't make it work, so let's leave it.

2019-09-11 14:03 UTC, Krigpl requested changes

2019-09-11 14:03 UTC, Krigpl commented on golem/task/requestedtaskmanager.py
> +    async def quit(self):
Please add a unit test for that method.

2019-09-11 14:55 UTC, maaktweluit commented on tests/golem/task/test_taskserver.py
> +            # Uncomment when this test works with asyncio
rebased onto develop, but will still leave it for now

2019-09-11 14:55 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +    async def quit(self):
That was very needed 😊 

Added it and fixed the errors

2019-09-11 15:54 UTC, Krigpl approved these changes

2019-09-12 09:52 UTC, mfranciszkiewicz submitted a review, later dismissed

2019-09-12 09:52 UTC, mfranciszkiewicz commented on golem/client.py
> +            sync_wait(self.task_server.pause())
(edge case) `yield CoreTask.VERIFICATION_QUEUE.pause()` will lock the event loop for the remaining time of the verification process and trigger various timeouts (e.g. disconnecting RPC clients).

2019-09-12 09:52 UTC, mfranciszkiewicz commented on golem/task/taskserver.py
> +            self.requested_task_manager.quit()
We don't re-instantiate app clients on `resume`. Is that intentional?

2019-09-12 11:53 UTC, maaktweluit commented on golem/task/taskserver.py
> +            self.requested_task_manager.quit()
yes, they are made and cached again on the next call

2019-09-12 11:54 UTC, maaktweluit commented on golem/client.py
> +            sync_wait(self.task_server.pause())
bad verification queue, it should pause like it is asked to..

Is there something i can do about this to make it not time out other calls?

2019-09-12 11:56 UTC, mfranciszkiewicz commented on golem/client.py
> +            sync_wait(self.task_server.pause())
Well, you can remove `sync_wait`

2019-09-12 13:47 UTC, maaktweluit commented on golem/client.py
> +            sync_wait(self.task_server.pause())
good one, done!

2019-09-12 14:32 UTC, Wiezzel requested changes

2019-09-12 14:32 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +                await app_client.shutdown()
After calling `shutdown()` you should call `wait_until_shutdown_complete()` to clean up the runtime.

2019-09-12 14:43 UTC, Wiezzel commented
I'm also not sure about naming the newly introduced methods `quit` because it seem to suggest an irreversible shutdown. Maybe `stop` would make a better name?

2019-09-12 15:23 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +                await app_client.shutdown()
Isnt this already called inside `app_client.shutdown()`?

Would be a pain to add here, since we do not store the service anywhere, just the client

2019-09-12 15:26 UTC, maaktweluit commented
@Wiezzel Made the change to `stop` agree its a better name

Will wait with pushing till we clarify if wait_for_shutdown is needed to not trigger tests twice

2019-09-12 15:33 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +                await app_client.shutdown()
> Isnt this already called inside `app_client.shutdown()`?
>
> Would be a pain to add here, since we do not store the service anywhere, just the client

Well, you're right that it would be a pain. Actually it's called in `RequestorAppClient`'s `_soft_shutdown` but I case the soft shutdown gets timed out we should call it as well. So I guess this should be changed in Task API, not here.

2019-09-12 15:39 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +                await app_client.shutdown()
good one! i'll move it to the "finally" part of that try block in task-api

2019-09-12 15:59 UTC, Wiezzel reviewed
You forgot about the tests when renaming.

2019-09-12 16:02 UTC, maaktweluit commented
🙈

Good catch, fixed

2019-09-12 16:08 UTC, Wiezzel approved these changes

2019-09-12 16:53 UTC, merged