Use dirutils introduced in Task API v0.20.0
golemfactory/clay pull request #4770
Opened 2019-09-25 11:05 UTC by Wiezzel

2019-09-25 15:38 UTC, maaktweluit requested changes
LGTM!

One small q, approve on reply or solve :)

2019-09-25 15:38 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        task_dir = self._dir_manager.task_dir(task.app_id, task.task_id)
do we still need self._dir_manager? there is only one function left that is more then 1 line

2019-09-25 15:47 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        task_dir = self._dir_manager.task_dir(task.app_id, task.task_id)
Heh, not really. Will refactor.

2019-09-26 10:00 UTC, maaktweluit approved these changes
LGTM!

Not sure if we need all those dirs as public functions, some might be only used by the RTM and then `self._task_dir(...).some_dir` would suffice

2019-09-26 10:03 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        task = RequestedTask.get(RequestedTask.task_id == task_id)
Seems like this query is always duplicate now, maybe we can make the dir part take a RequestedTask as argument?

2019-09-26 10:21 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +        task = RequestedTask.get(RequestedTask.task_id == task_id)
`get_subtask_inputs_dir` and `get_subtask_outputs_dir` are called from outside RTM. Other methods might probably be called as well at some moment. I don't see how we get it to work with `RequestedTask` as an argument instead of `task_id`.

2019-09-26 10:51 UTC, maaktweluit commented on golem/task/requestedtaskmanager.py
> +        task = RequestedTask.get(RequestedTask.task_id == task_id)
yeah, that will only work nice when called from inside RTM.. lets leave it for now

2019-09-26 11:13 UTC, merged