Task API app benchmarks
golemfactory/clay pull request #4789
Opened 2019-10-10 16:53 UTC by mfranciszkiewicz

- store app benchmarks in a separate db table
- do not compute a benchmark if one is already running
- clear app benchmarks on configuration change

2019-10-22 09:00 UTC, maaktweluit requested changes
LGTM!

Some small comments, will approve on reply or fix

2019-10-22 09:00 UTC, maaktweluit commented on golem/task/benchmarkmanager.py
> +        benchmark = AppBenchmark(hash=prereq_hash, score=score)
just to check: will this run when the benchmark raises an error?

2019-10-22 09:00 UTC, maaktweluit commented on golem/task/benchmarkmanager.py
> +        shared_dir.mkdir(parents=True, exist_ok=True)
should we clean up these folders after the benchmark is completed?

2019-10-22 09:00 UTC, maaktweluit commented on golem/task/taskserver.py
> +                    logger.debug(f"Not requesting task={theader.task_id}: {e}")
better to use the native formatter of `logger`

2019-10-22 09:00 UTC, maaktweluit commented on tests/golem/task/test_appbenchmarkmanager.py
> +# ^^ Pytest fixtures in the same file require the same name
maybe we can move these to the `lint.sh`

https://github.com/golemfactory/golem/blob/develop/lint.sh#L103

2019-10-22 09:00 UTC, maaktweluit commented on tests/golem/task/test_appbenchmarkmanager.py
> +        try:
you can use `with pytest.raises(...):` here:

http://doc.pytest.org/en/latest/assert.html#assertions-about-expected-exceptions

2019-10-22 09:07 UTC, mfranciszkiewicz commented on golem/task/benchmarkmanager.py
> +        benchmark = AppBenchmark(hash=prereq_hash, score=score)
It won't, exceptions aren't caught in the `try ... finally` block

2019-10-22 09:16 UTC, mfranciszkiewicz commented on tests/golem/task/test_appbenchmarkmanager.py
> +# ^^ Pytest fixtures in the same file require the same name
I'd rather not touch `lint.sh` here

2019-10-22 09:33 UTC, maaktweluit approved these changes

2019-10-23 09:24 UTC, Wiezzel commented on golem/task/taskserver.py
> +                    app_benchmark = yield Deferred.fromFuture(
Plz, use `deferred_from_future` from `golem.core.deferred`. It also calls `ensure_future`.

2019-10-23 09:24 UTC, Wiezzel commented on golem/task/taskserver.py
> +                except ComputationInProgress as error:
Other errors could also occur, like something gone wrong in benchmark computation. Don't we need any handling for these?

2019-10-23 09:24 UTC, Wiezzel commented on golem/model.py
> +    cpu_usage = IntegerField(default=0)  # total CPU usage in nanoseconds
Wouldn't default 0 cause any troubles (vide #4811)?

2019-10-24 09:56 UTC, merged