Use App Definition in task_api_tests/basic_integration.py
golemfactory/clay pull request #4817
Opened 2019-10-22 15:18 UTC by maaktweluit

2019-11-05 17:02 UTC, mfranciszkiewicz reviewed
Nothing really important, maybe besides the first `mkdir` call

2019-11-05 17:02 UTC, mfranciszkiewicz commented on scripts/task_api_tests/basic_integration.py
> +    app_definition = load_app_from_json_file(Path(app_definition_path))
```suggestion
    app_definition = load_app_from_json_file(app_definition_path)
```

2019-11-05 17:02 UTC, mfranciszkiewicz commented on scripts/task_api_tests/basic_integration.py
> +            subtask_output_dir / result_path.name,
```suggestion
            subtask_output_dir,
```
In general `copy` functions allow the second argument to be a directory

2019-11-05 17:02 UTC, mfranciszkiewicz commented on scripts/task_api_tests/basic_integration.py
>      rtm_work_dir.mkdir()
Maybe `rtm_work_dir.mkdir(parents=True, exist_ok=True)`? (a GH suggestion here modifies whitespace)

`exist_ok=True` may also apply to other `mkdir` calls. What do you think?

2019-11-06 10:47 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    app_definition = load_app_from_json_file(Path(app_definition_path))
tried this first, it gives this error :(

```
  File "/Users/mwu-gol/src/golem-project/golem/golem/apps/__init__.py", line 76, in load_app_from_json_file
    app_json = json_file.read_text(encoding='utf-8')
builtins.AttributeError: 'str' object has no attribute 'read_text'
```

seems something is wrong in Click with paths, will do some digging

2019-11-06 10:48 UTC, Wiezzel requested changes
The code doesn't quite match the acceptance criteria:
> * Providing a JSON file still works
> * There is an additional option to run the test on app_id

There is no option to provide app_id instead of a JSON file.

2019-11-06 10:48 UTC, Wiezzel commented on scripts/task_api_tests/basic_integration.py
> +    register_built_in_repositories()
Actually, if someone is testing their own app, registering built-in repositories won't help much. We need a mechanism for whitelisting the very image that the tested app uses. Which doesn't seem that obvious because app interface is abstract and whitelist is a docker-specific thing. I'm not sure if this issue belongs to this task but it surely has to be addressed.

2019-11-06 10:52 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    app_definition = load_app_from_json_file(Path(app_definition_path))
works as intended: https://github.com/pallets/click/issues/405

Will update the types to be correct for the arguments :)

2019-11-06 10:58 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
>      rtm_work_dir.mkdir()
By default the testing folders are deleted at the end of each run, so i think it works as intended to require a clean dir each run.

If we want to drop this "feature" i like your proposal :)

2019-11-06 10:58 UTC, Wiezzel commented on scripts/task_api_tests/basic_integration.py
> +    app_definition = load_app_from_json_file(Path(app_definition_path))
Why not use https://pypi.org/project/click-pathlib/ ?

2019-11-06 11:15 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +            subtask_output_dir / result_path.name,
You are right, bit strange i remember trying without result_path.name first and it gave a not found error..

2019-11-06 11:19 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    app_definition = load_app_from_json_file(Path(app_definition_path))
i think its a bit overkill to add a package, import and component that can break stuff to replace a single `Path(...)` cast

2019-11-06 11:20 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    register_built_in_repositories()
good one!

In the next PR ( app_id ) this call should be moved to the `task-by-app-id` call.

Would prefer to leave it as is in this PR since it works ( and its last weeks issue )

2019-11-06 11:25 UTC, maaktweluit commented
@Wiezzel this is last weeks issue, using a JSON only. 

app_id is a draft #4856  and will be open for review when this PR is merged

2019-11-06 11:27 UTC, Wiezzel commented on scripts/task_api_tests/basic_integration.py
> +    app_definition = load_app_from_json_file(Path(app_definition_path))
OK, fine.

2019-11-06 11:28 UTC, Wiezzel approved these changes

2019-11-06 13:19 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    app_definition = load_app_from_json_file(Path(app_definition_path))
Updated the argument types

2019-11-06 13:49 UTC, mfranciszkiewicz commented on scripts/task_api_tests/basic_integration.py
>      rtm_work_dir.mkdir()
Let’s keep it as it is

2019-11-06 15:20 UTC, mfranciszkiewicz approved these changes

2019-11-07 14:16 UTC, merged

2019-11-07 14:51 UTC, maaktweluit commented on scripts/task_api_tests/basic_integration.py
> +    register_built_in_repositories()
@Wiezzel updated the app_id PR accordingly, please check and comment there

Resolving this conversation