Update to Task API v0.23.0
golemfactory/clay pull request #4848
Opened 2019-11-04 10:24 UTC by Wiezzel

Task API v0.23.0 provider AbortSubtask call which is now invoked when a subtask times out. Subtasks in verification are not timed out. Updated the Blender app to v0.6.0 which is compatible with Task API v0.23.0

2019-11-04 14:36 UTC, maaktweluit requested changes
LGTM!

One small comment, asked this q before and got this reply from @mfranciszkiewicz

2019-11-04 14:36 UTC, maaktweluit commented on golem/apps/default.py
> +BlenderAppDefinition = AppDefinition(
Why did you remove the version from the app definition? it was meant to be able to run multiple versions of the same app side by side for compatibility reasons

2019-11-05 10:23 UTC, mfranciszkiewicz commented on golem/apps/default.py
> +BlenderAppDefinition = AppDefinition(
If you believe that including version in the name is an overkill, we may approach the problem differently:
- add version only to alternative versions of apps and treat the version-less one as "latest"
- inline app definitions in the `APPS` list

2019-11-05 10:27 UTC, mfranciszkiewicz approved these changes

2019-11-05 10:27 UTC, mfranciszkiewicz commented on golem/task/requestedtaskmanager.py
> +        if subtask.status in (
This could be a `not in` condition with a return to reduce code indentation

2019-11-05 16:59 UTC, mfranciszkiewicz commented
Please change the target branch to `develop`

2019-11-06 09:18 UTC, Wiezzel commented on golem/apps/default.py
> +BlenderAppDefinition = AppDefinition(
Inlining doesn't seem an option because this particular definition is imported.
I think we can put the version back in the name if we *actually include two versions of blenderapp* in the built-in definitions. For now, it's not necessary.

2019-11-07 08:07 UTC, Wiezzel commented
@maaktweluit Do you accept?

2019-11-07 12:15 UTC, maaktweluit commented on golem/apps/default.py
> +BlenderAppDefinition = AppDefinition(
I like that, this way we keep the latest without version number and give legacy versions a longer variable name.

This will keep the imports cleaner.

2019-11-07 12:15 UTC, maaktweluit approved these changes

2019-11-07 14:33 UTC, mfranciszkiewicz commented
Merging since only the Task API computation flow is affected

2019-11-07 14:33 UTC, merged