Docker stats POC
golemfactory/clay pull request #4862
Opened 2019-11-06 15:22 UTC by Wiezzel

Run e.g.
```
./scripts/docker_stats_poc.py busybox "sh -c 'while true; do echo dupa; sleep 1; done'"
```
Should print something like this:
```
Kernel: 0.000 s User: 0.200 s Total: 0.208 s Memory: 0.637 MiB
Kernel: 0.000 s User: 0.200 s Total: 0.209 s Memory: 0.641 MiB
Kernel: 0.000 s User: 0.200 s Total: 0.210 s Memory: 0.637 MiB
Kernel: 0.000 s User: 0.200 s Total: 0.210 s Memory: 0.637 MiB
Kernel: 0.000 s User: 0.200 s Total: 0.211 s Memory: 0.516 MiB
...
```
Hit <kbd>CTRL</kbd>+<kbd>C</kbd> to stop.

2019-11-07 12:13 UTC, maaktweluit requested changes
LGTM!

Some small comments.

Would move this file to `scripts/task_api` together with the basic integration tests if it will stay.

2019-11-07 12:13 UTC, maaktweluit commented on scripts/docker_stats_poc.py
> +    patch('golem.envs.docker.cpu.Whitelist.is_whitelisted', return_value=True)\
why patch this over just whitelisting the image in this line?

2019-11-07 12:13 UTC, maaktweluit commented on scripts/docker_stats_poc.py
> +            print('Wrong stats format')
maybe add if status == running here to, so it can be an "error" while running and a info ( or no message ) when its not

2019-11-07 12:13 UTC, maaktweluit commented on scripts/docker_stats_poc.py
> +    if len(sys.argv) != 3:
would recommend to use `Click` for args parsing if this poc file is going to stay

2019-11-07 12:16 UTC, Wiezzel commented on scripts/docker_stats_poc.py
> +    patch('golem.envs.docker.cpu.Whitelist.is_whitelisted', return_value=True)\
Because whitelisting requires a properly initialized database. :stuck_out_tongue:

2019-11-07 12:19 UTC, Wiezzel commented on scripts/docker_stats_poc.py
> +            print('Wrong stats format')
Nice idea.
However, I'm not sure if the last message is sent after the container is stopped or just before. Need to check it.

2019-11-07 12:53 UTC, Wiezzel commented on scripts/docker_stats_poc.py
> +    if len(sys.argv) != 3:
It's not going to stay.

2019-11-07 14:13 UTC, maaktweluit approved these changes

2019-12-04 15:47 UTC, mfranciszkiewicz commented
Merged in #4901

2019-12-04 15:47 UTC, closed without merging