Only include task_api apps on testnet
golemfactory/clay pull request #4871
Opened 2019-11-07 16:37 UTC by maaktweluit

So they can be safely tested on testnet first

2019-11-07 16:44 UTC, Wiezzel reviewed
What about provider part? Will it go in another PR?

2019-11-07 17:17 UTC, maaktweluit commented
@Wiezzel good one, will look at this tomorrow, in this PR :) Was thinking if a task is not able to be requested the provider "switch" is not needed, but it is a good practice to include it on both sides.

2019-11-08 13:16 UTC, Wiezzel requested changes
I don't approve this approach. I suggest to do what the task description says:
> don't register envs

This should effectively block all Task API-related activity both on requestor and provider side.

2019-11-08 13:16 UTC, Wiezzel commented on golem/task/taskserver.py
> +            if app_def.requestor_prereq['image'] in TASK_API_IMG_NAMES:
I liked the app-based approach better than this. It relies on Docker-specific `'image'` key thus breaking the abstraction.

2019-11-08 13:16 UTC, Wiezzel commented on golem/task/taskserver.py
> +                    repository_from_image_name(image_name)
`repository_from_image_name` is already being called inside `Whitelist.is_whitelisted`. No need to call it here. Maybe prepend the function name with underscore to avoid this kind of mistakes.

2019-11-08 13:16 UTC, Wiezzel commented on golem/task/taskserver.py
> +            if image_name not in TASK_API_IMG_NAMES:
This effectively blocks all apps other then blender. We don't want it.

2019-11-08 13:52 UTC, maaktweluit commented on golem/task/taskserver.py
> +            if image_name not in TASK_API_IMG_NAMES:
only task_api related apps, so i think this is as expected

2019-11-08 13:53 UTC, maaktweluit commented on golem/task/taskserver.py
> +            if app_def.requestor_prereq['image'] in TASK_API_IMG_NAMES:
with an app based approach the data is not available in the task_header, so if we only make it requestor side this is possible, for both sides we need to do it image based

2019-11-08 13:56 UTC, maaktweluit commented on golem/task/taskserver.py
> +                    repository_from_image_name(image_name)
fixed the duplicate call and made the function private

2019-11-08 14:07 UTC, Wiezzel commented on golem/task/taskserver.py
> +            if image_name not in TASK_API_IMG_NAMES:
How are developers supposed to do anything with the Task API then?

2019-11-08 14:07 UTC, Wiezzel commented on golem/task/taskserver.py
> +            if image_name not in TASK_API_IMG_NAMES:
Summon @mfranciszkiewicz

2019-11-08 14:12 UTC, maaktweluit commented
@Wiezzel saw your main comment after fixing all the others 🤦‍♂ 

Moved the logic to use envs instead, indeed much neater.

2019-11-08 14:14 UTC, Wiezzel commented on golem/config/environments/mainnet.py
> +TASK_API_IMG_NAMES = []
```suggestion
TASK_API_ENVS = []
```

2019-11-08 14:16 UTC, maaktweluit commented on golem/config/environments/mainnet.py
> +TASK_API_IMG_NAMES = []
Whoops, global find / replace fail, amended the previous commit

2019-11-08 14:17 UTC, maaktweluit commented on golem/task/taskserver.py
> +            if image_name not in TASK_API_IMG_NAMES:
in the above example they would have to add their image name to the list.

Now its all moved to envs the comment no longer applies and developers can use all apps on the enabled envs

2019-11-08 14:21 UTC, Wiezzel approved these changes

2019-11-08 14:35 UTC, mfranciszkiewicz approved these changes

2019-11-12 14:58 UTC, merged