wasm multicore support
golemfactory/clay pull request #4889
Opened 2019-11-14 16:25 UTC by prekucki

2019-11-15 14:07 UTC, tworec reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem/4889)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @mfranciszkiewicz, @prekucki, @shadeofblue, and @tworec)

___
*[golem/task/taskcomputer.py, line 91 at r1](https://reviewable.io/reviews/golemfactory/golem/4889#-Ltiz_DTElux8xw36AIp:-Ltiz_DTElux8xw36AIq:b-8fx2u7) ([raw file](https://github.com/golemfactory/golem/blob/d243dc3860dc4f0ed2793a9169b1372d833b6821/golem/task/taskcomputer.py#L91)):*
> ```Python
>     def task_given(self, ctd: ComputeTaskDef) -> None:
>         assert not self._new_computer.has_assigned_task()
>         assert self._old_computer.can_take_work()
> ```

:+1: 
___
*[golem/task/taskcomputer.py, line 431 at r2](https://reviewable.io/reviews/golemfactory/golem/4889#-Ltj-geg--g6Tv4KQrOM:-Ltj-geg--g6Tv4KQrON:b7av8yi) ([raw file](https://github.com/golemfactory/golem/blob/6783ae79e57b0013b8ce46534718bf9ea718f05c/golem/task/taskcomputer.py#L431)):*
> ```Python
> 
> @dataclass
> class TaskComputation:
> ```

I'd add a short purpose of this class --> to make multiple computations within single TaskComputer
___
*[golem/task/taskcomputer.py, line 552 at r2](https://reviewable.io/reviews/golemfactory/golem/4889#-LtjMAoQ2-2CVObWekwM:-LtjMAoQ2-2CVObWekwN:b571xb) ([raw file](https://github.com/golemfactory/golem/blob/6783ae79e57b0013b8ce46534718bf9ea718f05c/golem/task/taskcomputer.py#L552)):*
> ```Python
>         return self.task_computer.task_finished(self)
> 
>     def start_computation(self) -> None:  # pylint: disable=too-many-locals
> ```

this is within TaskComputation class so we can use shorter name here eg. `start`
___
*[golem/task/taskcomputer.py, line 648 at r2](https://reviewable.io/reviews/golemfactory/golem/4889#-Ltj5Pyk5-oce45C9eXA:-Ltj5Pyk5-oce45C9eXB:b-kb3374) ([raw file](https://github.com/golemfactory/golem/blob/6783ae79e57b0013b8ce46534718bf9ea718f05c/golem/task/taskcomputer.py#L648)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         # So apparently it is perfectly fine for mypy to assign None to a
> 
>         # non-optional variable. And if I tried Optional['ComputeTaskDef']
> 
>         # then I would get "Optional[Any] is not indexable" error.
> 
>         # Get your sh*t together, mypy!
> ```
</details>

while I like this comment, it is not adequate here anymore, bc you've replaced None with empty list
___
*[golem/task/taskcomputer.py, line 680 at r2](https://reviewable.io/reviews/golemfactory/golem/4889#-LtjA3h3BB_7CyyD_vI4:-Ltj9zEq1FL4CyPzYojB:b-23abis) ([raw file](https://github.com/golemfactory/golem/blob/6783ae79e57b0013b8ce46534718bf9ea718f05c/golem/task/taskcomputer.py#L680)):*
> ```Python
>         if not self.assigned_subtasks:
>             return None
>         return self.assigned_subtasks[0].assigned_task_id
> ```

I'm not sure if such a shortcut is correct. We can potentially have multiple task_id assigned but returning the one for the first subtask. 
`TaskServer.resource_failure` can be possibly affected. This is minor since it affects only error handling
___
*[golem/task/taskcomputer.py, line 718 at r2](https://reviewable.io/reviews/golemfactory/golem/4889#-Ltj76vqAC19-Nxgzrxi:-Ltj76vqAC19-Nxgzrxj:b-fpny89) ([raw file](https://github.com/golemfactory/golem/blob/6783ae79e57b0013b8ce46534718bf9ea718f05c/golem/task/taskcomputer.py#L718)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
>     def can_take_work(self) -> bool:
> 
>         with self.lock:
> 
>             if any([
> 
>                     computation for computation in self.assigned_subtasks
> 
>                     if not computation.single_core
> 
>             ]):
> 
>                 return False
> 
>             return len(self.assigned_subtasks) < self.max_num_cores
> ```
</details>


pls consider code below instead
```
    def can_take_work(self) -> bool:
        self.free_cores > 0
```
___
*[golem/task/taskcomputer.py, line 749 at r2](https://reviewable.io/reviews/golemfactory/golem/4889#-LtjE1PPDoSffc2MqW9t:-LtjE1PPDoSffc2MqW9u:b-m97t9u) ([raw file](https://github.com/golemfactory/golem/blob/6783ae79e57b0013b8ce46534718bf9ea718f05c/golem/task/taskcomputer.py#L749)):*
I'd change to debug here. 
> ```
> logger.debug(f"num_cores={config_desc.num_cores}")
> ```
___
*[golem/task/taskcomputer.py, line 754 at r2](https://reviewable.io/reviews/golemfactory/golem/4889#-LtjEGbr6GTqsqWK8lDm:-LtjEGbr6GTqsqWK8lDn:b-4ovbu9) ([raw file](https://github.com/golemfactory/golem/blob/6783ae79e57b0013b8ce46534718bf9ea718f05c/golem/task/taskcomputer.py#L754)):*
> ```Python
> 
>         dm = self.docker_manager
>         assert isinstance(dm, DockerManager)
> ```

seems to be a not necessary check... line below will fail if dm is not an instance of `DockerManager` class

maybe it was added to just satisfy some linter
___
*[golem/task/taskcomputer.py, line 803 at r2](https://reviewable.io/reviews/golemfactory/golem/4889#-LtjN7wA0YRzqDM97BS0:-LtjN7wA0YRzqDM97BS1:b3m0n2g) ([raw file](https://github.com/golemfactory/golem/blob/6783ae79e57b0013b8ce46534718bf9ea718f05c/golem/task/taskcomputer.py#L803)):*
> ```Python
>             if not [
>                     c for c in self.assigned_subtasks
>                     if c.assigned_subtask_id == task_id
> ```

obviously should be corrected  


<!-- Sent from Reviewable.io -->

2019-11-15 14:24 UTC, tworec commented
___
*[golem/task/taskserver.py, line 491 at r2](https://reviewable.io/reviews/golemfactory/golem/4889#-LtjRjrg0POPTB3no_10:-LtjRjrg0POPTB3no_11:bdt63c6) ([raw file](https://github.com/golemfactory/golem/blob/6783ae79e57b0013b8ce46534718bf9ea718f05c/golem/task/taskserver.py#L491)):*
> ```
> logger.error("Trying to assign a task, but we can not take more work at the moment")
> ```


<!-- Sent from Reviewable.io -->

2019-11-18 08:16 UTC, shadeofblue commented on golem/task/server/resources.py
> +    HANDSHAKE_TIMEOUT = 60  # s
does this change pertain to the functionality included in the pull request or is it here incidentally?

2019-11-18 11:28 UTC, tworec requested changes
fix marked condition

2019-11-18 11:29 UTC, tworec commented on golem/task/taskcomputer.py
> +                    if c.assigned_subtask_id == task_id
fixme

2019-11-18 12:49 UTC, tworec approved these changes

2019-11-19 11:07 UTC, prekucki commented on golem/task/server/resources.py
> +    HANDSHAKE_TIMEOUT = 60  # s
I reverted it. there is a problem with persistent ban between nodes if network is small enough, but a longer timeout won't help with this.

2019-11-20 11:57 UTC, Wiezzel requested changes
Please do not break indentation. Our [style guide](https://github.com/golemfactory/styleguide/blob/gh-pages/pyguide.md#34-indentation) explicitly says not to use indentation dependent on names and go for multiples of 4 instead. There are some changes in this PR that don't seem to have any other purpose than changing indentation from correct to incorrect. I marked out a few but soon gave up because there were too many.

2019-11-20 11:57 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +                 stats_keeper: Optional[IntStatsKeeper] = None) -> None:
Bad indentation.

2019-11-20 11:57 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +                   compute_task_def: ComputeTaskDef) -> None:
Bad indentation.

2019-11-20 11:57 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +                        assigned_task.task_id, assigned_task.subtask_id)
Bad indentation.

2019-11-20 11:57 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +                      work_dir: Path) -> defer.Deferred:
Bad indentation.

2019-11-20 11:57 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +                                                  to_unit=MemSize.mebi))
Bad indentation.

2019-11-20 11:57 UTC, Wiezzel commented on golem/task/taskcomputer.py
> +                                             task_thread.error_msg, reason)
Bad indentation.

2019-11-21 08:36 UTC, shadeofblue commented on golem/task/taskserver.py
> +                    }),)
@prekucki I honestly don't understand the need to update the code formatting for the sake of code formatting itself.... isn't this pull request complicated enough to maybe abstain from meddling with formatting at the same time?

especially if the changes you've made are, arguably, for worse, not better? ...

2019-11-21 08:38 UTC, shadeofblue commented on golem/task/taskserver.py
> +            **_kwargs):
especially here, when you're doing the opposite change ... what's the point?

2019-11-21 08:40 UTC, shadeofblue requested changes
please revert the formatting-only changes in this pull request... it's not a place or time to do them in a pull request that's sufficiently complicated even without them

2019-11-21 08:41 UTC, shadeofblue commented
> Please do not break indentation. Our [style guide](https://github.com/golemfactory/styleguide/blob/gh-pages/pyguide.md#34-indentation) explicitly says not to use indentation dependent on names and go for multiples of 4 instead. There are some changes in this PR that don't seem to have any other purpose than changing indentation from correct to incorrect. I marked out a few but soon gave up because there were too many.

_exactly_ my impression ... :( ...

2019-11-25 17:56 UTC, closed without merging