Safely update balances
golemfactory/clay pull request #4906
Opened 2019-11-18 15:31 UTC by jiivan

fixes: #4904 

1. Decrease verbosity of known geth connection issue to INFO
1. Try to update other balances even if one fails

2019-11-18 17:04 UTC, maaktweluit requested changes
LGTM!

One small q, will approve on fix or reply

2019-11-18 17:04 UTC, maaktweluit commented on golem/ethereum/transactionsystem.py
> +            print("safe update", currency)
why use `print` here? would be cleaner to use logger.debug i think

2019-11-19 20:24 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +            print("safe update", currency)
My bad. Those are my debug debris

2019-11-20 08:47 UTC, jiivan commented on golem/ethereum/transactionsystem.py
> +            print("safe update", currency)
Fixed

2019-11-20 10:13 UTC, maaktweluit approved these changes

2019-11-20 10:26 UTC, merged