Fixed CPU time limit calculation
golemfactory/clay pull request #4909
Opened 2019-11-18 15:58 UTC by zakaprov

2019-11-19 07:24 UTC, mbenke reviewed
Something seems wrong here - the cpu limit seems to be always 3600, no matter what the task budget:

```
INFO     [golem.task.taskcomputer            ] Starting computation of subtask 'cd5dbb18-0a9c-11ea-8580-054089b37bde' (task: 'c18d9810-0a9c-11ea-bcfe-054089b37bde', deadline: 1574147954, docker images: [{'repository': 'golemfactory/wasm', 'image_id': None, 'tag': '0.5.4'}], cpu_limit: 3600)
```

This probably stems from https://github.com/golemfactory/golem/blob/develop/golem/task/tasksession.py#L453

2019-11-19 09:36 UTC, mbenke requested changes

2019-11-19 09:36 UTC, mbenke commented on golem/task/taskcomputer.py
> +                self.cpu_limit
It might be worthwhile to add the `self.cpu_limit` value to the log message above

2019-11-19 09:36 UTC, mbenke commented on golem/task/taskserver.py
> +            task_header.subtask_budget, msg.price)
We should use price from WTCT as price in TTC is subtask budget, rather than price per hour
```suggestion
            task_header.subtask_budget, msg.want_to_compute_task.price)
```

2019-11-19 14:15 UTC, mbenke commented on tests/golem/task/test_taskserver.py
> +            task_header.subtask_budget, ttc.want_to_compute_task.price)
`ttc.want_to_compute_task.price` seem to be `None` here

2019-11-19 14:42 UTC, zakaprov commented on tests/golem/task/test_taskserver.py
> +            task_header.subtask_budget, ttc.want_to_compute_task.price)
Right, I've changed the factory for WTCT to include price, but that's in golem-messages... Let me update it.

2019-11-20 10:59 UTC, mbenke approved these changes

2019-11-20 15:22 UTC, merged