Sorting tasks returned by comp.tasks RPC endpoint
golemfactory/clay pull request #4920
Opened 2019-11-21 14:04 UTC by zakaprov

Changes the order of tasks returned by comp.tasks RPC endpoint.
Tasks are now sorted by their `time_started` field.

2019-11-21 15:00 UTC, maaktweluit requested changes

2019-11-21 15:00 UTC, maaktweluit commented on golem/client.py
> +        return sorted(filtered_tasks, key=lambda task: task['time_started'])
`time_started` is not put on the new task-api style task dicts, can you add it on #847 ? should be task.start_time

2019-11-21 15:01 UTC, maaktweluit commented
Please also note start_time is empty for newly created tasks, think these should count as the "highest" times

2019-11-21 15:30 UTC, zakaprov commented on golem/client.py
> +        return sorted(filtered_tasks, key=lambda task: task['time_started'])
Good catch, thanks! I'm not sure about the issue you wanted to link here though, since 847 is from more than 2 years back and not relevant to these changes.

2019-11-21 15:53 UTC, maaktweluit commented on golem/client.py
> +        return sorted(filtered_tasks, key=lambda task: task['time_started'])
whoops, it was 874

https://github.com/golemfactory/golem/pull/4920/files#diff-9f351727974c5655127c6a4dc0671995R874

2019-11-22 12:39 UTC, zakaprov commented on golem/client.py
> +        return sorted(filtered_tasks, key=lambda task: task['time_started'])
@maaktweluit added, can you take a second look?

2019-11-22 12:48 UTC, maaktweluit approved these changes

2019-11-22 12:48 UTC, maaktweluit commented
Looks great! Thanks for the fix :)

2019-11-22 16:31 UTC, merged