Task-api - QA guide to testnet tests
golemfactory/clay pull request #4939
Opened 2019-11-26 11:55 UTC by maaktweluit

Added a small guide on how to test and debug task_api tasks.

2019-11-26 13:52 UTC, mfranciszkiewicz requested changes
PR for missing RPC calls https://github.com/golemfactory/golem/pull/4940

2019-11-26 13:52 UTC, mfranciszkiewicz commented on scripts/task_api_tests/task-api-readme.md
> +the task will show up in the `golemcli tasks show` but not listen to all `golemcli tasks *` commands
Please refer to the linked PR and specify which calls are and aren't supported by Task API

2019-11-26 14:22 UTC, maaktweluit commented on scripts/task_api_tests/task-api-readme.md
> +the task will show up in the `golemcli tasks show` but not listen to all `golemcli tasks *` commands
Included the commands implemented in the PR as available.

2019-11-27 10:29 UTC, Wiezzel approved these changes

2019-11-27 17:50 UTC, mfranciszkiewicz approved these changes

2019-11-29 14:58 UTC, ederenn approved these changes

2019-11-29 15:39 UTC, merged