Send evt.net.connection only when status changes
golemfactory/clay pull request #4958
Opened 2019-12-02 14:31 UTC by jiivan

fixes: #4957

2019-12-02 14:49 UTC, etam approved these changes
![ok](https://media.giphy.com/media/4PSEQpvV5wUpnmpP1l/giphy.gif)

2019-12-02 15:30 UTC, etam requested changes

2019-12-02 15:30 UTC, etam commented on tests/golem/test_client.py
> +        poll_mock.return_value = {'random_key': random.random()}
This might very rarely fail, because it might produce the same value twice. You can assign an array to `side_effect` and it will return next value for each call.

2019-12-02 15:55 UTC, jiivan commented on tests/golem/test_client.py
> +        poll_mock.return_value = {'random_key': random.random()}
It won't fail, because service is initialized in `.setUp()` which uses original `.poll()` implementation, that returns totally different kind of dict.

https://github.com/golemfactory/golem/blob/3b92e82da512a7d3af9c8e31fbdf50638630dc1a/golem/client.py#L1329-L1342

2019-12-03 08:18 UTC, etam approved these changes

2019-12-03 15:56 UTC, merged