Container not shut down on task creation failure
golemfactory/clay pull request #4982
Opened 2019-12-09 15:07 UTC by mfranciszkiewicz

2019-12-09 15:34 UTC, maaktweluit requested changes
LGTM!

One small return type comment

2019-12-09 15:34 UTC, maaktweluit commented on golem/task/rpc.py
> +    ):
this still returns a `TaskId`

2019-12-09 15:45 UTC, mfranciszkiewicz commented on golem/task/rpc.py
> +    ):
The type returned is not `TaskId` but a derivative of `Generator` due to `inlineCallbacks`.

2019-12-09 15:46 UTC, mfranciszkiewicz commented on golem/task/rpc.py
> +    ):
I have issues with various linters regarding the returned type when I try to hint it as `Generator[...]`

2019-12-09 16:46 UTC, maaktweluit commented on golem/task/rpc.py
> +    ):
ahh, damn linters :(

ok, lets leave it like this then :)

2019-12-09 16:47 UTC, maaktweluit approved these changes

2019-12-11 09:32 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +                    await self._shutdown_app_client(app_id)
Shouldn't we check here if there are no more tasks running on this client?

2019-12-11 09:42 UTC, mfranciszkiewicz commented on golem/task/requestedtaskmanager.py
> +                    await self._shutdown_app_client(app_id)
The check is inside `_shutdown_app_client`

2019-12-11 10:34 UTC, Wiezzel commented on golem/task/requestedtaskmanager.py
> +                    await self._shutdown_app_client(app_id)
Oh, of course.

2019-12-11 10:35 UTC, Wiezzel approved these changes

2019-12-11 12:10 UTC, merged