fix force payment concent integration test
golemfactory/clay pull request #4989
Opened 2019-12-10 16:33 UTC by shadeofblue

additionally
* don't send `SystemExit` and `Exit` to sentry in any case
* don't try to freeze raven's time calls

2019-12-10 16:47 UTC, maaktweluit requested changes
LGTM!

small nit and bug in the log message

2019-12-10 16:47 UTC, maaktweluit commented on golem/ethereum/incomeskeeper.py
> +            logger.debug("Marking payment as overdue: sender: %s, amount: %s ")
```suggestion
            logger.debug("Marking payment as overdue. sender=%s, amount=%s ")
```
would format data as kwargs, according to logging guide

also no values are passed for the formatters.

2019-12-11 08:38 UTC, jiivan approved these changes

2019-12-11 09:40 UTC, maaktweluit approved these changes

2019-12-11 11:13 UTC, merged