update requirements
golemfactory/clay pull request #4990
Opened 2019-12-12 09:37 UTC by etam

I just used `pip freeze` on a fresh venv and manually adjusted multidict version. It has no further dependencies, so it should be fine.

2019-12-12 10:18 UTC, maaktweluit requested changes
`python-dateutil==2.8.1`

is now duplicate and should be removed from `requirements-lint.txt`
https://buildbot.golem.network/buildbot/#/builders/8/builds/16523

2019-12-12 11:21 UTC, maaktweluit approved these changes

2019-12-12 11:24 UTC, shadeofblue commented
![5 thumbs up](https://user-images.githubusercontent.com/7963044/70708244-5738a600-1cda-11ea-9498-a8821ff2973c.jpeg)

2019-12-12 14:53 UTC, merged

2020-02-07 08:38 UTC, etam commented
by the way: multidict issue with pyinstaller should be fixed by now: https://github.com/pyinstaller/pyinstaller/issues/4572