Bump golemfactory/wasm to 0.6.0
golemfactory/clay pull request #5089
Opened 2020-02-06 14:24 UTC by kubkon

This PR bumps our Wasm sandbox to latest release 0.6.0 in Docker Hub.
The corresponding changes can be found at golemfactory/sp-wasm#38.
For completeness though, here's the summary of major changes to the sandbox:
* port Reqc's change to VM which now makes `BINARYEN_ASYNC_COMPILATION` flag
  obsolete
* refactors the CLI interface for the sandbox (changes `clap` for `structopt`)
* refactors error handling (changes `failure` for `thiserror`)

2020-02-06 14:38 UTC, jiivan approved these changes

2020-02-07 10:51 UTC, kmazurek approved these changes
![rage](https://media.giphy.com/media/amUVFzg1wNZKg/giphy.gif)

2020-02-07 13:13 UTC, jiivan requested changes
Merge after prints are removed

2020-02-07 13:56 UTC, jiivan approved these changes
![gang_olsena](https://user-images.githubusercontent.com/293058/74035145-fff14200-49b9-11ea-9a4b-8c561fe03260.gif)

2020-02-07 13:58 UTC, kubkon commented
> ![gang_olsena](https://user-images.githubusercontent.com/293058/74035145-fff14200-49b9-11ea-9a4b-8c561fe03260.gif)

Am I the one getting hit with the brick by accident (or was it?)? :D

2020-02-07 14:20 UTC, kubkon commented
It's ALIIIIIVEEEE! Thanks @maaktweluit! 🎉

2020-02-07 14:28 UTC, merged