Acl improvement
golemfactory/clay pull request #5095
Opened 2020-02-13 15:53 UTC by mdtanrikulu

//TBD

2020-03-02 14:53 UTC, etam commented
FYI: https://github.com/golemfactory/golem/issues/4363

2020-03-02 15:11 UTC, etam commented on golem/task/acl.py
> +        if timeout_seconds < 0:
I think it would be more readable, to declare `persist = timeout_seconds < 0` at the beginning of function.

2020-03-02 15:14 UTC, etam commented on golem/task/acl.py
> +                raise Exception(node_id)
I'd add some explanation like "ACL already defined".

2020-03-02 15:14 UTC, etam commented on golem/task/acl.py
> +                raise Exception(node_id)
I'd add some explanation like "ACL doesn't exist".

2020-03-02 15:15 UTC, etam commented on golem/task/acl.py
> +        if timeout_seconds < 0:
I think it would be more readable, to declare `persist = timeout_seconds < 0` at the beginning of function.

2020-03-02 15:16 UTC, etam commented on golem/task/acl.py
> +                raise Exception(node_id)
I'd add some explanation like "ACL doesn't exist".

2020-03-02 15:16 UTC, etam commented on golem/task/acl.py
> +                raise Exception(node_id)
I'd add some explanation like "ACL already defined".

2020-03-18 11:23 UTC, jiivan commented
@mdtanrikulu Should this be rebased to develop?

2020-03-20 10:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem?pullRequest=5095) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem?pullRequest=5095) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem?pullRequest=5095) it.</sub>

2020-03-21 14:41 UTC, mdtanrikulu commented on golem/task/acl.py
> +        if timeout_seconds < 0:
make sense, added.

2020-03-21 14:50 UTC, mdtanrikulu commented on golem/task/acl.py
> +                raise Exception(node_id)
the exception is a return for failing cases in rpc, not for logging. see here L1256;
https://github.com/golemfactory/golem/blob/c345bba89b44258a2c5c26c9ab93826e45c49ea4/golem/task/taskserver.py#L1243-L1256

2020-03-21 14:50 UTC, mdtanrikulu commented on golem/task/acl.py
> +                raise Exception(node_id)
> the exception is a return for failing cases in rpc, not for logging. see here L1256;
> 
> https://github.com/golemfactory/golem/blob/c345bba89b44258a2c5c26c9ab93826e45c49ea4/golem/task/taskserver.py#L1243-L1256

2020-03-21 14:54 UTC, mdtanrikulu commented on golem/task/acl.py
> +                raise Exception(node_id)
> the exception is a return for failing cases in rpc, not for logging. see here L1256;
> 
> https://github.com/golemfactory/golem/blob/c345bba89b44258a2c5c26c9ab93826e45c49ea4/golem/task/taskserver.py#L1243-L1256

2020-03-21 14:54 UTC, mdtanrikulu commented on golem/task/acl.py
> +                raise Exception(node_id)
> the exception is a return for failing cases in rpc, not for logging. see here L1276;
> 
> https://github.com/golemfactory/golem/blob/c345bba89b44258a2c5c26c9ab93826e45c49ea4/golem/task/taskserver.py#L1266-L1276

2020-03-21 15:20 UTC, mdtanrikulu commented
@jiivan I can, but I see that there is still couple of commits ahead of dev in b0.22. Will we merge them?

2020-03-23 11:52 UTC, etam commented on golem/task/acl.py
> +                raise Exception(node_id)
So I'd do something like this:
```python
class ACLAlreadyDefined(Exception):
    def __init__(self, node_id: str) -> None:
        self.node_id = node_id
```
and in handler:
```python
try:
    [...]
except ACLAlreadyDefined as e:
    return False, e.node_id
except Exception as e:  #  pylint: disable=broad-except
    return False, str(e)
```
This way you make it clear what is the purpose of exception and where it's handled.

2020-03-23 11:57 UTC, etam commented on golem/task/acl.py
> +                raise Exception(node_id)
Also: `node_id` may be a list. If one of entries causes an exception, the rest will be omitted. Maybe instead of throwing exceptions, `disallow` method may return a bool (or enum if more options are needed) indicating the result, and in `disallow_node` you would first gather all results and then return collected status.

2020-03-26 12:47 UTC, jiivan commented
@mdtanrikulu yes, I've created a PR https://github.com/golemfactory/golem/pull/5147 (but those commits are unrelevant to ACL as far as I can see)

2020-03-27 11:22 UTC, etam requested changes

2020-03-27 11:22 UTC, etam commented on golem/task/acl.py
> +                 timeout_seconds: int = -1) -> Union[bool, str]:
This function now returns `True` if node was disallowed or `node_id` that it gets on input if it already was. I think it should be just a `bool`.

Also, there is a `return` without value in this funcion (I can't comment there, because it wasn't changed).

2020-03-27 11:22 UTC, etam commented on golem/task/taskserver.py
> +                    results.append(result)
```python
if not self.acl.disallow(item, timeout_seconds):
    results.append(item)
```

2020-03-27 11:22 UTC, etam commented on golem/task/taskserver.py
> +        results: List[str] = []
I'd call it `not_changed`

2020-03-27 11:22 UTC, etam commented on golem/task/taskserver.py
> +            return False, results, str(e)
I think that a dict, that gives names to those values would be more readable.

2020-03-27 16:40 UTC, etam commented on golem/task/acl.py
> +                return True
I think it's `False`, because node is already disallowed and nothing is changed.

2020-03-27 16:46 UTC, etam commented on golem/task/taskserver.py
> +        Error: [False, [], 'message']
```suggestion
        (is_disallow_success, list_of_already_disallowed_nodes, err_message)

        Success: (True, [], None)
        Success with existing node: (True, ['node_id'], None)
        Error: (False, [], 'message')
```

2020-03-27 16:47 UTC, etam commented on golem/task/taskserver.py
> +        Error: [False, [], 'message']
```suggestion
        (is_allow_success, list_of_already_allowed_nodes, err_message)

        Success: (True, [], None)
        Success with existing node: (True, ['node_id'], None)
        Error: (False, [], 'message')
```

2020-03-27 16:48 UTC, etam commented on golem/task/taskserver.py
> +        Error: [False, [], 'message']
It's either "is success" or "did succeed"

2020-03-30 09:02 UTC, mdtanrikulu commented on golem/task/acl.py
> +                return True
I rather in favor of keep this `True`.
1. There is no use of temporary ban by user, unless user wants to do it in purpose.
2. No point to show warning when golem itself makes temporary bans
3. If there is no warning needed when Golem makes temp bans, it means it actually doesn't matter what returns
4. The check is not comes from db, comes from memory.

2020-03-30 11:08 UTC, etam commented on golem/task/acl.py
> +                return True
I'm trying to understand the meaning of return value and I'm a bit puzzled.

Here's what I came up with (I put in _italic_ the result we're commenting on):

| | not persist | persist |
| --- | --- | --- | 
| **not banned** | True (a temporary ban is added to memory) | True (a persistent ban is added to database) |
| **is persistently banned** | _True_ (nothing changes, because existing ban is stronger) | False (nothing changes) |
| **is temporarily banned** | True (a temporary ban is extended) | True (temporary ban is removed and a persistent ban is added to database) |

So my first suggestion: Add documentation comments in `Acl` base class in `disallow` and `allow` methods what is the meaning of return value. Preferably in the form "returns True when ..." or "returns False when ...".

2020-03-30 11:27 UTC, etam commented on golem/task/acl.py
> +                return True
Returns False if node_id is already banned in database

2020-03-30 12:43 UTC, etam approved these changes
![ok](https://s3.envato.com/files/182504205/Access%20Granted%20590x332.jpg)

2020-04-29 15:15 UTC, merged