Ranking thread safety
golemfactory/clay pull request #636
Opened 2016-09-27 13:26 UTC by paulperegud

Ranking class is thread-safe as it is. I've added a test and demoted some methods to non-public.

resolves #624

2016-10-03 17:02 UTC, mfranciszkiewicz commented on tests/golem/ranking/test_ranking.py
> +        self.assertEqual(0.0, expected)
`expected` is assigned a value prior to the actual test. The outcome doesn't change, though, and the assertion still holds.

2016-10-03 18:35 UTC, paulperegud commented on tests/golem/ranking/test_ranking.py
> +        self.assertEqual(0.0, expected)
Fixed. Was trying not to rely on value 0.0 and omitted last step.

2016-10-06 17:28 UTC, badb requested changes

2016-10-06 17:28 UTC, badb commented on tests/golem/ranking/test_ranking.py
> +    def test_increase_trust_thread_safety(self):
This test doesn't work on windows:
1) `OperationalError: database is locked` occurs
2) `AssertionError: 0.01098901098901099 != 0.0`

2016-10-06 17:59 UTC, badb commented
I've added some locks so test passes on my machine, but feel free to revert and do something else.

2016-10-12 11:42 UTC, merged