Replace ethereum_rpc_client with web3.py #690
golemfactory/clay pull request #700
Opened 2016-12-05 16:35 UTC by banasiakadam60

Signed-off-by: Adam Banasiak <banasiakadam60@gmail.com>

2016-12-05 16:35 UTC, banasiakadam60 commented
#690

2016-12-05 21:23 UTC, chfast commented
Still some failures in tests.

2016-12-08 21:49 UTC, chfast requested changes

2016-12-08 21:49 UTC, chfast commented on golem/ethereum/client.py
> +        if hasattr(filer_id, 'filter_id'):  # in case of passing filter object
I guess the new_filler should return the `.filter_id` straight away. Besides you have type in `filer_id`.

2016-12-08 21:49 UTC, chfast commented on golem/ethereum/client.py
> +            'from': _from,
What happens if you omit the "from" field?

2016-12-08 21:49 UTC, chfast commented on golem/ethereum/node.py
> +            '--etherbase', '0x6528d9354356d7f668c75e9ed97f792bf910c8e5',
That make no sense.

2016-12-08 21:49 UTC, chfast commented on golem/ethereum/paymentmonitor.py
> +                payer.encode('hex'), value / denoms.ether))
Avoid not related changes in other files.

2016-12-09 00:19 UTC, banasiakadam60 commented on golem/ethereum/client.py
> +            'from': _from,
Due to documentation it's optional field with default value `web3.eth.defaultAccount`, so I've added `_from = _from or self.web3.eth.defaultAccount`
See: http://web3py.readthedocs.io/en/latest/web3.eth.html `sendTransaction`

2016-12-09 00:19 UTC, banasiakadam60 commented on golem/ethereum/client.py
> +        if hasattr(filer_id, 'filter_id'):  # in case of passing filter object
OK

2016-12-09 00:19 UTC, banasiakadam60 commented on golem/ethereum/node.py
> +            '--etherbase', '0x6528d9354356d7f668c75e9ed97f792bf910c8e5',
Removed

2016-12-09 00:19 UTC, banasiakadam60 commented on golem/ethereum/paymentmonitor.py
> +                payer.encode('hex'), value / denoms.ether))
Sorry, my IDE automatically changed it and I've accidentally sent this change

2016-12-09 10:53 UTC, banasiakadam60 commented on golem/ethereum/node.py
> +            '--etherbase', '0x6528d9354356d7f668c75e9ed97f792bf910c8e5',
It looks like `etherbase address` must be set

2016-12-09 13:21 UTC, chfast approved these changes

2016-12-09 13:22 UTC, merged