Replace asserts with raise exceptions
golemfactory/clay pull request #728
Opened 2016-12-22 16:28 UTC by banasiakadam60

2016-12-23 16:31 UTC, mfranciszkiewicz requested changes

2016-12-23 16:31 UTC, mfranciszkiewicz commented on golem/docker/task_thread.py
> +        if docker_images is None:
`if not docker_images` would handle empty lists

2016-12-23 16:31 UTC, mfranciszkiewicz commented on golem/network/transport/message.py
> +            if dict_repr.get(MessagePing.PING_STR) is None:
You can use `if not ...` to catch empty values

2016-12-23 16:31 UTC, mfranciszkiewicz commented on golem/task/taskmanager.py
> +        if self.key_id is None:
`if not self.key_id:`

2016-12-23 16:31 UTC, mfranciszkiewicz commented on tests/golem/interface/test_cli.py
> +                self.assertIsNotNone(err.getvalue())
This test expects that no messages were written to `sys.stderr`. `assertIsNotNone` does not check whether it is an empty string. The same goes for lines below.

2016-12-23 16:31 UTC, mfranciszkiewicz commented on tests/golem/interface/test_cli.py
> +        self.assertIsNotNone(out.getvalue())
Does not check for empty values.

2016-12-23 16:31 UTC, mfranciszkiewicz commented on tests/golem/interface/test_formatters.py
> +        self.assertIsNone(fmt.supports(ns_dict))
`supports` returns a `bool`ean

2017-01-04 15:36 UTC, banasiakadam60 commented on golem/docker/task_thread.py
> +        if docker_images is None:
Done

2017-01-04 15:36 UTC, banasiakadam60 commented on golem/network/transport/message.py
> +            if dict_repr.get(MessagePing.PING_STR) is None:
Done

2017-01-04 15:37 UTC, banasiakadam60 commented on golem/task/taskmanager.py
> +        if self.key_id is None:
Done

2017-01-04 15:37 UTC, banasiakadam60 commented on tests/golem/interface/test_cli.py
> +                self.assertIsNotNone(err.getvalue())
Fixed

2017-01-04 15:39 UTC, banasiakadam60 commented on tests/golem/interface/test_cli.py
> +        self.assertIsNotNone(out.getvalue())
Done

2017-01-04 15:39 UTC, banasiakadam60 commented on tests/golem/interface/test_formatters.py
> +        self.assertIsNone(fmt.supports(ns_dict))
Fixed

2017-01-04 17:22 UTC, merged