Dockerhub
golemfactory/clay pull request #771
Opened 2017-01-18 12:23 UTC by badb

Resolves #744

2017-01-19 13:08 UTC, chfast requested changes
When there is problem with docker in setup.py we should stop the script with error. The same for missing Qt tools.

2017-01-19 13:08 UTC, chfast commented on setup.py
> +        return
I think we should print error and stop the script.

2017-01-19 20:16 UTC, chfast approved these changes

2017-01-23 15:45 UTC, mfranciszkiewicz approved these changes

2017-01-23 16:01 UTC, merged