Additional tests for network
golemfactory/clay pull request #793
Opened 2017-01-26 14:54 UTC by banasiakadam60

Signed-off-by: Adam Banasiak <banasiakadam60@gmail.com>

2017-01-26 18:04 UTC, badb requested changes

2017-01-26 18:04 UTC, badb commented on tests/golem/network/p2p/test_node.py
> +        socket.inet_pton(socket.AF_INET, address)
Fails on windows

> socket.inet_pton(address_family, ip_string)
> (...)
> availability: Unix (maybe not all platforms).

2017-01-26 18:15 UTC, mfranciszkiewicz commented on tests/golem/network/p2p/test_node.py
> +        socket.inet_pton(socket.AF_INET, address)
`ipaddress.ip_address` might be a good replacement

2017-01-26 18:15 UTC, mfranciszkiewicz commented on tests/golem/network/ipfs/test_ipfs_daemon_manager.py
> +        ipfs_id = dm.store_client_info()
You could also validate the value of `ipfs_id`

2017-01-26 18:16 UTC, mfranciszkiewicz commented on tests/golem/network/p2p/test_node.py
> +        socket.inet_pton(socket.AF_INET, address)
`ipaddress.ip_address`

2017-01-27 10:29 UTC, banasiakadam60 commented on tests/golem/network/p2p/test_node.py
> +        socket.inet_pton(socket.AF_INET, address)
Fixed

2017-01-27 14:24 UTC, mfranciszkiewicz commented on tests/golem/network/p2p/test_node.py
> +        socket.inet_aton(address)
IPv4 addresses only.

2017-01-27 15:13 UTC, banasiakadam60 commented on tests/golem/network/p2p/test_node.py
> +        socket.inet_aton(address)
Done

2017-01-30 11:50 UTC, badb approved these changes

2017-01-30 12:03 UTC, merged