Verificator
golemfactory/clay pull request #830
Opened 2017-02-17 17:16 UTC by badb

2017-03-05 22:28 UTC, banasiakadam60 approved these changes

2017-03-06 13:25 UTC, jiivan requested changes

2017-03-06 13:25 UTC, jiivan commented on apps/blender/task/blenderrendertask.py
> +                 verificator_class=BlenderVerificator):
I suppose it wll always be the same class, so maybe do:
```python
class BlenderRenderTask(...):
    VERIFICATOR_CLASS = BlenderVerificator
```

2017-03-06 13:25 UTC, jiivan commented on apps/lux/task/luxrendertask.py
> +                 verificator_class=LuxRenderVerificator):
I propose the same solution as in Blender class with class attribute/const.

2017-03-06 13:25 UTC, jiivan commented on tests/apps/lux/task/test_luxrendertask.py
> +    def __get_test_lux_task(self):
why use `__` name mangling?

2017-03-06 13:25 UTC, jiivan commented on apps/blender/task/blenderrendertask.py
> +
Can this be moved to `RenderingTask` or even better `CoreTask`?

2017-03-06 13:25 UTC, jiivan commented on apps/core/task/verificator.py
> +    def __init__(self, verification_options=None, advance_verification=False):
`advance*d*_verification`?

2017-03-06 13:25 UTC, jiivan commented on apps/core/task/verificator.py
> +    def set_verification_options(self, verification_options):
Maybe `property.setter` instead of javaish setter method?

2017-03-06 16:28 UTC, badb commented on apps/core/task/verificator.py
> +    def set_verification_options(self, verification_options):
I don't know if this makes a difference. It's not a simple setter, because it also set other option and in more complicated cases may check some restrictions, set default values.

2017-03-09 14:24 UTC, jiivan approved these changes

2017-03-09 14:24 UTC, jiivan commented on apps/rendering/task/framerenderingtask.py
> +    def __init__(self,  **kwargs):
Hanging whitespace.

2017-03-13 13:59 UTC, merged