CompTaskInfo persistance
golemfactory/clay pull request #872
Opened 2017-03-09 14:41 UTC by jiivan

Whole CompTaskKeeper state is pickled in datadir.

2017-03-13 14:27 UTC, badb commented on golem/task/taskkeeper.py
> +                logger.exception('Problem restoring dumpfile: %s', self.dump_path)
Maybe we should remove files that we cannot unpickle?

2017-03-13 14:30 UTC, badb commented on golem/task/taskkeeper.py
> +        self.task_headers = {}  # all computing tasks that this node nows about
knows

2017-03-13 14:36 UTC, badb commented on tests/golem/task/test_taskkeeper.py
> +class TestCompTaskKeeper(LogTestCase, PEP8MixIn):
Can you use `golem.testutils.TempDirFixture` here?

2017-03-13 14:38 UTC, badb commented on tests/golem/task/test_taskkeeper.py
> +        """Tests wether tasks are persistent between restarts."""
`whether`?

2017-03-13 14:40 UTC, badb requested changes
Additionally I've been getting an error on `test_conformance`. How can I check why?

2017-03-15 09:10 UTC, jiivan commented on golem/task/taskkeeper.py
> +                logger.exception('Problem restoring dumpfile: %s', self.dump_path)
I'm not sure about this. Anyway this file will be overwritten in next dump().

2017-03-15 09:12 UTC, jiivan commented on golem/task/taskkeeper.py
> +        self.task_headers = {}  # all computing tasks that this node nows about
:heavy_check_mark:

2017-03-15 09:12 UTC, jiivan commented on tests/golem/task/test_taskkeeper.py
> +class TestCompTaskKeeper(LogTestCase, PEP8MixIn):
:heavy_check_mark:

2017-03-15 09:13 UTC, jiivan commented on tests/golem/task/test_taskkeeper.py
> +        """Tests wether tasks are persistent between restarts."""
:heavy_check_mark:

2017-03-15 09:17 UTC, jiivan commented
Hmm, they're written to stdout. Here it looks like this (my underline):
```
(golem) dybi@labelle:~/repo/golem$ nosetests tests/golem/task/test_taskkeeper.py
..F.........
======================================================================
FAIL: Test that we conform to PEP-8.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dybi/repo/golem/golem/testutils.py", line 136, in test_conformance
    self.assertEqual(result.total_errors, 0, "Found code style errors (and warnings).")
AssertionError: Found code style errors (and warnings).
-------------------- >> begin captured stdout << ---------------------
golem/task/taskkeeper.py:17:52: E261 at least two spaces before inline comment
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 12 tests in 1.676s

FAILED (failures=1)
```

2017-03-24 15:48 UTC, badb approved these changes

2017-03-24 18:12 UTC, merged